- build/module.mk
- build/readme.md
- main/src/main.cpp
- wiring/inc/spark_utilities.h
- wiring/inc/spark_wlan.h
- wiring/src/spark_utilities.cpp
- wiring/src/spark_wlan.cpp
(Requires a clean build of wiring.)
Mostly #ifdef/#endif, with some formatting changes.
Before:
80220	   1144	  11580	  92944	  16b10	../build/target/main/prod-0/main.elf
After:
45228	   1124	   8596	  54948	   d6a4	../build/target/main/prod-0/main.elf
So ca 3k ram and 35k flash saved.
> Add SPARK_CLOUD=n to the make cmd line to compile-time exclude the cloud.

- README.md
Hey @m-mcgowan - not sure if this warning is 100% accurate, but I figured we should get something in here so that people don't try to use this firmware repo with the Photon. Let me know if this looks right to you.
> Warn people not to use the current open source firmware on Photons

- user/build.mk
This allows the user code to be built with extra CFLAGS.  The user just has to set the shell variable EXTRA_CFLAGS and they will get added.
Something like:
export EXTRA_CFLAGS="flags"; make APP=userapp
> Added the a hook to EXTRA_CFLAGS in user/build.mk. 

- inc/spark_wiring.h
Now I can programmatically determine voltage when you decide to change to a 10-bit ADC.
`3.3V * (analogRead(A0) / ADC_MAX_VALUE)`
-- or --
If you want to implement [analogReadResolution()](http://arduino.cc/en/Reference/AnalogReadResolution)
`#define ADC_RESOLUTION_BITS 12`
`3.3V * (analogRead(A0) / ((1 << ADC_RESOLUTION_BITS) - 1))`
> Add #define for ADC resolution

- hal/src/core/usart_hal.c
- hal/src/photon/usart_hal.c
Fixes https://community.particle.io/t/changing-serial-baud-rate-inside-setup-code-causes-core-freezing-afterwards/10314
> Fix for Serial1.end() - Changing usart baud rate should work now

- user/inc/application.h
- wiring/inc/fast_pin.h
This covers fast pin set/reset. Does anyone have a suggestion for multiple pin set/reset, port access etc..?
> fast pin access

- hal/inc/usart_hal.h
- hal/src/core/usart_hal.c
- hal/src/stm32f2xx/usart_hal.c
- hal/src/template/usart_hal.c
- user/tests/wiring/api/wiring.cpp
- wiring/inc/spark_wiring_usartserial.h
- wiring/src/spark_wiring_usartserial.cpp
This patch will allow user code to enable half-duplex mode in Serial1.  I have not tried it with Serial2.  The patch works great on my Core.  I have yet to try it on a Photon, because I have not received them yet.  I will be trying it when I receive one.
Setting the serial port to half duplex enables the one-wire on the hardware.  Both TX and RX use the TX pin.
Thanks!
> Patch to enable half duplex mode in Serial1

- system/src/wifi_credentials_reader.cpp
When connecting to the device in Listening mode via serial, and receiving 's', this super small change makes the Describe Message output as valid JSON ready for copy/pasting into pretty print tools online or code like `JSON.stringify(DATA,null,4)`
@emilyrose just wanted to double check with you if this is needed for the CLI at all, and if so it would require some refactoring on your end most likely.
> valid JSON output for pretty printing tools like JSON.stringify(DATA,null,4)

- hal/src/photon/inet_hal.cpp
- system/src/system_cloud.cpp
- wiring/src/spark_wiring_tcpclient.cpp
Use return value directly in system_cloud.cpp, instead of inferring error
from an IP address of 0.0.0.0.
Stop writing garbage into ip address in photon/inet_hal.cpp when the underlying
wiced call failed.
Use and pass on inet_gethostbyname() return value in spark_wiring_tcpclient.cpp
> Fix inet_gethostbyname() behaviour and usage.

- services/inc/rgbled.h
- services/inc/services_dynalib.h
- services/src/rgbled.c
- user/tests/wiring/api/wiring.cpp
- user/tests/wiring/no_fixture/led.cpp
- wiring/inc/spark_wiring_rgb.h
- wiring/src/spark_wiring_rgb.cpp
A user can easily implement an external RGB LED by registering a change handler with `RGB.onChange` and doing `analogWrite` to another set of pins inside the change andler.
Multiple community topics show this is wanted.
http://community.particle.io/t/mirroring-on-board-rgb-led-to-external-led/13724/2
http://community.particle.io/t/best-way-to-implement-an-outboard-bright-rgb-led/12063/2
How to use:
```
// Needed to catch the initial cloud connection blinks
void externalLEDHandler(uint8_t r, uint8_t g, uint8_t b) {
// reproduce green to an external LED to get a pretty good idea if the cloud is connected
analogWrite(D0, g);
}
void setup()
{
pinMode(D0, OUTPUT);
RGB.onChange(&externalLEDHandler);
Spark.connect();
}
```
Note: `Set_RGB_LED_Values(0,0,0);` was …
> Add a change handler to the RGB class

- communication/src/communication_dynalib.h
`Spark.unsubscribe` uses `spark_protocol_remove_event_handlers` but it wasn't included in any dynalib export.
> Added spark_protocol_remove_event_handlers to dynalib

- CHANGELOG.md
- communication/src/events.h
- communication/src/spark_protocol.cpp
- communication/src/spark_protocol.h
- communication/src/spark_protocol_functions.cpp
- communication/src/spark_protocol_functions.h
- system/src/system_cloud.cpp
- user/tests/wiring/api/cloud.cpp
- user/tests/wiring/api/wiring.cpp
- user/tests/wiring/cloud/cloud.cpp
- wiring/inc/spark_wiring_cloud.h
- wiring/inc/spark_wiring_interrupts.h
- wiring/src/spark_wiring_cloud.cpp
Spark.function, Spark.subscribe and attachInterrupt can now take a pointer to a member and an instance to easily attach a callback to a C++ object as shown in the tests.
subscribe was missing lambda support and `spark_subscribe` did not save the data pointer to be passed to the `EventHandler` callback so I implemented the following solution to add lambda support:
* Don't change the signature of any dynalib method
* Save the handler data pointer in `FilteringEventHandler`
* If the data pointer is non-null, call the handler with the extra data pointer (3 arguments)
* If the data pointer is null, call the handler with 2 arguments
The idea is that this should be compatible with previous user code and HAL versions.
Compile and device tests pass (I didn't know how to add tests for …
> Add C++ handlers and handler_data to subscribe

- wiring/inc/spark_wiring_servo.h
- wiring/src/spark_wiring_servo.cpp
fix for #120 - provide a setTrim() method that users can minutely adjust the servo timing. Untested.
> servo trim

- CHANGELOG.md
- user/tests/wiring/api/time.cpp
- user/tests/wiring/no_fixture/time.cpp
- wiring/inc/spark_wiring_time.h
- wiring/src/spark_wiring_time.cpp
#455 - configurable format to Time.timeStr(), and a generic time formatter `Time.format(time_t, format_spec)` based on `strftime()`.  Complete with API and unit tests.
Here's the new APIs:
```c++
String s = Time.timeStr();
// as before - outputs time like
// Sat Jan 10 13:37:04 2004
String s = Time.timeStr(TIME_FORMAT_ISO8601_FULL);
// Current time formatted ISO8601,  no time zone configured
// 2004-01-10T13:37:04Z
// can also specify the time to convert
time_t beer_oclock = Time.now()+1234;
String s = Time.timeStr(beer_oclock, TIME_FORMAT_ISO8601_FULL);
// configure timezone
Time.zone(-5);
String s = Time.timeStr(TIME_FORMAT_ISO8601_FULL);
// current time formated in ISO8601, includes time zone
// 2004-01-10T08:37:04-05:00
// If not provided, the format is TIME_FORMAT_DEFAULT 
// (the …
```
> Time.timeStr() formatting

- CHANGELOG.md
- hal/inc/core_hal.h
- hal/inc/hal_dynalib_core.h
- hal/inc/hal_dynalib_spi.h
- hal/inc/spi_hal.h
- hal/src/core/core_hal.c
- hal/src/core/spi_hal.c
- hal/src/gcc/core_hal.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/stm32f2xx/spi_hal.c
- hal/src/template/core_hal.c
- hal/src/template/spi_hal.c
- user/tests/wiring/api/peripherals.cpp
- wiring/inc/spark_wiring_spi.h
- wiring/src/spark_wiring_spi.cpp
`SPI.setClockSpeed`, `SPI.setClockDividerReference` for more portable SPI clock speeds.
Examples:
Set the clock divider reference for arduino compatibility
```
SPI.setClockDividerReference(ARDUINO);
SPI.setClockDivider(SPI_CLOCK_DIV4);
```
Set an absolute clock speed (or the highest supported speed without going over)
```
unsigned acutalSpeed = SPI.setClockSpeed(20, MHZ);
```
> SPI.setClockSpeed/setClockDividerReference

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
To make it easier to figure out where a hard fault came from I set a breakpoint in HardFault_Handler but the variables r1, r2, r3, r12, lr, pc, psr are incremented because of the missing braces in if(false). It's cleaner to just use (void)variable to silence the compiler error.
> Don't modify registers in HardFault_Handler

- hal/src/electron/core_hal.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.h
@technobly @mohitbhoite @towynlin @brandoaire The RTC on electron works now after overriding the RTC alarm interrupt handler. So it's not an issue with the crystals or the loading caps as we concluded earlier
> Fix RTC issue on Electron - override RTC alarm interrupt handler

- system/src/main.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- system/src/system_task.cpp
addresses #616 - revert to breathing green when the cloud isn't serviced for 15 seconds.  System modes are unchanged - in automatic mode, the system will try to reconnect once the background loop is executed again. Semi-automatic and manual mode requires the application code to call `Particle.connect()`.
> cloud disconnect detect

- hal/inc/spi_hal.h
- hal/src/core/spi_hal.c
- hal/src/stm32f2xx/spi_hal.c
- system/inc/system_cloud.h
- system/inc/system_update.h
- user/tests/wiring/api/cloud.cpp
- wiring/inc/spark_wiring_cloud.h
- wiring/src/spark_wiring_spi.cpp
Catches this error:
```
Particle.variable("myvar", &string, STRING);
```
which comes up often in community discussions.
> strict typechecks for Particle.variable()

- user/tests/unit/print.cpp
- wiring/inc/spark_wiring_print.h
- wiring/src/spark_wiring_print.cpp
This little gem allows you to write printf-like statements to any Print instance (Serial, TCPClient etc...)
```
Serial.printfln("There are %s types of people in the world, those that understand binary and those that don't", "10");
Serial.printfln("There are %d sweets in the jar", rand()%560);
```
Without the API we'd have to write:
```
Serial.print("There are");
Serial.print(10);
Serial.println("types of people in the world, those that understand binary and those that don't");
Serial.print("There are ");
Serial.print(rand()%560);
Serial.println("sweets in the jar");
```
I've wanted this for ages - formatting messages otherwise is quite tedious, requiring them to be split over many lines of code.
`printf` formats the message as given, `printfln` adds a newline at the end.
> Print.printf/printfln

- hal/inc/cellular_hal.h
- hal/inc/hal_dynalib_cellular.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- system/src/system_network_cellular.h
* Fix LAC and Cell ID parsing
* Fix value used for finding a free socket
* If a SIM is not present after powerOn completes, the Electron will
flash blue.
* Cellular connection is moved to connect_finalize so it flashes green
during cellular registration and attachment.
Note: I was unable to get the uBlox module to allow persistent SIM polling. Thus if a SIM is not detected at startup, once it is inserted a RESET is required.
LED now behaves as below:
Power on: breathing white for a second or two
SIM present? No - flashing blue
Cellular connecting - Flashing green
Cloud connecting - Flashing cyan
Connected - Breathing cyan
> Fix LED states

- hal/src/photon/wlan_hal.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
save the antenna selection persistently so that safe-mode works when connected to an external antenna.  addresses #618
> persist antenna selection

- hal/inc/core_hal.h
- hal/inc/hal_dynalib_core.h
- hal/src/photon/ota_flash_hal.cpp
- user/tests/wiring/api/system.cpp
- wiring/inc/spark_wiring_system.h
Implementation of #630. Application firmware can set device keys and SSID prefix.
To set the prefix, use
```
HAL_Set_System_Config(SYSTEM_CONFIG_DEVICE_FAMILY_NAME, "Batman", 6);
```
To set the device private key:
```
// use xxd to convert .der key to C array. Add `const` to ensure data goes to flash rather than RAM
const char* key[612] = "....";
STARTUP(HAL_Set_System_Config(SYSTEM_CONFIG_DEVICE_PRIVATE_KEY, key, 612));
```
> DCT control

- docs/gettingstarted.md
Can't build in develop branch
```
➜  modules git:(develop) make clean all PLATFORM=photon -s program-dfu
clean all program-dfu
../../../build/checks.mk:5: *** Please note the develop branch contains untested, unreleased code. We recommend using the 'latest' branch which contains the latest released firmware code. To build the develop branch, please see the the build documentation at https://github.com/spark/firmware/blob/develop/docs/build.md#building-the-develop-branch.  Stop.
make: *** [/Users/anuj/code/spark/firmware/modules/photon/system-part1/makefile] Error 2
```
> Switch to latest branch before attempting to build

- wiring/inc/spark_wiring_cloud.h
Errors with Particle.variable("name", ..., STRING); are common. The changes in 0.4.7 introduce errors for incorrect cases instead of silently compiling. However the errors are weird template errors that are absolutely incomprehensible.
This at least shows clear error to users.
```C++
char buf[10];
String str;
Particle.variable("name", &buf, STRING);
Particle.variable("name", str, STRING);
Particle.variable("name", &str, STRING);
```
```
../wiring/inc/spark_wiring_cloud.h:67:9: error: static assertion failed:
Use Particle.varible("name", myVar, STRING); without & in front of myVar
../wiring/inc/spark_wiring_cloud.h:73:9: error: static assertion failed:
In Particle.varible("name", myVar, STRING); must be declared as char myVar[] not String myVar
```
See this forum discussion for why this is …
> Make the errors clearer for Particle.variable()

- wiring/src/spark_wiring_udp.cpp
I ran into an issue where I couldn't compare the remoteIP() to another IPAddress since the version was set to 0. Using index assignment doesn't set it to 4, but assigning uint8_t* to an IPAddress does set it as IPv4.
> Setting _remoteIP by index doesn't set it as IPv4

- hal/src/electron/core_hal.c
- hal/src/electron/delay_hal.c
- hal/src/photon/core_hal.c
- hal/src/stm32f2xx/concurrent_hal.cpp
I needed Electron threading to work for my application so I tweaked the FreeRTOS config for it to work. With these changes I'm able to use `SYSTEM_THREAD(ENABLED)` and wiring threads.
* Call the RTOS SysTick after the OS has been set up through `SysTickChain`
* Use RTOS `vTaskDelay` in `HAL_Delay_Milliseconds`
* Add `uxTopUsedPriority` to Electron
I don't know if you're ready to add multi-threading to the Electron, but I think this will be welcomed by all the beta testers.
> Electron multi-threading and OpenOCD support

- modules/shared/stm32f2xx/inc/user_part_export.c
- system/inc/system_user.h
- system/src/main.cpp
- user/libraries/Serial2/Serial2.h
- user/libraries/Serial3/Serial3.h
- user/libraries/Serial4/Serial4.h
- user/libraries/Serial5/Serial5.h
- wiring/inc/spark_wiring_platform.h
- wiring/inc/spark_wiring_usartserial.h
- wiring/src/user.cpp
Emulation of `serialEvent()` from arduino wiring.  Implemented as weak functions in user app to allow the application to know if there is serial data available.
This is a requested feature. I'm a bit puzzled why we might need this since the user loop can easily add code like
```
void loop()
{
// ... loopy stuff here
if (Serial1.available())
serialEvent1();
}
void serialEvent1()
{
char c = Serial1.read();  
}
```
Which is more efficient than what we are able to provide from the system code.
> serialEventX() 

- CHANGELOG.md
- hal/inc/gpio_hal.h
- hal/inc/hal_dynalib_gpio.h
- hal/src/core/gpio_hal.c
- hal/src/stm32f2xx/gpio_hal.c
- user/tests/wiring/no_fixture/gpio.cpp
- wiring/inc/spark_wiring.h
- wiring_globals/src/spark_wiring_gpio.cpp
Quick implementation of a [**pulseIn()**](https://www.arduino.cc/en/Reference/PulseIn) from Arduino/Wiring.
* Times out automatically after 3 seconds to keep from blocking background tasks.
* Tests ran and passed on Photon and Core, but Electron TEST=wiring/no_fixture has compiler errors from different tests, so could not run for E.  Ran tests for P1 and pulseIn() passed but about 8 other tests failed :(
* Thought it might be hard to test pulseIn() without a fixture, but surprise... you can read the state of an output when the PWM peripheral is banging out bits :joy:
> pulseIn() for Photon/P1/Core/Electron, with tests

- hal/src/stm32f2xx/i2c_hal.c
* 100ms timeout is now immediately aborted if ACK failure is detected, i.e., no response to Slave Address being sent.  Master sees NACK on 9th SCL clock.
* NOTE: If Slave is disconnected, Master must still have pull up resistors on SDA and SCL to properly detect an ACK failure.  Without these, the I2C interface will see many Bus Errors (BERR) and potentially ARLO failure.
* Improved comments for I2C Receive routine (HAL_I2C_Request_Data())
* Added missing re-enable commands for interrupts in SW RESET function
* mode and ackFailure elements added to end of STM32_I2C_Info structure to preserve organization in memory for DYNALIB, allows older I2C apps to work with new I2C library.
> Speed up I2C 100ms timeout on Slave_Address NACK - fixes #675

- build/arm/linker/stm32f2xx/backup_ram.ld
- hal/inc/core_hal.h
- hal/src/core/core_hal.c
- hal/src/electron/app_no_bootloader.ld
- hal/src/electron/include.mk
- hal/src/photon/include.mk
- hal/src/photon/wiced/platform/MCU/STM32F2xx/GCC/app_no_bootloader.ld
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- modules/shared/stm32f2xx/inc/user_part_export.c
- modules/shared/stm32f2xx/include.mk
- modules/shared/stm32f2xx/user.ld
- system/inc/system_user.h
- wiring/inc/spark_wiring_system.h
- wiring/src/user.cpp
* The code currently (v0.4.6) attempts to initialize SRAM if it's not waking up from Standby mode, but should instead be initializing based on if it powered up when the Backup RAM is enabled. Since it's a bit tricky to store a system variable in SRAM for this purpose, checking the Backup Regulator Ready status bit will do nicely; which is a hardware controlled bit that won't be cleared if we are waking up from Standby, software or hardware reset. This backup regulator is only enabled if we are enabling Backup RAM, so this is perfect.
* I've been testing this in all modes of operation it's rock solid now. Docs really need a matrix table to show all of the different states for SRAM. This will make it super clear when SRAM is initialized and when it's retained (at least that's the hope).  
* …
> initialize backup sram only on first use

- system/inc/system_cloud.h
- system/src/system_cloud.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- user/tests/wiring/api/cloud.cpp
- wiring/inc/spark_wiring_cloud.h
Allows `String` instances to be used as variables. 
static String myString;
```
Particle.variable("myvar", myString);
```
Simpler variable API - no need for address-of `&` operator, and the 3rd argument is dropped, since the variable type is determined from the variable.
> String varaibles

- hal/inc/cellular_hal.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- system/src/system_network_cellular.h
- system/src/system_network_internal.h
- system/src/system_task.cpp
- user/applications/tinker_electron/application.cpp
- double-tap SETUP button to activate
- Dim white RGB LED while shutting down
- Deactivates PDP context
- Detaches GPRS connection
- Puts modem to sleep
- Puts STM32 to sleep
- Press RESET button to wake up (or rising HIGH signal on WKP pin)
- Hold SETUP button for >3 seconds to enter
- Hold SETUP button for >3 && <8 seconds && let go of button to exit
- alternatively press `x` in serial terminal to exit
- Previously setup PDP context will resume if available on exit
- Sockets were being used up when system would go through soft power down or when STM32 went to sleep.  This was because the modem might still be powered and active, yet system code was resetting so all knowledge of which sockets were in use was reset as well.  After a couple power downs, all sockets were taken and it …
> Fixes Soft Power Down, Listening Mode operation and CFOD issue on Electron

- hal/src/electron/modem/mdm_hal.cpp
`AT+ UDNSRN` has a response time of up to 30 seconds, and has been observed this high at least once.  Usually this command takes  anywhere from sub second to a couple seconds, and less frequently more than 5 seconds.
> inc gethostbyname() timeout from 10s to 30s, fix for FIRM-222 CFOD

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- hal/src/electron/socket_hal.cpp
- system/src/system_cloud_internal.cpp
- wiring/src/spark_wiring_tcpclient.cpp
* Sockets can be closed remotely now (if connected), or locally (if connected or not connected and just open) and the parser deals with this much better.
* UDP sockets will now be closed locally.
* added _sockets[socket].open flag to be able to close an unconnected socket.
* socketSocket() will now reclaim open sockets that are presumed closed.
* This is hard to reproduce without forcing sockets to be used up, which will be easier with the AT pass through cellular hal interface that's coming soon to a PR near you.
* Multicast Packet Announcement is not useful on the electron, but this helps to keep sockets from disappearing from the pool until this is refactored out for electrons (this was the main cause of socket leak as it would create sockets and not close them.  Then later on it would …
> Fixes FIRM-275 - Electron socket leak

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
* if modem is unresponsive on power up, it will be reset and the power up sequence will be retried.
* if SIM card was inserted after power up, it may show up as not inserted.  System will now power down the modem & power back up (soft reset) to allow the SIM card to be recognized.
> Fixes FIRM-279 - Modem unresponsive on power up

- communication/src/lightssl_message_channel.h
- hal/src/gcc/device_config.cpp
- hal/src/gcc/rtc_hal.cpp
- hal/src/gcc/socket_hal.cpp
Sockets HAL implementation in GCC platform creates non-blocking sockets and read operation on them may return EAGAIN if there's no data available.
> Check for EAGAIN error code (gcc platform) and minor compilation fixes

- system/src/main.cpp
- system/src/system_sleep.cpp
- wiring/inc/spark_wiring_platform.h
* One click of the SETUP button invokes a blocking call for signal strength, when received it is converted to 0-5 "bars" of signal strength via a green LED.  First the LED dims to make the flashes more apparent and easy to count, then the LED is flashed bright green once for each bar of signal strength.  If the signal is really weak, dim green with no flashes equates to zero bars.
* Two clicks of the SETUP button invokes the Soft Power Down feature that was previously implemented, which powers off the modem and puts the STM32 in deep sleep mode.
* Disables the single/double tap feature for non-electron devices.
A little preview of how this works with 1 bar of signal strength.  Sorry my signal is not the best right now :)
https://www.dropbox.com/s/hph5mldtxysr185/rssi-ux-and-soft-power-down …
> Electron RSSI UX via SETUP button

- communication/src/dsakeygen.cpp
- user/tests/app/rsakeygen/rsakeygen.cpp
- user/tests/app/rsakeygen/verify_keys.py
Certain P/Q/DP/DQ/QP values caused RSAPrivateKeyWriter to generate incorrect private key in DER format.
> Fixes RSA private key generation

- communication/src/dtls_message_channel.cpp
- communication/src/dtls_protocol.cpp
- communication/src/lightssl_message_channel.cpp
- communication/src/protocol.h
Sends the ping as a zero-length UDP packet to keep the UDP NAT pathway open to the cloud.
> UDP ping keepalive

- hal/inc/core_hal.h
- hal/inc/hal_dynalib.h
- hal/inc/hal_dynalib_gpio.h
- hal/inc/interrupts_hal.h
- hal/inc/rtc_hal.h
- hal/src/core/core_hal.c
- hal/src/core/interrupts_hal.c
- hal/src/core/rtc_hal.c
- hal/src/gcc/core_hal.cpp
- hal/src/gcc/rtc_hal.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/stm32f2xx/interrupts_hal.c
- hal/src/stm32f2xx/rtc_hal.c
- hal/src/template/interrupts_hal.cpp
- hal/src/template/rtc_hal.c
- hal/src/template/rtc_hal.cpp
- system/src/system_sleep.cpp
HAL_Core_Enter_Stop_Mode should be wrapped with a critical section (cpsid/cpsie) to avoid
having an interrupt triggered while the device is entering sleep mode. Interrupts can be safely
disabled while in STOP mode.
All EXTI interrupts but the one associated with selected wakeup pin should be disabled as well
and restored after exiting STOP mode.
Fixes #655
> Fixes sleep (STOP mode) on Photon platform

- build/verbose.mk
It more looks like a bug in GNU make or bash, but I experienced weird issue related to this patch: e7b75d7848a3ac27e7428db766b18dd56bd88b24. When make is invoked in silent mode (-s argument) it fails to generate target binary with a valid checksum, leading newly flashed device to boot in safe mode after successful build.
Tested on Ubuntu 14.04 LTS (gmake 3.81 / 4.1, bash 4.3.11).
> Magical fix for strange build issue

- hal/src/stm32f2xx/usart_hal.c
Fixes the issue discussed here: https://github.com/spark/firmware/issues/776
> Fixes USART_ISR infinite loop due to ORE flag not handled

- services/inc/rgbled.h
- services/inc/services_dynalib.h
- services/src/rgbled.c
- system/src/main.cpp
- system/src/system_network_internal.h
- system/src/system_rgbled.h
Fixes an issue where entering listening mode while breathing white (network turned off) then existing listening mode would cause the LED to flash blue.
This is because the SysTick does not handle the default case of no network. 
Preserving the LED state ensures it is restored correctly.
> preserves the LED state

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
UDP currently pings the server every 23 minutes... 
If a PDP context is remotely deactivated or GPRS detached remotely, it would normally take up to 23 minutes to find out about it.  This PR catches the URCs associated with these events and notifies the system of network disconnect.
For GPRS detach, we set a 15 second watchdog timer because GPRS detach events have been seen to re-attach right after detaching.  No need to churn the whole system for that.  If it re-attaches, the WDT is cleared.
PDP deactivation will issue an immediate system network disconnect and retry.
To test:
* Try removing your antenna, waiting for logs to indicate a WDT is set... then replace the antenna and see if it clears.  Try publishing before and after.
* Try the same thing, but this time wait longer until the …
> notify system of PSD disconn. during GPRS detach & PDP deactivate URCs

- services/inc/service_debug.h
- services/src/debug.c
short-circuits debug functions if no debug output defined (making the debug function mostly a no-op) - parameters to the function are still evaluated by the caller, but vsnprintf() is not invoked.
Adds a log level and void* extension point to `log_direct_`
> short circuit debugging

- hal/src/electron/core_hal.c
- hal/src/photon/core_hal.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.h
- hal/src/stm32f2xx/spi_hal.c
Fixes #791
SPI hardware might still be busy pushing out bytes when SPI TX DMA transfer complete IRQ handler is fired. To ensure that SPI user callback is called when the actual transfer has been completed, it should be called from SPI RX DMA transfer complete IRQ handler.
1 (Yellow) - MISO/MOSI (loopback mode)
2 (Blue) - SPI User callback indicator pin (pulled low in callback)
3 (Purple) - SCK
This is the behavior observed in develop branch at 100KHz.
Left cursor indicates a point the user callback was called, right cursor indicates a start of a non-DMA single byte transfer sequence (0x00, 0xff, 0x00). Despite the fact that all the bytes were pushed out, this is still incorrect behavior, since neither actual TX transfer has been completed, nor RX DMA has been completed when user callback …
> SPI_DMA_UserCallback should be called in SPI RX DMA IRQ Handler

- hal/inc/hal_dynalib_wlan.h
- hal/inc/wlan_hal.h
- hal/src/core/wlan_hal.c
- hal/src/photon/wlan_hal.cpp
- user/tests/wiring/api/wifi.cpp
- wiring/inc/spark_wiring_wifi.h
- wiring/src/spark_wiring_wifi.cpp
* User provides an array of WiFiAccessPoint that get filled with the APs saved on the device
* Returns number of APs on device
* Photon only. Returns 0 on the Core since it cannot read APs back from the CC3000 :disappointed:
Changes
* Implement wlan_get_credentials in HAL
* Implement WiFi.getCredentials with array arguments
* Add API test
Fixes #453
Usage:
```
WiFiAccessPoint ap[5];
int found = WiFi.getCredentials(ap, 5);
for (int i=0; i<found; i++) {
Serial.print("ssid: ");
Serial.println(ap[i].ssid);
Serial.println(ap[i].security);
Serial.println(ap[i].channel);
Serial.println(ap[i].rssi);
}
```
For discussion: my first cut of this was to return a `vector<WiFiAccessPoint>` (typedefed to `WiFiAccessPointList`) from `WiFi.getCredentials`. This made for very nice application code:
``` …
```
> Implement WiFi.getCredentials

- system/src/system_network_wifi.h
> Reset WiFi credentials right after initializing WLAN hardware

- wiring/src/spark_wiring_interrupts.cpp
> wiring_interrupt_handler_t* handlers[] should hold TOTAL_PINS entries

- user/tests/wiring/threading/application.cpp
- user/tests/wiring/threading/listening.cpp
This is to keep up the discussion summarized here: #788, and also a generic fix for #743 and #761.
The patch ensures that system queue is processed while listening mode is enabled in multithreaded configuration, so that synchronous calls that need to be executed in the context of system thread don't block application code.
Solution is far from ideal, as listening loop is still separated from the main system loop, and thus additional checks in unrelated parts of the code are required in order to break this listening loop when necessary (e.g. https://github.com/sergeuz/firmware/blob/loop/system/src/system_network_internal.h#L378). In general, it seems that our whole flags and loops stuff needs to be refactored in favor of more or less strict state machine with centralized control over …
> Process system queue events while in listening mode

- system/inc/system_event.h
- system/src/main.cpp
- system/src/system_task.cpp
- user/tests/app/button_event/button_event.cpp
The patch introduces separate system event generated when setup button is double-clicked, as well as test application handling regular and double clicks.
> Separate system event generated when setup button is double-clicked

- wiring/inc/spark_wiring_eeprom.h
- wiring/inc/spark_wiring_i2c.h
- wiring/inc/spark_wiring_spi.h
- wiring/inc/spark_wiring_usbserial.h
- wiring/src/spark_wiring_eeprom.cpp
- wiring/src/spark_wiring_usbserial.cpp
- wiring_globals/src/wiring_globals_eeprom.cpp
- wiring_globals/src/wiring_globals_i2c.cpp
- wiring_globals/src/wiring_globals_spi.cpp
Test case:
```
SerialDebugOutput output(9600, ALL_LEVEL);
PRODUCT_ID(123);
```
Compile with DEBUG_BUILD=y.   The device doesn't get further than initializing the application. LED breathes white continually. 
Putting the PR out here for review, with a plan to apply this pattern to all global objects in Wiring so that application code can be certain they are properly initialized.
> ensure global Serial object is initialized before use

- communication/src/buffer_message_channel.h
The Message is instanciated with a prefix and a suffix to be able to
store the message length in the prefix, and a padding in the suffix.
The prefix is 2 bytes long, and the padding is 16 bytes long.
The buffer was pointing to queue+suffix instead of queue+prefix, leading
to possible corruption when the queue was full (sending more than one
message per second).
> Blinking Cyan bugfix

- wiring/inc/spark_wiring_arduino.h
It has been a few times members couldn't understand why `pgm_read_byte()` worked but `pgm_read_word()` not.
> add pgm_read_word() macro for easier porting

- hal/src/electron/FreeRTOSConfig.h
- hal/src/electron/rtos_hook.cpp
- hal/src/photon/rtos_hook.cpp
- services/inc/panic_codes.h
- system/src/system_threading.cpp
This PR fixes #821 by increasing stack size for threads created via `std::thread` wrapper and adds FreeRTOS hook for stack overflow detection -- latter is enabled only for debug builds on Electron currently (thanks to @avtolstoy for pointing me out).
> Increased stack size and stack overflow detection for Electron

- hal/inc/cellular_hal.h
- hal/inc/hal_dynalib_cellular.h
- hal/inc/hal_dynalib_wlan.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/cellular_internal.h
- hal/src/electron/modem/enums_hal.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- user/tests/wiring/api/cellular.cpp
- user/tests/wiring/no_fixture/cellular.cpp
- wiring/inc/spark_wiring_cellular.h
- wiring/inc/spark_wiring_cellular_printable.h
- wiring/src/spark_wiring_cellular.cpp
- wiring/src/spark_wiring_cellular_printable.cpp
>Docs and examples to be added here
> Cellular Band Select API

- hal/src/electron/modem/mdm_hal.cpp
- user/tests/app/socket_create/socket_create.cpp
- user/tests/wiring/no_fixture/cellular.cpp
```
/*
* Problem: On the Electron you can create TCP or UDP sockets and once you get to 7 total,
* the socket_create() function won’t return valid handles.  This will not knock
* the Electron off the cloud.  If you use disconnect from the cloud, then use up
* all the sockets, then try to reconnect, it attempts to recover, can’t, so it
* disconnects and resets the Cellular module which generates a URC for socket closed
* remotely, but the system did not free up the sockets because they were never set
* to a .connected status.  Each time the system then tries to allocate a new socket
* for the Cloud, it finds that they are all in use so the system is stuck with all
* sockets open (but not really, they were remotely closed).
*
* Solution: Force socketFree() when the socket is remotely …
```
> Force socketFree() when the socket is remotely closed on Electron

- user/tests/wiring/api/cloud.cpp
- wiring/inc/spark_wiring_cloud.h
A common error is to call `Particle.function("mylongfunction", ...)` with a name longer than 12 characters and overlook to check the return value. It will compile and silently ignore the call at run time.
This PR adds a compile-time check for the length of the name parameter of `Particle.function()` and `Particle.variable()` when the name is a static string literal (type `char [N]`). If the parameter is a dynamic string (type `char *`) or `String` then no check will be done at compile time.
> Give a compiler error for long names in Particle.variable/function

- hal/src/stm32f2xx/can_hal.cpp
- user/tests/wiring/no_fixture/can.cpp
Fix the CAN filter register layout for messages with extended IDs.
Per community post https://community.particle.io/t/photon-can-bus-in-progress/12634/123
I added a failing test then made it pass.
> Fix extended CAN filters

- hal/inc/dac_hal.h
- hal/inc/hal_dynalib_gpio.h
- hal/src/stm32f2xx/dac_hal.c
- hal/src/stm32f2xx/gpio_hal.c
- user/tests/wiring/adc_dac/adc_dac.cpp
> Added HAL_DAC_Enable()/HAL_DAC_Is_Enabled methods to control DAC state on pin

- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/inc/usbd_dfu_mal.h
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_dct_if.c
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_dfu_mal.c
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_flash_if.c
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_sflash_if.c
Tested by making several special versions that inject failures after 15 seconds of runtime, one modified the flash Address that was used in the verify routine.  Typical time to write v0.4.8-rc.6 system part 1 and 2 for electron via `particle update` is about 16.2 seconds before and after new verification process (i.e., it doesn't appear to lengthen the process, most likely due to overall lengthy delays in the DFU process padding the overhead - more on this later...).
> added write-verify-retry-fail logic to DFU writes

- hal/src/core/servo_hal.c
- hal/src/stm32f2xx/servo_hal.c
- user/tests/wiring/no_fixture/servo.cpp
This PR fixes #745 by tracking what timer channels are used to control attached servos.
Note that hardware timers are shared between different HAL submodules, namely, servo, tone and PWM HALs, and any of these still can override timer settings configured by another submodule. Ideally, we need to report an error when user application attempts to reuse already active timer with different settings.
> Servo HAL: Do not disable timer if some of its channels are still in use

- system/inc/system_event.h
- system/src/system_event.cpp
- system/src/system_update.cpp
extend system event notification to allow a data argument to be passed to the func…tion. This is used to stall the system thread waiting for the application (but not indefinitely, as that would create a potential deadlock.)  The system thread only blocks until the application event has been handled. Previously it would block until system updates were enabled, for a maximum of 30 seconds.
https://community.particle.io/t/dashboard-disableupdates-causes-user-code-to-stop-running/19731/7
> don't block application when OTA happens and updates are disabled. 

- hal/src/photon/wlan_hal.cpp
adds a 60 second timeout to wlan_connect() to attempt to regain control after a runaway wifi connect
> wifi connect timeout

- system/inc/system_sleep.h
- system/src/system_sleep.cpp
- user/tests/wiring/api/system.cpp
- wiring/inc/spark_wiring_system.h
- wiring/src/spark_wiring_system.cpp
After System.sleep(pin, trigger, seconds) or System.sleep(pin, trigger) electron will enter STOP mode, modem will remain on and powered in this mode (Photon/P1 will still have the Wi-Fi module powered off). The reason for this is to maintain an active PDP context to keep our current DTLS session happy.  Upon waking, the system will immediately be able to Particle.publish() with the bare minimum amount of data transferred (TX/RX).  Current consumption in this mode is ~4mA for the most of the idle time with small peaks when the modem is maintaining a cellular network connection.  Current consumption should be further reduced when Low Power mode is enabled. (**NOTE:** Please measure and test these current readings yourself before deploying a product based on them, this is preliminary info) …
> Electron resumes session after sleep

- communication/src/communication_dynalib.h
- communication/src/ping.h
- communication/src/protocol.h
- communication/src/protocol_defs.h
- communication/src/spark_protocol_functions.cpp
- communication/src/spark_protocol_functions.h
- user/tests/wiring/api/cloud.cpp
- user/tests/wiring/api/system.cpp
- wiring/inc/spark_wiring_cloud.h
adds `Particle.keepAlive(seconds)` for UDP comms platforms (Electron) to allow the application to set the frequency that ping keep-alives are sent.
Example:
```
void setup()
{
Particle.keepAlive(60*23);  // send keep alive ping every 23 minutes
}
```
A keepalive ping uses ca. 100 bytes of data. 
--
Provides a solution for issue that users with 3rd party SIM's were seeing, certain carriers may have slightly quicker network timeouts, requiring a more frequent ping interval than every 23 minutes (which is the default).
> configurable keepalive

- hal/inc/hal_dynalib_spi.h
- hal/inc/spi_hal.h
- hal/src/core/spi_hal.c
- hal/src/stm32f2xx/spi_hal.c
- hal/src/template/spi_hal.cpp
- user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp
- user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
- wiring/src/spark_wiring_spi.cpp
Fixes behavior of SPI.transfer with NULL callback. According to docs:
> If a user callback function is passed then it will be called after completion of the DMA transfer. This results in asynchronous filling of RX buffer after which the DMA transfer is disabled till the transfer function is called again. **If NULL is passed as a callback then the result is synchronous i.e. the function will only return once the DMA transfer is complete.**
PR also includes tests in `user/tests/wiring/spi_master_slave` for the synchronous behavior.
---
> SPI.transfer() synchronous operation when callback is NULL

- communication/src/build.mk
- communication/src/coap_channel.h
- communication/src/communication_dynalib.h
- communication/src/dtls_protocol.cpp
- communication/src/dtls_protocol.h
- communication/src/lightssl_protocol.cpp
- communication/src/lightssl_protocol.h
- communication/src/protocol.h
- communication/src/spark_protocol_functions.cpp
- communication/src/spark_protocol_functions.h
- hal/src/electron/modem/mdm_hal.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- system/src/system_sleep.cpp
This PR is a rebase against develop of PR #909
* It fixes a lockup issue observed on the Photon and Electron
* If resolves merge conflicts with PR #909 and develop
* It changes the behavior a bit for the new NETWORK_STANDBY flag so that messages are still confirmed before going to sleep while the nework remains on.
Original PR #909 descriptions:
>protocol sleep/wake commands which allow the caller to wait for all coap confirmable requests to be acknowledged, and allows the comms layer to take action when waking up after sleep.
>This is used as part of system sleep to ensure confirmable messages are confirmed before entering sleep.
>https://github.com/spark/firmware/commit/3014dd53bee31f89222d25276504657e608b575d addresses issue #894 - the system will reconnect to the cloud before …
> cloud sleep - waits for all outgoing confirmable UDP messages to be sent (rebased)

- hal/inc/concurrent_hal.h
- hal/inc/hal_dynalib_concurrent.h
- hal/src/stm32f2xx/concurrent_hal.cpp
- user/tests/wiring/no_fixture/timer.cpp
- wiring/inc/spark_wiring_timer.h
> Timer::isActive()

- hal/src/electron/modem/mdm_hal.cpp
Part of #896 was previously solved for U260's with #900, but G350's were still not working.  The complete message was not being received by the TCPClient for short messages.
The issue was that U260 and G350 both were receiving a +UUSOCL URC for a remotely closed socket. The U260 would receive this later in time and therefor did not see any issue.  The G350 would receive the URC earlier which caused the socketReadable() routine to throw an unexpected error by setting OK to false.  This was keeping the `cnt` from being returned for the last bytes received.  When not `readable` now, we ensure `len` is set to 0 and OK is set to `true`.
---
Doneness:
> Electron G350 TCP Client fix for #896

- hal/src/photon/softap.cpp
The problem and steps to reproduce it are described in issue #937.
fixes #937. The memory passed from the parse_json() call is only valid during that call, yet the SetValueCommand was caching these for use later. The fix is to copy the data rather than store the pointer.
---
Doneness:
- N/A - API tests compiled
- N/A - Add documentation
> softap claim code fix

- wiring/inc/spark_wiring_cloud.h
fixes issue #947.  Use explicit references to avoid creation of temporaries. Thanks @sergeuz!
A test should comprise an app with variables and functions registered using all the available syntaxes. 
---
Doneness:
> variable template fix

- system/inc/system_update.h
- system/src/system_setup.cpp
- system/src/system_update.cpp
- user/applications/tinker/application.cpp
- user/src/application.cpp
- wiring/inc/spark_wiring_system.h
adds `SYSTEM_FLAG_WIFITEST_OVER_SERIAL1` which is disabled by default. Tinker enables this so that the WiFi tester is available during  manufacturing.
---
Doneness:
> SYSTEM_FLAG_WIFITEST_OVER_SERIAL1

- build/module.mk
- platform/NET/CC3000/CC3000_Host_Driver/socket.h
adds GNU suport (for isascii and toascii) and avoids duplicate symbol definitions on linux. Provides compatibility with arm gcc 5.3.1 and fixes #963
---
Doneness:
…
> arm gcc 5.3.1 compatibility

- system/src/system_network_internal.h
when the wifi module was not active (and so made active in the listen method) the `on_stop_listning()` method was not called due to short-circuit evaluation when `started` was false.  Swapping the order fixes this.  Fixes #971.
---
Doneness:
> softap persists on exiting listening mode if wifi module was off.

- build/common-tools.mk
> Fail the build early if crc32 tool is not available

- hal/src/stm32/system_interrupts.cpp
- user/tests/wiring/no_fixture/interrupts.cpp
- wiring/src/spark_wiring_interrupts.cpp
> Free memory allocated for previous system interrupt handler

- hal/src/photon/platforms/BCM9WCDUSI09/wifi_nvram_image.h
- hal/src/photon/platforms/BCM9WCDUSI14/wifi_nvram_image.h
- hal/src/photon/resources.c
- hal/src/photon/softap.h
- hal/src/photon/wlan_hal.cpp
- hal/src/photon/wwd_resources.h
- modules/photon/system-part1/inc/wifi_dynalib.h
- modules/photon/system-part1/src/wiced_stubs.c
- modules/photon/system-part1/src/wifi_dynalib.c
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
adds support for setting the wifi country code. This is used to set the available channels, and in the case of japan, the transmit power.
This changes the default country setting to UK, which gives channels 1-13 (previously the default was japan.) This change is so that the default is still full power. 
The country code `JP2` can be used to set the region to Japan, with lower transmit power for TELEC conformance. 
```
echo -n "JP2" > jp2
dfu-util -d 2b04:d006 -a 1 -s 1758:leave -D jp2
echo -n "US4" > us
dfu-util -d 2b04:d006 -a 1 -s 1758:leave -D us
echo "0: 00000000" | xxd -r > null
dfu-util -d 2b04:d006 -a 1 -s 1758:leave -D null
```
In theory, the JP2 setting should have 25% less transmit power than the default setting. Looking at the Signal/Noise and SNR on my router, I could see some …
> wifi country

- hal/src/stm32f2xx/i2c_hal.c
- user/tests/wiring/i2c_master_slave/i2c_master/application.cpp
- user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp
- user/tests/wiring/i2c_master_slave/i2c_slave/application.cpp
- user/tests/wiring/i2c_master_slave/i2c_slave/i2c_slave.cpp
Related to #402. Minor fixes for I2C in Slave mode with clock stretching enabled.
PR also includes I2C Master/Slave test applications similar to wiring/spi_master_slave in wiring/i2c_master_slave/i2c_master and wiring/i2c_master_slave/i2c_slave.
The PR in particular fixes:
- Possible overflow of I2C RX buffer when operating in I2C Slave mode
- Possible bus lockup when clock stretching is enabled in I2C Slave mode (see https://github.com/spark/firmware/commit/4018e7d2b10135a91187ad551b6866b4663c8db2#diff-4657e1c7c22d248c72382fb3eb9c0c9dR75 for some explanation)
---
> Minor fixes for I2C in Slave mode with clock stretching enabled

- wiring/src/spark_wiring_power.cpp
In the Power Management, there is a function for setting the cut off voltage which takes an integer and converts it to the appropriate bit mask.
When sending in 4.208 volts (the upper bound on the LiPo battery provided with spark kits) it sets the voltage to 4.4 volts. This has caused units on our test bench to fail, and could cause fires if using any other standard LiPo battery that doesn't have a limit circuit installed in the battery.
I am not sure how to complete all of the required steps to get this through your processes, but see this bug as a danger, and would appreciate any help in getting it implemented. Or if someone else can do the unit testing required to get it passed I would not mind them taking over the issue.
---
Doneness:
When passing in 4208, 4400 is actually set to the …
> Fire Hazard, Wrong bitmask is provided for 4208

- services/inc/eeprom_emulation.h
- user/tests/unit/eeprom_emulation.cpp
- user/tests/wiring/no_fixture/eeprom.cpp
The EEPROM rewrite in 0.5.0 inadvertently reduced the EEPROM capacity from 2048 to 2047.
This restores the capacity and adds an explicit on-device test for it.
---
Doneness:
> Revert EEPROM capacity to 2048 instead of 2047 Photon / 128 Core

- CHANGELOG.md
- build/arm/linker/stm32f2xx/backup_ram_system.ld
- communication/src/coap_channel.h
- communication/src/dtls_message_channel.cpp
- communication/src/dtls_message_channel.h
- communication/src/dtls_protocol.cpp
- communication/src/dtls_session_persist.h
- communication/src/lightssl_message_channel.h
- communication/src/message_channel.h
- communication/src/protocol.cpp
- communication/src/protocol.h
- communication/src/protocol_defs.h
- communication/src/spark_descriptor.h
- communication/src/spark_protocol.cpp
- communication/src/subscriptions.h
- docs/reference/firmware.md
- hal/src/electron/core_hal.c
- modules/electron/system-part2/linker.ld
- modules/shared/stm32f2xx/part2.ld
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
Reduces data consumption when the device is reset or wakes up from deep sleep. 
Computes a checksum of the last set of subscriptions, functions, variables and system modules that were sent to the cloud, which is maintained in retained storage, as part of the session. 
Before sending a hello after resuming the session, the device checks the current checksum for the subscriptions, functions variables and system modules. If it is the same as the persisted checksum, the hello message is stkipped, since the local application state is the same as what was last sent to the cloud. When the checksums are not the same, the hello message is sent, which clears the app state on the server, so all subsequent describe messages and subscriptions are resent.
For this to work optimally, code should use …
> reduce datausage on reset/wakeup

- CHANGELOG.md
- system/src/system_network_internal.h
fixes #879 
Tested on the Core/P1
---
Doneness:
- N/A  API tests compiled
> makes the MAC address available after `WiFi.on()` in all modes.

- CHANGELOG.md
- platform/MCU/shared/STM32/src/hw_ticks.c
- user/tests/wiring/no_fixture_long_running/ticks.cpp
makes millis()/micros() operations atomic - an interrupt could cause the computed value to be off. Fixes #916 and #925 
---
Doneness:
> millis()/micros() hardening

- hal/src/core/usart_hal.c
- hal/src/stm32f2xx/usart_hal.c
- user/tests/wiring/serial_loopback/serial.cpp
- wiring/src/spark_wiring_usartserial.cpp
Fixes #1017 
`wiring/serial_loopback` includes a test `SERIAL1_AvailableForWriteWorksCorrectly` to verify correct `availableForWrite()` behavior.
---
Doneness:
> Fixes USARTSerial::availableForWrite() behavior

- CHANGELOG.md
- hal/src/core/adc_hal.c
- hal/src/core/gpio_hal.c
- hal/src/core/pinmap_impl.h
- hal/src/stm32f2xx/adc_hal.c
- hal/src/stm32f2xx/dac_hal.c
- hal/src/stm32f2xx/gpio_hal.c
- hal/src/stm32f2xx/pinmap_impl.h
- user/tests/wiring/adc_dac/adc_dac.cpp
- user/tests/wiring/no_fixture/gpio.cpp
Fixes #993
- Saves PinMode in `PIN_MAP[pin].user_property` instead of a single global variable
- Fixes ADC PinMode configuration
- Fixes DAC PinMode configuration (affected by the same issue as ADC pins described in #993 under certain conditions)
Relevant tests:
- `wiring/no_fixture` `GPIO_AnalogReadWorksMixedWithDigitalRead`
- `wiring/adc_dac` `DAC_AnalogWriteWorksMixedWithDigitalRead`
---
Doneness:
> digitalRead()/analogRead() interference

- CHANGELOG.md
- hal/inc/concurrent_hal.h
- hal/inc/hal_dynalib_concurrent.h
- hal/src/stm32f2xx/concurrent_hal.cpp
- system/inc/active_object.h
makes the os_queue interface extensible, and exposes it to the dynamic library.
fixes #1018 
---
Doneness:
> low-level queue API

- CHANGELOG.md
- hal/src/stm32f2xx/bootloader.cpp
Bootloader OTA updates were NOPed on Electron when bootloader image was removed from system-part2.
---
Doneness:
> Enable bootloader OTA updates on Electron

- CHANGELOG.md
- docs/reference/firmware.md
- wiring/inc/spark_wiring_udp.h
- wiring/src/spark_wiring_tcpclient.cpp
- wiring/src/spark_wiring_udp.cpp
> Fixes flush() semantics for UDP and TCPClient

- docs/reference/firmware.md
- hal/inc/hal_dynalib_usart.h
- hal/inc/usart_hal.h
- hal/src/core/usart_hal.c
- hal/src/gcc/usart_hal.cpp
- hal/src/stm32f2xx/usart_hal.c
- user/tests/wiring/api/wiring.cpp
- user/tests/wiring/serial_loopback/application.cpp
- user/tests/wiring/serial_loopback/serial.cpp
- wiring/inc/spark_wiring_usartserial.h
- wiring/src/spark_wiring_usartserial.cpp
The PR is created on top of #930 (**LIN Bus support, USART hardware flow control configuration support**)
- Cleaned up USART settings
- Adds support for 7E1, 7E2, 7O1, 7O2 modes
- Fixes 9-bit receiving. Issue #968
- Extra bits are masked out when receiving/transmitting data
- Extend tests to verify correct transmission
---
Doneness:
> USART configuration fixes

- docs/reference/firmware.md
- hal/inc/dac_hal.h
- hal/inc/hal_dynalib_gpio.h
- hal/inc/pwm_hal.h
- hal/src/stm32/pwm_hal.c
- hal/src/stm32f2xx/dac_hal.c
- hal/src/template/dac_hal.cpp
- hal/src/template/pwm_hal.cpp
- user/tests/wiring/adc_dac/adc_dac.cpp
- user/tests/wiring/adc_dac/application.cpp
- user/tests/wiring/no_fixture/pwm.cpp
- user/tests/wiring/no_fixture_long_running/pwm.cpp
- wiring/inc/spark_wiring.h
- wiring_globals/src/spark_wiring_gpio.cpp
Closes #841 
This PR implements configurable resolution for analogWrite (PWM and DAC).
New Wiring functions:
- `uint8_t analogWriteResolution(pin_t pin, uint8_t value);`
- `uint8_t analogWriteResolution(pin_t pin);`
- `uint32_t analogWriteMaxFrequency(pin_t pin);`
(see https://github.com/spark/firmware/blob/feature/dac-pwm-resolution/docs/reference/firmware.md for documentation)
DAC on Photon and Electron supports only 12-bit (default) or 8-bit resolution
Resolution also affects maximum frequency that can be used with `analogWrite()` on PWM pins:
Resolution (bits) / Pins (max F)|TIM1: RX, TX|TIM2: RGBR, RGBG, RGBB|TIM3: D2, D3, A4, A5, P1S0, P1S1|TIM4: D0, D1, C4, C5|TIM5: A7
---|---|---|---|---|---|
2|30000000|30000000|15000000|15000000|15000000 …
> DAC and PWM resolution

- hal/src/photon/softap.cpp
The soft AP name was broken by the renaming of the `device_id` field in DCT to `device_code` (that's the soft AP suffix) and the addition of a new `device_id` field (that's the 24 char device id). The soft AP code was still using the `device_id` field.
Test:
- Flash develop, put the device in soft AP and see that the soft AP name is Photon-$ (where $ is some weird suffix)
- Flash fix, see the soft AP name is Photon-AW23 (where AW23 is 4 device specific characters).
---
Doneness:
> Fix soft AP suffix broken by the addition of device id in DCT

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
Fixes #938 
Confirmed that after exiting STOP mode with some other pin specified as a wakeup source, WKP pin retains its configuration (e.g. tone() continues working).
If WKP is specified as wakeup source for System.sleep(), its pinMode will be changed to either INPUT, INPUT_PULLDOWN or INPUT_PULLUP depending on trigger condition. The pin will have to be reconfigured.
---
Doneness:
- N/A - API tests compiled
- N/A Add documentation
> WKP pin should not be enabled as a wakeup source unconditionally for STOP mode

- hal/src/photon/wlan_hal.cpp
Proposal to make the WiFi country behavior backwards compatible with previous firmware versions.
For the country code, we can leave the default country code sent to WICED as JP2 (used in firmware <= 0.5.0). If someone explicitly sets the country code in the Particle DCT section, then we send that to WICED and if that country is Japan we decrease the power.
| Behavior | Particle DCT country | returned WICED DCT country as | write WICED DCT country | WiFi NVRAM image |
|-------------|------------------|-------------|----------------------------|------------------------------|
| Default behavior | blank | jp2 | jp2 | full power |
| Japan | jp2 | jp2 | jp2 | reduced power |
| Other country (for example, UK) | gb0 | gb0 | gb0 | full power |
| Other country (for example, USA) | us4 | us4 | us4 …
> Restore the default WICED country to Japan

- system/inc/system_cloud.h
- system/inc/system_dynalib_cloud.h
- system/src/system_cloud.cpp
- wiring/inc/spark_wiring_cloud.h
Calling `Particle.syncTime()` in a multithreaded app has a small chance of crashing the system if the system thread is currently calling network functions too.
The fix is to call `Particle.syncTime()` on the system thread.
App to reproduce:
```
void setup()
{
Serial.blockOnOverrun(true); //don't ever block for serial integrity
Serial.begin(9600);
WiFi.on();
WiFi.connect();
Particle.connect();
Serial.println("breatheGreen5");
}
static unsigned long millisOfLastPublish = 0;
static unsigned long millisOfLastTimeSync = 0;
void loop()
{
Particle.process();
if( Particle.connected() )
{
if( ( millis() - millisOfLastPublish ) > (unsigned long)random(260, 500) )
{
millisOfLastPublish = millis(); …
```
> Sync time and unsubscribe called on the system thread

- hal/src/stm32f2xx/i2c_hal.c
- user/tests/app/weather3/HTU21D.cpp
- user/tests/app/weather3/SparkFun_MPL3115A2.cpp
- user/tests/app/weather3/SparkFun_Photon_Weather_Basic.cpp
- user/tests/wiring/i2c_mcp23017/application.cpp
- user/tests/wiring/i2c_mcp23017/i2c.cpp
- user/tests/wiring/i2c_mcp23017/i2c_helper.cpp
- user/tests/wiring/i2c_mcp23017/i2c_helper.h
- user/tests/wiring/i2c_mcp23017/interferer.h
- user/tests/wiring/i2c_mcp23017/mcp23017.cpp
- Additional flag check after EVENT_TIMEOUT
- Correct handling of NACK after sending address in HAL_I2C_End_Transmission (write)
- First data byte should be loaded in DR before checking BTF flag in HAL_I2C_End_Transmission
- I2C_FLAG_BTF should be used in place of I2C_EVENT_MASTER_BYTE_TRANSMITTING while transmitting bytes in HAL_I2C_End_Transmission
Slightly connected with #1042. The issue described in #1042 was mainly caused (after removal of `SINGLE_THREADED_SECTION` from wiring i2c functions) by non-monotonic millis()/micros() behavior that was fixed in PR #943, which isn't in 0.5.1. While debugging that, several other non-critical issues were found in I2C HAL.
---
Doneness:
> I2C improvements

- hal/src/stm32/pwm_hal.c
- user/tests/wiring/no_fixture/pwm.cpp
Removes accidental SYSTEM_MODE(MANUAL) from pwm.cpp in wiring/no_fixture. Also restores usage of uint64_t division on Electron for PWM calculations as system-part2 no longer overflows.
---
Doneness:
> Remove accidental SYSTEM_MODE(MANUAL) from pwm.cpp in wiring/no_fixture

- hal/src/photon/wiced/platform/MCU/STM32F2xx/GCC/app_no_bootloader.ld
- modules/photon/system-part2/linker.ld
- user/tests/app/backup_ram/backup_ram.cpp
- user/tests/wiring/api/system.cpp
- user/tests/wiring/no_fixture/system.cpp
adds system backup memory on the Photon (1K - same size as electron) reducing user backup memory to 3K.  api tests confirm that 3K is available for the user app.
---
Doneness:
> photon backup memory

- build/test/core.bats
- build/test/libs.bats
- user/build.mk
Adds libraries from the `lib` directory in extended projects. 
---
Doneness:
ENHANCEMENT
- automatically adds vendored libraries from the `lib` directory for extended application projects [#1053](https://github.com/spark/firmware/pull/1053)
> automatically adds vendored libraries for extended application projects

- docs/reference/firmware.md
- user/tests/wiring/api/time.cpp
- user/tests/wiring/no_fixture/time.cpp
- wiring/inc/spark_wiring_time.h
- wiring/src/spark_wiring_time.cpp
Implements initial Daylight Saving Time (DST) API proposed in #211.
Added Wiring functions:
```cpp
/* Retrieve the current DST offset that is added to the current local time when
* Time.beginDST() has been called.
* The default is 1 hour.
*/
float TimeClass::getDSTOffset();
/* Set a custom DST offset */
void TimeClass::setDSTOffset(float offset);
/* Add the offset from getDSTOffset() to the current time */
void TimeClass::beginDST();
/* Do not add the offset from getDSTOffset() to the current time */
void TimeClass::endDST();
/* Returns true if DST is in effect (beginDST() was called previously) */
uint8_t TimeClass::isDST();
```
---
Doneness:
FEATURE
- added Daylight Saving Time support [#1058](https://github.com/spark/firmware/pull/1058) per proposed …
> Daylight Saving Time support

- services/inc/config.h
- system/src/system_network_internal.h
- system/src/system_task.cpp
- replaces lost reset logic from 'feature/reset-network-flag' (fixes #1045)
- also adds CLR_WLAN_WD() when SYSTEM_FLAG_RESET_NETWORK_ON_CLOUD_ERRORS is disabled
- handle_cloud_errors() was not displaying orange blinks due to HAL_Delay_Milliseconds() not blocking
- handle_cloud_errors() was moved to the end of establish_cloud_connection() to ensure errors are shown
- added debugging info for all of the places ARM_WLAN_WD/CLR_WLAN_WD is called
- added new logic for notify_connected() to ensure ARM_WLAN_WD is not called after DHCP resolves successfully
- handle_cloud_errors() was fixed by making its process atomic, so that background system LED signaling did not interfere.
- Because this fix causes a slight 1 to 1.5 second delay in system code execution, even when multi-threading is enabled. …
> replaces lost reset logic from 'feature/reset-network-flag' (fixes #1045)

- .buildpackrc
- .travis.yml
- build/platform-id.mk
This PR updates how firmware buildpacks are build. It introduces `.buildpackrc` file which specifies for which platforms buildpacks should be prebuild, and for which platforms this firmware is considered stable/prerelease. It also allows to specify which GCC version should be used for specific platform.
With this merged in, it's encouraged to update `RELEASE_PLATFORMS` and `PRERELEASE_PLATFORMS` before releasing new version to reflect how build targets should be created. 
Also added lowercase `p1` platform alias.
---
Doneness:
> Automated buildpack creation

- .buildpackrc
- .travis.yml
- build/platform-id.mk
From original PR https://github.com/spark/firmware/pull/1068
This PR updates how firmware buildpacks are build. It introduces `.buildpackrc` file which specifies for which platforms buildpacks should be prebuild, and for which platforms this firmware is considered stable/prerelease. It also allows to specify which GCC version should be used for specific platform.
With this merged in, it's encouraged to update `RELEASE_PLATFORMS` and `PRERELEASE_PLATFORMS` before releasing new version to reflect how build targets should be created. 
Also added lowercase `p1` platform alias.
---
Doneness:
N/A
> Feature/automated buildpacks 0.5.x

- hal/src/electron/ota_flash_hal.cpp
0.5.x Electron should be aware of system-part3 to allow OTA/YModem updates to >=0.6.0
This is PR #1066 retargeted for `develop-0.5.x` branch.
---
Doneness:
Need to add somewhere that OTA/YModem updates to >=0.6.0 are not possible on electron until first upgrading to 0.5.3 (default).
ENHANCEMENT
- [Electron] System firmware is now aware of system-part3 to allow OTA/YModem updates to >=0.6.0
> [0.5.x] feature/electron/system-part-3

- hal/inc/core_hal.h
- hal/inc/interrupts_hal.h
- hal/src/core/interrupts_hal.c
- hal/src/stm32f2xx/concurrent_hal.cpp
- hal/src/template/interrupts_hal.cpp
- system/src/system_task.cpp
- user/tests/wiring/no_fixture/interrupts.cpp
Original PR #959.
- Fixes #673 
- Requirement for #1073 (`HAL_IsISR()/HAL_WillPreempt()/HAL_ServicedIRQn()`)
---
Doneness:
BUGFIX
- added HAL_IsISR() which is used to skip calling the background loop from delay(). fixes [#673](https://github.com/spark/firmware/issue/673)
> [0.5.x] HAL_IsISR backport (original PR #959)

- hal/inc/core_hal.h
- hal/inc/interrupts_hal.h
- hal/src/core/interrupts_hal.c
- hal/src/core/usb_settings.h
- hal/src/stm32f2xx/concurrent_hal.cpp
- hal/src/stm32f2xx/usb_hal.c
- hal/src/stm32f2xx/usb_settings.h
- hal/src/template/interrupts_hal.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/usbd_conf.h
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/inc/usbd_mcdc.h
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/sources.mk
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_mcdc.c
- services/inc/ringbuf_helper.h
- system/src/system_task.cpp
- user/tests/wiring/no_fixture/interrupts.cpp
- user/tests/wiring/usbserial/application.cpp
- user/tests/wiring/usbserial/usbserial.cpp
- wiring/inc/spark_wiring_usbserial.h
- wiring/src/spark_wiring_usbserial.cpp
- Almost 1-1 USB CDC driver implementation backport from `develop`, without composite support:
- DTR/RTS support (open/closed detection: `Serial.isConnected()`)
- Fixes the issue of USB Serial erroneously switching to closed state
- Various other small fixes and improvements
- Cleaned up old USB HAL (`USB_USART_`) functions to behave like their new (`HAL_USB_`) counterparts in 0.6.x
- Added `wiring/usbserial` tests:
- 0_USBSERIAL_RingBufferHelperIsSane
- 1_USBSERIAL_ReadWrite
- 2_USBSERIAL_isConnectedWorksCorrectly
- 3_USBSERIAL_RxBufferFillsCompletely
This PR includes #1072
---
Doneness:
DTR/RTS support (open/closed detection: Serial.isConnected()) will be _since 0.5.3_
FEATURE
- DTR/RTS support (open/closed detection: `Serial.isConnected()`). …
> [0.5.x] USB Serial implementation backport

- system/src/system_cloud_internal.cpp
Removes the fallback IP that is used when DNS resolution fails. Instead, the cloud connection is failed and the system will have to retry.  This means DNS lookup failure is now consistent with other modes of connection failure. 
Addresses #139 
Related to #1024
---
Doneness:
- Removed hardcoded server IP that was used when DNS resolution fails. Instead, the cloud connection is failed and the system will have to retry.  This means DNS lookup failure is now consistent with other modes of connection failure.  Addresses #139 Related to #1024
> remove IP fallback

- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/usbd_conf.h
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/usbd_composite.c
Fixes issue #1089
https://blogs.msdn.microsoft.com/usbcoreblog/2010/05/18/multi-config-usb-devices-and-windows/ :
> USBCCGP will not load on a multi-config device by default because the hub driver doesn't create a "USB\COMPOSITE" PNP ID for a composite device if it has multiple configurations. However, you can write your own INF that matches a device-specific PNP ID to get USBCCGP to load as your device's function driver.
- follow all steps here, including clearing the cache with the required tools.  Only after then connect your device https://github.com/avtolstoy/particle-usb-testing#windows
---
Doneness:
Disabling multiple USB configurations (normal/high power) as this breaks composite driver on Windows. Fixes [#1089](https://github.com/spark/firmware/issues/1089) Serial and USBSerial1 …
> Disabling multiple USB configurations (normal/high power) as this breaks composite driver on Windows

- system/src/system_network.cpp
- system/src/system_network_internal.h
- user/tests/app/listening_mode_delay_issue_1013/listening_mode_delay.cpp
This PR fixes #1013 by canceling current connection attempt before entering the listening mode.
---
Doneness:
- Cancel current connection attempt before entering the listening mode with WiFi.listen(true) and also WiFi.off(). Fixes [#1013](https://github.com/spark/firmware/issues/1013)
> Fix for listening mode delay

- communication/src/subscriptions.h
`handler.scope` is an enum, and we want its address to be casted to `uint8_t*`, not its value
---
Doneness:
- Particle.subscribe() used with same events but changing scope between PUBLIC and PRIVATE or vice versa would potentially result in non-registered subscriptions.  This was also crashing the GCC virtual device with a segfault when subscription checksums were calculated.
> Bugfix for subscriptions checksum calculation

- hal/src/photon/wlan_hal.cpp
- system/src/system_sleep.cpp
- user/tests/app/stop_mode_power_usage_issue_1098/app.cpp
Fixes #1098
---
Doneness:
- [Photon/P1] Previously, when entering Sleep-stop mode: `System.sleep(D1, RISING, 60);` while in the process of making a Wi-Fi connection resulted in some parts of the radio still being initialized, consuming about 10-15mA more than normal. Fixes [#1098](https://github.com/spark/firmware/issues/1098)
> Uninitialize WICED's WLAN module when turning off the WiFi

- hal/src/gcc/socket_hal.cpp
This PR fixes seemingly random cloud connection errors on virtual device, caused by incorrect error handling in `socket_receive()`: socket hal uses global `ec` variable for exceptionless error handling, and previously any error on unrelated socket (such as socket used for multicast announcement) might affect cloud connection.
Doneness:
- [GCC Virtual Device] Error in socket_hal's socket_receive() logic caused random cloud connection errors.  PR [#1134](https://github.com/spark/firmware/pull/1134)
> Socket HAL bugfix (virtual device)

- ci/build_boost.sh
- ci/install_boost.sh
- ci/run_tests.sh
- user/inc/application.h
- user/tests/unit/json.cpp
- user/tests/unit/makefile
- user/tests/unit/tools/alloc.cpp
- user/tests/unit/tools/alloc.h
- user/tests/unit/tools/buffer.cpp
- user/tests/unit/tools/buffer.h
- user/tests/unit/tools/catch.h
- user/tests/unit/tools/check.h
- user/tests/unit/tools/random.cpp
- user/tests/unit/tools/random.h
- user/tests/unit/tools/stream.h
- user/tests/unit/tools/string.cpp
- user/tests/unit/tools/string.h
- user/tests/unit/vector.cpp
- wiring/inc/spark_wiring_json.h
- wiring/inc/spark_wiring_string.h
- wiring/inc/spark_wiring_vector.h
- wiring/src/spark_wiring_json.cpp
- wiring/src/spark_wiring_string.cpp
This PR is a part 1 of 2 of the code adding support for [runtime logging configuration](https://github.com/spark/firmware/pull/1127), and contains various common tools which I think can be reviewed separately, in order to simplify overall review process. Some background on the topic can be found here: #1037.
This PR adds the following:
**Vector container** ([spark_wiring_vector.h](https://github.com/spark/firmware/blob/feature/usb_logging_1_of_2/wiring/inc/spark_wiring_vector.h#L50))
The problem is that we can't really use STL containers in our firmware (though we do use `std::vector` in some places), as none of them are designed to work with disabled exceptions: it's not possible to write custom allocator that doesn't use exceptions, and standard APIs do not provide any alternative …
> Common tools for the Wiring library and unit testing

- services/inc/config.h
- system/src/main.cpp
This PR fixes #1036 by suspending main thread for some minimum time on every Nth iteration of the application loop. That's probably not the best solution possible, but it allowed to reduce CPU usage from 100 to 10-15% on my machine (Intel Core i7), while keeping reasonable performance comparing to the real devices.
Note that calling `std::this_thread::yield()` has appeared to be insufficient to workaround the problem, also a simple unconditional sleep on each iteration makes an application significantly slower comparing to the same application running on the real device (at least 7 times slower in my tests).
Below is the simple test application that can be used to check how many times application loop is being invoked per second:
```cpp …
```
> Workaround for 100% CPU usage problem on the virtual device

- wiring/inc/spark_wiring_cloud.h
@ScruffR reported a typo in the error message when doing `Particle.function("superLongNameOfFunction", myFunction);`
---
Doneness:
> Fix error message for long function names

- hal/src/electron/modem/electronserialpipe_hal.cpp
- hal/src/electron/modem/electronserialpipe_hal.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/pipe_hal.h
- user/tests/wiring/no_fixture/cellular.cpp
Closes #1138 and #1104.
Fixes several issues:
- `USART_FLAG_TXE` was not checked when writing into DR register from system thread which caused an unsent data byte to be overwritten
- RX flow control was not correctly handled. When an internal `ElectronSerialPipe` buffer overflows, a data byte should be left in DR register to de-assert RTS line to ask modem to pause transmission for a while
- `ElectronSerialPipe` circular buffer was initialized to 1024 bytes, but the implementation allowed only 1023 bytes to be held inside the buffer
- `AT+CLAC`-like commands weren't parsed correctly (thanks @technobly)
Relevant tests:
- `MDM_01_socket_writes_with_length_more_than_1023_work_correctly`
- `MDM_02_at_commands_with_long_response_are_correctly_parsed_and_flow_controlled`
---
Doneness:
- …
> Electron modem USART and buffer handling fixes

- system/src/system_sleep.cpp
- user/tests/wiring/sleep/sleep.cpp
Closes #1155
Fixes a bug introduced by PR #1051/#1076.
Relevant tests:
- `wiring/sleep` (`sleep_2_system_sleep_sleep_mode_wlan_works_correctly`)
---
Doneness:
- System.sleep(30) wasn't reapplying power to the network device after set time.  [[Fixes #1155]](https://github.com/spark/firmware/pull/1156)
> Fixes System.sleep(seconds) or SLEEP_MODE_WLAN behavior

- hal/src/stm32f2xx/usb_hal.c
- user/tests/wiring/usbserial/usbserial.cpp
> USB Serial might deadlock when interrupts are masked

- hal/src/raspberrypi/i2c_hal.cpp
I'd like someone to review the container <-> array buffer code for improvement suggestions.
Specifically how `read` expects an array, but the I2C HAL interface must be able to provide bytes one by one later.
https://github.com/spark/firmware/pull/1187/files#diff-b8a60c5ba8245093dafd297716cb879aR115
And how `write` expects an array, but the data is accumulated through the I2C HAL interface one by one.
https://github.com/spark/firmware/pull/1187/files#diff-b8a60c5ba8245093dafd297716cb879aR148
Questions:
- What's I2C Stop?
- Does I2C only work inside transactions?
> First implementation of I2C for RPi

- docs/dependencies.md
The `homebrew-px4` tap keeps updating the latest GCC compiler version and does not have `gcc-arm-non-eabi-49` any longer.  This edit to the documentation preserves the info needed to install v4.9.3 20150303 of arm-none-eabi-gcc which is the recommended version to use locally when building firmware.
Fixes #1077 
Closes #1103 #1078
---
Doneness:
> fixes docs to install arm-none-eabi-gcc version 4.9.3 20150303

- user/tests/wiring/no_fixture/cellular.cpp
---
Doneness:
- Typo caused a warning during compilation in wiring/no_fixture Cellular tests.
> Typo causes a warning during compilation in wiring/no_fixture Cellular tests

- docs/reference/firmware.md
- wiring/inc/spark_wiring_cloud.h
- wiring/src/spark_wiring_cloud.cpp
As long as we decided to release 0.6.1 instead of 0.7.0, we need to revert API breaking changes in `Particle.publish()` introduced by this PR: https://github.com/spark/firmware/pull/1144.
This PR also adds reference documentation for `WITH_ACK` flag.
---
Doneness:
> Revert Particle.publish() API changes

- docs/reference/firmware.md
- system/inc/system_event.h
- system/src/main.cpp
This PR adds `low_battery` system event, which is generated when low battery condition is detected. The event doesn't carry any data.
I don't have any battery, nor adjustable power supply unit to test this PR properly, so any help with the testing would be appreciated. Test application can be as simple as the following:
``` cpp
SYSTEM_MODE(MANUAL); // Electron will be offline!!!
SerialLogHandler logHandler(LOG_LEVEL_WARN, {
});
void lowBatteryHandler() {
Log.warn("Low battery!");
}
void setup() {
FuelGauge().setAlertThreshold(32); // MAX 32% (default 10%)
System.on(low_battery, lowBatteryHandler);
}
void loop() {
FuelGauge().quickStart();
String stats = String(FuelGauge().getAlertThreshold()) + "(\%) "
+ String(FuelGauge().getSoC()) + …
```
> Generate system event when low battery condition is detected

- system/src/system_sleep.cpp
- user/tests/wiring/sleep/sleep.cpp
Fixes #1155
Fixes a bug introduced by PR #1051/#1076.
Relevant tests:
- `wiring/sleep` (`sleep_2_system_sleep_sleep_mode_wlan_works_correctly`)
---
Doneness:
- System.sleep(30) wasn't reapplying power to the network device after set time.  [[Fixes #1155]](https://github.com/spark/firmware/pull/1156)
> [0.5.x] Fixes System.sleep(seconds) or SLEEP_MODE_WLAN behavior

- system/src/system_cloud_internal.cpp
- user/tests/accept/features/support/env.rb
---
Doneness:
N/A - fixes to 0.6.1-rc.1 commits
> Adds a log string when `spark/device/ota_result` event is published

- user/tests/wiring/no_fixture/system.cpp
SYSTEM_04_button_mirror should "click" SETUP button 3 times instead of 2, as double-click causes Electron to enter soft power down mode.
---
Doneness:
N/A - fixes to 0.6.1-rc.1 commits
> [Electron] SYSTEM_04_button_mirror test fix

- user/tests/accept/features/logging/log_config_app/app.cpp
- wiring/inc/spark_wiring_system.h
- wiring/src/spark_wiring_system.cpp
- wiring/src/user.cpp
This PR makes dynamically configurable logging enabled only if application calls `System.enableFeature(FEATURE_CONFIGURABLE_LOGGING)` explicitly. This allows to significantly reduce size of application binary for applications that don't use logging.
No documentation is provided, since we currently don't have support for dynamically configurable logging in our developer tools, such as the CLI.
---
Doneness:
N/A updates to exiting PR's submitted for 0.6.1-rc.1 (CHANGELOG updated)
> Disable dynamically configurable logging by default

- services/inc/led_service.h
- services/inc/services_dynalib.h
- services/src/led_service.cpp
- system/src/main.cpp
- user/tests/unit/led_service.cpp
This PR adds additional argument for dynalib-exported `led_update()` function (not used in any way at the moment). Motivation is to support real-time LED updates that comply to the LED priorities specified by the system in future.
---
Doneness:
> Additional argument for led_update() function for future extension

- wiring/inc/spark_wiring_usbkeyboard_scancode.h
Added:
- Windows left & right key reference
- Mac command left & right key reference
- *nix meta left & right key reference
**Problem:** Platform-specific command keys not called out in scancode reference. Addition prompted by confusion in the [forums](https://community.particle.io/t/keyboard-press-and-write-do-not-work/28117/).
**Solution:** Add platform-specific command keys to scancode reference.
---
Doneness:
- [[PR# 1217]](https://github.com/spark/firmware/pull/1217) Added Windows, Mac command, & Unix/Linux meta USB keyboard scancode definitions.
> Added Windows, Mac Command, & *nix Meta Keys

- user/tests/wiring/api/string.cpp
- wiring/src/spark_wiring_string.cpp
fixes bug in `String(const char* str, int len)` constructor when the string is longer than the specified length. Instead of extracting just the specified substring, it copies the full string to the smaller buffer, corrupting the heap beyond the buffer.
---
Doneness:
- [[PR #1222]](https://github.com/spark/firmware/pull/1222) Fixed bug in `String(const char* str, int len)` constructor when the string is longer than the specified length.
> string buffer overflow

- wiring/inc/spark_wiring_usbkeyboard.h
- wiring/inc/spark_wiring_usbmouse.h
- wiring/src/spark_wiring_usbkeyboard.cpp
- wiring/src/spark_wiring_usbmouse.cpp
Allows the compiler to garbage collect USBKeyboard and USBMouse implementations if they are not used in user code, saving flash space.
```
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.9.3 20141119 (release) [ARM/embedded-4_9-branch revision 218278]
Electron, 0.6.1-rc.1, app/blank:
5564	      8	   1640	   7212	   1c2c	../../../build/target/user-part/platform-10-m/blank.elf
Electron, this PR, app/blank:
4684	      8	   1572	   6264	   1878	../../../build/target/user-part/platform-10-m/blank.elf
Electron, this PR, app/blank + Mouse.begin() and Keyboard.begin():
5676	      8	   1652	   7336	   1ca8 …
```
> Move Keyboard and Mouse object instantiation into a function to reduce user-part binary size

- communication/src/protocol.cpp
- communication/src/spark_protocol.cpp
Fixes #1181
**NOTE:** Device currently receives incorrect DESCRIBE request with `flags=0x09` (see https://github.com/spark/firmware/blob/dfc5e68866cdd794d17ab51640ca565ae3a757ab/communication/src/protocol_defs.h#L91). The length of the request also seems to be wrong (judging by #1181), and instead of 9 bytes, the device receives 16 bytes, all extra bytes are 0x09:
```
Photon:                        41016b7d02b16409 09 09090909090909
Electron DESCRIBE_SYSTEM:      4101305d01b16441 01
Electron DESCRIBE_APPLICATION: 4101305e02b16441 02
```
The PR accounts for this by assuming that the server actually requests `DESCRIBE_ALL (0x03)`, if describe flags byte `>= DESCRIBE_ALL (0x03)`
---
Doneness:
- [[PR #1226]](https://github.com/spark/firmware/pull/1226) [[Fixes …
> Correctly process APPLICATION/SYSTEM DESCRIBE requests

- docs/reference/firmware.md
- user/tests/wiring/api/cellular.cpp
- user/tests/wiring/no_fixture/cellular.cpp
- wiring/inc/spark_wiring_cellular.h
Implements #961
---
Doneness:
- [[PR #1227]](https://github.com/spark/firmware/pull/1227) [[Implements #961]](https://github.com/spark/firmware/issues/961) [Electron] Added new API for hostname IP address lookup `IPAddress ip = Cellular.resolve(hostname)`
> Cellular.resolve()

- system/src/system_cloud_internal.cpp
Adding logging here without { } was publishing safe mode unconditionally
---
Doneness:
- [[PR #1230]](https://github.com/spark/firmware/pull/1230) Safe Mode event was being published unconditionally
> adding logging here without { } was publishing safe mode unconditionally

- hal/src/electron/modem/enums_hal.h
- hal/src/electron/modem/mdm_hal.cpp
Fixes double newline parser issue on G350 introduced in 428835a
This resolves a case on G350 where **\r\n** is generated after **+USORF** response, but missing
on U260/U270, which would otherwise generate **\r\n\r\nOK\r\n** which is not parseable.  This was preventing the G350 from handshaking with the Cloud on v0.6.1-rc.1.
---
Doneness:
- [[PR #1231]](https://github.com/spark/firmware/pull/1231) [Electron] fixes double newline parser issue on G350 introduced in 428835a v0.6.1-rc.1
> [Electron] Fixes double newline parser issue on G350 introduced in 428835a

- system/src/system_cloud_internal.cpp
This PR fixes possible corruption of an event data in multithreaded firmware. Symptoms of the problem are described here: http://community.particle.io/t/webhooks-corrupt-data-in-multipart-webhook-response/28683
---
Doneness:
> Event data corruption in multithreaded firmware

- user/tests/unit/flags.cpp
- user/tests/unit/tools/catch.h
- user/tests/wiring/api/cloud.cpp
- wiring/inc/spark_wiring_cloud.h
- wiring/inc/spark_wiring_flags.h
- wiring/src/spark_wiring_cloud.cpp
This PR sanitizes `Particle.publish()` overloads, making it possible to specify one or two flags for any variant of this method. The PR also implements a generic type-safe wrapper for enum-based flags, aka `particle::Flags<T>`, which enables regular syntax for ORed flag combinations as an option:
```cpp
Particle.publish("event", "data", PRIVATE | NO_ACK);
```
Fixes #1201 and #1194.
---
Doneness:
[[PR #1236]](https://github.com/spark/firmware/pull/1236) [[Fixes #1201]](https://github.com/spark/firmware/issues/1201) [[Fixes #1194]](https://github.com/spark/firmware/issues/1194) Sanitized `Particle.publish()` overloads.
[[PR #1236]](https://github.com/spark/firmware/pull/1236) [[Fixes #1201]](https://github.com/spark/firmware/issues/1201) [[Fixes …
> Particle.publish() flags fixes

- services/inc/led_service.h
- system/inc/system_led_signal.h
- system/src/system_network_internal.h
- user/tests/unit/led_service.cpp
- user/tests/wiring/no_fixture/led.cpp
- wiring/inc/spark_wiring_rgb.h
- wiring/src/spark_wiring_rgb.cpp
This PR introduces the following changes:
- Fixes potential memory leak and race condition issues in `RGB.onChange()` method.
- Fixes `unit/led_service.cpp` and `wiring/no_fixture/led.cpp` tests that are currently failing intermittently (CH story 1742).
- Raises priority of the listening mode LED indication in single-threaded mode.
_TODO: Update firmware reference_
---
Doneness:
- [[PR #1237]](https://github.com/spark/firmware/pull/1237) Fixes potential memory leak and race condition issues in `RGB.onChange()` function.
- [[PR #1237]](https://github.com/spark/firmware/pull/1237) Added `uint8_t val = RGB.brightness();` getter function.
> RGB LED fixes [ch1742]

- docs/reference/firmware.md
- user/tests/wiring/api/wiring.cpp
- user/tests/wiring/no_fixture/misc.cpp
- wiring/inc/spark_wiring.h
- wiring/src/spark_wiring.cpp
This PR fixes #1193 by adding a check into `map()` function that ensures that incorrect parameters won't cause division by zero error. The PR also overloads `map()` to take `double` arguments.
---
Doneness:
- [[PR #1248]](https://github.com/spark/firmware/pull/1248) [[Fixes #1193]](https://github.com/spark/firmware/issues/1193) Fixes divide by zero on incorrect parameters of `map()` function.
- [[PR #1248]](https://github.com/spark/firmware/pull/1248) Added an overload to `map()` function that takes `double` arguments.
> Avoid division by zero when map() is called with incorrect parameters

- system/src/system_network_internal.h
- system/src/system_task.cpp
This PR fixes #1241 by making `WLAN_CONNECTING` and `WLAN_CONNECTED` flags span over the entire network connection process, including DHCP configuration phase.
I'm not sure how I can write a good test for this fix, so below is my usual test application which I play with to debug network/cloud connectivity problems. Make sure you build the system firmware with debugging enabled and `DEBUG_NETWORK_STATE` macro defined to get internal state of the `ManagedNetworkInterface` class logged.
Tested on Photon and Electron with static and dynamic IP configurations.
```cpp
// SYSTEM_THREAD(ENABLED)
#if PLATFORM_ID == 10
#define Network Cellular
#else
#define Network WiFi
#endif
namespace {
Serial1LogHandler logHandler(115200, LOG_LEVEL_WARN, {
{ …
```
> Fix for WiFi.connecting() returning false during DHCP configuration

- user/inc/Arduino.h
- wiring/inc/spark_wiring_arduino.h
removed extraneous include of math.h in spark_wiring_arduino.h - we only want to include it when Arduino compatibility is enabled (via Arduino.h)
math.h was being included, plus a check for isnan being a defined symbol. This will fail if `<algrithm>` has already been included before the header.  
Only include math.h when Arduino compatibility is requested. (math.h was not included in 0.6.0).
Run the firmware library compile script to validate all libraries that compiled with 0.6.0 continue to compile with this PR.  (this has been done.)
---
- N/A Run unit/integration/application tests on device
- N/A Added documentation
---
- [[PR #1310]](https://github.com/spark/firmware/pull/1310) Fixes a error when `<algorithm>` has already been included before the `math.h` header. Now we only include …
> math.h fix

- hal/inc/cellular_hal.h
- hal/inc/cellular_hal_constants.h
- hal/inc/hal_dynalib_cellular.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/cellular_internal.cpp
- hal/src/electron/cellular_internal.h
- hal/src/electron/modem/enums_hal.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- modules/electron/system-part1/src/cellular_hal.cpp
- system/inc/system_cloud.h
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- system/src/system_network_cellular.h
- system/src/system_network_internal.h
- system/src/system_task.cpp
- user/tests/unit/cellular.cpp
- user/tests/unit/makefile
Supersedes PR #1288 so we can release in 0.6.2-rc.2 instead of 0.7.0-rc.1.
---
[[PR#1311]](https://github.com/spark/firmware/pull/1311) `[Implements CH1537] [Electron]` Added support for Twilio SIMs by default in system firmware.
> Support for Twilio SIMs by default in system firmware [ch1537]

- hal/src/core/interrupts_hal.c
This PR fixes #1136 by reverting what I believe was an accidental change introduced by this PR: https://github.com/spark/firmware/pull/1076.
I don't have a Core device personally, but I've managed to reproduce symptoms of the issue on the Photon, so any help with testing is appreciated.
---
Doneness:
> Fix for attachInterrupt() on the Core

- system/src/system_sleep.cpp
This PR fixes #1176 by making `System.sleep(mode, seconds)` a synchronous operation in multithreaded firmware. This allows to ensure that the device is in a well-defined state before entering sleep mode.
---
Doneness:
> Make System.sleep(mode, seconds) a synchronous operation

- system/inc/system_task.h
- system/src/main.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- system/src/system_task.cpp
This PR fixes #1067 by introducing a flag that can be set from an ISR and cause read/write operations on the cloud socket to fail with a generic error, effectively breaking any busy loop within the comms library.
---
Doneness:
> Interrupt cloud connection when entering listening mode or powering off the device via setup button

- hal/src/photon/wlan_hal.cpp
A simple fix for #1180
---
Doneness:
> WiFi.RSSI() shouldn't report positive values. Constrain RSSI to -1dBm max

- hal/src/gcc/core_hal.cpp
- hal/src/gcc/socket_hal.cpp
- system/src/system_network_wifi.h
Compilation of the firmware currently fails on Mac OS.
Remove unused member variables, add missing functions to the gcc platform's HAL.
firmware/main$ make -s clean all PLATFORM=gcc
---
> Compilation fixes for GCC platform

- user/tests/unit/flags.cpp
- wiring/inc/spark_wiring_cloud.h
- wiring/inc/spark_wiring_flags.h
- wiring/src/spark_wiring_cloud.cpp
This PR fixes a regression introduced into current `develop` by https://github.com/spark/firmware/pull/1236, which allowed `Particle.publish()` flags to be converted to `int` implicitly.
@technobly, thanks for finding out this!
Use type-safe wrapper for individual flag values, similarly to how it was implemented in 0.6.1.
Run unit tests, compile wiring/api tests.
```c
void setup() {
// NO_ACK flag should disable acknowledgement of the event (previously it was changing event's TTL instead)
Particle.publish("event", "data", NO_ACK);
}
void loop() {
}
```
---
> Use type-safe wrapper for flag values

- system/src/system_network_internal.h
The LED doesn't blink rapidly when clearing network credentials.
_Note:_ This regression doesn't present in any of the releases, so there's no need to update the change log.
Use higher priority for the LED indication.
Ensure the device has some network credentials configured, then hold SETUP button for ~10 seconds.
N/A
https://docs.particle.io/guide/getting-started/modes/photon/#wi-fi-network-reset
---
> Fix LED indication when clearing network credentials

- hal/src/stm32f2xx/usb_hal.c
- services/inc/appender.h
- system/inc/system_control.h
- system/src/system_control.cpp
- system/src/system_network_internal.h
Most of the currently supported vendor requests should be executed on system thread instead of being processed in ISR.
Utilize `SystemISRTaskQueue` for vendor requests.
N/A
N/A
---
> Process USB vendor requests in system thread

- communication/src/protocol_defs.cpp
- communication/src/protocol_defs.h
- services/inc/system_error.h
- wiring/inc/spark_wiring_error.h
C++11 defines `std::system_error` class which may cause global name conflicts with the firmware's `system_error` enum, especially in applications that abuse `using namespace std`.
Rename `system_error` enum to `system_error_t`. We never exposed `system_error` as part of any public API, so the fix won't affect existing applications.
The firmware and unit tests should build normally.
N/A
Original community post: https://community.particle.io/t/compile-error-gcc-arm-on-linux-firmware-v-0-6-1/31157
---
> Rename system_error to system_error_t

- hal/src/photon/core_hal.c
- hal/src/stm32f2xx/bootloader.cpp
- hal/src/stm32f2xx/bootloader.h
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.h
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
- platform/MCU/shared/STM32/inc/flash_access.h
_Targets `feature/dct-locking-recursive-mutex` for now because it's based on it. Makes it easier to review the changes. Should be retargeted to `feature/photon/wiced-3.7.0-7` later._
As a safety measure we should verify that when updating bootloader OTA or over YModem the copy operation from ota_module area to the bootloader area has succeeded and the bootloader image in bootloader_module area passes the checks. If not, there is nothing we can do but retry until it does.
Verify the bootloader was flashed correctly and retry if not.
N/A
N/A
N/A
---
> Verify the bootloader was flashed correctly and retry if not

- hal/src/photon/core_hal.c
- hal/src/stm32f2xx/bootloader.cpp
- hal/src/stm32f2xx/bootloader.h
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.h
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
- platform/MCU/shared/STM32/inc/flash_access.h
As a safety measure we should verify that when updating bootloader OTA or over YModem the copy operation from ota_module area to the bootloader area has succeeded and the bootloader image in bootloader_module area passes the checks. If not, there is nothing we can do but retry until it does.
Verify the bootloader was flashed correctly and retry if not.
N/A
N/A
N/A
---
> [Original #1324] Verify the bootloader was flashed correctly and retry if not

- hal/src/photon/socket_hal.cpp
- system/src/system_control.cpp
- user/tests/accept/tools/send_usb_req
- user/tests/app/tcp_server/README.md
- user/tests/app/tcp_server/client/client
- user/tests/app/tcp_server/client/lib/client.js
- user/tests/app/tcp_server/client/lib/device.js
- user/tests/app/tcp_server/client/lib/test.js
- user/tests/app/tcp_server/client/lib/util.js
- user/tests/app/tcp_server/client/main.js
- user/tests/app/tcp_server/client/package.json
- user/tests/app/tcp_server/client/tests.js
- user/tests/app/tcp_server/server.cpp
- wiring/inc/spark_wiring_error.h
- wiring/inc/spark_wiring_ipaddress.h
- wiring/inc/spark_wiring_tcpclient.h
- wiring/src/spark_wiring_ipaddress.cpp
- wiring/src/spark_wiring_tcpclient.cpp
- wiring/src/spark_wiring_tcpserver.cpp
This PR accompanies [TCP server fixes in WICED](https://github.com/spark/photon-wiced/pull/6) and introduces the following changes to improve stability of the firmware's TCP server implementation:
- Update server's list of clients on a client destruction (thanks @tlangmo!).
- `TCPClient` now closes underlying socket on destruction.
- Test app for above fixes (including fixes in WICED).
```
Flash server application to the device:
$ cd ~/firmware/modules
$ make -s all program-dfu PLATFORM=photon TEST=app/tcp_server
Install client dependencies:
$ cd ~/firmware/user/tests/app/tcp_server/client
$ npm install
Run client:
$ ./client
```
---
> TCP server fixes

- ci/unit_tests.sh
- hal/src/electron/dct_hal.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dcd_flash_impl.h
- services/inc/dcd.h
- user/tests/unit/dcd.cpp
- user/tests/unit/makefile
Original #1295 
Hypothesised write errors in flash that appear only after power cycle can corrupt the configuration data.
Flash access is not thread-safe.
Adds CRC checking to the Electron DCD implementation so that write errors are detected.
Add a critical section around flash operations and around DCD operations.
Run the firmware unit tests.
Manual testing:
- flash system firmware to an electron that was connecting to the cloud
- verify that the device continues to connect to the cloud
- make a change in DCD via DFU
- verify the device still connects to the cloud (the DCD contents will have been upgraded to the V2 format.)
This is an internal system change. No example application.
---
> [Original #1295] v2 dcd format and tests

- hal/src/photon/wlan_hal.cpp
See #1098, #1125
```
// FIXME:
// This was required for PR #1125 to reduce Wi-Fi power completely for Sleep stop mode
// however it introduced a new connectivity bug in LwIP that was unresolved in commit 87892a3837d4,
// which was reverted in commit 6b78d7662f62.  WICED should be updated to pull in a newer version of LwIP
// before this change is attempted again.
```
This was fixed by updating WICED to 3.7.0-7, LwIP to 1.4.1 and introducing a couple of fixes to those.
`wiced_wlan_connectivity_deinit`/`wiced_wlan_connectivity_init` is also used for WPA Enterprise as a workaround when BCM chip stops responding under some circumstances.
See #1125.
Related: `wiring/no_fixture` `WIFI_05_reconnections_that_use_wlan_restart_dont_cause_memory_leaks` …
> Bring back part of #1125

- build/checks.mk
Problem: When building on the `develop` branch a compile error recommended using the `latest` branch which doesn't exist.
Solution: Recommend `release/stable` instead.
- [n/a] Run unit/integration/application tests on device
- [n/a] Added documentation
- [n/a] Added to CHANGELOG.md after merging (add links to docs and issues)
> Updates recommended stable branch in compile error

- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/usbd_mcdc.c
With RX queue full, the device NAKs OUT (Host->Device) transfers. With `bInterval` set to `0` (1 ms) this causes the device to spend too much time in USB interrupt, not giving any processing time to the application/system thread to consume RX queue. For some reason CDC driver on OSX doesn't attempt to send any data after about 300 NAKed transfers. Closing/re-opening the port doesn't help either.
Set `bInterval` to a maximum value (16 ms) on OUT endpoint to give enough time for the device to consume RX queue and not send too many NAKs to Host.
We should probably add some workaround as well: e.g. count the number of NAKs sent and silently drop incoming data after a certain threshold instead of NAKing it. Even though this is OSX driver's fault. :face_with_head_bandage:
The bug is easily …
> [USB] Fixes an issue with Serial when receiving consecutive multiple 64-byte transmissions from Host

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
Device panic (assertion failure) occurs when DFU mode is triggered via baud rate change.
Do not read or write feature flags, which are stored in DCT, from an ISR. Users are still allowed to call such methods as `System.reset()` and `System.dfu()` from an ISR to preserve backwards compatibility.
- Try to enable DFU mode via baud rate change.
- Check what happens with System.resetReason(), characterize the behavior.
N/A
N/A
---
> Do not read or write feature flags from an ISR

- hal/src/photon/wlan_hal.cpp
- user/tests/wiring/no_fixture/wifi.cpp
A call to `WiFi.scan()` when WiFi module is off or not ready results in a hard fault.
See #1062
Photon wlan_hal: `sniff_security()` should check that `wiced_wlan_connectivity_initialized()` returns true
- wiring/no_fixture: WIFI_11_scan_returns_zero_result_or_error_when_wifi_is_off
N/A
Closes #1062
---
---
- [`[PR #1354]`](https://github.com/spark/firmware/pull/1354) [`[Fixes #1062]`](https://github.com/spark/firmware/issues/1062) A call to `WiFi.scan()` when Wi-Fi module is off or not ready was resulting in a hard fault.
> [Photon] Fixes WiFi.scan() hardfault

- user/tests/wiring/no_fixture/led.cpp
This PR adds a test for `RGB.onChange()` handler leak which was fixed in https://github.com/spark/firmware/pull/1237
---
---
- [`[PR #1352]`](https://github.com/spark/firmware/pull/1352) Added test for `RGB.onChange()` handler leak
> Test for RGB.onChange() handler leak

- build/arm-tools.mk
Currently, minimum ARM gcc version is set to 4.8.4, which will fail to build firmware starting with 0.7.0.
- Update minimal ARM gcc version to 5.3.1
- Update gcc version check in arm-tools.mk to use `arm-none-eabi-gcc -dumpversion` instead of `arm-none-eabi-gcc --version`
- Check that firmware successfully builds with gcc 5.3.1
- Check that firmware fails to build with gcc < 5.3.1 and reports error:
```
../build/arm-tools.mk:45: *** "ARM gcc version 5.3.1 or later required, but found 4.9.3".  Stop.
```
N/A
Related issue: #1356
---
---
- [`[PR #1358]`](https://github.com/spark/firmware/pull/1358) Updates minimal ARM gcc version required to 5.3.1
> Updates minimal ARM gcc version required to 5.3.1

- crypto/inc/mbedtls_config.h
- wiring/inc/spark_wiring_cloud.h
`PLATFORM=gcc` builds fail on OSX with default gcc compiler (which is actually a wrapper over clang).
- Provide some clang-specific fixes
- `make PLATFORM=gcc clean all` should succeed with OSX gcc:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
N/A
N/A
---
---
- [`[PR #1359]`](https://github.com/spark/firmware/pull/1359) Fixes build with `PLATFORM=gcc` on OSX with clang's gcc wrapper
> Fixes build with PLATFORM=gcc on OSX with clang's gcc wrapper

- user/build.mk
- wiring/inc/spark_wiring_cloud.h
- wiring/inc/spark_wiring_global.h
Beginning with 0.8.0 release, `Particle.publish()` and `Particle.subscribe()` methods will require event scope to be specified explicitly. This change will potentially break a lot of existing applications.
Generate deprecation warning when `Particle.publish()` and `Particle.subscribe()` are used with a default event scope.
Compile and run `wiring/api` test.
```cpp
void setup() {
// Particle.publish()
Particle.publish("event");
Particle.publish("event", "data");
Particle.publish("event", "data", 60);
// Particle.subscribe()
void (*handler1)(const char*, const char*) = nullptr;
Particle.subscribe("event", handler1);
std::function<void(const char*, const char*)> handler2;
Particle.subscribe("event", handler2);
struct Handler3 {
void handler(const char*, const char*) {
}
} handler3; …
```
> Deprecate Particle.publish() and Particle.subscribe() invoked with default event scope

- README.md
This PR adds a clarifying FAQ section to the README about the license of this project and the implications.  Since we've received some concerns from customers about their obligations under the LGPL licensing, we felt it was very important that we make it explicitly clear that they are not expected to share the source code of their application firmware, only distributed changes to system firmware covered by the LGPL.
> Adds "License FAQ" to Firmware Repo

- system/src/system_network.cpp
The system should expose RSSI diagnostic info on platforms that have a wireless network module.
Add `net.rssi` diagnostic data source.
```cpp
namespace {
});
bool logDiagData(void* appender, const uint8_t* data, size_t size) {
Log.write(LOG_LEVEL_INFO, (const char*)data, size);
return true;
}
} // namespace
void setup() {
uint16_t id = DIAG_ID_NETWORK_RSSI;
system_format_diag_data(&id, 1, 0, logDiagData, nullptr, nullptr);
Log.print("\r\n");
}
void loop() {
}
```
* [ch7642]
* #1390 
---
> "net.rssi" diagnostic data

- hal/inc/hal_dynalib.h
- hal/inc/timer_hal.h
- hal/src/core/timer_hal.c
- hal/src/gcc/timer_hal.cpp
- hal/src/stm32f2xx/timer_hal.c
- hal/src/template/timer_hal.cpp
- platform/MCU/newhal-mcu/inc/hw_ticks.h
- platform/MCU/shared/STM32/inc/hw_ticks.h
- platform/MCU/shared/STM32/src/hw_ticks.c
- system/src/main.cpp
- user/tests/wiring/api/system.cpp
- user/tests/wiring/no_fixture_long_running/pwm.cpp
- user/tests/wiring/no_fixture_long_running/ticks.cpp
- wiring/inc/spark_wiring_system.h
The system should report its uptime in seconds.
* ~Add `HAL_Timer_Get_Seconds()` function returning the number of seconds passed since the device was powered on or woken up from sleep.~
* Add `hal_timer_millis()` function returning the number of milliseconds passed since the device was last reset as a 64-bit value.
* Add `System.uptime()` and `System.millis()` methods returning the system uptime in seconds and milliseconds respectively.
* Add `sys.uptime` diagnostic data source.
Run `wiring/no_fixture_long_running` test.
```cpp
namespace {
});
bool logDiagData(void* appender, const uint8_t* data, size_t size) {
Log.write(LOG_LEVEL_INFO, (const char*)data, …
```
> "sys.uptime" diagnostic data

- hal/src/stm32f2xx/bootloader.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
When downgrading from 0.7.0 to 0.5.x firmware, the bootloader needs to be downgraded along with other system modules (see [Release notes](https://github.com/spark/firmware/releases/tag/v0.7.0-rc.3)). This PR simplifies the procedure by making the system automatically downgrade the bootloader if necessary.
Flash 0.7.0 firmware binaries (including bootloader) to a device, and ensure that the system can be downgraded to 0.5.x following the regular downgrade procedure.
- [CH8765]
---
> Bootloader downgrade (0.5.x)

- hal/src/stm32f2xx/bootloader.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
When downgrading from 0.7.0 to 0.6.x firmware, the bootloader needs to be downgraded along with other system modules (see [Release notes](https://github.com/spark/firmware/releases/tag/v0.7.0-rc.3)). This PR simplifies the procedure by making the system automatically downgrade the bootloader if necessary.
Flash 0.7.0 firmware binaries (including bootloader) to a device, and ensure that the system can be downgraded to 0.6.x following the regular downgrade procedure.
- [CH8765]
---
> Bootloader downgrade (0.6.x)

- hal/inc/core_hal.h
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- services/inc/diagnostics.h
- system/src/main.cpp
<details>
```
```
</details>
**NOTE: This PR targets [feature/diagnostics-merge](https://github.com/spark/firmware/tree/feature/diagnostics-merge) branch**
This PR adds the following diagnostic sources:
- Total RAM: ID 25, Type: scalar(32)
-  Total amount of RAM available on the device in bytes. This value normally equals the size of …
> [Diagnostics] RAM usage diagnostic sources

- hal/inc/usart_hal.h
- hal/src/core/usart_hal.c
- hal/src/stm32f2xx/usart_hal.c
- user/tests/wiring/serial_halfduplex/application.cpp
- user/tests/wiring/serial_halfduplex/serial.cpp
Original issue: #1276.
- Adds `SERIAL_HALF_DUPLEX` configuration option to enable half-duplex mode in `begin()`
- Adds `SERIAL_HALF_DUPLEX_NO_ECHO` configuration option to disable echoing (receiver gets disabled while transmitting)
- default USART half-duplex mode set to push-pull
- Adds SERIAL_OPEN_DRAIN, SERIAL_HALF_DUPLEX_OPEN_DRAIN and
- SERIAL_TX_PULL_UP USART config options.
`wiring/serial_halfduplex`
N/A
---
---
- [`[PR #1308]`](https://github.com/spark/firmware/pull/1308) New configuration options added for USART Half-Duplex mode, push-pull outputs are still default.  Adds: `SERIAL_OPEN_DRAIN`, `SERIAL_HALF_DUPLEX_OPEN_DRAIN`, `SERIAL_TX_PULL_UP`, `SERIAL_HALF_DUPLEX`, and `SERIAL_HALF_DUPLEX_NO_ECHO`.
- [`[PR #1308]`](https://github.com/spark/firmware/pull/1308)  [`[Fixes …
> USART half-duplex enhancements

- hal/src/stm32f2xx/device_code.cpp
fixes issue #1380 [ch7922] where invalid characters were appearing after the end of an existing 4-digit setup code. 
Fixes by checking the actual length of the string. The code previously assumed the string was null-terminated, which is not the case typically.  The check looks for any invalid character at location 4 (valid v is (32 < v < 128)) to detect an existing 4-digit code.
- Flash 0.6.2 to the device (`particle update` worked at the time of writing.)
- Erase the existing setup code (my device already had a 6-digit code.)
- `echo -e -n  "\xFF\xFF\xFF\xFF\xFF\xFF" > ff6`
- `dfu-util -d 2b04:d006 -a 1 -s 1852 -D ff6`
- Reboot the device, and enter listening mode
- Use your pc/mobile app to verify the Photon has a 4 digit code
- Flash system part1/2 built from this PR
- Reboot the …
> 4-digit code has extra characters at the end 

- hal/src/photon/wiced/platform/MCU/STM32F2xx/GCC/app_no_bootloader.ld
See #1368 
`link_heap_location` and `link_heap_location_end` definitions missing in linker file.
Cherry-pick a71eba6aed768356a2d696e73fa28aa8ef158eea from #1369
Monolithic build should now succeed.
N/A
Closes #1368
---
---
[`[PR #1370]`](https://github.com/spark/firmware/pull/1370) [`[Fixes #1368]`](https://github.com/spark/firmware/issues/1368) `[Photon/P1]` Fixes Photon/P1 monolithic builds (MODULAR=n) introduced in 0.7.0-rc.2.
> Fixes Photon monolithic builds on 0.7.0-rc.3

- hal/src/stm32f2xx/concurrent_hal.cpp
- services/inc/diagnostics.h
- system/inc/system_event.h
- system/inc/system_power.h
- system/src/system_network_internal.h
- system/src/system_power.cpp
- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- system/src/system_task.cpp
- wiring/inc/spark_wiring_fuel.h
- wiring/inc/spark_wiring_power.h
- wiring/src/spark_wiring_fuel.cpp
- wiring/src/spark_wiring_power.cpp
<details>
```
```
</details>
This PR:
- Adds `DIAG_ID_SYSTEM_POWER_SOURCE` diagnostics data source:
- `POWER_SOURCE_UNKNOWN = 0`
- Default value
- `POWER_SOURCE_VIN = 1`
- The device is being powered by VIN pin or a non-compliant USB-charger
- `POWER_SOURCE_USB_HOST = 2`
- The device is being powered by a USB Host
- …
> [Electron] Power management

- services/inc/diagnostics.h
- system/src/system_network.cpp
- system/src/system_power_manager.cpp
<details>
```
```
</details>
N/A
- Brings back `net:rssi` diagnostic source
- Changes signal strength value diagnostic source id to 37
- Small Electron power management fix disabling some debug logs that might flood the log output under certain conditions
N/A
N/A
N/A
---
> Compatibility net:rssi diagnostic source

- modules/shared/system_module_version.mk
<details>
```
```
</details>
Due to the introduction of #1421, we will need to have an intermediate release that will enable OTA/Ymodem upgrades to the system firmware with WiFi firmware compression (0.8.0-rc.1). The support for this has been included into 0.7.0-rc.4 (#1420). When upgrading from < 0.7.0-rc.4 right now, the device will …
> Photon/P1: adds system-part2 v0.7.0-rc.4 as a dependency of system-part1

- bootloader/src/photon/bootloader_dct.c
- modules/shared/system_module_version.mk
Starting with 0.8.0-rc.1 firmware, part1 on Photon has a dependency on part2 of a specific minimum version. The bootloader doesn't expect that part1 can have any dependencies and fails to import DCT functions, making it impossible to access the DCT when the device is in DFU mode.
Remove the failing dependency check from the bootloader on Photon. The fix requires making an intermediate release (0.7.0-rc.5).
Prepare 3 sets of the firmware binaries:
- 0.7.0-rc.4 (`release/v0.7.0-rc.4` branch).
- 0.7.0-rc.5 (`fix/bootloader_dep_check_0.7.x` branch). Make sure to set [the module versions](https://github.com/spark/firmware/blob/fix/bootloader_dep_check_0.7.x/modules/shared/system_module_version.mk#L3) to 204.
- 0.8.0-rc.1 (`fix/bootloader_dep_check_0.8.x` branch).
Test steps:
1. Flash …
> Remove dependency check in bootloader (0.7.x)

- bootloader/src/stm32f2xx/usbd_desc.c
- hal/src/stm32f2xx/usbd_desc_stm32f2xx.c
- services/inc/bytes2hexbuf.h
- user/tests/unit/service_bytes2hex.cpp
Fixes https://github.com/spark/firmware/issues/1432.
Note: There's no need to increment the bootloader version, since it has already been done in https://github.com/spark/firmware/pull/1433.
Ensure that the USB serial descriptor reports the device ID in all lower case in both the regular and DFU device modes.
- [CH9628]
---
> USB serial number descriptor should report device ID in lower case (0.7.x)

- bootloader/src/stm32f2xx/usbd_desc.c
- hal/src/stm32f2xx/usbd_desc_stm32f2xx.c
- services/inc/bytes2hexbuf.h
Fixes https://github.com/spark/firmware/issues/1432.
Ensure that the USB serial descriptor reports the device ID in all lower case in both the regular and DFU device modes.
- The same fix for 0.7.x release: https://github.com/spark/firmware/pull/1436
- [CH9628]
---
> USB serial number descriptor should report device ID in lower case (0.8.x)

- wiring/src/spark_wiring_fuel.cpp
<details>
```
```
</details>
`FuelGauge.getNormalizedSoC()` currently maps 20% of physical state of charge to 0%. This artificial clamping should be removed for now to avoid any confusion when interpreting diagnostics information.
- [CH9697]
---
> fuelgauge: removes lower 20%-0% state of charge mapping

- wiring/src/spark_wiring_cellular.cpp
This PR makes `Cellular::getDataUsage()` and `Cellular::setDataUsage()` return `false` if the data usage counters cannot be retrieved or updated (e.g. if the network is turned off).
Note: https://github.com/spark/firmware/issues/1171 reports a similar problem with `Cellular::resetDataUsage()`, but I wasn't able to reproduce it. 
Below is the test application that can be used to check the data usage under various scenarios:
```c
namespace {
});
CellularData dataUsage;
void logDataUsage() {
Log.info("ok: %s; cid: %d; tx_session: %d; rx_session: %d; tx_total: %d; rx_total: %d",
(dataUsage.ok ? "true" : "false"), dataUsage.cid, dataUsage.tx_session, …
```
> Fix error handling in the data usage API (Electron)

- build/arm/startup/startup_stm32f2xx_electron.S
- build/platform-id.mk
- communication/src/communication_dynalib.cpp
- hal/inc/hal_dynalib_gpio.h
- hal/inc/interrupts_hal.h
- hal/src/core/interrupts_hal.c
- hal/src/electron/core_hal.c
- hal/src/electron/include.mk
- hal/src/newhal/interrupts_irq.h
- hal/src/photon/core_hal.c
- hal/src/stm32/interrupts_irq.h
- hal/src/stm32f2xx/interrupts_hal.c
- hal/src/template/interrupts_hal.cpp
- modules/electron/system-part3/build.mk
- platform/MCU/STM32F2xx/CMSIS/Device/ST/Include/stm32f2xx.h
- services/src/led_service.cpp
- services/src/panic.c
- user/tests/unit/makefile
- user/tests/wiring/no_fixture/interrupts.cpp
- wiring/inc/spark_wiring_interrupts.h
- wiring/src/spark_wiring_interrupts.cpp
<details>
```
```
</details>
See #1168 #1333
This PR adds two wiring functions `attachInterruptDirect()` and `detachInterruptDirect()` that allow the user code to directly insert interrupt handlers into the interrupt vector table.
- `wiring/no_fixture`: `INTERRUPTS_04_attachInterruptDirect`
```c++
void pvd_irqn_handler() {
// Do …
```
> Low latency (direct) interrupt handlers

- build/module.mk
Commit ee1d29e made it possible to run program-dfu and friends without
first running `make all`, but it also made it so the $(TARGET_BASE).elf
recipe is constantly executed, whether it needs it or not.
The problem is that currently, $(MAKE_DEPENDENCIES) is phony, so real
targets shouldn't depend on that [1]. Phony prerequisites are never up
to date, so neither is anything that depends on them, and make rebuilds
anything that isn't up to date.
One solution is to move the phony prerequisites from the real targets to
program-dfu, which is itself phony. That's how the `all` target worked
before ee1d29e.
[1] https://www.gnu.org/software/make/manual/html_node/Phony-Targets
---
Doneness:
> Only remake $(TARGET_BASE).elf el al. if necessary

- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
- services/inc/dcd.h
- user/tests/unit/dcd.cpp
<details>
```
```
</details>
Despite introduction of #1295, Electrons sometimes still end up corrupting their DCD data (mainly keys).
This PR introduces a bugfix for a scenario where a valid secondary sector (marked with `SEAL_INVALID_V2`) is treated as invalid if primary is lost, causing DCD erasure.
This PR also introduces a couple …
> [Electron] DCD fixes

- wiring/inc/spark_wiring_arduino.h
**Summary of Commits:**
Fix C++ build using std::isnan or std::isinf with explicit namespace specification
**Problem:** 
Using define for using c++ namespaces breaking compilation when names are used with explicit namespace specification. So std::isnan converts to std::std::isnan.
**Solution:** 
use c++ _using_ keyword insead of define.
---
Doneness:
> use 'using std::**' instead of define * std::*

- build/module.mk
This PR fixes an issue introduced by 9aa4b8ff358b472f7a3308f26268a73f7fe88299, which causes GNU make to fail when invoked with such targets as `program-dfu`, `program-ocd`, etc.
Check that the `make -s all TARGET` command work as expected with `program-dfu`, `program-ocd`, `st-flash`, `program-cloud`, `program-serial` targets. 
- https://github.com/particle-iot/firmware/pull/1223
---
> Fix usage of an incorrect prerequisite name in program-* targets

- modules/electron/system-part1/src/export_services2.c
- services/inc/printf_export.h
- services/inc/services2_dynalib.h
- services/src/services_dynalib.c
Some things can be moved out of Electron system-part3 (module index 2) to free up flash space there. See also #1469.
- Export `_tzset_unlocked_r`, `__udivmoddi4`, `mktime`, `__ssvfscanf_r`, `_printf_i`, `localtime_r`
```
72932	    556	   2588	  76076	  1292c	../../../build/target/system-part1/platform-10-m/system-part1.elf
117932	    216	    564	 118712	  1cfb8	../../../build/target/system-part2/platform-10-m/system-part2.elf
115404	   2700	   3988	 122092	  1dcec	../../../build/target/system-part3/platform-10-m/system-part3.elf
3708	    108	   1468	   5284	   14a4 …
```
> Electron: moves some newlib functions into part1

- bootloader/src/stm32f2xx/concurrent_hal.c
- hal/src/stm32f2xx/concurrent_hal.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/periph_lock.h
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/hw_config.c
- user/tests/wiring/no_fixture/concurrent.cpp
The CRC peripheral is not thread-safe and thus concurrent hardware-accelerated CRC calculations should be serialized. 
While there's no evidence that the system and application threads perform CRC calculations concurrently, a synthetic test shows that such a situation can cause invalidation of the DCT.
Guard the platform's `Compute_CRC32()` function with a global lock.
- `wiring/no_fixture`: `CONCURRENT_02*`
- [CH10651]
> Serialize access to the CRC peripheral (STM32F2xx)

- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- system/src/system_network_cellular.h
<details>
```
```
</details>
Only the first `CellularNetworkInterface::connect_cancel()` call succeeds, subsequent calls do not cancel running connection attempt due to the fact that `connect_cancelled` flag is never cleared.
Clear it in `CellularNetworkInterface::connect_finalize()`.
This PR also fixes a method name clash between …
> [Electron] connect_cancel() fix

- hal/src/gcc/socket_hal.cpp
- system/src/system_cloud_internal.cpp
<details>
```
```
</details>
There are two issues that prevent GCC virtual device to successfully connect to the cloud with UDP:
1. (main) The UDP socket is being bound to a multicast address 224.0.0.251, instead of 0.0.0.0 or some interface address
2. Cloud sockets use the same source UDP port, which prevents from running several …
> Fixes GCC virtual device running with UDP protocol

- communication/src/dtls_message_channel.cpp
- communication/src/protocol.cpp
- system/src/system_cloud_internal.cpp
This PR fixes #1172 by ensuring that the application/system description checksums stored in the backup RAM don't get overwritten by invalid values when DTLS context is updated.
1. Flash a blank application with enabled logging to an Electron.
2. Toggle the power off and on to ensure that the persistent session data is invalidated.
3. Check that the device sends the HELLO message.
4. Flash the same application binary to the device OTA.
5. Check that the device skips sending the HELLO message.
- [CH8911]
---
> Fix caching of the description CRCs in the backup RAM

- hal/inc/cellular_hal.h
- hal/inc/hal_dynalib_cellular.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- user/tests/wiring/api/cellular.cpp
- wiring/inc/spark_wiring_cellular.h
This PR fixes #1298 by guarding the implementation of `cellular_command()` with the Cellular HAL's global lock.
Flash the following application to an Electron, and ensure that repeated attempts to update the device OTA don't cause communication errors and hard faults.
```cpp
SYSTEM_THREAD(ENABLED)
namespace {
const Serial1LogHandler logHandler(115200, LOG_LEVEL_INFO, {
});
const unsigned INTERVAL = 500;
unsigned lastMillis = 0;
void onFirmwareUpdate() {
lastMillis = millis();
}
} // namespace
void setup() {
System.on(firmware_update_pending, onFirmwareUpdate);
}
void loop() {
if (lastMillis != 0) {
if (!Particle.connected()) {
Log.info("disconnected");
lastMillis = 0;
} else if (millis() - lastMillis >= INTERVAL) {
Log.info("sending …
```
> Guard cellular_command() with a global lock

- hal/inc/core_hal.h
- hal/inc/hal_dynalib_core.h
- hal/src/core/core_hal.c
- hal/src/gcc/core_hal.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/template/core_hal.cpp
- system/inc/system_sleep.h
- system/src/system_sleep.cpp
- user/tests/wiring/api/system.cpp
- wiring/inc/spark_wiring_system.h
- wiring/src/spark_wiring_system.cpp
<details>
```
```
</details>
See #1345 
Adds `SLEEP_DISABLE_WKP_PIN` `System.sleep()` flag to disable waking up from STANDBY (deep sleep).
- `wiring/api`
```c
void setup() {
}
void loop() {
System.sleep(SLEEP_MODE_DEEP, SLEEP_DISABLE_WKP_PIN, 60);
}
```
- Closes #1345
- [CH1345]
---
> Disable WKP pin waking device up from SLEEP_MODE_DEEP

- system/src/usb_control_request_channel.cpp
- system/src/usb_control_request_channel.h
This PR splits implementation of `UsbControlRequestChannel::processServiceRequest()` into several methods, and adds comments to clarify which methods are called in the context of an ISR. See the discussion here: https://github.com/particle-iot/firmware/pull/1406
- `user/tests/unit`
- `user/tests/app/usb_ctrl_request`
---
> Minor refactoring of the USB protocol implementation

- hal/src/core/core_hal.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/template/core_hal.cpp
- system/inc/system_dynalib.h
- system/src/system_sleep.cpp
- user/tests/app/sleep_multiple_pins/application.cpp
- user/tests/unit/system_task.cpp
- user/tests/wiring/api/system.cpp
- wiring/inc/spark_wiring_system.h
- wiring/src/spark_wiring_system.cpp
<details>
```
```
</details>
**NOTE: Target branch is set to [feature/system-sleep-multiple-pins](https://github.com/spark/firmware/tree/feature/system-sleep-multiple-pins)**
Users should be able to easily determine why the device woke up from STOP mode, especially after introduction of #1405 
- All `System.sleep()` variants now …
> System.sleep() wake up reason

- hal/src/core/i2c_hal.c
Core crashes when I2C is configured in slave mode.
- Fixes incorrectly named interrupt handlers: `HAL_I2C1_ER_Handler`, `HAL_I2C1_EV_Handler`
- Copied relevant I2C slave code from Photon/Electron implementation
`wiring/i2c_master_slave`
N/A
Supersedes #1305
---
> [Core] Fixes I2C slave mode

- modules/electron/system-part3/module_system_part2_export.ld
- modules/shared/stm32f2xx/part2.ld
SYSTEM_07_* memory stress test was failing on the Electron. This was because the heap extended into the region of static RAM for system-part1 (module index 3).
There were no assertions for the symbol `link_heap_location_end` and so this issue went undetected at build time.
Move the upper bound of the heap to before the static RAM block.  The symbol `system_heap_end` was already pointing to the correct location. 
`SYSTEM_07*` in `wiring/no_fixture`
---
> heap upperbound overlaps system-part1 (module index 3) static RAM

- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/inc/usbd_def.h
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_core.c
- platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_req.c
Documents low level USB request completion notifications as suggested in #1406. Replaces literal `1` with `USB_REQ_DATA_STAGE_COMPLETED` for better readability.
- #1406
- [CH10790]
---
> Documents low level USB request completion notifications

- hal/src/electron/FreeRTOSConfig.h
- hal/src/electron/rtos/FreeRTOSv8.2.2/FreeRTOS/Source/tasks.c
- hal/src/stm32f2xx/concurrent_hal.cpp
- user/tests/wiring/no_fixture/cellular.cpp
- wiring/inc/spark_wiring_fuel.h
- wiring/src/spark_wiring_fuel.cpp
<details>
```
```
</details>
1. Cellular band select tests should be performed while deregistered from the network, otherwise current RAT affects a selection of bands available. See *7.22 Select band +UBANDSEL* documentation from u-blox Cellular Modules - AT Commands Manual:
```
TOBY-L2 / MPCI-L2 / LARA-R2 / TOBY-R2 / SARA-U2 / …
```
> Fixes some 0.8.0-rc.2 tests

- wiring/inc/spark_wiring_usbkeyboard.h
The USBKeyboard class inherits from Print and reimplements virtual function `write(uint8_t ch)`.
It does not re-implement `write(const uint8_t *buffer, size_t size)`.
This results in a compiler warning about the second function being shadowed:
```
In file included from ../wiring/inc/spark_wiring_string.h:34:0,
from ../wiring/inc/spark_wiring_stream.h:30,
from ../wiring/inc/spark_wiring.h:38,
from ./inc/application.h:40,
from /home/elco/repos/firmware/platform/spark/modules/Platform.h:4,
from /home/elco/repos/firmware/lib/src/DS2408.cpp:8:
../wiring/inc/spark_wiring_print.h:67:20: warning: 'virtual size_t Print::write(const uint8_t*, size_t)' was hidden [-Woverloaded-virtual]
virtual size_t write(const uint8_t *buffer, size_t size);
^
In file included from ./inc/application.h:51:0,
from …
```
> Fixed shadowing of write(const unint_8_t*, sizte_t) in USBKeyboard

- hal/inc/cellular_hal.h
- hal/inc/hal_dynalib_cellular.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
No way to change the UPSV level so it doesn't get overridden when system firmware re-initializes the modem.
Adds a cellular_hal function to set the UPSV level from 0-3 (default: 1).
- Run test app, look for UPSV=0 in logs.
- Comment out cellular_set_power_mode() and look for UPSV=1 in logs.
```c
void setup() {
cellular_set_power_mode(0, NULL);
Particle.connect();
}
```
---
- [N/A] Run unit/integration/application tests on device
- [N/A] Added documentation
> adds UPSV handling to cellular_hal

- bootloader/src/core/dfu_usb.c
- bootloader/src/core/usb_desc.h
- hal/src/core/usb_hal.c
- platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc/usb_desc.h
When connecting a Core to USB, the serial number reported is a strange number instead of the device ID. The Photon and Electron report their device ID.
```
$ lsusb -v | grep Particle -A 2
iManufacturer           1 Particle          
iProduct                2 Spark Core with WiFi    
iSerial                 3 6D75569D4957
```
This is blocking the CLI from using the USB serial number to detect the device ID of any connected device.
Port USB serial number code from Photon/Electron to Core.
Note: DFU mode still reports the original serial number instead of the device ID. I'm not sure how to recompile and flash the piece of software that contains DFU to a Core. It would be good to update in the long run, but it's not crucial to do it right away.
Connect Core to USB, flash system firmware from …
> Use the device ID as the USB serial number for Core

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- user/tests/wiring/sleep/sleep.cpp
See #1447
Call `PWR_WakeUpPinCmd(DISABLE);` on boot to allow normal WKP/A7 pin operation.
N/A
```c++
static system_tick_t last = 0;
void setup() {
pinMode(A7, OUTPUT);
}
void loop() {
if (Serial.available() > 0) {
System.sleep(SLEEP_MODE_DEEP, 30);
}
if (millis() - last > 1000) {
digitalWrite(A7, !digitalRead(A7));
last = millis();
}
}
```
1. Connect WKP to D7
2. Run the app, D7 should be blinking at 1Hz
3. Connect via serial to the device, send any character
4. The device should go into deep sleep for 30 seconds
5. After waking up it should continue blinking D7 at 1Hz
- Closes #1447
---
> [Photon/Electron] WKP pin needs to be disabled as a wakeup source on boot to allow its normal operation

- user/tests/wiring/no_fixture/logging.cpp
- wiring/inc/spark_wiring_logging.h
- wiring/src/spark_wiring_logging.cpp
Recursive logging freezes the application thread while the LogHandler is trying to acquire a lock on the resource (#1497).
1. Use a `RecursiveMutex` in `spark_wiring_logging.h`
2. Prevent re-entry into subclassed `logHandler` functions `logMessage` and `logWrite` from the `LogManager` instance
Run `TEST=wiring/no_fixture`
- Closes #1497
---
> [Photon/P1/Electron] Recursive logging freezes the application thread while the LogHandler is trying to acquire a lock on the resource.

- hal/src/electron/modem/mdm_hal.cpp
We've been getting reports of times when devices seem to stop being able to receive data.  They seem to recover after the device exhausts its retries (about 78 seconds) and reconnects to the Cloud.  This has been a tricky bug to nail down, but it appears to be a corner case in how the cellular modem reports URCs, or in this case, doesn't report them.
The error condition occurs with the following sequence.  We start with the RX buffer is empty.  We receive some data, and the modem notifies us of this pending data via URC (Unsolicited Response Code). When we go to read that data from the modem, if we received more data concurrently, no further URC is generated after the data is received, or after the read completes.  The error case can occur during a write operation as well (receiving data …
> Fixes missing URCs for received data during TX or RX socket operations

- communication/src/communication_dynalib.h
- communication/src/ping.h
- communication/src/protocol.h
- communication/src/protocol_defs.h
- communication/src/spark_protocol_functions.cpp
- communication/src/spark_protocol_functions.h
- communication/tests/catch/ping.cpp
- system/inc/system_cloud.h
- system/inc/system_dynalib_cloud.h
- system/src/system_cloud.cpp
- system/src/system_task.cpp
- wiring/inc/spark_wiring_cloud.h
`Particle.keepAlive()` API was broken since v0.6.2-rc.2 firmware on Electron where the System could override a User set ping interval.  This required a workaround of updating the keepAlive after the System made a connection to the Cloud.  See issue #1482.
Adds `keepalive_source_t` to infer when Pinger interval should be updated.  The only time the interval will not be updated is when the User has previously set it, and the System tries to override it.  All other cases are updatable.
communication unit tests added and ran by merging this PR with branch `feature/ch13052` then run `firmware/communication/tests/catch $ make all run`
Also the test app found in issue #1482 now works as expected without the workaround.
fixes #1482 
- [N/A] Added documentation
> [Electron] Adds `keepalive_source_t` to infer when Pinger interval should be updated

- communication/src/communication_dynalib.h
- communication/src/functions.h
- communication/src/messages.cpp
- communication/src/protocol.cpp
- communication/src/protocol.h
- communication/src/protocol_defs.h
- communication/src/spark_protocol.cpp
- communication/src/spark_protocol_functions.cpp
- communication/src/spark_protocol_functions.h
- communication/src/variables.h
- system/inc/append_list.h
- system/inc/system_cloud.h
- system/src/system_cloud.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
Device OS API arguments have limitations that can be increased.
| API Field | Old | New | Comment |
|--:|--:|--:|:--|
| Variable Key | 12 | 64 | |
| Variable Data | 622 | 622 | |
| Function Key | 12 | 64 | |
| Function Argument | 63 | 622 | |
| Publish/Subscribe Event Name | 64 | 64 | |
| Publish/Subscribe Event Data | 255 | 622 | Cloud API currently still limits to 255, but Device OS can publish 622.  Will change Cloud API to accept 622. |
| Number of registered Functions or Variables | limited by memory available | limited by memory available | |
An additional feature has been added that will return `false` when attempting to register a `Particle.variable()` or `Particle.function()` that exceeds the memory limits of the describe message (about 800 bytes for the Photon/P1/Electron). …
> [Electron/Photon/P1] Increase Device OS API argument lengths

- hal/inc/cellular_hal.h
- hal/inc/cellular_hal_constants.h
- hal/inc/hal_dynalib_cellular.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/cellular_internal.cpp
- hal/src/electron/modem/dns_client.cpp
- hal/src/electron/modem/dns_client.h
- hal/src/electron/modem/electronserialpipe_hal.cpp
- hal/src/electron/modem/electronserialpipe_hal.h
- hal/src/electron/modem/enums_hal.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- modules/electron/system-part1/src/cellular_hal.cpp
- services/inc/hex_to_bytes.h
- system/src/main.cpp
- system/src/system_network_cellular.h
- user/tests/wiring/no_fixture/cellular.cpp
- user/tests/wiring/no_fixture/tcp.cpp
- wiring/inc/spark_wiring_cellular.h
This PR adds support for U-blox SARA-R410 modules to the Cellular HAL.
The major difference between SARA-U2/G3 and SARA-R4 modules is the network registration process: in case of SARA-R4 the module automatically establishes a PSD (Packed Switched Data) connection as part of the network registration process, so there's no need to activate a PDP context/EPS bearer explicitly. Cellular HAL has been refactored accordingly (and in a backward-compatible way) in order to support different network registration flows.
Additionally, SARA-R4 doesn't currently support the RTS/CTS flow control and this poses a problem for the runtime modem type detection, since we first need to initialize UART without any flow control enabled, detect the modem type and then reinitialize UART if it appears that the …
> Add support for SARA-R410 to the Cellular HAL

- hal/src/electron/modem/dns_client.cpp
`firmware/main$ make clean all -s PLATFORM=electron MODULAR=n` was failing
Adds a few missing headers
Should build without errors `firmware/main$ make clean all -s PLATFORM=electron MODULAR=n`
---
> [Electron] Fixes monolithic build

- wiring/src/spark_wiring_wifitester.cpp
`POWER_ON:;` was operating intermittently in the Sticker Rig during MFG'ing for LTE E-Series modules.
`delay(200)` used in the test routine was changed to `HAL_Delay_Milliseconds(200)` to avoid the situation where the `spark_process()` is run after an accumulation of 1s.  This was causing the device to try to re-connect to the cloud while it was in listening mode, and AT commands were getting interrupted.
Run `firmware/user/tests/accept/sticker-rig` test several times to verify it completes successfully.
E.g. with Python 2.7.14 installed, running:
`python test.py /dev/cu.usbserial-A702OGCQ /dev/cu.usbmodem141441`
Test will complete without failure each time:
`Tests PASSED!!`
---
> [Electron] fixes sticker-rig issue with POWER_ON command

- communication/src/chunked_transfer.cpp
- communication/src/chunked_transfer.h
- communication/src/protocol.h
- communication/src/protocol_defs.h
- communication/src/spark_protocol_functions.cpp
- hal/inc/cellular_hal_constants.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- system/src/system_task.cpp
- GPRS URCs (CIEV: 9,x) were causing SARA_R410 to disconnect
- Fast OTA is not working correctly for SARA_R410
- Kore SIMs on SARA_R410 experience a UDP NAT timeout after 60s
- GPRS URCs disabled on SARA_R410
- disables Fast OTA for SARA_R410
- enables 30 second ping for Kore SIMs on SARA_R410
- Test with Kore SIM on SARA_R410 E Series, should exhibit 30 second ping, port 5684 and use Slow OTA updates.
- Test with any SIM on SARA_R410 E Series with 3rd Party credentials API with no Particle.keepAlive() API, should exhibit 23 minute ping, port 5684 and use Slow OTA updates (should connect using custom APN).
- Test with Twilio SIM on U260 Electron, should exhibit 23 minute ping, port 4500 and use Fast OTA updates.
- Test with Telefonica SIM on U260 Electron, should exhibit 23 minute ping, …
> Bug fixes for SARA_R410 LTE E Series [ch16140]

- communication/src/chunked_transfer.cpp
- communication/src/chunked_transfer.h
- communication/src/protocol_defs.h
- system/src/system_task.cpp
- system/src/system_update.cpp
- Fast OTA on the E Series LTE v0.8.0-rc.8 is disabled pending a Cat-M1 rate limit investigation.  Chunks would hang at index 48 out of 49, and usually be missing most of the 0-48.
- Devices were resetting before sending the UpdateDone ACK to the server, leaving it in a limbo OTA process state for 16 minutes.  During this 16 minutes, the device APIs were blocked (no function calls, etc..)
- Event loop error = 3 (INVALID_STATE) when working around the reset too soon issue with a "Delay 5 seconds before resetting after OTA update" fix.
- Instead of 50 chunks at a time, only 40 are requested (reduces lossy behavior of Cat-M1)
- The Particle Cloud also needs to initially send 40 instead of 50 chunks (currently deployed).
- Multiple UpdateDone replies reduced to one (removes errors)
- Multiple …
> [LTE/Electron] Fast OTA Fixes [ch16346]

- hal/src/electron/modem/mdm_hal.cpp
LTE socket send AT commands in Binary mode are being interrupted with data being received, which causes the send to error.  This subsequently causes a handshake error immediately.  This has been identified as an issue with the u-blox SARA-R410M-02B at this time only and does not seem to affect SARA-U260/U270/G350 modems.
```
socketSendTo(0,34.207.239.88,5684,,91)
1545.444 AT send      36 "AT+USOST=0,\"86.75.309.42\",5684,91\r\n"
1545.460 AT read  >    3 "\r\n@"
1545.510 AT send      91 "\x16\xfe\xfd\x00\x00\x00\x00\x00\x00\x00\x04\x00N\x10\x00\x00B\x00\x03\x00\x00\x00\x00\x00BA\x04\x03t\xe4\xe5?U\xce^.\x80M\xf5\x87\x05\xebI\x92\xafN3\a\xab^,\xe2\xd2\x80E\x18\xf5\xc3\xee\n\xb5{\xb4,Q\x01\xf9\xfd\xc2\x10\xcaZ\x91\xf0+2{\xba5\xcc,F}\x13#\xf0\xa54\ny\xa2"
1545.550 AT read ERR   9 …
```
> [LTE] adds 1 retry for UDP/TCP socket send in case of error [ch18789]

- hal/src/electron/core_hal.c
- services/inc/panic_codes.h
If the system thread or application thread gets stuck attempting to dynamically allocation memory, and the opposing thread subsequently also attempts to allocate memory, the recursive semaphore will deadlock.  This recursive semaphore does have a timeout, but was set to approximately 1193 hours, so basically it would be stalled forever.
- The semaphore lock timeout was changed to 60 seconds, and a new PANIC SOS 14 "Semaphore Lock Timeout" was added to note this condition and reset the device.  The PANIC code is also saved in the last Reset Reason.
- Additionally SPARK_ASSERT() was added to ensure __malloc_lock/unlock is not called from an ISR.
This semaphore deadlock condition is so rare, I could not create a simple user app to force it to occur.  The new PANIC was tested just by adding …
> Fixes recursive semaphore lock timeout [ch21928]

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
Checking and locking the bootloader sector write protection (if needed) on every boot could be contributing to flash memory corruption, although no testing has shown this to occur. It has only occurred naturally in the wild.  See references.
Do not check and lock bootloader write protect on every boot
The idea being that a power glitch could result in the read of sector 0 write protection bits being misinterpreted as unprotected, which would unlock the Option Bytes register to change these bits to be protected.  While writing to Option Bytes register, if power is lost or the MCU is reset, this can result in Read Protection level being set to 1. This is fairly well understood and easy to reproduce, so not attempting to write protect the bootloader on every boot is a great mitigation …
> Do not check and lock bootloader sector write protection on every boot [ch17416]

- hal/src/nRF52840/lwip/lwipopts.h
Despite the fact that we currently don't support IPv6 on non-mesh interfaces, our network stack still processes incoming ND6 (RFC4861) messages. When receiving RA, ND6 code will blindly overwrite DNS servers previously set by DHCPv4.
Disable ND6 packet processing if `NETIF_FLAG_NO_ND6` is set on the interface (particle-iot/lwip#3). This holds true at the moment for all our interfaces.
Check that Argons or Xenons with Ethernet FeatherWing can correctly perform gateway functionality when connected to an IPv6-enabled network on WiFi or Ethernet interface.
N/A
- [CH24688]
---
> [Mesh] Fixes a conflict between DHCPv4 and ND6 DNS server list

- system/src/system_listening_mode.cpp
- system/src/system_listening_mode.h
- system/src/system_network_manager.cpp
- system/src/system_network_manager_api.cpp
Mesh devices currently do not generate any `network_*` or `setup_*` system events.
Fix that :)
**TODO:** Long term, we should revise our network system events and make them per-interface instead.
N/A
N/A
N/A
---
> [Mesh] Network system events

- hal/inc/i2c_hal.h
- hal/src/nRF52840/i2c_hal.cpp
- platform/MCU/nRF52840/inc/sdk_config_system.h
Implement I2C slave
1. Flash `firmware-private/user/tests/wiring/i2c_master_slave/i2c_master` to Xenon-Master
2. Flash `firmware-private/user/tests/wiring/i2c_master_slave/i2c_slave` to Xenon-Slave
3. Watch the output from terminal
Overview:
Master Write:
Master Read:
> Note: The low level delay is clock stretch test
Output log:
[CH19818]
---
> Implement I2C Slave

- hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
- hal/src/nRF52840/mbedtls/sha1_alt.h
- hal/src/nRF52840/mbedtls/sha1_alt_cc310.c
This PR adds hardware-accelerated alternative version of mbedtls SHA1 functions relying on CC310 peripheral available on NRF52840 devices.
N/A
N/A
N/A
---
> [Mesh] mbedtls: adds hardware accelerated sha1

- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/lwip/esp32/esp32ncpnetif.h
- hal/network/lwip/ifapi.cpp
- hal/network/lwip/wiznet/wiznetif.cpp
- hal/network/lwip/wiznet/wiznetif.h
- hal/src/nRF52840/lwip/lwipopts.h
- Sets default hostname to deviceId on Ethernet and WiFi interfaces
- Enables LwIP `LWIP_NETIF_HOSTNAME` option
N/A
N/A
N/A
---
> [Mesh] Adds DHCP hostname for Ethernet and WiFi interfaces

- services/inc/printf_export.h
If eventually the firmware is built with Newlib 3.0.0, then without this change there's an `error: unknown type name '_CONST'` because `_CONST` was [dropped in Newlib 3.0.0](https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=0bda30e1ffd23488aa4a9b73f228089463fbee1a).
This patch follows the same pattern as the change in Newlib and replaces `_CONST` with `const`. Building with previous version of Newlib is unaffected. The firmware already employs the `const` type qualifier.
> _CONST was dropped in Newlib 3.0.0

- hal/network/lwip/nat64.cpp
There is a known issue in Device Service sometimes preventing Gen 3 devices from connecting to a different node from the same source IP and port pair (see [CH23915]). We've introduced a workaround for this in rc.25 by using ephemeral ports for connections over non-mesh network interfaces.
For connections over mesh we use a fixed source port (5684), because we don't want to easily exhaust the gateway NAT64 translation table, however after the gateway resets, first connection from within the mesh will always get 40000 source port on the outside interface after NAT64, which may or may not be the cause of the same issue we've seen on gateway devices in [CH23915].
Randomize initial base NAT64 UDP source port.
N/A
N/A
- [CH25381]
---
> [network] nat64: randomize base source port on boot

- hal/src/argon/network/esp32_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- https://github.com/particle-iot/gsm0710muxer/pull/2
- When the muxer stops asynchronously for example due to a keepalive timeout or due to the other peer requesting to terminate the link, we should unblock the parser as well.
N/A
N/A
- [CH25380]
---
> [NCP] Unblock parser when the muxer exits asynchronously and fixes a race condition in muxer

- hal/network/lwip/ppp_client.cpp
- hal/network/lwip/ppp_client.h
- hal/network/lwip/ppp_ipcp.cpp
- hal/network/lwip/ppp_ipcp.h
- hal/network/lwip/ppp_ncp.cpp
- hal/network/lwip/ppp_ncp.h
- hal/src/nRF52840/lwip/lwipopts.h
- hal/src/nRF52840/lwip/lwippppopts.h
- wiring/inc/spark_wiring_posix_common.h
1. `PBUF_POOL_SIZE` reduced to 16
2. PPP completely disabled on Argon and Xenon
3. Also fixes an endianness issue with `IPAddress` -> `sockaddr_in` conversion
N/A
N/A
N/A
---
> [Gen 3] Some LwIP optimizations

- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/nRF52840/core_hal.c
U201 will auto power-on when it detects a rising VIN. If we perform a power-off sequence immediately after it just started to power-on, it will not be detected and we incur a 10 second delay (power-off timeout).
- Add an artificial delay when cold boot is detected
- This PR also fixes reset reason (`RESET_REASON_POWER_DOWN`/`RESET_REASON_POWER_BROWNOUT` can in fact be supported on NRF52840 devices)
- Cold boot a 3G Boron
- Take a look at the logs, there shouldn't be any `[hal] ERROR: Failed to power off modem` lines
N/A
N/A
---
> [Boron] Fixes a race condition on startup from cold boot (U201)

- hal/src/boron/cellular_hal.cpp
The following code will cause a crash on Boron:
```
STARTUP(Cellular.setActiveSim(EXTERNAL_SIM));
STARTUP(Cellular.setCredentials("spark.telefonica.com", "", ""));
```
The issue stems from the fact that user-part C++ constructors are executed very early before the whole networking subsystem is properly initialized.
Use static member functions of `CellularNetworkManager` in `cellular_hal` instead of obtaining (and as a consequence constructing) its instance in functions managing credentials.
Run the example app. It shouldn't crash.
```cpp
STARTUP(Cellular.setActiveSim(EXTERNAL_SIM));
STARTUP(Cellular.setCredentials("spark.telefonica.com", "", ""));
void setup() {
}
void loop() {
}
```
- [CH25566]
---
> [boron] cellular_hal: fixes a crash with STARTUP() macros and credentials management functions

- .buildpackrc
Until this branch is merged with `develop`, the Gen 3 platforms should be specified in `.buildpackrc` to support automated buildpack creation on git tag.
> Mark Gen 3 platforms as prerelease

- hal/src/nRF52840/lwip/lwipopts.h
- hal/src/nRF52840/lwip/sys_arch.c
- third_party/lwip/build.mk
Xenons with Ethernet FeatherWing and Argons go into panic state due to an assertion failure in LwIP DHCP code when receiving a DHCP OFFER with more than 2 DNS servers.
1. Fix the bug in LwIP code: https://github.com/particle-iot/lwip/pull/4
2. Disables LwIP assertions in non-debug builds
Configure DHCP server to provide more than 2 DNS servers. The devices should successfully lease an IP address without going into panic.
N/A
- https://github.com/particle-iot/lwip/pull/4
- [CH25692]
- [CH25694]
---
> Fixes an assertion failure in LwIP DHCP code when receiving an offer with > 2 DNS servers

- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/user.cpp
- hal/src/nRF52840/user.h
- system/src/system_task.cpp
When flashing a user-part that depends on the newer version of system-part1, hybrid firmware will overwrite that user part with the embedded tinker due to failed dependency check (https://github.com/particle-iot/firmware/blob/mesh-develop/hal/src/nRF52840/core_hal.c#L352), preventing safe mode from triggering and as a consequence preventing safe mode healer from applying newer system-part1 to resolve the dependencies.
Flash the embedded tinker only if there is no valid user module or it fails to pass the integrity check. Dependencies shouldn't be checked.
This PR also fixes safe mode LED indication priority issue.
1. Build with `HYBRID_BUILD=y INCLUDE_APP=y`
2. Flash `system-part1`
3. Erase user-part
4. Reset
5. The device should boot into tinker
6. Bump module versions, rebuild normal …
> Fixes user part update procedure in hybrid build

- hal/network/ncp/at_parser/at_parser.cpp
- hal/network/ncp/at_parser/at_parser.h
- hal/network/ncp/at_parser/at_parser_impl.cpp
- hal/network/ncp/at_parser/at_parser_impl.h
- hal/src/argon/network/esp32_ncp_client.cpp
The AT command parser logs all AT commands and responses, including WiFi passwords on the Argon platform. Given that we often request device logs from the users this may disclose their sensitive data.
- Update the parser to make it possible to disable logging for certain commands.
- Disable logging of the echo received from the NCP.
Compile and flash the firmware and make sure the WiFi password doesn't get logged during the network connection.
---
> Do not log WiFi passwords

- platform/MCU/nRF52840/inc/sdk_config_bootloader.h
- platform/MCU/nRF52840/inc/sdk_config_system.h
- platform/MCU/nRF52840/src/hw_config.c
nRF52840 MCU can easily operate at voltage as low as 1.7V, however the external QSPI flash we are using requires at least 2.8V, thus we require some form of undervoltage protection, because several key components of the DeviceOS rely on the external flash: DCT, OpenThread settings, WiFi settings.
We've previously introduced a workaround in the bootloader: we've enabled nRF52840 power failure comparator configured for 2.8V in early boot for about 200ms, checked if a failure was detected and reset the device if so.
This PR enables the power failure comparator in early boot as well, but keeps it running with a registered handler function which will reset the device if power failure is detected at any point in time while the device runs.
Use lab power supply and gradually decrease voltage to …
> [nrf52840] Enables power failure comparator on boot with a registered power failure handler that resets the device

- system/src/system_power.cpp
- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- wiring/src/spark_wiring_power.cpp
Modem on Electron/LTE turn off unexpectedly during initialization when powered from a USB Host only (no battery).
After an investigation it was discovered that the PMIC watchdog causes current limit to drop to 100mA temporarily which causes the modem to stop responding to AT commands.
Power Manager no longer using PMIC watchdog because it causes current limit to drop to 100mA temporarily when it expires
**Workaround:** For 0.8.0-rc.1 ~ 0.8.0-rc.11, add `PMIC().disableCharging()` to `setup()` when no battery is used.
1. Program an Electron with this PR's firmware
2. Leave the battery disconnected, powered via USB only
3. The system will check for a disconnected battery every 40 seconds
4. The device should stay connected, AT commands should continue to work.
5. Compared to 0.8.0-rc.11 …
> [Electron/LTE] Power Manager Watchdog Timer Fix

- communication/src/protocol.cpp
After OTA the device should send the HELLO message so it gets prompted to send its describe message.
Occasionally after sending the HELLO message, the cloud communications fail. After reconnecting, it does not send the HELLO message again so the version of firmware running on the device is not updated in the database.
The correct logic is in `DTLSMessageChannel`, but this sticky flag that gets set before we hear anything back from the cloud in fact breaks it in case the cloud disconnects before the describe message is sent since the HELLO won't be sent after reconnecting.
* `$ particle flash tinker-serial1-debugging-0.8.0-rc.25-xenon.bin  --usb`
* Pull power
* Verify in the database that current_build_target is 0.8.0-rc.25
* `$ particle flash x2 system-part1-0.8.0-rc.26-xenon.bin`
* …
> Do not set the sticky skip hello after handshake

- system/src/system_network_manager_api.cpp
Interface state list in Network Manager is not populated until `network_connect()` call is made.
Populate it in `network_setup()`.
N/A
N/A
N/A
---
> Fixes Network Manager initial state after network_setup()

- hal/src/electron/modem/mdm_hal.cpp
AT+CNUM command is used in the registration process just to log the phone number of the inserted SIM.  It has been observed that some SIMs in LTE devices have invalid characters in the phone number string that causes this command to error.  
```
40.796 AT send       9 "AT+CNUM\r\n"
40.826 AT read ERR  49 "\r\n+CME ERROR: invalid characters in dial string\r\n"
```
This prevents the registration process from completing and the device will blink green continuously.
Remove the AT+CNUM command.
Test on a unit that was previously causing this error.  It should now connect without a problem.
---
> [LTE] AT+CNUM command causing registration failure on LTE devices

- hal/src/photon/miniz.h
The decompression of the WiFi blob firmware, which is performed every time `WiFi.on()` is called, requires about 10K of heap memory in 0.8.0-rc.11, and such an increased memory usage can pose a problem for user applications.
- Tweak miniz to reduce the size of the decompressor context structure (`tinfl_decompressor`). The fix in this PR reduces the size of the structure from 10 to 5K at the cost of some performance hit. I would appreciate double-checking if the proposed change is safe.
- ~Do not reset the network interface on cloud connection errors on the Photon. The previous behavior can be enabled by setting [`SYSTEM_FLAG_RESET_NETWORK_ON_CLOUD_ERRORS`](https://prerelease-docs.particle.io/reference/firmware/photon/#system-flags-disable-) in a user application.~
Flash the following …
> [Photon] Memory usage optimizations

- hal/src/photon/socket_hal.cpp
- hal/src/photon/wlan_hal.cpp
- system/src/system_cloud_internal.cpp
Socket operations, such as `socket_close()`, may cause a hard fault when performed after a WiFi reset.
Invalidate all sockets when WiFi is being turned off. It is important to keep socket handles allocated via `socket_create()` valid.
The following application should not cause a hard fault or deadlock:
```cpp
SYSTEM_MODE(SEMI_AUTOMATIC)
namespace {
});
system_tick_t lastMillis = 0;
bool done = false;
} // namespace
void setup() {
Log.info("setup()");
}
void loop() {
if (done) {
if (millis() - lastMillis >= 3000) {
Log.info("loop()");
lastMillis = millis();
}
return;
}
done = true;
Log.info("WiFi.connect()");
WiFi.connect();
Log.info("socket_create()");
const sock_handle_t sock = …
```
>  Invalidate sockets when turning WiFi off

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
DCT operations in WICED 3.7.0 consume significantly more stack memory than in WICED 3.3.0. This may cause a stack overflow in `HAL_Core_System_Reset()`, which checks whether the reset info feature flag is set in the DCT.
Cache persistent feature flags in RAM.
The application provided in the [original issue](https://github.com/particle-iot/firmware/issues/1513) should work correctly without changing the default stack size of the watchdog thread.
- [ch26433]
> Cache persistent feature flags

- user/tests/wiring/api/thread.cpp
- user/tests/wiring/no_fixture/thread.cpp
- wiring/inc/spark_wiring_thread.h
Wait for Wiring `Thread` to reach `Thread::run` before returning from the constructor to avoid HardFault crash when the Thread instance is not available anymore.
Fixes #1527. See that issue for details, steps to reproduce and example app.
This is a regression that was introduced in 0.7.0. It should be backported to the 0.7.x line.
- [CH17452]
> Wait for Wiring Thread to start

- hal/src/nRF52840/newlib.cpp
- rt-dynalib/inc/rt_dynalib.h
Currentl libc `assert()` will simply trigger `abort()` and `_exit()`, which doesn't really give us any insight into the cause of the failure.
This PR implements newlib `__assert_func()` that logs the assertion failure information and executes the correct panic handler.
Run the test app, open device's serial port, log output should contain assertion failure info.
```cpp
void setup() {
}
void loop() {
if (Serial.isConnected()) {
assert(false);
}
}
```
N/A
---
> [nrf52840] hal: implements __assert_func() to handle libc assert()

- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/lwip/esp32/esp32ncpnetif.h
- hal/src/argon/wlan_hal.cpp
- system/src/system_setup.cpp
The Argon shows MAC address with "00:00:00:00:00:00" in Listening Mode with command `m` which is incorrect.
Allows to read MAC address from NCP even the interface is not up yet.
1. Compile and load system-part1 using DFU to an Argon.
2. Enter Listening Mode and press `m`, it should show the Wi-Fi MAC address correctly.
3. Using `$ particle serial mac` should also show it correctly.
---
> Fixes to the Argon in Listening Mode showing wrong MAC address with the command `m`.

- hal/src/argon/network/esp32_ncp_client.cpp
Fixes a regression introduced by #1608: `updateFirmware()` always returns `SYSTEM_ERROR_INVALID_STATE` despite applying the update successfully.
Manually stop the muxer after applying the update, wait for the NCP to reset, re-enable the client and reset client state.
```console
$ particle flash --serial argon-ncp-firmware-0.0.5-ota.bin
```
The device log should contain the following line right before resetting:
```console
0000087159 [hal] INFO: ESP32 firmware version updated to version 5
```
```cpp
Serial1LogHandler dbg(115200, LOG_LEVEL_ALL);
void setup() {
Network.listen(true);
}
void loop() {
}
```
N/A
---
> [argon] ncp: updateFirmware() after the NCP reset needs to re-enable the client

- user/tests/wiring/no_fixture/system.cpp
This PR fixes the `SYSTEM_04_button_mirror` test from the `wiring/no_fixture` suite.
---
> Fix SYSTEM_04_button_mirror test

- system/inc/system_event.h
- system/src/main.cpp
- system/src/system_event.cpp
- user/tests/wiring/no_fixture/system.cpp
Prior to the changes introduced in https://github.com/particle-iot/firmware/pull/1600, there was a bug in `system_notify_event()` that was causing a system panic in multithreaded applications when a button event was generated. That PR fixed the problem by making all button handlers asynchronous, which, however, is a breaking change, and we'd like to avoid introducing breaking changes at this point.
- Execute button event handlers synchronously in the ISR. This matches the behavior of a single-threaded firmware in 0.6.x and 0.7.0.
- Also makes the out_of_memory event synchronous.
- Make sure `system_notify_event()` doesn't attempt to allocate memory in an ISR.
**Note:** This is a temporary solution. Ideally, it should be up to an application developer to decide which event handlers need to …
> Execute button and OOM event handlers synchronously

- hal/network/lwip/openthread/lwip_openthreadif.cpp
- wiring/src/spark_wiring_udp_posix.cpp
The following app will trigger an [assertion failure](https://github.com/particle-iot/openthread/blob/release/20181217-particle/src/core/net/netif.cpp#L124) in OpenThread:
```cpp
void setup() {
Mesh.subscribe("test", [](const char* a, const char* b) {
});
}
```
This is a side-effect of OpenThread upgrade. It was previously possible to manage multicast subscriptions even if OpenThread netif was down or not fully up. In order to resolve this issue, we are adding a check for `otIp6IsEnabled()` in `OpenThreadNetif::mldMacFilterCb()` that manages multicast subscription state between LwIP and OpenThread. If OpenThread netif is down, we will keep them stored and will synchronize the state once it comes up.
This PR also enables wiring `UDP` logs only in `DEBUG_BUILD=y` …
> Fixes an assertion failure (SOS 10) with Mesh.subscribe() and threading enabled

- hal/src/electron/modem/mdm_hal.cpp
A unique situation on LTE devices appears when cellular coverage drops briefly and the device remains unreachable until reset.
If cellular coverage drops and comes back just as the cloud socket close operation is executing.  The observed issue is that the cloud socket handle on the modem is attempted to be closed, but at the time the modem is unable to process the request.  The socket is freed from the lookup table in RAM and when the system attempts to re-connect to the cloud, a new socket is requested and the modem returns handle 1 on port 5684.  0 is still open on port 5684 and the modem apparently doesn't mind having two sockets open on the same port.  Data is sent on handle 1 and expected back on handle 1, but it's being received on handle 0 by the modem.  This state persists until …
> Fixes unique stale socket issue with LTE devices

- hal/src/gcc/readme.md
Trying to build a virtual device on macOS and ran into the issue.
> Mojave doesn't ship with `wget`

- hal/src/boron/cellular_hal.cpp
Boron in Listening Mode does not show IMEI and ICCID.
```console
i
Device ID: XXXXXXXXXXXXXXXXXXXXXX
Device Secret: XXXXXXXXXXXXXX
Serial Number: XXXXXXXXXXXXXX
IMEI:
ICCID:
v
system firmware version: 0.8.0-rc.26
```
Ensure that the modem is on before trying to retrieve IMEI and ICCID in `cellular_device_info()`.
Put the Boron into listening mode, open its serial port, send 'i', it should correctly output IMEI and ICCID.
N/A
- [CH26968]
---
> [Boron] Ensure that the modem is on before trying to retrieve IMEI and ICCID

- bootloader/src/nRF52840/usbd_device.cpp
- bootloader/src/nRF52840/usbd_dfu.cpp
- bootloader/src/nRF52840/usbd_wcid.h
WinUSB driver is not being automagically attached to DFU interface on Windows.
Fixes [WCID](https://github.com/pbatard/libwdi/wiki/WCID-Devices) handling in the bootloader.
Flash the bootloader, connect to a Windows machine, the device should automagically show up in Device Manager under USB devices with WinUSB driver. `dfu-util` should work without requiring to use Zadig or anything else.
N/A
N/A
---
> [Mesh] Fixes WCID in bootloader

- build/checks.mk
`git` should not be a build dependency.
It is possible for the firmware to build correctly without having `git` installed. Currently, `git` is used to test which branch is being built and offer a warning message if you are working on the `develop` branch, without the having specified the `PARTICLE_DEVELOP` environment variable.
The branch check forces a dependency on Git and spews error messages in its absence. The false positive error messages obfuscate true errors and warnings, which make it harder for a developer to monitor and catch warnings and errors.
Gate the logic in `checks.mk` behind a check to see if `git` is installed
Build the firmware
N/A
--------
> Bypass git dependency in build

- hal/src/electron/rtos/FreeRTOSv8.2.2/FreeRTOS/Source/timers.c
The [Particle software timers aka `Timer`](https://docs.particle.io/reference/device-os/firmware/photon/#software-timers) use the FreeRTOS timer feature. FreeRTOS version 8.2.2 used on the Electron introduced a bug where timers stop triggering after an overflow of the tick count, which happens after ~49 days.
Rather than upgrade the whole FreeRTOS this PR backports the bugfix from https://github.com/cjlano/freertos/commit/f780d64f5244431c609696f7ca1c3e06ea268a76#diff-ed9ddddbc8c65ef44735bc5950056ef7R474
Steps to validate the issue and fix:
1. Modify https://github.com/particle-iot/device-os/blob/0b83dbf09fb9c98d910c91ac39d0a75c983fecad/hal/src/electron/rtos/FreeRTOSv8.2.2/FreeRTOS/Source/tasks.c#L1593 to trigger the timer overflow soon after boot
```
xTickCount = ( TickType_t ) …
```
> [LTE/Electron] Fixes software Timer()'s halting after millis() overflows (every 49.7 days)

- hal/src/electron/modem/electronserialpipe_hal.cpp
- hal/src/electron/modem/electronserialpipe_hal.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- hal/src/electron/modem/pipe_hal.h
- user/tests/wiring/no_fixture/cellular.cpp
- user/tests/wiring/no_fixture/pwm.cpp
Several LTE bugs have been found that all revolve around socket AT commands being prone to various types of failure.  See below.
- If signal was lost before socket send, first command would timeout, during retry if signal was restored the first command would send and return OK instead of the second command requiring a PROMPT.  We would return a socket error instead of signaling data was sent OK.  This caused a network teardown and reconnection unnecessarily.
- Also adjusts the timeouts for various commands used during socket send operations.
- Despite eDRX mode being disabled via CEDRXS=0, it would still indicate \r\n+CEDRXS: 2, ... \r\n
- Now with CEDRXS=3,2 it will respond as fully disabled \r\n+CEDRXS:\r\n
- If signal was lost before data sent, the AT interface would hang until the …
> [LTE/Electron] bug fixes and enhancements

- hal/src/boron/cellular_hal.cpp
- user/tests/hal/cellular/application.cpp
- user/tests/hal/cellular/test_cellular_command.cpp
Providing Cellular command on Gen 3 Devices to allow testing customer AT commands.
Given `AT Parser` has helped do some formatting work, for compatibility, we add some workarounds to make sure the behavior has the same result as it on Gen 2 devices.
**unsupported feature:**
- Not support SMS, need to support `>` AT response int AT Parser
- Not support Socket, need to support `@` AT response in AT Parser
1. Flash unit test application `user/tests/hal/cellular` to Electron and Boron
`user/tests/hal/cellular/test_cellular_command.cpp`
[CH26290]
---
> Basic implementation for cellular command

- hal/inc/core_hal.h
- hal/inc/exflash_hal.h
- hal/inc/hal_dynalib_core.h
- hal/inc/timer_hal.h
- hal/src/core/core_hal.c
- hal/src/gcc/core_hal.cpp
- hal/src/mesh-virtual/core_hal.cpp
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/exflash_hal.c
- hal/src/nRF52840/interrupts_hal.cpp
- hal/src/nRF52840/openthread/alarm.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/template/core_hal.cpp
- platform/MCU/nRF52840/inc/sdk_config_system.h
- platform/MCU/nRF52840/src/hw_config.c
- system/src/system_network_manager_api.cpp
- system/src/system_sleep.cpp
- user/tests/app/sleep_multiple_pins/application.cpp
- user/tests/wiring/sleep/sleep.cpp
STOP mode is not implemented for Gen 3 devices.
Well, implement it.
- :heavy_check_mark: `app/sleep_multiple_pins`
- :heavy_check_mark: `wiring/sleep`
- [CH26710]
- [CH27767]
---
> [Gen 3] STOP sleep mode support

- user/tests/readme.md
- user/tests/scripts/country-updown/country-updown.sh
- user/tests/scripts/p1sflashtest/p1sflashtest.sh
- user/tests/scripts/upgrade-downgrade/upgrade-downgrade.sh
- user/tests/wiring/spi_master_slave_alt/spi_master/application.cpp
- user/tests/wiring/spi_master_slave_alt/spi_master/spi_master.cpp
- user/tests/wiring/spi_master_slave_alt/spi_master/test.mk
- user/tests/wiring/spi_master_slave_alt/spi_slave/application.cpp
- user/tests/wiring/spi_master_slave_alt/spi_slave/spi_slave.cpp
- user/tests/wiring/spi_master_slave_alt/spi_slave/test.mk
Some Device OS release tests are missing from the repo
Add missing tests that are only on Brett's machine :)
- adds upgrade-downgrade, country-updown scripts and updates tests README.md
- cleanup p1sflashtest script, add exit codes
- adds SPI Master / Slave (ALT) test
---
> [Internal] Adds missing Device OS release tests

- hal/src/argon/network/esp32_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
NCP client may end up in a half-initialized state if early initialization in `initReady()` fails. Unless the calling code catches this and manually resets the state via `client->off()`, the NCP client will be left in a broken state.
Catch `initReady()` failure in `waitReady()` and reset NCP state.
1. Set `setup_done` flag to `0xff` (unset)
2. Configure Boron to use external SIM, don't plug it in
3. Reset the device, it should end up in listening mode, open its serial port and run `i` command
4. ICCID and IMEI should be empty
5. Plug SIM card in
6. Run `i` command two more times, the second time IMEI and ICCID should be printed normally
N/A
N/A
---
> [Gen 3] NCP state reset

- docs/dependencies.md
On MacOS High Sierra 10.13.3:
running the `brew install gcc-arm-none-eabi-53` step fails:
```Error: gcc-arm-none-eabi-53: /usr/local/Homebrew/Library/Taps/px4/homebrew-px4/gcc-arm-none-eabi-53.rb:13: syntax error, unexpected keyword_end```
Adding quotes on line 13 around the prefix command fixes the problem.  they need to be escaped in the echo command.
Running again we see the following problem:
```undefined local variable or method `gcc' for Formulary::FormulaNamespace400315692c1c92e387b328263702f935:Module```
removing gcc-arm-none-eabi-53.rb from the first line of the ruby file allows for successful installation. 
copy and paste of the new text allows brew install to succeed without errors:
```
brew install gcc-arm-none-eabi-53
==> Installing gcc-arm-none-eabi-53 from px4/px4
Warning: …
```
> [Internal] Fix `brew install gcc-arm-none-eabi-53` formula

- hal/src/electron/modem/mdm_hal.cpp
Cellular.RSSI() does not work on Electron G350 due to RAT (Radio Access Technology) being unknown, and subsequently conversion of values errors out.  This affects the Cellular.RSSI() API and also Device Diagnostics.
During registration, default to RAT = ACT_GSM if device is Electron G350.
- Observe with v1.0.0 or v1.0.1 firmware and Tinker, Device Diagnostics contains no `device.network.signal.strength:` info.
- Compile with this PR and everything works as expected, assuming the device really has a signal.
Examples of the issue here:
https://community.particle.io/t/no-signal-strength-information-for-electron-2g-on-device-os-1-0-0/47460/10?u=bdub
---
---
- [Bugfix] [Electron] [G350] fixes Cellular.RSSI() issues due to unknown RAT [#1721](https://github.com/particle-iot/device-os/pull/1721)
> [Electron] [G350] fixes Cellular.RSSI() issues due to unknown RAT

- hal/network/ncp/at_parser/at_response.cpp
- hal/network/ncp/at_parser/at_response.h
- hal/src/boron/network/sara_ncp_client.cpp
- wiring/inc/spark_wiring_vector.h
This PR sets the modem to the LTE Cat M1-only mode during the initialization, and also disables eDRX individually for each reported RAT (`AT+CEDRXS=0` doesn't seem to disable eDRX correctly).
1. Make sure the modem is set to the factory default settings, e.g. by using the following commands:
```
AT+URAT=7,8
AT+CEDRXS=1,2,"1001"
AT+CEDRXS=1,4,"1001"
AT+CEDRXS=1,5,"1001"
```
2. Make sure the NCP client overrides the default settings during the modem initialization.
- [ch29791]
---
---
- [Enhancement] [Boron/LTE] Enable Cat M1-only mode and disable eDRX completely [#1723](https://github.com/particle-iot/device-os/pull/1723)
> [Boron/LTE] Enable Cat M1-only mode

- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/exflash_hal.c
1. We don't send enter sleep command to external flash before uninitializing it
1. We don't uninitialize external flash before entering STANDBY mode.
Test the fix on Xenon-SoM, the power consumption decrease from 8uA to 1uA in STANDBY mode.
```c
void setup() {
}
void loop() {
System.sleep(SLEEP_MODE_DEEP, 0);
}
```
[CH29844]
[CH29689]
---
- [Bugfix] [Gen 3] Fixes a deadlock in `system_power_manager` and `i2c_hal` when exiting the sleep mode  [1725](https://github.com/particle-iot/device-os/pull/1725)
- [Enhancement] [Gen 3] QSPI flash is put into sleep mode and is deinitialized when entering STANDBY or STOP sleep mode [1725](https://github.com/particle-iot/device-os/pull/1725)
> Power leakage from external flash

- hal/src/nRF52840/spi_hal.cpp
We use high-speed SPI as default SPI, however, it doesn't support SPI slave. This PR adds a parameter check in case users use the wrong mode and cause a failure.
---
---
- [Enhancement] [Gen 3] Parameter check for SPI slave mode with HAL_SPI_INTERFACE1 [#1731](https://github.com/particle-iot/device-os/pull/1731)
> Parameter check for SPI slave mode with HAL_SPI_INTERFACE1

- .travis.yml
We've introduced a change to .travis.yml recently to shallowly checkout the submodules with depth=1 to optimize build times, which doesn't really work if the submodule master branch is updated and the reference update is not in `develop` yet.
This PR Removes `submodule_depth: 1` option from .travis.yml. This does not affect build times that much, they are still at around 15 mins.
N/A
N/A
N/A
---
> [ci] disables shallow submodule checkouts

- hal/src/argon/app_usbd_string_config.h
- hal/src/boron/app_usbd_string_config.h
- hal/src/xenon/app_usbd_string_config.h
- platform/MCU/nRF52840/inc/sdk_config_system.h
1. Particle CLI is unable to communicate with Gen 3 devices over USB Control Interface
2. Windows complains about USB strings
1. particle-iot/nrf5_sdk#7 along with d3212bfb25276e97442780b0113bf4d4a64dab49 fix `bDeviceClass`, `bDeviceSubClass` and `bDeviceProtocol` in USB device descriptor
2. Hardcoding `0x0409` (English (US)) as the USB LangID. I wasn't able to figure out why `APP_USBD_LANG_ENGLISH` and `APP_USBD_SUBLANG_ENGLISH_US` weren't producing the correct result. The resulting LangID was `0x0009`.
3. particle-iot/nrf5_sdk#8 fixes interface-specific vendor request handling
1. Verify that Particle CLI works (assuming no interfering drivers are installed)
2. `usbview.exe` may be used to verify there are no complaints about the strings, see screenshot below
- particle-iot/nrf5_sdk#7
- …
> [Gen 3] Fixes USB descriptors

- platform/MCU/STM32F1xx/SPARK_Firmware_Driver/inc/hw_config.h
- platform/MCU/STM32F1xx/SPARK_Firmware_Driver/src/hw_config.c
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/hw_config.c
Bootloader on Gen 2 platforms built out of `develop` currently fails to boot correctly into system parts. This is an artifact of Gen2/3 merge, where the preparatory logic for deinitializing things in the bootloader before jumping into the application was moved out of the common bootloader code into platform-specific `Reset_System()` function.
Disable `SysTick` in `Reset_System()` on Gen 2 platforms and core.
Build bootloader out of this branch, flash it, it should correctly jump into system parts.
N/A
N/A
---
> [bootloader] SysTick needs to be disabled in Reset_System() on Gen 2 platforms

- crypto/inc/crypto_dynalib.h
- crypto/inc/mbedtls_config_photon.h
- crypto/inc/mbedtls_weaken.h
MD5 got erroneously disabled for Photon and P1, which prevents WPA Enterprise authentication not working correctly.
Bring it back!
Connect to WPA Enterprise AP with PEAP. Your device shouldn't crash.
N/A
N/A
---
> [photon/p1] crypto: re-enables MD5 for TLS (WPA Enterprise)

- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/lwip/ublox/pppncpnetif.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.h
- user/build.mk
- user/makefile
- user/tests/wiring/no_fixture_long_running/network.cpp
- user/tests/wiring/no_fixture_long_running/ticks.cpp
- wiring/src/spark_wiring_udp_posix.cpp
1. PPP link gets broken on LTE Borons and SoMs when sending larget packets:
```
0000040423 [lwip] TRACE: pppos_netif_output[3]: proto=0x21, len = 40
0000040426 [hal] TRACE: Outputing 1320 bytes
0000040433 [lwip] TRACE: pppos_netif_output[3]: proto=0x21, len = 1316
0000042175 [hal] TRACE: Outputing 16 bytes
0000042175 [lwip] TRACE: pppos_write[3]: len=12
0000042360 [hal] TRACE: Outputing 22 bytes
0000042360 [lwip] TRACE: pppos_write[3]: len=18
0000043426 [hal] TRACE: Outputing 1321 bytes
0000043427 [lwip] TRACE: pppos_netif_output[3]: proto=0x21, len = 1316
0000047176 [hal] TRACE: Outputing 16 bytes
0000047176 [lwip] TRACE: pppos_write[3]: len=12
0000048361 [hal] TRACE: Outputing 22 bytes
0000048361 [lwip] TRACE: pppos_write[3]: len=18
0000049429 [hal] TRACE: Outputing 1321 bytes …
```
> [Boron] Workaround for SARA R4 ppp session getting broken

- system/src/control/storage.cpp
```
device-os/modules$ make PLATFORM=argon -s
/home/monkbroc/Programming/firmware/modules/argon/system-part1/makefile /home/monkbroc/Programming/firmware/modules/argon/user-part/makefile
src/control/storage.cpp:63:50: note: #pragma message: External flash is not supported
#pragma message("External flash is not supported")
^
649424	   2156	  65792	 717372	  af23c	../../../build/target/system-part1/platform-12-m/system-part1.elf
Creating ../../../build/target/user-part/platform-12-m/module_user_memory.ld ...
Creating ../../../build/target/user-part/platform-12-m/module_user_memory.ld ...
4764	    104	    780	   5648	   1610	../../../build/target/user-part/platform-12-m/user-part.elf
```
This message …
> Remove the message "External flash is not supported" from Gen 3 builds

- build/checks.mk
- docs/build.md
The `PARTICLE_DEVELOP` check still generates a lot of noise during compilation: https://community.particle.io/t/issue-fatal-not-a-git-repository-or-any-of-the-parent-directories-git/48744.
After a discussion with @monkbroc we decided to remove that check entirely.
> Do not fail the build if PARTICLE_DEVELOP is not defined

- hal/src/argon/network/esp32_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- services/inc/system_error.h
Update `SYSTEM_ERROR_UNKNOWN` to `SYSTEM_ERROR_AT_NOT_OK` and `SYSTEM_ERROR_AT_RESPONSE_UNEXPECTED` to provide context to error messages for the sake of debugging.
ch32350 - Update error codes in Gen3 parser to facilitate debugging efforts and provide context to system errors
> ch32350/error codes - Create AT specific errors

- hal/src/nRF52840/usart_hal.cpp
- user/tests/wiring/serial_loopback2/README.md
- user/tests/wiring/serial_loopback2/application.cpp
- user/tests/wiring/serial_loopback2/loopback.cpp
`SerialX.available()` may report smaller number of bytes available in RX buffer than actually received, until the data is read out. There is no data loss though.
This is a "bug" in how we handle partial DMA transfers. We commit pending DMA data only if the RX buffer is empty, so you would see a smaller number in `available()` that wouldn't change until read out and then partially completed DMA transfer would be commited.
Originally issue was reported in https://community.particle.io/t/error-serial1-available-argon/48380/4
Always check ongoing RX DMA transaction when reporting number of bytes available in RX buffer.
Run the `wiring/serial_loopback2` test.
N/A
- https://community.particle.io/t/error-serial1-available-argon/48380/4
- [CH31890]
---
> [Gen 3] Always check ongoing RX DMA transaction when reporting number of bytes available in RX buffer

- hal/src/electron/core_hal.c
- hal/src/nRF52840/core_hal.c
- newlib_nano/makefile
- newlib_nano/src/malloc.c
- services/inc/panic_codes.h
Apparently we don't have checks on whether `malloc()`/`free()` etc functions are being called from an ISR, which should not be possible due to the usage of a semaphore for thread-safety.
We did have assertions for this previously but only for Electron.
This PR renames `SemaphoreLockTimeout` panic code into a generic `HeapError` and adds `HAL_IsISR()` checks to `malloc()`, `free()`, `realloc()`, `mallinfo()`, and `malloc_usable_size()` functions (instead of `__malloc_lock()/unlock()` which are implemented separately for each platform and defined in WICED for Photons and P1 for example).
Run the example app, the device should panic once D0 is deasserted.
```cpp
void setup() {
pinMode(D0, INPUT_PULLUP);
attachInterrupt(D0, (wiring_interrupt_handler_t)[](void) -> void {
void* ptr = …
```
> Introduce safety checks on heap usage from ISRs

- system/src/system_network_manager.cpp
`WiFi.clearCredentials()` doesn't work unless `WiFi.disconnect()/off()` are called.
Allow to clear interface-specific credentials notwithstanding interface state, except for Mesh.
Run the example app on an Argon with configured WiFi credentials.
1. D7 should light up and go off in 5 seconds
2. Argon should still be breathing cyan
3. Reset it, it should no longer be able to connect to WiFi network
```cpp
/* executes once at startup */
void setup() {
pinMode(D7, OUTPUT);
digitalWrite(D7, LOW);
digitalWrite(D7, WiFi.clearCredentials() ? HIGH : LOW);
delay(5000);
digitalWrite(D7, WiFi.hasCredentials() ? LOW : HIGH);
}
/* executes continuously after setup() runs */
void loop() {
}
```
- [CH30587]
---
> [system] network manager: allows to clear interface-specific credentials notwithstanding interface state, except for Mesh

- communication/src/dtls_message_channel.cpp
- communication/src/dtls_message_channel.h
- communication/src/dtls_protocol.cpp
- communication/src/dtls_session_persist.h
The device and cloud may get out of sync when reusing a session. For instance, session data may become corrupted on the device, or session caches on the cloud expired. 
When this occurs the device presently retries indefinitely to use the current session. 
The number of times the session is used is counted - each time the session is restored as part of the main handshake, the use count is incremented.  When the use count reaches the expiration count (presently 3), the session is considered invalid, forcing it to be discarded and performing a full handshake. 
The use count is reset after successfully decrypting a message from the cloud. This validates the session data.
* Apply the randbytes hack, but rather than invert, we increment the data (or the session becomes valid every 2nd …
> expires a session after 3 unsuccessful attempts at connecting to the cloud

- communication/src/dtls_protocol.cpp
- communication/src/dtls_protocol.h
- system/inc/system_sleep.h
- system/src/system_sleep.cpp
- user/tests/wiring/api/system.cpp
- wiring/inc/spark_wiring_system.h
`System.sleep(SLEEP_MODE_DEEP, ...)` doesn't wait for confirmable messages to be processed before entering the deep sleep mode. If the current session data became invalid for some reason, this may put a sleepy device into an endless loop, where it wakes up, restores the session, publishes an event and goes back to sleep without ever noticing that there's no established connection with the cloud.
By default, the system should wait for all confirmable messages to be processed before entering a sleep mode. This PR also introduces a flag that allows overriding the default behavior (`SLEEP_NO_WAIT`).
1. Flash the following application to an Electron:
```cpp
// SYSTEM_THREAD(ENABLED)
namespace {
{ "app", …
```
> Wait for confirmable messages when entering the deep sleep mode

- modules/electron/system-part1/linker.ld
- modules/electron/system-part1/module_system_part3_export.ld
- modules/electron/system-part2/module_system_part1_export.ld
- modules/electron/system-part3/module_system_part2_export.ld
- modules/electron/user-part/module_user_memory.ld
- modules/photon/system-part1/module_system_part1_export.ld
- modules/photon/system-part2/module_system_part2_export.ld
- modules/shared/stm32f2xx/inc/system_part1_loader.c
- modules/shared/stm32f2xx/inc/system_part2_loader.c
- modules/shared/stm32f2xx/inc/system_part3_loader.c
- modules/shared/stm32f2xx/part2.ld
On the Photon, the size of the static RAM (SRAM) allocated for system-part1 is only 768 bytes, which is not enough to build Device OS with newer versions of GCC (5.4.x – 8.2.x): https://github.com/particle-iot/device-os/pull/1159#issuecomment-262969953.
The user part's SRAM is located immediately after the system-part1 SRAM, so the size of the latter region cannot be increased without breaking the backward compatibility:
```
Photon                                  Electron
+-------------------+ 0x20000000        +-------------------+ 0x20000000
| system-part1 SRAM |                   | system-part1 SRAM |
+-------------------+ 0x20000300        +-------------------+ 0x20000400
| user-part SRAM    |                   | user-part SRAM    |
+~~~~~~~~~~~~~~~~~~~+ …
```
> Reserve memory for system-part1 SRAM

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
eDRX is enabled by default on production u-Blox modules, and it causes a variable lag in the network data transmissions.  We have previously disabled it, but not entirely.
Scan for and disable each eDRX AcT type, and reset the modem if disabling is required or an error occurs.
>**Note:** When disabling eDRX mode, the modem needs to be reset to clear eDRX behavior in the cellular network.  This will cause a one time ~30s reconnection delay after OTA updating the new firmware.
>**Note:** When eDRX mode is enabled, TX on the device temporarily allows the network to RX faster.  For example, if the device published every 2 minutes and we asynchronous tried to read a Particle Variable every ~5 seconds, the device would up timing out 2-3 times in a row and succeeding 2-3 times in a row …
> [Electron/LTE] disables all eDRX AcT types [ch32051]

- hal/src/electron/modem/enums_hal.h
- hal/src/electron/modem/mdm_hal.cpp
Invalid RAT information causes signal strength/quality information to be unavailable. This is caused by `AT+COPS?` in `checkNetStatus()` which invalidates the RAT set by URC handlers as it only handles `GSM` and `UTRAN` for some reason: https://github.com/particle-iot/device-os/blob/develop/hal/src/electron/modem/mdm_hal.cpp#L1380
1. Fix `AT+COPS?` handler to correctly parse all RATs
2. Adds explicit `AT+COPS?` call to `getSignalStrength()`
N/A
N/A
- [CH32382]
- #1759 
---
---
- [bugfix] [Electron/LTE] Make sure that the RAT information is actual before calculating signal strength (RSSI) and quality [#1779](https://github.com/particle-iot/device-os/pull/1779)
> [Electron/LTE] Make sure that the RAT information is actual before calculating signal strength (RSSI) and quality

- system/src/system_cloud_internal.cpp
The device previously only sends the value of these flags when they have changed from the default. However, they are reset when the device resets, yet the cloud is not informed of this change. 
Send the state of these flags whenever connecting to the cloud, so the cloud has the latest state.  This will increase data usage marginally.  This feature will be reworked in a later release to allow synchronization with less data use. 
- Load the intelligent updates test app to a device
- View the device in the Console
- Call the function enableUpdates with value 0.  Confirm that updates are disabled.
- Reset the device
- The console will automatically detect that updates are now enabled. 
- [[CH30507]](https://app.clubhouse.io/particle/story/30507/synchronize-state-between-the-device-and-cloud) …
> intelligent update flags synchronization

- hal/network/lwip/openthread/lwip_openthreadif.cpp
- hal/network/lwip/openthread/lwip_openthreadif.h
- hal/network/openthread/border_router_manager.cpp
- hal/network/openthread/border_router_manager.h
- hal/src/nRF52840/openthread/openthread-config-project.h
- system/src/system_network_manager.cpp
Mesh devices may be unable to connect to the cloud or appear to be connected but can neither send nor receive data to/from the cloud under certain conditions.
1. OpenThread version we've upgraded to in the end of January moved SLAAC functionality into its core and enabled it by default, which interfered with our own SLAAC logic. A PR was submitted later to the OpenThread repo to make this configurable, so for now we are simply pulling in that PR and disable SLAAC: https://github.com/particle-iot/openthread/commit/ea382ea6002ce41af4151bac64e26b36a1e3cb49
2. Under certain conditions (see 'Steps to Test' to replicate) mesh devices don't notice that the gateway has been reset. This is resolved by artificially publishing a prefix with `preferred` flag set to 0 (which means that the addresses …
> [Gen 3] Fixes various issues caused by the gateway reset

- system/src/system_network_compat.cpp
#1781
This is an artifact of Gen 2 / Gen 3 merge where we've changed the behavior of listening mode: it's no longer blocking and is a part of the system loop. This causes network config to be zeroed out by `manage_ip_config()` -> [`update_config()`](https://github.com/particle-iot/device-os/blob/develop/system/src/system_network_internal.h#L786).
A simplest fix is probably just force-filling the configuration in the API `network_config()` call.
Put your Photon into listening mode, call `particle serial mac`. The MAC address should be available.
N/A
- Closes #1781
---
---
- [bugfix] [Photon/P1] Fixes MAC address info not being available in listening mode [#1783](https://github.com/particle-iot/device-os/pull/1783)
> [Photon / P1] Fixes MAC address info not being available in listening mode

- wiring/src/spark_wiring_usartserial.cpp
- wiring/src/spark_wiring_usbserial.cpp
#1737
Make sure that `available()`, `availableForWrite()`, `peek()` and `read()` don't forward the errors from HAL and only return 0 or -1 in case of errors appropriately.
N/A
N/A
- Closes #1737
- [CH32372]
---
---
- [wiring] Make sure that `Serial` and `SerialX` methods are in sync with the documentation and don't return unexpected values [#1782](https://github.com/particle-iot/device-os/pull/1782)
> [wiring] Make sure that `Serial` and `SerialX` methods are in sync with the documentation and don't return unexpected values

- build/platform-id.mk
- modules/shared/system_module_version.mk
After merging Gen 3 and Gen 2 firmware bases together, there was no way to bump the bootloader dependency separately for each generation of device.
Separate the BOOTLOADER_DEPENDENCY for each generation based on a new definition PLATFORM_GEN, which is set to 0, 1, 2, 3, and 60000 (of course).
Backstory:
- v1.1.0 contains bootloader v301, and dependency of v201 for both platforms.  However Gen 3 devices  (except for SoMs) and Electron contained the bootloader in system firmware, so they would apply the bootloader if it was less than v301.  Photon/P1 don't contain bootloaders though, so they rely on the CLI  via `particle update` or the Cloud to update them.  The CLI only gets updated on default releases and did get v301 bootloaders for Photon/P1 added.  That said, the dependency was still …
> [gen 3] update bootloader dependency to v302

- hal/src/nRF52840/openthread/random.c
`rand()` when called from an ISR will attempt to allocate `_reent` struct from heap for thread safety, which shouldn't happen in the interrupt context.
The main fix is in OpenThread repo: https://github.com/particle-iot/openthread/pull/1
This PR simply initializes random seed to be used by Nordic 802.15.4 CSMA/CA.
**NOTE: this is a stop-gap solution and we'll report this issue to OpenThread/Nordic on Monday, so that they can come up with something that doesn't require the seed to be provided externally**
Just let the devices run for a while doing all sorts of mesh communications. They should no longer panic.
N/A
- https://github.com/particle-iot/openthread/pull/1
---
---
- [bugfix] [Gen3] Fixes a HeapError panic due to malloc() call from an ISR (caused by rand() usage) …
> [Gen3] Fixes a HeapError panic due to malloc() call from an ISR (caused by rand() usage)

- system/src/main.cpp
Softdevice assertion failed when initializing radio on Softdevice S140v6.1.1.
Change the initialization sequence for BLE and thread.
1. Flash  Softdevice S140v6.1.1
1. Flash Device OS 1.2.1-rc.1
1. Device enters PANIC
After applying this fix, PANIC issue disappears.
N/A
---
---
- [bugfix] [gen 3] Fixes radio initialization sequence for SoftDevice S140v6.1.1 [#1794](https://github.com/particle-iot/device-os/pull/1794)
> [system] Fixes radio initialization sequence for Softdevice S140v6.1.1

- hal/inc/exflash_hal.h
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/exflash_hal.c
We've introduced an incompatibility in the bootloader with older versions of system firmware in the releases containing https://github.com/particle-iot/device-os/pull/1725.
When you have a bootloader that has this feature on your device, before we jump into the system-part1 the QSPI flash is put into low power mode and requires a special command to wake it up. So, when you have a system-part1 that doesn't send that special command, the QSPI flash is left in low power mode and anything dealing with it fails, e.g. filesystem.
This PR does a couple of things:
1. External QSPI flash is no longer implicitly being put into lower power mode when executing `hal_exflash_uninit()`. This call only disables the QSPI peripheral on nRF52840. 
2. External flash sleep functionality has been decoupled …
> [gen 3] [bootloader] External flash sleep refactoring

- hal/build.mk
Normally, the flash consumption of the DeviceOS building for platform Boron and BSoM are nearly the same. But when building for platform BSoM, it results flash overflow.
This issue is encountered due to the `LOG_COMPILE_TIME_LEVEL` in "./hal/build.mk" being not applied to platform BSoM.
> Building platform BSOM results flash overflow.

- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/openthread/alarm.c
See #1789.
For some reason when we are configuring the RTC before going into STOP sleep mode, the prescaler writes don't take effect. This can only happen if the RTC is not stopped, but it should have been stopped by that point.
This PR adds an ugly hack of looping and checking that the prescaler setting did take effect. We are also adding a similar hack to OpenThread alarm code just in case.
If anybody has better ideas on how to resolve this, I'll be more than willing to change this. I've tried various barriers (DMB, DSB and ISB) at multiple places but wasn't completely able to mitigate the issue. Perhaps a dummy prescaler read is what actually helps? :man_shrugging: 
See a test from #1789
- Closes #1789 
- [CH33538]
---
---
- [bgufix] [gen3] hal: fixes early wakeup by RTC from STOP …
> [gen3] hal: fixes early wakeup by RTC from STOP sleep mode

- hal/inc/cellular_hal.h
- hal/inc/cellular_hal_cellular_global_identity.h
- hal/src/boron/cellular_hal.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- system/src/system_network_diagnostics.cpp
- user/tests/accept/hal-api-test-plan.md
- user/tests/app/cellular_global_identity/cellular_global_identity.cpp
<details>
<summary><i>The two-digit `mnc` diagnostic allows the original `mnc` to be reconstructed accurately.</i></summary>
</details>
Currently, the `mnc` is translated to and stored as a decimal value. According to the specification, `40` and `040` are not equal values. Currently when using the `mcc` and `mnc` tuple, there does not appear to be a clash. However, maintaining this distinction is important is important to ensure future bugs do not appear in the system.
By sending an indicator as to the original form of the information, we are able to reconstruct the original value in a lossless manner.
user/tests/accept/hal-api-test-plan.md
user/tests/app/cellular_global_identity/cellular_global_identity.cpp
- ch33501
---
> Add two-digit mnc diagnostic flag

- .travis.yml
When merging the private and public repo after Gen3 development, the private repo was using an unencrypted slack token. This was inadvertently copied to the public repo during the merge.
Re-generate the token and re-encrypt it.
Let's see if this PR shows up in slack ;-)
---
> add encrypted slack token

- system/src/system_network_diagnostics.cpp
Current implementation requires multiple calls to `AT+COPS` and could result in an inconsistent cellular global identity.
By caching the diagnostic results we only check every 1 second.
Watch the modem logs.
- [[CH34335]](https://app.clubhouse.io/particle/story/34335/optimize-diagnostic-message-broadcast-for-cellular-network-traffic)
---
> Cache cellular diagnostics

- system/src/system_network_diagnostics.cpp
This code has already been reviewed and merged into the `develop` branch in #1810 , and now needs to be merged into 1.2.1.
---
> Cellular Global Identity diagnostic cache

- wiring/inc/spark_wiring_nfc.h
- wiring/src/spark_wiring_nfc.cpp
Context parameter is missing and NFC.update() will remove callback
Flash the example, use Serial to observe the log to see whether the callback is called and whether the context value is right.
```c
Serial1LogHandler logHandler(115200, LOG_LEVEL_ALL, {{"app", LOG_LEVEL_ALL}});
void nfc_event_callback(nfc_event_type_t type, nfc_event_t* event, void* context) {
switch (type) {
case NFC_EVENT_FIELD_ON: {
Serial.printf("on, context: %d\r\n", *reinterpret_cast<int*>(context));
break;
};
case NFC_EVENT_FIELD_OFF: {
Serial.printf("off, context: %d\r\n", *reinterpret_cast<int*>(context));
break;
};
default:
break;
}
}
void setup(void) {
Serial.begin();
static int context = 123;
void *p = &context;
NFC.setText("Hello Particle!", "en"); …
```
> [NFC] Context parameter is missing and NFC.update() will remove callback

- hal/src/nRF52840/core_hal.c
- modules/shared/nRF52840/part1.ld
---
The memory usage diagnostics report negative values in the safe mode. The problem is caused by `HAL_Core_Runtime_Info()` which uses an incorrect initial heap size for calculations.
Set the initial end address of the heap to the start address of the stack (see the diagram [here](https://github.com/particle-iot/device-os/blob/feature/part1_sram/build/arm/linker/nrf52840/platform_ram.ld#L4)). This address is normally adjusted according to the size of the static RAM allocated in the user part, but is used as is in the safe mode.
1. Apply [this patch](https://github.com/particle-iot/device-os/files/3276515/test.diff.txt) via `git apply` and flash the system firmware to a Gen 3 device.
2. Flash an incompatible user part to the device to make it enter the safe mode (it's not enough to put …
> [Gen 3] Fix memory usage diagnostics

- ci/enumerate_build_matrix.sh
- communication/src/events.h
- system/inc/system_cloud.h
- system/src/system_cloud.cpp
- system/src/system_update.cpp
For a full description see the clubhouse story.  In a nutshell, System.disableUpdates() should not block the application thread to send the event to the cloud.
The internal function `system_send_event` gains an additional flag to indicate the event should be processed asynchronously.  This is a temporary solution until we introduce futures to all synchronous system APIs so that they may be used synchronously or asynchronously as chosen by the caller.
Testing was done by using the app below both with and without the asynchornous event flag handling. The connection to the cloud was interrupted by turning off the mobile hotspot and the LED observed to see if the application thread continued running.  Without asynchronous events, the LED stopped blinking immediately.  With asynchronous …
> System.disableUpdates() operates asynchronously

- hal/inc/hal_dynalib_ota.h
- hal/inc/ota_flash_hal.h
- hal/src/core/ota_flash_hal.c
- hal/src/gcc/ota_flash_hal.cpp
- hal/src/nRF52840/ota_flash_hal.cpp
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h
- platform/MCU/nRF52840/inc/dct.h
- system/src/main.cpp
- system/src/system_update.cpp
When preparing a new firmware release for Gen2 and Gen3 platforms that don't contain the bootloader, we currently prepare an Ascender app that allows updating the bootloader of the device. This causes unnecessary delay in the release process.
This PR allows the bootloader (and other DeviceOS images) to be flashed via DFU.
The image is flashed to the OTA update region, and a flag set in the DCT.  When the system reboots, the image is applied just as if it were sent OTA or OTW.  This enables the bootloader to be flashed via DFU (such as by the CLI.)
1. Flash the Device OS from this PR to your target device
1.  Use `particle serial inspect` to retrieve the bootloader version of the current bootloader
1. edit modules/shared/system_module_version.mk, and change `BOOTLOADER_VERSION` to higher …
> allow the bootloader to be flashed over DFU

- hal/src/electron/modem/mdm_hal.cpp
- user/tests/wiring/no_fixture/cellular.cpp
A regression in the Cellular.RSSI() API was introduced in Device OS 1.2.0-rc.1 PR #1779 where the G350 RSSI functionality was broken.
Forces ACT_GSM for G350 in functions that query AT+COPS?
- Run new test CELLULAR_07_rssi_is_valid in TEST=wiring/no_fixture
- Try pressing the MODE button on G350 one time to see Signal Strength indicated in "Bars" flashed with a green LED.  With 1.2.0-rc.1 / 1.2.1-rc.3 / 1.3.0-rc.1, the G350 will NOT flash 1-5 blips of the green LED.  With this PR it should at least flash 1 green blip, if not more.
https://community.particle.io/t/no-signal-strength-information-for-electron-2g-on-device-os-1-0-0/47460/16
With the added test CELLULAR_07_rssi_is_valid, it became clear that on Gen 3 devices Boron & B SoM, the Cellular.RSSI() API was not implemented correctly …
> fixes RSSI regression on G350 (2G) devices [ch35194]

- system/src/main.cpp
This PR fixes an issue in PR #1788 that prevents the system from resetting after a bootloader update.  Not resetting after the update when the BOOTLOADER_DEPENDENCY has not been met yet means the device will be in SAFE MODE.  The device should update the bootloader and boot normally, which this change addresses.
Tested on Photon.
> Fix to ensure device resets after bootloader update

- hal/src/core/ota_flash_hal.c
Fixes issue introduced in #1788 for Core.  HAL_FLASH_End() was clobbered by mistake with an implementation of HAL_FLASH_ApplyPendingUpdate() that was intended to be a stub.
> Fixes boot issue for Core introduced in 1.2.1-rc.3

- hal/src/electron/FreeRTOSConfig.h
- hal/src/electron/rtos_hook.cpp
- hal/src/nRF52840/freertos/FreeRTOSConfig.h
- hal/src/nRF52840/rtos_hook.cpp
Due to the busy-loop nature of the application thread and higher priority (2) FreeRTOS IDLE thread responsible for thread resources cleanup (stack) is not being given CPU time, causing memory leaks, unless the application thread goes into a blocked state (waiting on a synchronization primitive or delaying).
Temporarily increase IDLE thread priority to `configMAX_PRIORITIES - 1` (maximum) whenever `vTaskDelete(NULL)` is called using `portPRE_TASK_DELETE_HOOK` to clean up the stack as soon as possible and restore it back to `tskIDLE_PRIORITY` once IDLE thread runs using idle hook.
Set a breakpoint to `vApplicationIdleHook`, make some thread exit, it should get executed.
N/A
- [CH36038]
---
> [electron, gen3] Temporarily increase IDLE task priority whenever a thread exits (calls vTaskDelete)

- hal/src/nRF52840/lwip/lwipopts.h
- user/tests/wiring/no_fixture/mesh.cpp
- wiring/inc/spark_wiring_mesh.h
- wiring/inc/spark_wiring_thread.h
- wiring/inc/spark_wiring_udp.h
- wiring/src/spark_wiring_mesh.cpp
See #1828
This PR mainly simply starts mesh pub/sub thread that reads the data out of the socket even if only `publish()` is called.
Apart from that it:
1. Refactors/cleans up `MeshPublish` class
2. Provides a workaround for wiring `Thread` class where the thread being started was not given processing time due to `os_thread_yield`
3. Enables mutlicast loop LwIP options which enables on-device testing of mesh pub/sub and adds the `MESH_01_PublishWithoutSubscribeStillReadsDataOutOfPubSubSocket` test.
- `wiring/no_fixture`: `MESH_01_PublishWithoutSubscribeStillReadsDataOutOfPubSubSocket`
N/A
- Closes #1828 
- [CH35133]
---
- [bugfix] [Gen 3] Fixes mesh pub/sub socket consuming all packet buffers
> [Gen 3] Fixes mesh pub/sub socket consuming all packet buffers

- wiring/inc/spark_wiring_mesh.h
Issue: #1813 
SEMI_AUTOMATIC mode blocks loop() after calling Mesh.off()
For user scenario like:
```
Mesh.on();
Mesh.connect(); 
Particle.connect();
...
Mesh.off();
```
`SPARK_CLOUD_AUTO_CONNECT` is set in `Particle.connect()` and it isn't cleaned in `Mesh.off()` which causes `semi_automatic_connecting()` always return `ture`, then the device assumes it is in a network connection task, it jumps over `loop()` task.
1. Use Argon as a border router
1. Connect Xenon to the Argon mesh network
1. Burn the example app to Xenon
1. Observe whether Xenon gets stuck in blinking green.
```c
Serial1LogHandler logHandler(115200, LOG_LEVEL_ALL, {{"app", LOG_LEVEL_ALL}});
void setup() {
Serial.begin();
}
void loop() {
static uint32_t msLast = 0; …
```
> [system] disconnect the cloud when calling Mesh.off()

- hal/inc/pinmap_hal.h
By default, D8 pin is the wakeup pin, but D8 pin is also used by Ethernet on BSoM EVB, when BSoM enters deep sleep mode, it will be woken up accidentally.
Change wakeup pin from D8 to A7 on SoM boards.
N/A
N/A
[CH34764]
---
- [internal] [Gen3] Changes WKP pin to A7 for SoM platforms to avoid an overlap with Ethernet chip on EVB
> [gen3] hal: change wakeup pin for SoM boards

- hal/src/argon/network/esp32_ncp_client.cpp
The reset pin (RST) on the side of the Argon is unable to reset the board by another board using a GPIO (e.g. a Xenon).
We saw two kinds of symptoms of this issue:
1. Argon cannot be reset
2. Argon can be reset, but the reset pin on Argon goes from 3.3V to 1.6V and wait for around 500ms, then it goes to 0V.
As we can see from the picture, if we configure WIFI_EN(ESPEN) pin to OUTPUT high, the voltage decline a little after the D2 diode, given there is a pull-up resistor R30 100k, we should configuration WIFI_EN(ESPEN) pin to open drain.
1. Configure WIFI_EN(ESPEN) as output mode
1. Download below application to two Argon, connect Argon-A's D8 pin to Argon-B's reset pin
1. Observe the symptoms
1. Configure WIFI_EN(ESPEN) as the open-drain mode
1. Repeat the above steps
```c
void setup() { …
```
> [hal] Fixes Argon cannot be reset by external gpio

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- user/tests/wiring/no_fixture/cellular.cpp
- wiring/src/spark_wiring_tcpclient.cpp
LTE E-series R410 devices drop Cloud connection every time user firmware opens and closes a TCP socket.  This does not appear to affect U260/U201/G350 devices.
The timeout for the socket close command USOCL times out after 10s (has been this way since the first electron release).  Sara R410M timeout of this command is 120 seconds, but that is likely only for TCP sockets since UDP sockets can be closed immediately.  Sara U201/260/G350 timeout of this command is 1 second.  If the TCP socket took more than 10 seconds to close, the USOCL command would timeout and allow the AT interface to be accessed by the next command, but it would not ready because it's still waiting for the socket close command to finish or timeout.  If a following command happens to be a Particle Publish, Keep Alive Ping …
> [Electron/LTE] devices drop Cloud connection every time user firmware opens and closes a TCP socket [ch34976]

- system/src/usb_control_request_channel.cpp
- user/tests/unit/stubs/system_cloud.cpp
- user/tests/unit/stubs/system_network.cpp
Control requests are normally processed in the system thread, and if the thread is blocked on some operation, a request may time out. This is especially noticeable on Gen 2 platforms where networking events are processed in the system thread and such CLI commands as `usb reset` and `usb dfu` are likely to fail when the device is trying to establish a network or cloud connection.
Cancel the current network connection attempt and break the communication loop when processing a USB request that causes the device to reset (`CTRL_REQUEST_RESET`, `CTRL_REQUEST_DFU_MODE`, etc.)
Verify that the CLI is able to reset an Electron when it's blinking green and registering in the network.
> Cancel network connection when processing a USB request that resets the device

- hal/src/stm32f2xx/i2c_hal.c
- user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp
This PR is a proposed solution for issue #1809 , we found when Gen2 device acts as an I2C slave device, it will send an extra address byte before its data bytes. This is because the stretch configuration is disabled after a transmission. 
```
/* Check on EV3 */
case I2C_EVENT_SLAVE_BYTE_TRANSMITTING:
case I2C_EVENT_SLAVE_BYTE_TRANSMITTED:
if (i2cMap[i2c]->txBufferIndex < i2cMap[i2c]->txBufferLength)
{
I2C_SendData(i2cMap[i2c]->I2C_Peripheral, i2cMap[i2c]->txBuffer[i2cMap[i2c]->txBufferIndex++]);
}
else
{
// If no data is loaded into DR register and clock stretching is enabled,
// the device will continue pulling SCL low. To avoid that, disable clock stretching
// when the tx buffer is exhausted to release SCL.
I2C_StretchClockCmd(i2cMap[i2c]->I2C_Peripheral, DISABLE); 👈👈👈
}
break;
``` …
> [gen2] hal: Fixes I2C bus missing stretch configuration

- hal/src/core/ota_flash_hal.c
- system/src/main.cpp
Two fixes were applied directly to v1.2.1 and need to be cherry-picked to latest `develop` for next release: `1.3.1-rc.1`
#1850 
#1851 
This PR cherry-picks the above two commits
For #1850 
- Build firmware and bump bootloader version and dependencies to v400 on Photon
- Flash firmware with latest tinker, device should be in safe mode with older bootloader version dependency issue
- flash new bootloader via
```console
$ dfu; sleep 3; dfu-util -d 2b04:d006 -a 0 -s 0x80C0000 -D photon-bootloader\@1.3.1-rc.1-v500.bin; sleep 2; dfu-util -d 2b04:d006 -a 1 -s 1753:leave -D ota-flag-a5.bin 
```
- device should reboot with latest bootloader
For #1851 
- Build tinker firmware for Core and ensure it boots and breathes cyan
---
---
- [bugfix] Fix to ensure device resets after bootloader update …
> Fixes from 1.2.1

- ci/build_boost.sh
- ci/install_boost.sh
- ci/run_tests.sh
- test/unit_tests/CMakeLists.txt
It is now required to have Boost libraries installed globally in the system to build CMake-based unit tests locally (this change was introduced in https://github.com/particle-iot/device-os/pull/1869). This PR changes the paths to Boost libraries back to `$BOOST_ROOT` which is set by CI scripts.
Note: This is a temporary solution. Ideally, we'd want all necessary paths to be detected and set using built-in CMake mechanisms.
- Run `source ci/install_boost.sh`.
- Run `ci/build_boost.sh`.
- Compile and run CMake-based unit tests.
> Set path to Boost libraries

- hal/inc/usb_hal.h
- hal/src/nRF52840/usb_hal.cpp
- hal/src/nRF52840/usb_hal_cdc.c
- system/src/system_power_manager.cpp
We Introduced USB state in #1846 , the USB sending API didn't update its available condition.
Change The available state of USB serial from `HAL_USB_STATE_POWERED ` to `HAL_USB_STATE_DEFAULT`
Make sure the USB can send data.
```c
void setup() {
Serial.begin();
}
void loop() {
Serial.print("hello");
delay(1000);
}
```
---
- [bugfix] [Gen3] Resolved a HardFault after USB cable is unplugged under certain conditions
- [enhancement] [Gen3] USB state tracking enhancements
> [hal] Fixes USB send failed

- hal/src/gcc/ota_flash_hal.cpp
<details>
</details>
The Gen2 virtual platform failed on startup due to a coding error. 
Fix the coding error.  This was clearly a remnant from early thoughts on the code design.
Start the executable produced when building platform 3. 
Note that I was unable to test this since the cross compile build was not working on my system. 
Closes #1842
---
---
- [bugfix] [gcc] fixes virtual platform exception on startup [#1878](https://github.com/particle-iot/device-os/pull/1878)
> [gcc] fixes virtual platform exception on startup #1878 [ch35243]

- hal/src/electron/modem/mdm_hal.cpp
Long timeouts from Publish Vitals use of COPS command when AT interface is unresponsive
Story details: https://app.clubhouse.io/particle/story/37231
---
- [enhancement] ensures AT interface is responsive [#1886](https://github.com/particle-iot/device-os/pull/1886)
> Ensure AT interface is responsive

- hal/src/argon/network/esp32_ncp_client.cpp
ASOM has a pull-down resistor on ESPEN pin, it's different from ARGON, so the pin mode should be output drain on ARGON, output on ASOM.
Fix the pin mode.
Connect ARGON and ASOM to the cloud.
Test result: Passed.
N/A
N/A
---
---
- [bugfix] [hal] Fixes WIFIEN pin mode for ASoM [#1889](https://github.com/particle-iot/device-os/pull/1889)
> [hal] Fixes WIFIEN pin mode for ASoM

- modules/shared/nRF52840/user.ld
- modules/shared/stm32f2xx/user.ld
Closes #1843
Putting the dynalib into a separate section in the linker file seems to help.
Build the test application from #1843. It should build without linker errors.
N/A
- #1843
---
- [bugfix] [Gen2 / Gen3] Fixes dynalib alignment issue when compiling relatively large applications potentially due to an unconfirmed bug in GCC by moving the dynalib into a separate section (`.dynalib`)
> [user] fixes weird alignment error with the dynalib table location

- system/src/ble_listening_mode_handler.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
In Device OS 1.3.1-rc.1 and below, to terminate all the BLE activities initiated by user application, we can call `BLE.off()` to just shut off the BLE radio. While this API will also prevent the mobile setup from going further when device is in the Listening mode, since BLE will stop advertising and Peripheral connection is dropped if connected when that API is called.
By introducing the `BLE.end()` API, it makes sure that only the BLE activities initiated by user application is terminated, leaving the mobile setup works as expected.
1. BLE scanner
```c
void bleOnScanResultCallback(const BleScanResult* result, void* context) {
LOG(TRACE, "---------- END ----------");
BLE.end()
}
void setup() {
}
void …
```
> BLE: introduces BLE.begin() and BLE.end() wiring APIs.

- hal/src/nRF52840/ble_hal.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
- Restored default BLE device address is incorrect.
- Read BLE device name might be contracted.
- `operator&` of the `BleCharacteristicProperty` enum class doesn't work as expected.
- The length of got advertising and scan response data is not updated.
> BLE: minor fixes

- hal/src/argon/platform_ncp_argon.cpp
- hal/src/nRF52840/platform_radio_stack.cpp
- platform/MCU/nRF52840/src/flash_mal.c
1. The bootloader doesn't correctly handle `MODULE_INFO_FLAG_DROP_MODULE_INFO` flag. The returned module info for the SoftDevice module is a copy into a static variable, so direct pointer comparisons can't work.
2. The state checksum doesn't change after an update of either SoftDevice or NCP module, which causes the device to get stuck in safe mode
1. Use `memcmp()` instead
2. Add a dummy suffix structure to module info and fill SHA for NCP and SoftDevice modules
**This should probably be backported into 1.3.0 default**
1. Flash the bootloader and then flash the SoftDevice binary OTA. It should apply correctly.
2. TBD on staging.
N/A
N/A
---
> Fixes SoftDevice OTA updates

- .travis.yml
- ci/install_gcovr.sh
- ci/report/LICENSE
- ci/report/report.py
- ci/unit_tests.sh
- scripts/fetch-buildpack
- test/unit_tests/CMakeLists.txt
Travis CI is not integrated with Coveralls
Update scripts, called by Travis CI, to generate Coveralls formatted coverage JSON, and submit the results to Coveralls.
Run Travis CI, and see if the coverage results appear in Coveralls
[Coveralls](https://coveralls.io)
[Travis CI](https://travisci.org)
---
> Update Travis CI for Coveralls

- communication/src/dtls_message_channel.cpp
- crypto/inc/mbedtls_config_photon.h
- hal/src/boron/cellular_hal.cpp
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
- user/applications/tinker/tinker.mk
- user/tests/wiring/no_fixture/cellular.cpp
- user/tests/wiring/no_fixture/mesh.cpp
- user/tests/wiring/no_fixture/pwm.cpp
- user/tests/wiring/no_fixture/system.cpp
- user/tests/wiring/no_fixture/thread.cpp
- user/tests/wiring/no_fixture/wifi.cpp
This PR:
1. **CRITICAL:** Fixes session resume broken after an upgrade of MbedTLS. One of the internal fields in the `mbedtls_ssl_context` changed its meaning.
2. MbedTLS logging was not re-enabled on all the platforms. `#define MBEDTLS_DEBUG_C` was added to platform configs where it was commented out.
3. Fixes `CellularSignal` `rssi` and `qual` compatibility with Gen 2 on Gen 3 platforms. Fixes `CELLULAR_07_rssi_is_valid` test
4. Removes a rogue `$(error)` call in tinker makefile when building with `LOG_SERIAL=y`
5. **CRITICAL:** fixes heap and application static RAM overlap. This was the cause of `SYSTEM_07_fragmented_heap` stress test failure and who knows how many of the other weird Gen 3 issues. **This needs be backported into 1.3.1 default** as we broke things in 1.3.0-rc.1 in …
> Fixes issues encountered during 1.4.0 rc.1 testing

- communication/src/protocol.cpp
- hal/network/lwip/ifapi.cpp
- hal/src/nRF52840/core_hal.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- system/src/active_object.cpp
- system/src/usb_control_request_channel.cpp
This PR fixes a number of issues which I encountered while testing Device OS with a local device service instance:
- Due to a regression introduced in 1.1.0, the system layer always sends its handshake messages, even if the session was resumed. This causes increased data usage.
- `rand()` isn't properly seeded in multiple threads, including the system thread. On Gen 3 specifically this breaks allocation of ephemeral port numbers in LwIP.
- Control requests that reset the device (e.g. `particle usb dfu`) can cause unnecessary reconnection to the cloud.
- User module isn't initialized in monolithic builds.
> Various bugfixes

- communication/src/protocol.cpp
- hal/network/lwip/ifapi.cpp
- hal/src/argon/platform_ncp_argon.cpp
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/platform_radio_stack.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- modules/shared/nRF52840/user.ld
- modules/shared/stm32f2xx/user.ld
- platform/MCU/nRF52840/src/flash_mal.c
- system/src/active_object.cpp
- system/src/usb_control_request_channel.cpp
- user/applications/tinker/tinker.mk
- user/tests/wiring/no_fixture/cellular.cpp
- user/tests/wiring/no_fixture/mesh.cpp
- user/tests/wiring/no_fixture/pwm.cpp
- user/tests/wiring/no_fixture/system.cpp
- user/tests/wiring/no_fixture/thread.cpp
- user/tests/wiring/no_fixture/wifi.cpp
Backports a number of bugfixes from 1.4.0-rc.1 and develop.
1. #1905 
2. #1894 
3. #1897
4. Everything from #1898 except for https://github.com/particle-iot/device-os/pull/1898/commits/f5ccd79aaad659416d4d1385ae0a7f06eea2f30e, https://github.com/particle-iot/device-os/pull/1898/commits/2d983d357f054b0cdce5e2204d161ff9681a2f88 and https://github.com/particle-iot/device-os/pull/1898/commits/580cfaf08736b11a83e87c8e17380fc368cfef4e
---
- [Gen 3] Fixes heap and application static RAM overlap introduced in 1.3.0-rc.1 [#1898](https://github.com/particle-iot/device-os/pull/1898)
- Fixes tinker build errors when building with `LOG_SERIAL=y` [#1898](https://github.com/particle-iot/device-os/pull/1898)
- Fixes dynalib alignment issue when compiling relatively large applications potentially due to …
> Backports into 1.3.1

- build/release.sh
- Some customers would like the Electron released with DEBUG_BUILD=n
- When debugging Gen 3 devices, it is very convenient to use `tinker-serial-debugging` if you do not have a Serial USB adapter for use with `tinker-serial1-debugging` that is already being generated.
- Add Electron release binaries without DEBUG_BUILD=y
- Add Gen 3 tinker-serial-debugging apps (USB output)
```
build $ ./make_release.sh --platform=electron --debug --publish=1.4.0-rc.1
build $ ./make_release.sh --platform=boron --debug --publish=1.4.0-rc.1
// repeat last command for other Gen 3 devices if desired
```
ch34058
---
---
-- [internal] [ch34058] update release script to include Electron without DEBUG_BUILD=y and `tinker-serial-debugging` apps for Gen 3 [#1903](https://github.com/particle-iot/device-os/pull/1903)
> [ch34058] update release script to include Electron without DEBUG_BUILD=y and tinker-serial-debugging apps for Gen 3

- wiring/src/spark_wiring_logging.cpp
This PR cherry-picks cae58bcdd84d1d6d5fa1a1c5fa0bf2b88608e221 from https://github.com/particle-iot/device-os/pull/1748 to make sure logging over `Serial` does not interfere with the serial console in listening mode.
Flash `tinker-serial-debugging` and verify that the device can be flashed over the serial interface without errors.
> Do not mix logging and serial console output

- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
- Independent template type of the characteristic and service UUID arguments.
- Add restriction for the `BleCharacteristic::setValue()` template type.
- BLE UUID fails to compare with lower case string.
> BLE: wiring minor fixes

- .gitmodules
<details>
<summary><i>Whitespace changes to `.gitmodules` were (almost certainly accidentally) introduced in v.1.4.0-rc with https://github.com/particle-iot/device-os/pull/1864, via commit
504114b0af67fb8dc0a61791fb9d75469efb2086. As a result, these changes cause
merge conflicts with feature branches. This commit removes those so that
merges are clean again.
</i></summary>
</details>
A change in 1.4.0-rc1 causes merge conflicts. This is important to fix before 1.4.0 goes live so that feature branch maintainers don't suffer needless headaches when targeting new `device-os` releases.
Removing the additional whitespace returns the file to the condition in https://github.com/particle-iot/device-os/tree/release/v1.3.1
> Git: fix submodules whitespace

- hal/src/electron/modem/mdm_hal.cpp
- user/tests/wiring/no_fixture/tcp.cpp
- wiring/src/spark_wiring_tcpclient.cpp
- wiring/src/spark_wiring_tcpclient_posix.cpp
- See #1865 where TCPClient::connect() return values are not working as documented (1 = connected, 0 = all errors)
- [gen 2][lte] TCP Sockets generally take much longer to close on the SARA-R410M-02B vs. U260, U201 and other modems.
- fixes #1865, TCPClient::connect() return values by ensuring Gen 2 and 3 both return only 1 for success and 0 for all errors.
- [gen 2][lte] fixes slow to close TCP sockets on SARA-R410M-02B [ch35609] by using the USOSO TCP linger option for TCP sockets only, and setting the timeout to 0 which forces a disconnect immediately when the USOCL socket close command is used.
- Added TCP_03 and TCP_04 and updated TCP_01 and TCP_02 tests.
Run TEST=wiring/no_fixture (i, TCP*, i, MDM* to run all TCP related tests)
- fixes #1865 
- closes [ch35609] 
🔽 …
> [gen 2][lte] TCP socket closing slowly and TCPClient::connect() return values are incorrect

- user/tests/wiring/no_fixture/gpio.cpp
- user/tests/wiring/no_fixture_long_running/network.cpp
- wiring/src/spark_wiring_ipaddress.cpp
1. Fixes a bug in `IPAddress::operator bool()` for IPv6 addresses
2. Changes a default pin from `D0` to `A0` in GPIO tests. `D0` is usually an I2C pin as well, so the test might not work depending on how things are wired (e.g. on SoM EVB)
3. Minor fixes in `NETWORK_01_LargePacketsDontCauseIssues_ResolveMtu`
- `wiring/no_fixture` `GPIO*` on BSoM
- `wiring/no_fixture_long_running` on a Xenon
N/A
N/A
---
> Minor test fixes for 1.4.0

- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
PR #1886 added some AT / OK checks before commands with long delays, to force a quicker timeout when the AT interface was not responsive.  Unfortunately this negatively affected Gen 2 2G/3G modems due to the Power Saving mode being set to UPSV=1 by default which enables low power mode after about 9.2 seconds in most cases.  The issue is that when power saving mode is active, the AT / OK check can take longer than the 1 second timeout is currently has set, while the modem is transitioning from the IDLE to ACTIVE state.  In practice, I see this take anywhere from 0.5 seconds to 3 seconds.  The U2/G3 integration manual does not state how long this should take.
Gen 2 & Gen 3 LTE devices are not affected due to power saving mode being disabled by default.
Gen 3 2G/3G devices are also not …
> [electron, gen2] fixes RSSI failing due to Power Saving mode active [ch38428]

- system/src/system_publish_vitals.cpp
- system/src/system_publish_vitals.h
- test/unit_tests/cloud/publish_vitals.cpp
Despite VitalsPublisher being a new class, it is not fully covered.
Added test to improve coverage. Mark all untestable code and create a CH ticket to identify the work required to make it testable.
Run the DeviceOS CMake Catch2 tests
```bash
cd <particle-iot/device-os>/test/unit-tests/
mkdir .build && cd .build/
cmake ..
make all test coverage
```
CH38583: Improve VitalsPublisher Coverage
---
> Increase VitalsPublisher coverage

- user/inc/application.h
- user/tests/app/chrono_literals/chrono_literals.cpp
- user/tests/wiring/api/cellular.cpp
- user/tests/wiring/api/cloud.cpp
- user/tests/wiring/api/system.cpp
- user/tests/wiring/api/timedelay.cpp
- user/tests/wiring/api/wifi.cpp
- wiring/inc/spark_wiring_cellular.h
- wiring/inc/spark_wiring_cloud.h
- wiring/inc/spark_wiring_system.h
- wiring/inc/spark_wiring_ticks.h
- wiring/inc/spark_wiring_timer.h
- wiring/inc/spark_wiring_watchdog.h
- wiring/inc/spark_wiring_wifi.h
I wanted to follow the naming of the `stl` under the `particle` namespace, but had to make a compromise on the naming convention.
**`stl::literals::chrono_literals`**
- `ms`
- `s`
- `min`
- `h`
**`particle::literals::chrono_literals`**
- `_ms`
- `_s`
- `_min`
- `_h`
**Usage example:**
```
delay(3);      // delay 3 milliseconds
delay(3_ms);   // delay 3 milliseconds
delay(3_s);    // delay 3 seconds
delay(3_min);  // delay 3 minutes
delay(3_h);    // delay 3 hours
```
The compiler will _NOT_ allow, under any circumstance, disabling the warning generated when a user-defined string literal is not proceeded by an underscore.
The biggest difference is the fact the `stl` literals use a base storage of `uint64_t`, which would be slow to compute on our hardware, but the `particle` literals use a …
> Enable chrono string literals for time units

- user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
- user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
- wiring/src/spark_wiring_ble.cpp
https://github.com/particle-iot/device-os/issues/1913
Send characteristic value, which property is `WRITE`, when `BleTxRxType::AUTO` is used by default.
1. Build and flash the test applications `user/tests/wiring/ble_central_peripheral` to two Gen3 devices respectively.
2. Simply connect them to serial terminals and type `t` on the terminal to start the test.
N/A
- Closes #1913
- Closes #1924
> BLE: fixes that setValue() doesn't work with BleTxRxType::AUTO if characteristic has WRITE property.

- hal/src/nRF52840/ble_hal.cpp
Discovered descriptor of peer characteristic with 128-bits UUID is incorrect. That would report a fake CCCD handle, which is the same as the characteristic value handle, even if that characteristic has no CCCD presented. As a result, BLE Central device will send two byte, which is supposed to be the CCCD value, to the characteristic value instead upon connected when automatic connecting scheme is adopted.
Filter the discovered descriptors with bluetooth SIG 16-bits UUID.
1. Build and flash the example apps `user/tests/app/ble/uart_central` and `user/tests/app/ble/uart_peripheral` to two Gen3 devices respectively with debug enabled.
2. Observe the log on the Peripheral device side and see if it received two bytes from Central device upon connected.
N/A …
> BLE: discovered descriptor is incorrect

- hal/src/nRF52840/ble_hal.cpp
- wiring/src/spark_wiring_ble.cpp
BLE memory leak during scanning.
Issue: https://github.com/particle-iot/device-os/issues/1926
- Release the memory allocated for scanned advertising data if that event is not processed
- Do not acquire BLE wiring lock in characteristic data received callback.
1. Build the test applications below with `DEBUG_BUILD=y MODULAR=n` under the main folder
2. Flash the Central test app into a Xenon and flash the Peripheral test app into 3 Xenons respectively.
3. Run it for a long period and observe the log on the Central side.
Central:
```c
#define SCAN_RESULT_COUNT       50
BleScanResult results[SCAN_RESULT_COUNT];
BleCharacteristic peerTxCharacteristic[3];
BlePeerDevice peers[3];
void onDataReceived(const …
```
> Fix: BLE scanning memory leak

- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
Boron 2G/3G unable to connect when powered via VIN only with no Battery connected
Increase the input current limit from 900mA to 1500mA by software, we also have the hardware limitation for the input current. It's around 1590mA.
1. Power on the device by VIN, don't connect battery.
1. Apply below patch to force to use 2G network
```
diff --git a/hal/src/boron/network/sara_ncp_client.cpp b/hal/src/boron/network/sara_ncp_client.cpp
index 043582914..b34d032a9 100644
--- a/hal/src/boron/network/sara_ncp_client.cpp
+++ b/hal/src/boron/network/sara_ncp_client.cpp
@@ -881,6 +881,7 @@ int SaraNcpClient::initReady() {
// TODO: if we enable this feature in the future add logic to CHECK_PARSER macro(s)
// to wait longer for device to become active (see MDMParser::_atOk) …
```
> [system] Increase the input current limit from 900mA to 1500mA

- hal/src/electron/ota_flash_hal.cpp
- hal/src/photon/ota_flash_hal.cpp
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.h
#1927 did not completely enabled reporting of device serial and secret in `i` command in listening mode.
This PR fixes that.
1. Run the test app from #1927 to populate the OTP on Photon or Electron.
2. Put the device into listening mode
3. `i` command should output serial number and secret
N/A
- #1927
---
> [gen 2] hal: enables reporting of serial and mobile secret from OTP area in listening mode (`i` command)

- user/tests/wiring/no_fixture/interrupts.cpp
</details>
D7 pin interrupt unit tests for platform ID macro judgment. 
Fixes D7 pin interrupt unit test: be #if instead of #ifdef
Unit test about the D7 pin interrupt 
NULL
---
> Fixes D7 pin interrupt unit test: be #if instead of #ifdef

- hal/src/electron/modem/mdm_hal.cpp
We've seen SARA U2XX modems stuck returning potentially cached DNS lookup results for longer than records' TTL despite the fact that DNS records have been modified. The only thing that caused AT+UDNSRN to correctly re-resolve in those particular cases was to reset the modem.
This causes problems for device service deploys.
In order to remove this layer of uncertainty with AT+UDNSRN we are using our own DNS client on all Gen 2 cellular devices now, whereas previously we've only used it for LTE SARA R4 devices where AT+UDNSRN was not supported.
N/A
N/A
- [CH39529]
---
> electron: use standalone DNS client for all modem types

- hal/src/electron/modem/electronserialpipe_hal.cpp
- hal/src/electron/modem/mdm_debug.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- hal/src/electron/modem/pipe_hal.h
Electron modem logs are only enabled in debug builds (DEBUG_BUILD=y). They are useful, but we don't want to keep using debug binaries as default release binaries.
This PR modifies `mdm_hal.cpp` to use non-debug `LOG_PRINTF` calls instead of `DEBUG_D`.
Build example app, modem logs should be output on `Serial`.
```c++
void setup() {
}
void loop() {
}
```
N/A
---
> [electron] enables modem logs in non-debug builds [ch35402]

- hal/src/photon/wlan_hal.cpp
WPA Enterprise authentication fails in some environments.
By default WICED sets maximum TLS version to 1.2, however testing WPA Enterprise authentication in various environemnts showed that its implementation is flawed at least in WICED 3.7.0-7.
Limiting the maximum TLS version to 1.1 seems to resolve the issues for a number of the environemnts where the authentication was previously failing with TLS 1.2.
N/A
N/A
- [CH35409]
---
> [photon] wlan: limit WPA Enterprise maximum TLS version to 1.1

- system/src/system_cloud_internal.cpp
- system/src/system_network_internal.cpp
- system/src/system_network_internal.h
We'd like to have a way to reset the modem of a cellular device remotely. This PR extends the existing system handler for `device/reset` events to support a new reset type (`network`), which toggles all active network interfaces off an on.
Testing requires manipulating the Device Service to send the above event to a device. As of now, there's no easy way to send a reserved event to a device.
- [ch39772]
> Implement a command to reset all network interfaces of a device remotely

- hal/src/electron/modem/dns_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
See #1936 
- Open the socket for DNS Client and keep it open, do not close it.
- If the socket send fails, retry once after closing and reopening the socket.
- If the socket send fails a second time, close the socket and return the error.
- Changes polling of socket for pending data to using URCs to indicate pending data with `socketReadable()`
- Automatic socket/handle cleanup on creation of sockets
- Detects state mismatch between system and modem and invalidates DNS Client sock_ handle and also reinitializing mdm_hal sockets[] state
- Removes log noise by closing only untracked socket handles that are open [ch37610]
- Increases USOCO timeout to 130s based on observation that 120s timeout is not being respected by u-blox modem when the command results in CME ERROR.
See #1936 and …
> [LTE, u-blox] adds a mitigation to keep DNS Client responsive [ch38990]

- user/tests/wiring/i2c_mcp23017/interferer.cpp
- user/tests/wiring/i2c_mcp23017/interferer.h
`HighPriorityInterruptInterferer` is not properly implemented for Gen 3 devices in `wiring/i2c_mcp23017` test.
Implement it :)
- Run `wiring/i2c_mcp23017` test on Gen 3 platforms
N/A
N/A
---
> [test] i2c_mcp23017: implements HighPriorityInterruptInterferer for nRF52840-based platforms

- platform/MCU/nRF52840/src/hw_config.c
Originally reported in https://community.particle.io/t/workbench-local-flash-occasionally-requires-hard-reset/52744
The main issue is that `POWER_CLOCK_IRQn` interrupt comes in immediately after we jump from bootloader into the system part and before we initialize all the necessary power/clock related things in the Nordic SDK which causes a jump to `0x00000000` because the clock event handler has not been registered.
The problem comes from the fact that we are not stopping the clocks or disabling interrupts (all or at least `POWER_CLOCK_IRQn` specifically) before jumping into the system part.
I have no explanation on why we haven't seen this previously, perhaps a compiler started optimizing things slightly differently due to the Nordic SDK update in 1.2.1.
Surprisingly the event that …
> [nrf52840] platform: disable clock driver in Reset_System() before jumping into system firmware

- .workbench/manifest.json
Utilize temporary manifest.json to enable current tooling
manifest.json stored in hidden `.workbench` folder until a more permanent solution has been settled upon
A `manifest.json` file is required to enable DeviceOS development in the Workbench.
Provides a manifest.json file that allows us to take advantage of this functionality
Enable local development from the "Settings" menu in the workbench.
[Slack convo](https://s.slack.com/archives/CB4R2N05V/p1572557308140800)
---
> Enable Workbench DeviceOS local development

- modules/shared/nRF52840/build_linker_script.mk
Fixes a issue on Gen 3 devices when the compiler is not on the PATH
Use configuration from `build/common-tools` to call objdump to ensure the path configured with environment is used.
fixes #1960 
---
> Fix call to objdump

- .workbench/manifest.json
Missing target platforms
Adds platforms to `manifest.json`
Look for platform availability in Workbench, attempt compilation.
Mentioned in DeviceOS Guild Meeting
---
> Update manifest platforms

- hal/src/gcc/gpio_hal.cpp
Fixes init order bug as described in #1962 
Replaced global with fetch function that initializes static object on first use and returns a ref.
- [x ] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
> Ensure gpio pin map is initialized on first use for gcc build

- hal/network/ncp/wifi_network_manager.cpp
- hal/src/argon/network/esp32_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
Devices may get stuck in a state where they think they are connected to the network, where in fact they are not.
1. Bumps the `gsm0710muxer` submodule to bring in the fix that signals back to the NCP client whenever it exits with an error
2. Errors in data channel (carrying actual network packets) writes over muxer are now correctly handled
On Argon specifically we are now always performing a wifi scan before connecting, because we've learned that ESP32 doesn't support 802.11v/k/r, so with multiple access points in the area, Argons might have been connecting to a previously remembered AP which is not the best choice in its current location
N/A
N/A
- [CH39245]
- particle-iot/gsm0710muxer#4
---
> [Argon/Boron] NCP bugfixes

- hal/src/photon/wlan_hal.cpp
- user/tests/wiring/no_fixture/wifi.cpp
https://github.com/particle-iot/device-os/issues/1858
Calling `wiced_wifi_get_mac_address())` or potentially other functions before `wiced_wlan_connectivity_initialized()` returns true seems to lead to a hardfault. Add `wiced_wlan_connectivity_initialized()` check.
Test app shouldn't cause a hardfault.
```c++
void setup() {
WiFi.on();
uint8_t mac[6] = {};
WiFi.macAddress(mac);
}
void loop() {
Particle.process();
}
```
- Closes #1858 
---
> [photon] wlan: add wiced_wlan_connectivity_initialized() check in wlan_fetch_ipconfig()

- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/sleep_hal.cpp
- system/inc/system_sleep.h
**This branch currently targets to the internal/rework_system_sleep branch.**
N/A
N/A
N/A
```c
#define UART_TX_BUF_SIZE        20
void onDataReceived(const uint8_t* data, size_t len, const BlePeerDevice& peer, void* context);
const char* serviceUuid = "6E400001-B5A3-F393-E0A9-E50E24DCCA9E";
const char* rxUuid = "6E400002-B5A3-F393-E0A9-E50E24DCCA9E";
const char* txUuid = "6E400003-B5A3-F393-E0A9-E50E24DCCA9E";
BleCharacteristic txCharacteristic("tx",
BleCharacteristicProperty::NOTIFY,
txUuid,
serviceUuid);
BleCharacteristic rxCharacteristic("rx",
BleCharacteristicProperty::WRITE_WO_RSP,
rxUuid,
serviceUuid,
onDataReceived, &rxCharacteristic);
uint8_t txBuf[UART_TX_BUF_SIZE];
size_t txLen = 0; …
```
> Gen3 devices now can be woken up by BLE.

- hal/inc/interrupts_hal.h
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/sleep_hal.cpp
- hal/src/stm32f2xx/sleep_hal.cpp
- system/inc/system_sleep.h
- wiring/src/spark_wiring_system.cpp
N/A
N/A
N/A
```c
void onDataReceived(const uint8_t* data, size_t len, const BlePeerDevice& peer, void* context);
const char* serviceUuid = "6E400001-B5A3-F393-E0A9-E50E24DCCA9E";
const char* rxUuid = "6E400002-B5A3-F393-E0A9-E50E24DCCA9E";
BleCharacteristic rxCharacteristic("rx",
BleCharacteristicProperty::WRITE_WO_RSP,
rxUuid,
serviceUuid,
onDataReceived, &rxCharacteristic);
SystemSleepConfiguration config;
void onDataReceived(const uint8_t* data, size_t len, const BlePeerDevice& peer, void* context) {
System.sleep(config);
}
void setup() {
LOG(TRACE, "Application started.");
BLE.addCharacteristic(rxCharacteristic);
BleAdvertisingData data;
data.appendServiceUUID(serviceUuid);
BLE.advertise(&data); …
```
> Implements that Gen3 platforms can be woken up by multiple pins when they are in standby mode.

- hal/inc/hal_dynalib_core.h
- hal/inc/sleep_hal.h
- hal/src/core/sleep_hal.cpp
- hal/src/gcc/sleep_hal.cpp
- hal/src/nRF52840/sleep_hal.cpp
- hal/src/stm32f2xx/sleep_hal.cpp
- system/inc/system_sleep.h
- system/src/system_sleep.cpp
- wiring/src/spark_wiring_system.cpp
Device enters sleep mode without checking the sleep configuration.
Sleep configuration that varies from platforms should be validated before entering sleep mode.
N/A
```c
Serial1LogHandler log(115200, LOG_LEVEL_INFO);
/* This function is called once at start up ----------------------------------*/
void setup()
{
LOG(INFO, "Application started");
}
/* This function loops forever -----------------------------------------------*/
void loop()
{
delay(3000);
LOG(INFO, "Device is going to enter sleep mode.");
SystemSleepConfiguration config;
config.mode(SystemSleepMode::HIBERNATE).gpio(D0, RISING).gpio(WKP, RISING);
SystemSleepResult result = System.sleep(config);
LOG(INFO, "Device is woken up by: %d, error: %d.", result.wakeupReason(), …
```
> Validates sleep configuration before entering sleep mode

- hal/inc/hal_dynalib_socket_posix.h
- hal/inc/socket_hal_posix.h
- hal/network/lwip/posix/sys/socket.h
- hal/network/lwip/socket_hal.cpp
Export `sendmsg()` and `recvmsg()` systems calls
Only `sendmsg()` and `recvmsg()` allow sending and receiving ancillary data, which is the only way to access IP TOS information.
> Export sendmsg() and recvmsg() systems calls

- system/inc/system_control.h
- system/src/control/config.cpp
- system/src/control/config.h
- system/src/control/mesh.cpp
- system/src/system_control_internal.cpp
- system/src/usb_control_request_channel.cpp
- system/src/usb_control_request_channel.h
- user/tests/unit/led_service.cpp
- user/tests/unit/usb_control_request_channel.cpp
libusb limits the maximum length of a control transfer's data stage to [4096 bytes](https://github.com/libusb/libusb/blob/f20f2be7825e34b5273af17fc0740c60bd352b32/libusb/os/linux_usbfs.h#L85). This causes larger USB control requests to fail.
Implement support for chunked transfer of request/reply data by allowing the host to send multiple `SEND` and `RECV` requests for the same control request. This protocol change is backwards compatible with existing client implementations, i.e. newer versions of `particle-usb` will continue to work normally with older versions of Device OS that don't support chunked transfer.
- Run unit tests.
- Run integration tests from https://github.com/particle-iot/particle-usb/pull/19.
- [ch43088]
> Add support for chunked transfer of USB request/reply data

- hal/network/lwip/ppp_client.cpp
- hal/network/ncp/at_parser/at_parser_impl.cpp
- hal/src/boron/network/sara_ncp_client.cpp
As a user of a Gen 3 device, I would like the logging of modem AT commands and data TX/RX to be included in firmware by default on modular Boron/B SoM.
Unfortunately there is not enough space in modular firmware to enable all logging for Boron/B SoM, which is why it's only enabled for monolithic firmware.
Enable a minimal subset of logs for Boron/B SoM by default in modular firmware:
- AT commands and URCs
- PPP Client TX and RX bytes
Local Build outputting logs on TX (Serial1):
`device-os/modular $ make clean all -s PLATFORM=boron COMPILE_LTO=n APP=tinker-serial1-debugging program-dfu`
```c
// Build as modular app
// Outputting logs on USB (Serial)
void setup() {
}
void loop() {
}
```
ch33624
---
> [Gen 3] Logging modem AT commands and data TX/RX by default on modular Boron/B SoM [ch33624]

- ci/unit_tests.sh
- hal/src/electron/cellular_internal.cpp
- test/unit_tests/cellular/cellular.cpp
Some tests missing for currently covered cellular code.
Adds tests and fixes some comments.
Coveralls percentages for these files should have increased above these baseline amounts
```
63.79% cellular_internal.cpp
44.68% spark_wiring_cellular_printable.cpp
```
to
```
100% cellular_internal.cpp
100% spark_wiring_cellular_printable.cpp
```
---
---
- [internal] Increases cellular test coverage [ch35587] [#1930](https://github.com/particle-iot/device-os/pull/1930)
> Improves cellular test coverage [ch35587]

- hal/src/b5som/network/quectel_ncp_client.cpp
HW Flow control needs to be temporarily disabled on b5som due to hardware incompatibility
- Explicitly disable HW Flow control in the USART
- Remove AT command that enables HW Flow control on modem
- Manual testing required for now :D
---
> [b5som] Temporarily disables HW Flow Control

- hal/src/nRF52840/ble_hal.cpp
- hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
We've run out of flash space (again) on some Gen 3 platforms.
This PR:
1. Disables logging of checked errors in BLE HAL
2. Disable mbedtls debug logs
Both of these things together free up about 20-30k.
---
> [Gen3] Frees up some flash space

- docs/build.md
Story details: https://app.clubhouse.io/particle/story/45807
`EXTRA_CFLAGS` was added in 2015 but not documented. It's a very useful feature for customizing local builds.
> Document adding custom symbols during Device OS application build

- hal/inc/cellular_hal.h
- hal/inc/hal_dynalib_cellular.h
- hal/network/ncp/cellular/cellular_hal.cpp
- hal/network/ncp/cellular/cellular_ncp_client.h
- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/b5som/network/quectel_ncp_client.h
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.h
- hal/src/electron/cellular_hal.cpp
- user/tests/wiring/api/cellular.cpp
Cellular registration timeout is hardcoded to 5 minutes.  There may be instances where this needs to be specified by the user for their particular carrier/application.
Add cellular_registration_timout_set() API to override the 5 minute default timeout.
```c
void setup() {
cellular_registration_timeout_set(60 * 60 * 1000, nullptr); // 60 minutes
}
```
- [CH45850]
> Adds internal function to modify cellular registration timeout

- hal/src/b5som/network/quectel_ncp_client.cpp
Quectel modems don't support `CHAP:` option for `AT+CGDCONT` in the form: `AT+CGDCONT=<id>,<type>,CHAP:<apn>`.
This is something that has been copied over from ublox NCP client and should be removed.
This will cause problems (i.e. inability to get cellular connectivity due to `ERROR` response from the modem) for custom credentials with username and password as well as with empty credentials and Kore SIM cards due to our IMSI-based credentials store (see `network_config_db.cpp`: `{ "204", "04", "vfd1.korem2m.com", "kore", "kore" } // Kore/Vodafone`).
```
0000078901 [ncp.at] TRACE: > AT+CGDCONT=1,"IP","CHAP:vfd1.korem2m.com"
0000078949 [ncp.at] TRACE: < ERROR
```
Remove `CHAP:` generation for `AT+CGDCONT`.
Use Kore SIM (e.g. internal), clear the credentials, the device should not connect on …
> [b5som] hal: quectel modems don't support CHAP:<APN> in CGDCONT

- hal/src/stm32f2xx/core_hal_stm32f2xx.c
There is a possibility that in low power / unreliable power situations that checking if the system firmware flash pages are write protected will give the wrong result. The system firmware would attempt to write protect the system firmware flash pages, which erases the option bytes and if the device resets at that moment, sets the write protection level 1.
Remove all code paths in device boot that might change the option bytes which contains the write protection configuration.
Flash bootloader, system firmware and user firmware over the air.
Check the write protection registers by connecting to the device with a debugger using Workbench and running `monitor flash info 0` in the Debug Console.
```
#0 : stm32f2x at 0x08000000, size 0x00100000, buswidth 0, chipwidth 0
```
This shows that only …
> Don't check and write protect the system firmware on boot

- hal/src/boron/network/sara_ncp_client.cpp
Boron 2G/3G devices are having a hard time connecting to the cellular tower due to a few issues:
- AT+COPS=0 command is taking longer than the specified 3 minutes to resolve, if this times out initialization can fail early, and the cycle will repeat.
- The AT interface has been noted to not respond directly after the baudrate change command AT+IPR=921600 which causes a similar response.
- The observed status here is "blinking green"
- We are working with u-blox and Kore to gain insight on why COPS=0 is taking so long to resolve, but while we are digging in to pinpoint the source of the problem we will increase the timeout from 3 minutes to 5 minutes to help it complete successfully.
- The baudrate was changed to 115200 to avoid the issue seen with no response.  When other issues are …
> [Gen 3] Boron 2G/3G fixes

- user/build.mk
special shell variables are expanded when the `EXTRA_CFLAGS` build env var is processed by the build system resulting in build failures.
```sh
$echo $EXTRA_CFLAGS
-DFOO="$"
```
...then build
```sh
cd "${DEVICE_OS_PATH}/main" && make all program-dfu
#snipping out log noise...
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
```
don't expand the `EXTRA_CFLAGS` variable when setting `CFLAGS`
https://www.gnu.org/software/make/manual/html_node/Value-Function.html
build an app which [reads in a custom symbol](https://docs.particle.io/support/particle-tools-faq/local-build/#defining-custom-symbols) set via `EXTRA_CFLAGS` and reports the value as a cloud variable then build:
```
EXTRA_CFLAGS='-DFOO="$"' cd …
```
> prevent expansion of `EXTRA_CFLAGS` build env var

- hal/src/nRF52840/exflash_hal.c
- hal/src/nRF52840/ota_flash_hal.cpp
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
- user/tests/release-tests.json
- user/tests/wiring/no_fixture_stress/application.cpp
- user/tests/wiring/no_fixture_stress/exflash.cpp
- user/tests/wiring/no_fixture_stress/test.mk
See #1832 
https://infocenter.nordicsemi.com/index.jsp?topic=%2Ferrata_nRF52840_Rev2%2FERR%2FnRF52840%2FRev2%2Flatest%2Fanomaly_840_215.html&anchor=anomaly_840_215
The gist of the problem is that we concurrently access the external QSPI flash through two different mechanisms: QSPI peripheral and XIP (maps the external flash into the microcontroller memory space). As outlined in the anomaly description, the access to certain QSPI registers after the access to XIP region may lead to a complete CPU lockup. In our testing it showed also that under some circumstances it's not a complete lockup, but a failure to communicate with the QSPI flash.
The original plan was to any and all usage of XIP (currently used for OTA and module info retreival e.g. when sending a describe, validating modules, …
> [Gen 3] Workaround for QSPI/XIP nRF52840 hardware anomaly 215

- system/src/system_network_internal.h
- user/tests/wiring/cell_connect_after_off/application.cpp
- user/tests/wiring/cell_connect_after_off/cellular_conn_after_off.cpp
- user/tests/wiring/cell_connect_after_off/readme.md
…icle.connect()
<details>
```
```
</details>
In the case when a `'first' Particle.connect()` does not connect to cloud, and `Cellular.off()` was called to power off the cell radio, `subsequent Particle.connect()` does not work. The problem is due to `WLAN Watchdog timer` not clearing when Particle.connect() fails or when …
> Clear WLAN WD so it does not interfere with Particle.connect()

- .workbench/manifest.json
`.workbench/manifest.json` uses an older version of the `buildscripts` dependency
Update to `buildscripts@1.9.2`
Follow the steps to enable the `deviceOS@source` toolchain within Particle Workbench ([docs](https://docs.particle.io/support/particle-tools-faq/workbench/#working-with-a-custom-device-os-build)) - you should be able to compile and flash all platforms successfully
https://github.com/particle-iot/workbench/pull/114
---
> update workbench manifest with latest `buildscripts` dependency

- wiring/inc/spark_wiring_arduino.h
- wiring/inc/spark_wiring_spi.h
- wiring/src/spark_wiring_spi.cpp
- wiring_globals/src/wiring_globals_spi.cpp
1. Using SPI object in global object constructors leads to a crash due to undefined initialization order of global objects
2. `pinAvailable()` calls `SPI.isEnabled()`, potentially from interrupt context.
3. #1668
1. Use singleton-ish type of initialization for SPI objects with a function returning a reference to static object
2. Remove locking from `SPI.isEnabled()`, since in HAL it is anyway implemented with a volatile variable.
3. Adds `SPI_HAS_TRANSACTION` define
N/A
N/A
- https://community.particle.io/t/updating-from-deviceos-1-4-4-to-1-5-0-rc-1-sos-panic-1/54566
- #1879
- Closes #1668 
---
> [wiring] Fixes a regression in SPI due to thread-safety additions from #1879

- hal/src/nRF52840/usb_hal.cpp
The `USBSerial::read` method returns 0 instead of returning an invalid character to signal that there are no characters to read. It makes it impossible to make the difference between the 0 character and there being no characters to read from the serial port. 
This causes problems with functions that expect this method to return -1 whenever there are no characters left to read. This is the case of `Serial::readStringUntil`.
To solve the problem, I've added a check before reading a byte from the serial port to see whether there is one to read. If there isn't, it returns -1, otherwise the function works just like it did before.
System info:
* Firmware: built from this pull request
* Device: Particle Boron
Steps:
* Upload the following code to the device:
```c
#include <Particle.h> …
```
> [hal] usb serial: return -1 instead of 0 when there's no data to read

- test/unit_tests/wiring/print.cpp
`wiring_Print tests for all types` test suite may fail with Segmentation Fault.
Add a constructor to `PrintTest`, make sure the member variables are properly initialized.
Run the unit-tests.
N/A
N/A
---
> [test] unit: fixes Print tests failing

- user/tests/wiring/no_fixture/cellular.cpp
- user/tests/wiring/no_fixture/network.cpp
- wiring/src/spark_wiring_udp.cpp
`UDP::begin()` can be called when already active with an open socket. It will unconditionally create open a new socket and discard its reference to the old socket while leaving it open.
If this sequence is repeated the system can run out of socket handles preventing new UDP sockets from being opened and even preventing cloud connection.
While users should call `UDP::end()` to close any open socket before a new `UDP::begin()` the implementation should defensively check for and close an open socket on `UDP::begin()`.
**NOTE: this bug only applies to Gen 2 devices**
Call `stop()` in `begin()`.
This PR also frees up some flash space in `wiring/no_fixture` test suite for cellular platforms, as we started to overflow.
Run `wiring/no_fixture` tests on Gen 2 and Gen 3 platforms. All tests can be …
> [Gen 2] Fixes socket leak in UDP.begin()

- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
<details>
```
```
</details>
Quectel modems do not correctly report CGI data.
`quectel_ncp_client.cpp` appears to have been copied before CGI data was finished.
This results in not setting the flags TWO_DIGIT_MNC flag value, and the lac and ci are reported from uninitialized values.
Copy the latest Gen3 implementation from …
> Fix CGI for Quectel modems

- hal/network/ncp/at_parser/at_response.cpp
- hal/network/ncp/at_parser/at_response.h
> Fix parsing of large AT command responses

- hal/network/lwip/ppp_client.cpp
- hal/network/lwip/ppp_configuration_option.h
- hal/network/lwip/ppp_ipcp.cpp
- hal/network/lwip/ppp_ipcp.h
- hal/network/lwip/ppp_ipcp_options.cpp
- hal/network/lwip/ppp_ipcp_options.h
- hal/network/lwip/ppp_ncp.h
- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/nRF52840/lwip/lwippppopts.h
1. We sometimes see that the devices establish the PPP link, however remain stuck in blinking green. This is caused by the remote side changing offered DNS servers during the negotiation (i.e. it offers one set first and then after we accept if, for some reason offers another).
2. IPCP packets are not easy to debug and are dumped raw
3. [B5 SoM] For some reason we are not receiving CREG/CGREG/CEREG URCs on muxed AT channel and they only appear in the muxed data channel, which causes us to not notice loss of carrier.
1. All default IPCP options (IP addresses, Primary/Secondary DNS) are now overridable by the remote side. Once the PPP link is established, we now also check whether we've agreed on a set of DNS servers, and if not, teardown the link.
2. IPCP packet parsing is added.
3. [B5 …
> [Gen 3] Fixes renegotiation of options and adds IPCP packet parsing

- hal/inc/pinmap_hal.h
- hal/src/nRF52840/spi_hal.cpp
- hal/src/stm32f2xx/spi_hal.c
- user/tests/wiring/no_fixture_spi/application.cpp
- user/tests/wiring/no_fixture_spi/spi.cpp
- user/tests/wiring/no_fixture_spi/test.mk
- wiring/inc/spark_wiring_spi.h
- wiring/src/spark_wiring_spi.cpp
`SPI.begin(SPI_MODE_MASTER);` doesn't configure the default SS pin to be output high initially.
Assign default parameter for the second argument of the `SPIClass::begin(SPI_Mode mode, uint16_t ss_pin = SPI_DEFAULT_SS)`.
1. Build and download the following example App.
2. Check if the default SS pin according to https://docs.particle.io/reference/device-os/firmware/electron/#begin--4 can be toggled periodically.
```c
#if HAL_PLATFORM_STM32F2XX
#define SPI_DEFAULT_SS_PIN  A2
#elif PLATFORM_ID == PLATFORM_XENON || PLATFORM_ID == PLATFORM_ARGON || PLATFORM_ID == PLATFORM_BORON
#define SPI_DEFAULT_SS_PIN  A5
#endif
void setup()
{
SPI.begin(SPI_MODE_MASTER);
}
void loop()
{
digitalWrite(SPI_DEFAULT_SS_PIN, LOW);
delay(3000); …
```
> Redo: Fixes the issue that SPI default SS pin is not configured

- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
#1989
Flash the rest of the buffer using `Flash_ProgramByte`.
Gen 2 OTA/ymodem updates are not affected.
N/A
- Closes #1989 
- [CH46859]
---
> [stm32f2xx] platform: fix FLASH_Update() for unaligned writes

- communication/src/coap_channel.cpp
`g_unacknowledgedMessageCounter` goes up for devices that are connected and healthy when they get a Particle.variable request from the cloud. This was seen on Electrons running Device OS 1.4.4.
Root cause:
- Cloud makes a variable request
- Response is piggybacked on ACK for original request
- In `CoAPMessageStore::send`, it checks for message type. Since it's not `CoAPType::CON`, it calls `set_expiration` which sets `transmit_count` to a large value
- Some time later, `CoAPMessageStore::process` sees that the message has expired and it deletes it from the queue and calls `message_timeout` which increments `g_unacknowledgedMessageCounter`
`g_unacknowledgedMessageCounter` should only be incremented for confirmable messages that time out.
- Compile an application with a Particle.variable
- …
> Only increment unacknowledged counter for requests, not acknowledgements

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
<details>
```
```
</details>
Signal strength on Gen2 is collected using CSQ command. 
1. This command does not provide quality value on Gen2
2. This command is quite unreliable, meaning that is sometimes gives invalid signal strength value in an expectedly solid cell coverage location. 
u-blox recommends to use UCGED command, which is …
> Replace CSQ on Gen2 with UCGED (mode 5)

- hal/src/boron/network/sara_ncp_client.cpp
- user/tests/wiring/no_fixture/cellular.cpp
<details>
```
```
</details>
R410M uses CESQ to collect data, which is an unstable AT command to collect signal strength values.
Replace CESQ with UCGED (mode 5) only on R410M. UCGED gives RSRP/RSRQ in dBm/dB and CESQ gives in index values. RSRP/RSRQ from UCGED are converted from dBm/dB to CESQ-type index values and further processed. …
> Adding changes for R410M to use UCGED instead of CESQ

- ci/build_boost.sh
- ci/install_boost.sh
On macOS, `ci/build_boost.sh` builds Boost using the system's clang compiler while Device OS for the virtual platform requires GCC and the two can't be linked together.
Passing `toolset=darwin` to `b2` seems to resolve the problem.
On a macOS machine:
1. Remove cached Boost binaries:
```
rm -rf ~/.ci
```
2. Recompile Boost:
```
cd path/to/device_os
source ci/install_boost.sh
ci/build_boost.sh
```
3. Build Device OS:
```
cd path/to/device_os/main
make -s clean all PLATFORM=gcc TEST=app/blank
```
> Fix building of Boost on macOS

- communication/inc/file_transfer.h
This PR fixes a regression introduced in https://github.com/particle-iot/device-os/pull/2041, which relies on a wrong assumption that the `FileTransfer::Descriptor` class correctly initializes itself. This is a good example of why all class member and stack variables should be initialized explicitly at the time of their declaration, even if their initial values are overwritten later in the code.
Firmware update via YModem should succeed.
> Fix YModem transfer

- hal/inc/hal_dynalib_concurrent.h
Expose the rest of concurrent HAL APIs.
> [hal] concurrent: expose full concurrent APIs.

- wiring/inc/spark_wiring_thread.h
Memory leakage if using wiring `Mutex` or `RecursiveMutex` class.
Add destructor which destroys the mutex if valid.
```c
SerialLogHandler log(LOG_LEVEL_ALL);
void setup() {
}
void loop() {
while(!Serial.isConnected());
delay(1000);
static runtime_info_t heapInfo;
if (heapInfo.size == 0) {
heapInfo.size = sizeof(heapInfo);
}
HAL_Core_Runtime_Info(&heapInfo, nullptr);
Serial.printlnf("\n\n\n=======TP21============");
Serial.printlnf("Heapinfo: size :%d, largest_free_block_heap :%lu", heapInfo.size, heapInfo.largest_free_block_heap);
Serial.printlnf("===================\n\n\n");
Mutex _buffer_mutex;
HAL_Core_Runtime_Info(&heapInfo, nullptr);
Serial.printlnf("\n\n\n=======TP22============");
Serial.printlnf("Heapinfo: size :%d, …
```
> [wiring] Thread: fixes memory leakage due to mutex not being destroyed.

- user/tests/wiring/api/wiring.cpp
- wiring/inc/spark_wiring_i2c.h
- wiring/src/spark_wiring_i2c.cpp
Multiple conflicting candidates when calling Wire.requestFrom() in 1.5.0-rc.x:
```
../wiring/inc/spark_wiring_i2c.h:108:10: note: candidate: size_t TwoWire::requestFrom(uint8_t, size_t)
size_t requestFrom(uint8_t, size_t);
^
../wiring/inc/spark_wiring_i2c.h:110:10: note: candidate: size_t TwoWire::requestFrom(int, int)
size_t requestFrom(int, int);
^
```
Removes unnecessary `requestFrom(int, int)` and `requestFrom(int, int, int)` overloads.
`wiring/api`
N/A
- [CH50131]
- https://community.particle.io/t/deviceos-1-5-0-rc2-causing-compile-errors-for-i2c-libraries/55099
- https://community.particle.io/t/updating-from-deviceos-1-5-0-rc-1-rc-2-adafruit-ssd1306-lib-causes-freeze/54740/14
---
> [wiring] Wire.requestFrom() multiple conflicting candidates

- user/tests/wiring/no_fixture/spi.cpp
- wiring/inc/spark_wiring_spi.h
Originally reported in https://community.particle.io/t/updating-from-deviceos-1-5-0-rc-1-rc-2-adafruit-ssd1306-lib-causes-freeze/54740/7
This is another side effect of https://github.com/particle-iot/device-os/pull/2023 and https://github.com/particle-iot/device-os/pull/1879.
The issue is caused by the usage of [`Mutex`](https://github.com/particle-iot/device-os/blob/develop/wiring/inc/spark_wiring_spi.h#L156) as a synchronization primitive on Gen 2 platforms, whereas after the changes in the PRs mentioned above, wiring is expecting a recursive mutex.
Replace with `RecursiveMutex`.
- `wiring/no_fixture`
N/A
- https://community.particle.io/t/updating-from-deviceos-1-5-0-rc-1-rc-2-adafruit-ssd1306-lib-causes-freeze/54740/7
- [CH50091]
---
> [Gen 2] Fixes SPI.beginTransaction() deadlocking

- hal/src/argon/network/esp32_ncp_client.cpp
- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- user/tests/wiring/no_fixture_long_running/network.cpp
The loss of signal can cause the modem to draw higher currents and if the power supply is not sufficient, the modem power supply will brown out and the NCP client will become unresponsive to keep alive pings.  `[gsm0710muxer] ERROR: The other end has not replied to keep alives (TESTs) 5 times, considering muxed connection dead` can be observed in the logs when this happens.  This could be immediately after signal is lost, or approx. 5.2 minutes afterwards.  This causes the AT command & Data muxer to go through a teardown, which in turn causes the NCP client to turn off the modem, but the PPP client doesn't know about this and keeps trying to retransmit a configure-request for IPCP.  The modem will attempt to be turned on, the retransmitted configure-request will fail, and the modem …
> Ensure NCP connection state is processed when changed by the muxer [ch48825]

- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/b5som/network/quectel_ncp_client.h
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.h
There is a race condition between CREG/CGREG/CEREG URC handlers that may leave LAC and Cell ID parts of CGI invalid.
Set conditionally based on RAT in CGREG and CEREG handlers, fallback to CREG.
N/A
N/A
N/A
---
> [Boron/B SoM/B5 SoM] Fix Cellular Global Identity generation

- hal/network/ncp/cellular/cellular_hal.cpp
- hal/src/electron/cellular_hal.cpp
See #2066.
The main problem is `getCellularGlobalIdentity()` function (in NCP or modem implementation) was getting a temporary intermediate on-stack structure `CellularGlobalIdentity` completely uninitialized (thus containing garbage data of whatever was potentially previously on stack). We were lucky (and are lucky with 1.5.0 release on every platform except for Electron) that its `size` field was always initialized to some large value > `sizeof(CellularGlobalIdentity)`, which made the sanity check pass correctly.
Just pass `CellularGlobalIdentity` struct directly into the modem/NCP code and let it handle it, instead of using a temporary uninitialized on-stack variable as an intermediate.
Make sure CGI is available on all cellular platforms in vitals.
```c++
void setup() { …
```
> [Cellular] Fixes an issue with CGI (Cellular Global Identity) not available on some devices

- hal/src/b5som/network/quectel_ncp_client.cpp
Move code to enable hardware flow control to do this earlier in the code, as soon as AT is ready.
Story details: https://app.clubhouse.io/particle/story/51153
> Enable HW Flow control on Quectel modems earlier in the init process

- hal/src/b5som/network/quectel_ncp_client.cpp
Related to [ch51153](https://app.clubhouse.io/particle/story/51153/add-at-command-at-ifc-2-2-to-enable-hw-flow-control-on-quectel-modems-during-init)
Check for AT interface to respond after setting baud rate
Change `QUECTEL_NCP_DEFAULT_SERIAL_BAUDRATE` to a different baud rate than existing
https://app.clubhouse.io/particle/story/51153/add-at-command-at-ifc-2-2-to-enable-hw-flow-control-on-quectel-modems-during-init
---
> Move code to wait for AT after setting run time baud

- hal/src/electron/modem/mdm_hal.cpp
Old API rssi and qual values are not available on LTE Electrons/E Series because we've switched over to UCGED in #2033.
Add a compatibiltiy layer, same as on Gen 3.
Use the app. On Electron LTE it should provide sane values instead of `2,0` and should be comparable to pre-1.5.0.
```c++
void setup() {
}
void loop() {
auto sig = Cellular.RSSI();
Log.trace("%d, %d", sig.rssi, sig.qual);
delay(5s);
}
```
- [CH51264]
---
> [electron] cellular: compat rssi/qual for LTE devices using UCGED

- hal/src/nRF52840/lwip/lwipopts.h
The size of the ARP queue for pending network packets is limited to 3 on Argon. This results in the loss and subsequent retransmission of one of the four handshake packets sent when the session is resumed.
Increase the size of the ARP queue.
- [ch51720]
> Increase the size of the ARP queue

- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
We have been requested by cellular providers to increase the registration timeout to 10 minutes.
Increase it to 10.
N/A
N/A
N/A
---
> [cellular] increase registartion timeout to 10 minutes

- communication/inc/protocol.h
- communication/inc/protocol_defs.h
- communication/src/chunked_transfer.cpp
- communication/src/chunked_transfer.h
This PR introduces the following changes:
1. Reduce the maximum number of firmware chunks that can be requested by an Argon during OTA from 40 to 20. Argon doesn't seem to be able to receive more than 25 chunks from a given flight of chunks, which causes it to drop `UpdateDone` messages repeatedly.
2. Do not wait for an ACK for a `ChunkMissed` message synchronously. This causes the comms library to drop packets and blocks the system loop during OTA.
3. Rework logging in the OTA code so that it's easier to debug.
- [ch48671]
> OTA adjustments for Argon

- hal/src/b5som/network/quectel_ncp_client.cpp
<details>
```
```
</details>
Quectel BG96 does not give valid values in QCSQ command to calculate signal stregnth immediately after power up. There is a known delay associated with this modem to give a valid value. If the code checks this AT command before it's ready, we get `0` for RSRP and RSRQ. Currently, we are translating `0` as …
> Invalidate value of '0' for RSRP and RSRQ on B5SoM

- wiring/src/spark_wiring_ble.cpp
```c
SerialLogHandler log(LOG_LEVEL_ALL);
iBeacon beacon(0, 0, "6E400001-B5A3-F393-E0A9-E50E24DCCA9E", 0);
/* This function is called once at start up ----------------------------------*/
void setup()
{
while(!Serial.isConnected());
delay(1000);
static runtime_info_t heapInfo;
if (heapInfo.size == 0) {
heapInfo.size = sizeof(heapInfo);
}
HAL_Core_Runtime_Info(&heapInfo, nullptr);
Serial.printlnf("\n\n\n=======TP1============");
Serial.printlnf("Heapinfo: size :%d, largest_free_block_heap :%lu", heapInfo.freeheap, heapInfo.largest_free_block_heap);
Serial.printlnf("===================\n\n\n");
BLE.advertise(beacon);
HAL_Core_Runtime_Info(&heapInfo, nullptr);
Serial.printlnf("\n\n\n=======TP2============");
Serial.printlnf("Heapinfo: size :%d, …
```
> [wiring] BLE: use 'delete' in corresponding to the 'new' keyword

- hal/network/ncp/cellular/cellular_hal.cpp
- hal/network/ncp/cellular/cellular_ncp_client.h
- hal/shared/cellular_enums_hal.h
- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
- Access technology on R410M modems on Boron LTE is sometimes registered as `7` and sometimes registered as `8`. Hence, mapping them correctly for the R410M platform, by considering both `7` and `8` as Cat-m1 RAT.
- Rename access technology related enums to be more understandable.
Story details: https://app.clubhouse.io/particle/story/49272
> Map AccessTechnology correctly on SARA R410M

- modules/shared/nRF52840/build_linker_script.mk
https://community.particle.io/t/workbench-local-compile-syntax-error/55841/3
We need to be more specific in grepping the `.data` and `.bss` section description entries from `arm-none-eabi-objdump` output.
Name your application e.g. `adata`, build it. The build should succeed on all platforms: Windows, Linux, macOS.
N/A
- https://community.particle.io/t/workbench-local-compile-syntax-error/55841/3
---
> [nrf52840] fix an issue with platform_user_ram.ld generation when path contains 'data'

- hal/src/nRF52840/i2c_hal.cpp
- hal/src/nRF52840/spi_hal.cpp
- hal/src/nRF52840/usart_hal.cpp
- hal/src/stm32f2xx/i2c_hal.c
- hal/src/stm32f2xx/spi_hal.c
- hal/src/stm32f2xx/usart_hal.c
- user/tests/wiring/no_fixture_spi/spi.cpp
- wiring/src/spark_wiring_spi.cpp
SPI and I2C transaction becomes slow after introducing locking mechanism.
Removes lock in some functions.
Build and flash the `wiring/no_fixture_spi` testing application.
- Photon [Gen2]:
```
87 ms
Test SPI_11_SPI_Transfer_10000_Bytes_No_Locking_Less_Than_135_Ms passed.
51 ms
Test SPI_12_SPI_Transfer_10000_Bytes_Locking_Less_Than_135_Ms passed.
51 ms
Test SPI_13_SPI_Transfer_2_Miltiply_5000_Bytes_Locking_Less_Than_135_Ms passed.
175 ms
Test SPI_14_SPI_Transfer_10000_Bytes_DMA_No_Locking_Less_Than_140_Ms failed.
141 ms
Test SPI_15_SPI_Transfer_10000_Bytes_DMA_Locking_Less_Than_140_Ms failed.
85 ms
Test SPI_16_SPI_Transfer_2_Multiply_5000_Bytes_DMA_Locking_Less_Than_85_Ms failed.
34 ms
Test SPI_17_SPI_Transfer_10_Multiply_1000_Bytes_DMA_Locking_Less_Than_40_Ms passed.
```
- Argon [Gen3]: …
> Removes locking in some of the SPI and I2C APIs to improve performance

- system/src/system_cloud.cpp
- user/tests/wiring/no_fixture/thread.cpp
…a custom thread
<details>
```
```
</details>
If `Particle.process()` is called from custom thread, it runs `Spark_idle_events()`
(It's not safe is that Particle.process (and the underlying spark function) also handle things like serial event handlers, subscription handlers, function handlers, and (in 1.5.0 and later) variable …
> Particle.process() is a no-op when called from a custom thread.

- system/src/system_network_cellular.h
Gen2 reports `SIM not inserted` or `Sim not inserted? Detecting...` when modem is not responsive. It is misleading because modem AT was not responsive and is confusing users to think that Sim is not inserted.
Changed log message from `Sim not inserted` to `SIM/modem not responsive or SIM not inserted/requires a PIN.`
May spoof AT not working by changing baud rate, or by connecting cell USB at the same time for testing purposes.
```c
void setup() {
}
void loop() {
}
```
[ch50557](https://app.clubhouse.io/particle/story/50557/remove-sim-not-inserted-for-unresponsive-modem)
---
> [electron] Fix "Sim not inserted" debug log when modem is not responsive

- user/tests/wiring/api/spi.cpp
- wiring/inc/spark_wiring_spi.h
- wiring/inc/spark_wiring_spi_proxy.h
A number of libraries rely on the internals of our wiring SPI implementation (`SPIClass`). After introducing a proxy class in #2089, we inadvertently broke them.
As a workaround we can introduce implicit conversion operator to the proxy class to convert to `SPIClass&`, as well as `operator&` overload to be able to convert a proxy instance to `SPIClass*`. This is not ideal, but pretty much the simplest thing we can do.
- Test affected libraries/projects e.g. LIS3DH
- `wiring/api`
N/A
- https://community.particle.io/t/updating-from-deviceos-1-5-0-to-1-5-1-rc-1-sdfat-spiproxy-compile-issue/55993
- https://community.particle.io/t/electron-1-5-1-rc-1-and-assettrackerv2-error-lis3dh/56002/4?u=scruffr
---
> [wiring] spi: an attempt to bring back compatibility with SPIClass

- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.h
Boron LTE-M1 cell radio becomes unresponsive (by getting stuck at an AT command) after "large" data or application describe message is sent continuously over muxer data channel
This is a callback that writes data into muxer channel 2 (data PPP channel). Whenever we encounter a large packet, we enforce a certain number of ms to pass before transmitting anything else on this channel. After we send large packet of size 250, we drop messages(bytes) for a certain amount of time defined by UBLOX_NCP_R4_WINDOW_SIZE_MS (50ms)
Which unit/integration/application tests are applicable to this code change? (At minimum a test of some kind should be provided)
```c
SerialLogHandler logHandler(Serial, LOG_LEVEL_TRACE);
void …
```
> [Boron] Radio unresponsive when sending large data or application desc msgs

- wiring/inc/spark_wiring_fuel.h
- wiring/src/spark_wiring_fuel.cpp
Returned value of FuelGauge's wiring APIs cannot indicate error on failed.
1. Build and flash the following example application for B5SoM that is attached on SoM evaluation board.
2. Connect the SoM evaluation board to serial terminal.
3. Detach the jumper for PM_SCL or PM_SDA and see if a negative value is printed on serial terminal.
```c
SerialLogHandler log(115200, LOG_LEVEL_ALL);
void setup()
{
Serial.begin(115200);
while(!Serial.isConnected());
LOG(TRACE, "Application started.");
}
void loop() {
FuelGauge gauge;
LOG(TRACE, "SoC: %4.2f %%", gauge.getSoC());
delay(1000);
}
```
---
> FuelGauge: return error if it failed to read/write registers.

- hal/src/electron/pinmap_defines.h
- hal/src/photon/pinmap_defines.h
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/stm32f2xx/i2c_hal.c
I2C bus is driven LOW after `Wire.begin()` when building with JTAG/SWD enabled on Electron.
Initialize I2C pins to be float input.
```c
void setup() {
Wire.begin();
}
void loop() {
}
```
1. Build modular firmware with JTAG/SWD enabled:
`make PLATFORM=electron DEBUG_BUILD=y USE_SWD_JTAG=y`
2. Flash system firmware and the above application.
3. Use logic analyser to monitor the SDA(D0) and SCL(D1) and see if both pins go to high level or not.
---
> [hal] i2c: bus is driven low if building with JTAG/SWD enabled.

- system/src/system_cloud_internal.cpp
- system/src/system_string_interpolate.cpp
- user/tests/unit/string_interpolate.cpp
- user/tests/unit/stubs/system_cloud_internal.cpp
Currently the default particle server key for UDP devices is `$id.udp.particle.io` and `$id.udp-mesh.particle.io`. The wildcard `$id` is expanded to the device ID. In order to support LTS and to be able to route all devices on a particular major version of Device OS to a specific Device Service, expand the wildcard `$id` to the `<device_id>.v<device_os_major_version>` so for a device `1234` at `Device OS v2.1.0` it would connect to `1234.v2.udp.particle.io`
If appropriate, the public server key is updated after loaded with the major version from v0 ~ v255.
- Unit tests have been added and can be run
- UDP devices can be tested and should continue to connect appropriately now, and can also be routed in the future as required.
- Tested these devices, all connect:
```
Electron
0000007381 …
```
> Update the Particle server hostname wildcard to include the Device OS major version [ch53190]

- hal/network/lwip/cellular/pppncpnetif.cpp
- hal/src/b5som/network/quectel_ncp_client.cpp
- hal/src/b5som/network/quectel_ncp_client.h
- hal/src/boron/network/sara_ncp_client.cpp
- hal/src/boron/network/sara_ncp_client.h
Gen 3 cellular devices currently always power off and power the modem back on on boot. This affects the boot/cloud connection times significantly especially on platforms where poweron/poweroff times are noticeable.
Implement support for warm bootup!
N/A
N/A
- [CH50404]
---
> [Gen 3] Modem warm bootup

- hal/src/boron/network/sara_ncp_client.cpp
We want to increase the baudrate on SARA R4-based devices to improve OTA times, however compared to all the other modems, `AT+IPR` setting on SARA R4 is persistent (!).
We need to have an intermediate release in 1.5.x line supporting both baudrates and changing the persistent value to 115200 in order to support downgrades from 2.x.
Try to talk to the modem on both 460800 and 115200 and change persistent value to 115200.
1. Force LTE Boron/BSoM modem to use 460800 (`AT+IPR=460800`), power down device completely, flash system-part out of this branch
2. The device should connect to the cloud
3. Downgrade to 1.5.1, the device should connect to the cloud
N/A
- [CH54763]
---
> [boron] forward compatibility with 460800 baudrate on SARA R4

- hal/src/photon/softap.cpp
- system/src/system_setup.cpp
- user/tests/wiring/api/wifi.cpp
- wiring/inc/spark_wiring_wifi_credentials.h
</details>
As per documentation,` setSecurity()` should be given a value belonging to `SecurityType` enum, but currently it expects a `WLANSecurityType` in the code, and hence results in compile error for `WLAN.setSecurity(WPA2)`
Currently, the argument for `setSecurity()` is `WLANSecurityType` which throws the compile error. Changing the argument to `SecurityType` fixes it but breaks other internal code that passes `WLANSecurityType` to the `setSecurity()`. Hence, changed the `setSecurity()`'s argument to `SecurityType` for wiring and added another member `setWlanSecurity()` for internal use. 
```c
void setup() {
WiFiCredentials credentials;
credentials.setSecurity(WPA2);
}
void loop() {
}
```
- [ch50408](https://app.clubhouse.io/particle/story/50408/incompatibili …
> Add a new member to differentiate internal and wiring setSecurity

- hal/src/b5som/network/quectel_ncp_client.cpp
BG96 falls back to 2G network even if we force it to connect to Cat-M1. We found that `AT+COPS=0` will reset `AT+QCFG="nwscanmode"` from `3 LTE only` to `0 Automatic`
```
AT+QCFG="nwscanmode",3,1
OK
AT+COPS=0
OK
AT+QCFG="nwscanmode"
+QCFG: "nwscanmode",0
OK
```
Set `nwscanmode` configuration after `AT+COPS=0` 
Check `nwscanmode` configuration after connecting to the Particle Cloud.
```c
Serial1LogHandler logHandler(115200, LOG_LEVEL_ALL, {
{"app", LOG_LEVEL_ALL},
{"ncp.at", LOG_LEVEL_ALL},
{"hal.ble", LOG_LEVEL_WARN},
{"system.listen.ble", LOG_LEVEL_WARN},
{"sys.power", LOG_LEVEL_WARN}
});
static int lines;
static int handler(int type, const char* buf, int len, int* lines) {
Log.info("data: %s", buf);
return WAIT;
}
void setup() {
}
void loop(void) { …
```
> [hal] Forbid BG96 falling back to 2G network

- hal/shared/cellular_enums_hal.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
Modem software version of `DevStatus` is allocated 16 bytes overall, but the modem version itself is 16 bytes, so it is missing an additional byte for the null termination. Similarly, other functions in modem hal are to be checked for buffer size before writing into them.
Add an extra byte in the `ver` member of the `DevStatus` struct to accommodate 16 bytes data and one null. 
Fix `_cbString` and other relevant `_cb` functions by adding a `CStringHelper` that allows passing string and string size into the callback, which can be used for size checking when writing into buffers. 
Check that version number is logging correctly. This may _not_ be indicative of failure/success but a  basic test app that might help uncover the problem.
```c
SerialLogHandler logHandler …
```
> [Gen2] Fix buffer overrun in modem hal 

- system/src/system_power_manager.cpp
SoC (State of Charging) is not updating after device being woken up.
From the FuelGauge's datasheet, we should add a delay about 500ms after the FuelGauge exiting sleep mode.
We simply add the delay in system power manager, instead in the FuelGauge library. This provides an opportunity that users can omit such a delay if they use the FuelGauge library directly and don't need to update the SoC right after the FuelGauge being woken up. @rickkas7 We should probably document this for visibility.
Reference: 
https://community.particle.io/t/sleepy-boron-soc-not-updating/55086/37
---
> Fixes the issue that FuelGauge doesn't work as expected after being woken up

- user/tests/wiring/api/wifi.cpp
- user/tests/wiring/no_fixture/wifi.cpp
- wiring/inc/spark_wiring_wifi.h
Wifi wiring calls that are either unimplemented or unsupported might cause confusion to customers who are trying to use them (may be because they are likely supported on different platforms)
Throw compile time errors for unimplemented or unsupported wifi wiring calls on Gen3
The following code should throw a compile error when built on Gen3 - Argon, for example
such as 
```
filename.cpp:6:28: error: 'class spark::WiFiClass' has no member named 'hostname'; did you mean 'setHostname'?
```
```c
void setup() {
String hostname = WiFi.hostname();
Serial.printlnf("Wifi hostname is %s" ,hostname);
}
void loop() {
}
```
[ch51761](https://app.clubhouse.io/particle/story/51761/hide-wifi-hostname-on-gen-3)
[ch51357](https://app.clubhouse.io/particle/story/51357/wifi-hostname-i …
> [Gen3] Hide wifi wiring API that are not supported

- hal/src/electron/modem/mdm_hal.cpp
- user/tests/app/band_select/band_select.cpp
Compile error when building Electron after updating to gcc compiler 9.2.1
```
error: 'sprintf' may write a terminating nul past the end of the destination
```
Use `snprintf` instead of `sprintf` to give number of bytes.
Compiling Electron on gcc 9.2.1 likely triggers this error.
```c
void setup() {
}
void loop() {
}
```
[ch55930](https://app.clubhouse.io/particle/story/55930/electron-fix-an-sprintf-error-surfacing-in-gcc-9-2-1)
---
> [Gen2] Fix sprintf compile err on gcc9

- hal/src/electron/modem/mdm_hal.cpp
A registration URC like `CEREG: 0` is not processed by Electron LTEs, and hence even though a `CEREG: 0` is received by the device, the device still blinks cyan assuming it's connected to cloud, and does not attempt a disconnection process.
Read and process reg URCs for `CxREG :0` to notify a disconnection
After a successful cloud connection, remove antenna or trigger (somehow) a loss of registration, by which you will see a `CEREG: 0` on the module. When this happens, notice that the device should go back to blinking green, signaling a new connection attempt. 
```c
void setup() {
}
void loop() {
}
```
[ch36648](https://app.clubhouse.io/particle/story/36648/electron-lte-stuck-breathing-cyan-but-offline-when-de-registered-urc-received-by-not-acted-on-to-force-network-teardown)
---
> Process 'CEREG: 0' URCs on R410M

- system/src/control/storage.cpp
Result codes returned by `Spark_Finish_Firmware_Update()` have changed in `develop` and firmware updates via control requests no longer work.
Updating the firmware via particle-usb should work.
> Fix firmware updates via control requests

- hal/src/photon/include.mk
`third_party/miniz` is not linked when linking `hal` module, which causes the following error:
```
firmware_public/hal/src/photon/compressed_resources.c:33: undefined reference to `tinfl_decompress'
```
Add `third_party/miniz` to `HAL_DEPS`
```
> cd main
> make PLATFORM=photon TEST=app/blank MODULAR=n clean all
```
N/A
N/A
---
> [build] Fixes monolithic build on photon

- wiring/inc/spark_wiring_spi.h
__SPISettings naming is not compatible with Arduino layer
Rename `__SPISettings` to `SPISettings` and still keep `__SPISettings` as an alias
Existing unit tests, but also something like this app should compile without errors 
```
void setup() {
int32_t r = SPI.beginTransaction(__SPISettings(SPI_CLK_SYSTEM, SPI_MODE0, MSBFIRST));
(void)r;
int32_t r2 = SPI.beginTransaction(SPISettings(SPI_CLK_SYSTEM, SPI_MODE0, MSBFIRST));
(void)r2;
}
void loop() {
}
```
[ch55527](https://app.clubhouse.io/particle/story/55527/rename-spisettings-to-spisettings-while-keeping-spisettings-as-an-alias)
[ch54115](https://app.clubhouse.io/particle/story/54115/free-up-flash-space-removing-default-in-spisettings)
---
> Add SPISettings while keeping __SPISettings as an alias for wiring layer

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
Despite being registered, an `AT+COPS=0` call under some conditions may take substantial amount of time, which will prolong the bootup times.
1. Only perform `AT+COPS=0` conditionally. This is only implemented for uBlox-based devices, as Quectel seems to behave correctly and also we cannot reliably tell whether it's attempting to perform registration or not (it may report `+COPS: 0` even if it's not attempting to find an operator).
2. Additionally we've enabled packet domain errors (`AT+CGEREP`) which are useful in debugging connectivity issues
3. This PR also makes sure that failure to open muxer data channel used for PPP connections is treated as a non-recoverable failure, causing modem reset.
1. Make sure a cellular device is connected to the cloud
2. Reset
3. `AT+COPS=0` should not be …
> [ublox] Do not run AT+COPS=0 when performing warm bootup if already registering/registered

- hal/src/nRF52840/posix/syscalls_posix.cpp
- user/tests/wiring/filesystem/posix.cpp
`rename()` does not actually call into dynalib-exposed `_rename()` due to `HAVE_RENAME` not defined with our variant of newlib supplied with ARM GCC toolchain and it's actually implemented as `_link()` + `_unlink()`: https://github.com/mirror/newlib-cygwin/blob/master/newlib/libc/reent/renamer.c#L43
Disclaimer: it's a hack
Rename in `_link` if `HAVE_RENAME` is not defined and temporarily cache the oldpath to an unused location in the reentrant thread-local structure and suppress errors in subsequent `_unlink()` call if the path matches.
`wiring/filesystem`.
N/A
- [CH57479]
---
> [gen3] syscall: our newlib variant implements rename as _link + _unlink

- user/tests/wiring/api/spi.cpp
- user/tests/wiring/no_fixture_spi/spi.cpp
- user/tests/wiring/spi1_stress/application.cpp
- user/tests/wiring/spi1_stress/port.cpp
To add unit tests for `__SPISettings` renamed to `SPISettings`. See [PR2138](https://github.com/particle-iot/device-os/pull/2138)
Added tests
[PR2138](https://github.com/particle-iot/device-os/pull/2138)
[ch55527](https://app.clubhouse.io/particle/story/55527/rename-spisettings-to-spisettings-while-keeping-spisettings-as-an-alias)
---
> Add unit tests for SPISettings

- build/release.sh
- build/version.mk
- modules/shared/system_module_version.mk
- system/inc/system_version.h
- system/system-versions.md
- user/tests/integration/application/src/application.cpp
- user/tests/integration/wiring/no_fixture
- user/tests/wiring/no_fixture/application.cpp
- user/tests/wiring/no_fixture/cellular.cpp
- user/tests/wiring/no_fixture/led.cpp
- user/tests/wiring/no_fixture/no_fixture.spec.js
- user/tests/wiring/no_fixture/system.cpp
- user/tests/wiring/no_fixture/time.cpp
- user/tests/wiring/no_fixture/wifi.cpp
Currently test runner expects tests to be in integration folder. As a quick workaround for now we've added a spec file to no_fixture test suite and symlinked it to integration.
This PR also contains a number of fixes for no_fixture tests.
This PR also bumps version to 2.0.0-alpha.3 in order not to mess with existing alpha.1/alpha.2 releases on CI.
N/A
N/A
N/A
---
> Some changes in order to run no fixture tests under test runner / CI

- hal/src/nRF52840/sleep_hal.cpp
- hal/src/nRF52840/timer_hal.cpp
`System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).duration(3s));` doesn't work on Gen3 platforms.
This issue is caused by not clearing RTC event in its interrupt handler. After device being woken up in `hal_sleep_enter()`, it will repeat entering the RTC interrupt handler.
- Build and flash the example below
- Build and flash the test application in `user/tests/wiring/sleep20`
```c
void setup() {
delay(1000);
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).duration(3s));
}
void loop() {
}
```
---
> Fixes the issue that gen3 devices cannot be woken up by RTC.

- hal/inc/adc_hal.h
- hal/inc/hal_dynalib_gpio.h
- hal/src/nRF52840/adc_hal.cpp
- hal/src/stm32f2xx/adc_hal.c
- hal/src/template/adc_hal.cpp
- user/tests/hal/adc/test_adc.cpp
- wiring/src/spark_wiring.cpp
- wiring_globals/src/spark_wiring_gpio.cpp
Implement sleep API for ADC on Gen2 and Gen3 device
Download the example application, make sure the sleep API won't affect ADC function.
Formatting changes will be added after the review.
```c
void setup(void) {
}
void loop() {
HAL_ADC_Sleep(true, nullptr);
delay(1000);
HAL_ADC_Sleep(false, nullptr);
Log.info("A0: %ld", HAL_ADC_Read(A0));
}
```
[CH55886]
---
>  Implement sleep API for ADC on Gen2 and Gen3 device

- hal/inc/hal_dynalib_usart.h
- hal/inc/usart_hal.h
- hal/inc/usart_hal_private.h
- hal/src/electron/modem/electronserialpipe_hal.cpp
- hal/src/gcc/usart_hal.cpp
- hal/src/nRF52840/i2c_hal.cpp
- hal/src/nRF52840/serial_stream.cpp
- hal/src/nRF52840/serial_stream.h
- hal/src/nRF52840/sleep_hal.cpp
- hal/src/nRF52840/usart_hal.cpp
- hal/src/stm32f2xx/sleep_hal.cpp
- hal/src/stm32f2xx/usart_hal.c
- hal/src/template/usart_hal.cpp
- services/inc/ringbuffer.h
- user/libraries/Serial2/Serial2.h
- user/libraries/Serial3/Serial3.h
- user/libraries/Serial4/Serial4.h
- user/libraries/Serial5/Serial5.h
- user/tests/hal/uart/test_uart.cpp
- user/tests/wiring/no_fixture_long_running/network.cpp
- user/tests/wiring/serial_loopback2/loopback.cpp
- wiring/inc/spark_wiring_usartserial.h
- wiring/src/spark_wiring_usartserial.cpp
```c
void setup() {
Serial1.begin(115200);
Serial1.println("Application started.");
}
void loop() {
static system_tick_t now = millis();
if (millis() - now >= 1000) {
now = millis();
Serial1.println("Suspend UART");
hal_usart_sleep(HAL_USART_SERIAL1, true, nullptr);
delay(1000);
hal_usart_sleep(HAL_USART_SERIAL1, false, nullptr);
Serial1.println("UART state is restored");
Serial1.println("fjkgsajfgkajsgfkyusdgh");
}
}
```
---
> Implement sleep function for UART peripheral.

- hal/inc/exflash_hal.h
- hal/src/nRF52840/exflash_hal.c
Implement sleep function for external flash
Test the sleep API with the example application, make sure the sleep API won't affect the behavior of the file system.
```c
void setup(void) {
}
void loop() {
static int index = 0;
EEPROM.begin();
EEPROM.write(10, '0' + index++ % 10);
Log.info("Read: %c", EEPROM.read(10));
EEPROM.end();
hal_exflash_sleep(true, nullptr);
delay(1000);
hal_exflash_sleep(false, nullptr);
}
```
[CH55886]
---
> Implement sleep function for external flash

- system/src/system_power_manager.cpp
The buck converter might be disabled occasionally by the PMIC itself while the MCU is stopped by pulling down the EN pin, in which case charging cannot resume after MCU powering up.
Enable the buck converter by default on every startup.
https://community.particle.io/t/battery-charge-doesnt-work-if-starting-when-en-grounded/56082
---
> Enable the buck converter of PMIC by default.

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
Older cell radio firmware versions of Boron LTE support only `115200` baud rate where the newer versions support `460800`. When we resume with warm boot up, we need to check more than one baud rate to resume session correctly. 
Check for `460800` baud for session resumption and if we fail there, we will check muxer session resumption with `115200` baud. 
Make sure Boron LTE has muxer thread started in the previous run. This is can ensured by connecting to cloud. And then hit RESET button, this will make the modem resume with warm boot up. Check that we are able to resume session without issues. We can use a basic tinker app.
```c
void setup() {
}
void loop() {
}
```
[ch58180](https://app.clubhouse.io/particle/story/58180/boron-lte-bsom-lte-unreliable-warm-bootup)
---
> [Boron LTE] Muxer resumption to be checked at multiple baud rates as needed

- system/src/system_network_manager_api.cpp
The system loop on Gen 3 modifies the value of the `SPARK_WLAN_SLEEP` flag, which may prevent `Particle.connect()` from initiating a connection to the cloud when the app is running in threaded mode.
Do not call `network_off()` in the system loop if `SPARK_WLAN_SLEEP` is set but there's no active or ongoing network connection.
Note that this is more a workaround rather than a solution. Ideally, we need to refactor the system state management logic so that `SPARK_WLAN_SLEEP` (or its equivalent) only controls the "administrative" state of the networking subsystem, i.e. whether the user wants networking to be enabled, rather than both the administrative state and the actual one.
The easiest way to reproduce this issue is to introduce artificial delays in the system loop:
1. Apply [this …
> Workaround for Gen 3 devices not connecting to the cloud in non-automatic threaded mode

- hal/src/stm32f2xx/rtc_hal.c
As the title says.
Add an atomic section around RTC time/date fetch calls.
N/A
N/A
- [CH42243]
---
> [gen2] rtc: hal_rtc_get_time() is not thread-safe

- hal/src/nRF52840/sleep_hal.cpp
BLE cannot restart advertising when disconnected by peer device if sleep mode is enabled
1. Build and flash the below example application.
2. Connect to device using mobile App, e.g. LightBlue.
3. Disconnect from device using mobile App.
4. Device should restart advertising automatically.
```c
void setup() {
BLE.advertise();
}
void loop() {
delay(1000);
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).gpio(D0, RISING).ble());
}
```
---
> BLE cannot restart advertising when it is asleep.

- hal/network/ncp/cellular/cellular_hal.cpp
AT parser is accessed without a lock on Gen 3 cellular platforms.
Access it under a lock.
N/A
N/A
- [CH56485]
---
> [gen3] cellular: parser should not be accessed without a lock

- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
By applying the changes, device can resume from sleep faster if system power manager is enabled.
```c
void startup() {
SystemPowerConfiguration conf;
// conf.feature(SystemPowerFeature::DISABLE);
System.setPowerConfiguration(conf);
}
STARTUP( startup() );
void setup() {
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).duration(3s));
LOG(TRACE, "Now: %d", millis());
}
void loop() {
}
```
Log if system power manager is not enabled:
>0000004027 [app] application.cpp:17, setup(): TRACE: Now: 4027
Log if system power manager is enabled:
>0000003537 [app] application.cpp:17, setup(): TRACE: Now: 3537
---
> FuelGauge waking up enhancement

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
COPS=0 running when not de-registered.
Only check for COPS: 2 mode and switch to automatic registration when deregistered.
---
> Only run AT+COPS=0 if currently de-registered, to avoid PLMN reselection

- hal/network/lwip/ppp_client.cpp
- hal/network/lwip/ppp_ipcp.cpp
Sometimes the device may not the DNS servers from the remote in which case we don't progress further.
Start off by requesting public primary and secondary DNS servers (in this case, google's) which will help when we are unable to obtain DNS servers from remote (Separately, if the remote changes them, they are overwritten.)
```c
void setup() {
}
void loop() {
}
```
[ch59747](https://app.clubhouse.io/particle/story/59747/gen3-hard-code-dns-servers-if-unable-to-obtain-automatically)
---
> [Gen3] Workaround when unable to obtain DNS servers from remote

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
Every other release the Gen 2 Electron logging timestamp seems to wrap at boot, starting at very high numbers.
There was a variable used for detecting when the debugging level was changed, that was inadvertently set in a constructor and subtracted from all timestamps.  Doing things like this in constructors is unpredictable.  Solution is just to remove this variable in the timestamps.
- build system firmware
- run `particle flash --usb tinker-usb-debugging` on the DUT.
- observe no timestamps at very high values at boot
---
> [gen 2][electron] fixes timestamp wrapping at boot

- bootloader/src/main.c
- bootloader/src/stm32f2xx/core_hal.c
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
- platform/MCU/nRF52840/src/flash_mal.c
The bootloader prematurely clears OTA flags in the DCT before ensuring that the firmware modules have been successfully copied from the OTA section to the internal flash.
Clear OTA flags **after** the firmware modules have been updated.
1. Compile and flash the bootloader from this branch to a Gen 2 or Gen 3 device.
2. Flash a system part to the device OTA.
3. Wait until the device resets to apply the update and reset it via the reset button.
4. The device should reapply the update after the reset.
- [ch61683]
> Clear OTA slots after updating firmware modules

- hal/src/electron/modem/mdm_hal.cpp
On Gen2, detect IMSI switches when not registered, and read IMSI with which the radio is registered with the network immediately when registered. Update `_dev.imsi` which stores the IMSI in work.
- Read IMSI immediately when registered to check which IMSI the radio module registered with
- When not registered, check IMSI periodically as currently there is no special URC support on ublox based radios used in Gen2. Timer for IMSI query when not registered yet is set to 60 sec.
```c
void setup() {
}
void loop() {
}
```
https://github.com/particle-iot/device-os/pull/2174/
[ch60650](https://app.clubhouse.io/particle/story/60650/twilio-identify-imsi-switching-with-it-s-urc-and-trigger-an-at-cimi-to-query-new-imsi)
---
> [Gen2] Detect IMSI switches

- hal/src/nRF52840/tone_hal.cpp
- user/tests/wiring/no_fixture/tone.cpp
Closes #2170
As title says
- `wiring/no_fixture`
N/A
- [CH60815]
---
> [gen3] tone: fixes behavior with duration = 0

- wiring/inc/spark_wiring_cellular_printable.h
- wiring/src/spark_wiring_cellular.cpp
- wiring/src/spark_wiring_cellular_printable.cpp
These are old APIs that don't account well for RAT (Radio Access Technology).
`getStrengthValue()` and `getQualityValue()` with `getAccessTechnology()` should be preferred going forward.
https://docs.particle.io/reference/device-os/firmware/electron/#getstrengthvalue-
Mark these class member variables as deprecated.
Build the test app, it should provide deprecated warnings.
```c++
void loop() {
auto s = Cellular.RSSI();
Log.trace("%d", s.rssi);
Log.trace("%d", s.qual);
}
```
- [CH61037]
---
> [wiring] cellular: mark CellularSignal::rssi and CellularSignal::qual as deprecated

- test/unit_tests/wiring/print.cpp
- wiring/inc/spark_wiring_print.h
For printable types (e.g. `IPAddress`) that also happen to be implicitly convertible to an integral or unsigned integer type (e.g. `bool`) `Print` overload printing integers will take precedence over the overload taking `const Printable&`.
For example:
```c++
Serial.println(WiFi.localIP());
```
This will print only `0` or `1`, instead of an actual address.
As title says.
- unit tests
N/A
- Closes #2124 
---
> [wiring] print: exclude printable objects from an overload taking integral and uint convertible types

- hal/src/stm32f2xx/sleep_hal.cpp
- platform/MCU/shared/STM32/src/hw_ticks.c
As the title describes. But unlike the same wakeup source on Gen3, this wakeup source is only valid when it is used accompany with the STOP mode only.
```c
void setup() {
}
void loop() {
static system_tick_t now = millis();
if (millis() - now > 5000) {
now = millis();
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).analog(A0, 1500, AnalogInterruptMode::ABOVE));
} else {
LOG(INFO, "A0: %d", analogRead(A0));
delay(1000);
}
}
```
---
> Support woken up by analog pin on Gen2 platforms.

- hal/src/stm32f2xx/sleep_hal.cpp
- platform/MCU/shared/STM32/src/hw_ticks.c
As the title describes. But unlike the same wakeup source on Gen3, this wakeup source is only valid when it is used accompany with the STOP mode only.
```c
SYSTEM_MODE(AUTOMATIC);
void setup() {
}
void loop() {
delay(1000);
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).usart(Serial1));
LOG(TRACE, "Device wakes up.");
}
```
---
> Support woken up by USART on Gen2 platforms.

- hal/src/stm32f2xx/i2c_hal.c
See: https://github.com/particle-iot/device-os/issues/2093.
Notify user application on slave receiver worked for a cycle.
```c
#define I2C_SLAVE_ADDR  0x32
const auto slaveMsg = "This is slave.";
const auto masterMsg = "This is master.";
// Use Photon or Argon the slave device to test
#if PLATFORM_ID == PLATFORM_PHOTON || PLATFORM_ID == PLATFORM_ARGON
void receiveEvent(int howMany) {
while (1 < Wire.available()) {
char c = Wire.read();
Serial1.print(c);
}
char x = Wire.read();
Serial1.println(x);
}
void requestEvent() {
Wire.write(slaveMsg);
}
#endif
void setup() {
Log.info("Application started.");
#if PLATFORM_ID == PLATFORM_PHOTON || PLATFORM_ID == PLATFORM_ARGON
Wire.begin(I2C_SLAVE_ADDR); …
```
> Gen2 I2C: fix the issue #2093.

- hal/inc/hal_dynalib_core.h
Certain applications might require access to device serial and secret, currently it's only possible to do so with monolithic builds.
Expose the appropriate functions through dynalib.
Run test app on Gen 2 (only recently manufactured) and Gen 3 devices.
```c++
void setup() {
waitUntil(Serial.isConnected);
char tmp[64] = {};
int sz = hal_get_device_serial_number(tmp, sizeof(tmp), nullptr);
if (sz > 0) {
Log.info("Device serial: %s", tmp);
} else {
Log.error("Device serial: unknown (error=%d)", sz);
}
memset(tmp, 0, sizeof(tmp));
sz = hal_get_device_secret(tmp, sizeof(tmp), nullptr);
if (sz > 0) {
Log.info("Device secret: %s", tmp);
} else {
Log.error("Device secret: unknown (error=%d)", sz);
}
}
```
- [CH42002]
---
> [hal] core: expose functions to fetch serial/secret through dynalib

- system/src/system_network_cellular.h
> When the cellular modem is powering on for Electron it will potentially block for a long period of time during initialization and waiting for the modem to register onto the network. In bad cases, where network registration is not possible, this may block the system thread for up to 5 minutes.
> Cellular.off calls a cellular_cancel function to abort a connection attempt. This allows the system thread to return out of the network registration phase, become more responsive, and process the Cellular.off.
> However, if the modem is caught during its initial init/power-on sequence cellular_cancel will be skipped and the thread will block until either success or five-minutes till failure before powering down the modem. It appears the cellular_cancel is protected behind a check for active …
> [electron] network: abort poweron/initialization sequence

- wiring/inc/fast_pin.h
- wiring/inc/spark_wiring_logging.h
- wiring/inc/spark_wiring_print.h
- wiring/inc/spark_wiring_spi.h
- wiring/inc/spark_wiring_time.h
- wiring/src/spark_wiring_print.cpp
- wiring/src/spark_wiring_time.cpp
1. Stream-based objects providing `printf()` and `printlnf()` are not generating `-Wformat`
2. `time_t` printing with `%d` causes crashes sometimes and `%lld` format specifier is not supported in newlib-nano
1. Add printf attributes to appropriate functions
2. For now changing `Time::now()` and `Time::local()` to return `time32_t`, until we can introduce 64-bit printf/scanf support
See example app. It should generate warnings for all cases:
```
tests/app/blank/blank.cpp: In function 'void loop()':
tests/app/blank/blank.cpp:30:28: warning: format '%d' expects argument of type 'int', but argument 3 has type 'long unsigned int' [-Wformat=]
30 |     Serial.printlnf("test %d", test);
|                           ~^   ~~~~
|                            |   |
|                            int long …
```
> Add printf attributes to appropriate wiring functions, change Time::now() to use time32_t

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- system/src/system_network_compat.cpp
- system/src/system_network_internal.h
**Note: this PR is targeting to the fix/electron-recovery-non-responsive branch**
If the Electron is powered on but the modem is not initialized (by calling Cellular.on() or Particle.connect()) before entering sleep mode in the MANUAL mode, the modem persist on and it will consume additional ~15mA after device entering sleep mode.
1. We initialize the pins interacting with the modem.
2. Check the modem power state before entering sleep mode. If the modem is on, then perform the power-off sequence to turn off the modem.
```c
void setup() {
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::HIBERNATE));
}
void loop() {
}
```
---
> Gen2: fix the electron power leakage issue when device is asleep.

- hal/src/nRF52840/sleep_hal.cpp
- hal/src/stm32f2xx/sleep_hal.cpp
- platform/MCU/shared/STM32/src/hw_ticks.c
- system/src/system_sleep.cpp
**Note: This PR is targeting to the feature/gen2_usart_wakeup/ch60474 branch**
As the title says.
```c
Serial1LogHandler handler(115200, LOG_LEVEL_ALL);
/* This function is called once at start up ----------------------------------*/
void setup()
{
waitUntil(Particle.connected);
}
/* This function loops forever -----------------------------------------------*/
void loop()
{
// This will run in a loop
SystemSleepResult result = System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).network(Cellular));
if (result.error() != SYSTEM_ERROR_NONE) {
Log.error("Failed to enter sleep mode: %d", result.error());
}
delay(1s);
}
```
---
> Gen2: supports network wakeup source for Electron specifically.

- wiring/src/spark_wiring_ble.cpp
If the peripheral device has an array of service UUIDs on any of the individual types, then none are returned for that type.
Fixed by checking if returned size from locate is larger than a single service UUID (and a multiple of the expected size of UUID). If that's the case, iterate over the data to return all the available UUIDs.
Connect to a standard Heart Rate Monitor which provides several 16-bit service UUIDs, such as Heart Rate Service, Battery Service, Device Information Service. Prior to this PR, serviceUUID() returns 0 services. After, it returns 3.
> Fix issue with serviceUUID not returning UUID when there is an array

- system/src/system_power_manager.cpp
Interrupts for the fuel gauge device were not firing after attaching handlers, mainly on the tracker platform.  An MCP23S17 GPIO expander is used to receive the input from the fuel gauge and it's defaults were not set for the interrupt pins to accept inputs with pullup.
The PMIC and fuel gauge interrupt pins were explicitly configured for input source with pullups.
1. A battery with charge greater than 10% should be powering the device.
2. Flash the application
3. Unplug any cabled power sources (VIN or USB)
4. Allow the battery to discharge
5. Check if the handler print statement prints when the SOC (not normalized) value decreases and crosses 8%.
```c
void lowBatteryHandler(system_event_t event, int data) {
Serial1.println("Battery charge low handler");
}
void setup() { …
```
> Set pin mode for PMIC and fuel gauge interrupts

- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- system/src/system_sleep.cpp
- system/src/system_sleep_compat.cpp
By default, the Sleep 2.0 API leaves the protocol layer in whatever state it was before going to sleep and continues to use it after waking up from sleep without checking whether the session with the server is still valid.
Always disconnect from the cloud before going to sleep unless the network interface is used as a wake-up source. In the latter case, send a PING message to the server after waking up from sleep.
1. Verify that a sleepy device that doesn't use its network interface as a wake-up source successfully resumes its session when reconnecting to the cloud from a different address.
2. Using one of the network interfaces as a wake-up source, verify that the device sends a ping message to the cloud after waking up from sleep.
- [ch64208]
> Disconnect from the cloud before going to sleep

- hal/inc/adc_hal_compat.h
- hal/inc/i2c_hal_compat.h
- hal/inc/pwm_hal_compat.h
- hal/inc/rtc_hal_compat.h
- hal/inc/spi_hal_compat.h
- hal/inc/usart_hal_compat.h
If the deprecated APIs are invoked in c files, they might not be inlined by compiler actually, which would encounter "undefined reference xxxx" error.
Add `always_inline` attribute for the deprecated functions.
N/A
---
> HAL: add always_inline attribute for deprecated APIs

- system/src/system_task.cpp
When cloud _connecting_, the RGB LED doesn't go back to (blinking) green when de-registered from network, or when having DNS test failures
The cloud signaling procedure is correct, however, the LED doesn't reflect the same. The LED stays in blinking cyan, although the system state has backed off from "Cloud Connecting" state.
- Run any app that allows connecting to cloud, with serial logging enabled helpfully
- As soon as "Cloud connecting" is seen (device must have started blinking cyan), disconnect the module from network (probably by removing antenna). This needs to be done after "Cloud: Connecting" and before "Cloud socket connected" states
- The device struggles at that point to connect, and likely gets a `CEREG: x` deregistered URC
- The device should be blinking green (instead of …
> [Gen3] Fix LED behavior in case of network failure in Cloud Connecting state 

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
3rd party SIMs that are not detected with a UMNOPROF, do not default to the SW_DEFAULT profile (0), but get stuck in an init loop in Gen 3.
On Gen 2, it will default to SW_DEFAULT profile, but it will take 8 tries before it does taking up unnecessary time.
- [gen2] A repeated UMNOPROF SIM_SELECT allows MDMParser::init to continue early [ch64292]
- [gen3] Allow UMNOPROF SIM_SELECT to default back to SW_DEFAULT [ch64292]
- Run the example app
- Let the device connect to the cloud with a Particle SIM
- Triple tap the Mode button and wait for "Cold boot for a Factory Boot Experience!"
- Power off the device
- Switch the SIM for a 3rd party SIM
- Power on the device and it should connect quickly using the SW_DEFAULT profile.
NOTE: You will see a log that says the following if this happens:
> …
> [gen3] Allow UMNOPROF SIM_SELECT to default back to SW_DEFAULT

- wiring/inc/spark_wiring_cloud.h
Deprecation notice exists on Particle.publish without a scope, although there is no need for a scope now.
Remove the deprecation notice on Particle.publish without a scope, since there is only one event stream. 
Compile the following code, and you should **no longer** see warning of deprecation notice like this
```
warning: 'particle::Future<bool> CloudClass::publish(const char*)' is deprecated: Beginning with 0.8.0 release, Particle.publish() will require event scope to be specified explicitly. Define PARTICLE_USING_DEPRECATED_API macro to avoid this warning. [-Wdeprecated-declarations]
```
or
```
warning: 'bool CloudClass::subscribe(const char*, EventHandler)' is deprecated: Beginning with 0.8.0 release, Particle.subscribe() will require event scope to be specified explicitly. Define …
```
> [Wiring] Remove warning for publish scope deprecation

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- R410 - Gets stuck in loop where UMNOPROF=100 was not sticking, but erroring out instead, on older modem firmware
- R410 - Mostly an issue for Gen 3 with external SIM support on Boron/B SoM, switching between Kore AT&T vs. Twilio Super vs. 3rd Party SIMs could get stuck on the wrong UMNOPROF.
- Gen 3 Modem version detection was running too late for where it needed to be used, and could potentially return an invalid version number instead of 0.
- Allow modem to continue with SW_DEFAULT (UMNOPROF=0) when older modem firmware detected.
- Allow UMNOPROF to be switched accordingly between Kore AT&T vs. Twilio Super vs. 3rd Party SIMs.
- Run Gen 3 modem detection earlier, and use temporary variables to ensure if an error occurs, we don't return the error code as the firmware version.
- Make …
> [u-blox] older modem firmware does not have UMNOPROF=100 available [ch64670]

- hal/network/lwip/ppp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
SARA R4 PPP implementation is peculiar and for unknown reason after IPCP is already up, it sends up an _empty_ ConfReq. If we follow the standard to the T, we are supposed to bring IPCP down and restart negotiation. This increases warm bootup cloud connection times significantly.
The solution is to utilize a new PPP option introduced in https://github.com/particle-iot/lwip/pull/8 to slightly go off standard and ACK these Configure-Requests in an already opened state if the protocol handler does not disagree with the options provided in them and we already in an appropriate state (authed, and it's not LCP protocol that we need to renegotiate)
This PR also disables `ATH` command on R4-based devices as it does not function anyway. See https://github.com/particle-iot/device-os/pull/2188
1. …
> [u-blox][Boron / B SoM] PPP workaround for SARA R4 ConfReq behavior

- wiring/inc/spark_wiring_cellular_printable.h
Compile warnings for CellularSignal class public member variables `rssi` and `qual` report the incorrect member function to use.
```c
int rssi __attribute__((deprecated("Use getSignalStrengthValue() instead"))) = 0;
int qual __attribute__((deprecated("Use getSignalQualityValue() instead"))) = 0;
```
Existing member functions are instead `getStrengthValue()` and `getQualityValue()`.
Change the deprecated attribute warnings to the following.
```c
int rssi __attribute__((deprecated("Use getStrengthValue() instead"))) = 0;
int qual __attribute__((deprecated("Use getQualityValue() instead"))) = 0;
```
Implement the deprecated member variables and observe compile warnings.
```
main.cpp: In member function 'void loop()':
main.cpp:30:47: warning: 'CellularSignal::rssi' is deprecated: Use …
```
> Fix CellularSignal deprecation messages

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- user/tests/wiring/no_fixture_long_running/cellular.cpp
Electron was found to suffer from a modem reset while antenna was disconnected in low signal environment on battery only (and also with USB and battery). This leads to `C*REG=2` verbose mode + URCS being reset to `C*REG=0` non-verbose mode + no URCs, which causes the system firmware to not be notified that the modem has deregistered. NO_ACK publishes can continue to be sent into the breeze, and a user's firmware will not know `Particle.connected()` or `Cellular.ready()` are `false`.
#2215 addresses the root cause of the problem, but just in case for unexpected reasons the following solution offers a recovery method.
To periodically poll for `C*REG?` every 30 seconds look for changes to CREG verbosity. If there is a valid response, and we see `C*REG: 0,x`, URCs are disabled. Notify the …
> [gen2][electron] modem brownout or unexpected reset causes system to think it still is connected [ch64465]

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- system/src/system_network_cellular.h
- system/src/system_network_internal.h
There are two problems which have some common roots. If the power-on sequence on Electrons fails (and there are two stages in it: power on and SIM initialization, additional initialization), a specific set of actions needs to be taken by the _system networking layer_ to get the modem HAL into a proper state.
1. We are relying on a hack to get the system layer to restart poweron initialization when `MDMParser::init()` fails to initialize and requires a modem reset e.g. to set UMNO profile. This used to work somewhat until we've introduced reliable modem power off in one of the Sleep 2.0 PRs, which now causes the modem to be hard powercycled almost immediately after we've reset it through an AT command.
```
219.818 AT send      14 "AT+CFUN=15,0\r\n"
219.828 AT read OK    6 "\r\nOK\r\n" …
```
> [Electron] Workaround for modem HAL relying on system networking code to re-attempt initialization

- hal/src/nRF52840/sleep_hal.cpp
- hal/src/stm32f2xx/sleep_hal.cpp
A wakeup source's interrupt priority is increased and never restored if it is duplicated in the wakeup source list or shares the same IRQ with other wakeup sources. Especially on Gen3, for critical SoftDevice region, a user application interrupt that would result in an error in SoftDevice.
Bump a wakeup source's interrupt priority only if it hasn't been bumped previously.
N/A
> [hal] sleep: restore waleup sources' interrupt priority appropriately

- system/src/system_network_diagnostics.cpp
- system/src/system_network_diagnostics.h
- system/src/system_network_internal.cpp
- system/src/system_network_internal.h
- system/src/system_network_manager.cpp
- system/src/system_network_manager.h
- system/src/system_network_manager_api.cpp
Network diagnostics/vitals are only enabled on Gen 2 platforms.
Fix that and enable them for Gen 3 as well.
Request vitals in the console. They should contain network diagnostics. Make the device disconnect e.g. by unplugging antenna, let it connect again, request vitals.
N/A
- [CH66610]
---
> [system] network diagnostics for Gen 3 platforms

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- services/inc/services2_dynalib.h
- user/tests/wiring/no_fixture_long_running/cellular.cpp
The Electron with SARA-G350 doesn't support powering off using the PWR_ON pin. The low level pulse of the PWR_ON pin being performed in current powerOff() will actually power on the modem.
Use `AT+CPWROFF` completely to power off the modem.
N/A
---
> [hal] electron: use AT+CPWROFF to turn off the modem completely

- system/inc/system_sleep_configuration.h
```c
void setup() {
}
void loop() {
delay(300);
Vector<std::pair<pin_t, InterruptMode>> pins;
pins.append(std::make_pair(D0, FALLING));
pins.append(std::make_pair(D1, RISING));
Vector<pin_t> altPins;
altPins.append(D2);
altPins.append(D3);
uint8_t pinArray[2] = {D4, D5};
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::ULTRA_LOW_POWER)
.gpios(pins)
.gpios(altPins, FALLING)
.gpios(pinArray, sizeof(pinArray), RISING));
}
```
---
> [wiring] system: configure multiple pins as wakeup source at a time.

- system/inc/system_sleep_configuration.h
- user/tests/wiring/api/system.cpp
`uint8_t*` in `SystemSleepConfiguration& SystemSleepConfiguration::gpios(const uint8_t* pins, size_t count, InterruptMode mode)` should be replaced with `pin_t*`.
> [wiring] system: minor fix for sleep configuration method

- communication/src/dtls_message_channel.cpp
- crypto/inc/mbedtls_config_default.h
- crypto/inc/mbedtls_config_photon.h
- hal/src/nRF52840/mbedtls/ecp_alt_cc310.c
- hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
- hal/src/photon/crypto_compat.cpp
This PR updates mbedTLS from 2.16.2 to 2.22.0. The submodule has been updated to point to the tip of this branch: https://github.com/particle-iot/mbedtls/tree/particle-2.22.0.
For reference, below are diffs of our patchset applied to the upstream mbedTLS 2.16.2 and 2.22.0 releases respectively:
- https://github.com/ARMmbed/mbedtls/compare/mbedtls-2.16.2...particle-iot:particle
- https://github.com/ARMmbed/mbedtls/compare/mbedtls-2.22.0...particle-iot:particle-2.22.0
- Devices running this branch should connect to the cloud normally.
- UDP devices should be able to resume their sessions.
- Photon should be able to connect to a WPA Enterprise network.
- Device setup via BLE should work correctly.
- [ch55085]
> Update mbedTLS to 2.22.0

- hal/src/nRF52840/sleep_hal.cpp
- hal/src/tracker/mcp23s17.cpp
- hal/src/tracker/mcp23s17.h
- system/inc/system_power.h
- system/inc/system_sleep_configuration.h
- system/src/system_power.cpp
- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- system/src/system_sleep.cpp
- system/src/system_sleep_compat.cpp
- user/tests/app/tracker_wakeup/esp32_soch.h
- user/tests/app/tracker_wakeup/port.cpp
- user/tests/app/tracker_wakeup/port.h
- user/tests/app/tracker_wakeup/sdspi_host.cpp
- user/tests/app/tracker_wakeup/sdspi_host.h
- user/tests/app/tracker_wakeup/tracker_wakeup.cpp
- user/tests/wiring/sleep20/sleep20.cpp
Currently if we want to utilize the Wi-Fi/GNSS/FuelGauge to wake up device from sleep mode, we need to attach an interrupt to the INT pin of these peripherals followed by specifying the `IOE_INT`, which is the INT pin of the IO expander, as the wakeup source. For instance:
```
void handler() {
// Do nothing
}
void sleepNow() {
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).gpio(IOE_INT, FALLING));
}
void setup() {
attachInterrupt(GPS_INT, handler, FALLING);
}
```
This PR will simplify the code to configure the INT pins of these peripherals as a wakeup source directly:
```
void sleepNow() {
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).gpio(GPS_INT, FALLING));
}
```
Test application added within this PR.
N/A
---
> Tracker: an easy way to configure Wi-Fi/GNSS/FuelGauge as a wakeup source

- hal/src/nRF52840/ble_hal.cpp
- hal/src/nRF52840/ble_hal_impl.h
- user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
BLE may hang the thread that calls `BLE.scan()` due to unexpected scanning failure. Since the `BLE.scan()` is a blocking API waiting until a semaphore is given on scanning timeout event, in some condition the scanning procedure never timeout or a incorrect event is delivered from SoftDevice on scanning failure, in which case the semaphore cannot be taken any more.
Introduce a timer to guard the scanning procedure. For example, if the scanning timeout is set to 5s and it starts scanning, the timer will expire after 6s to stop scanning actively. Normally BLE scanning can timeout by SoftDevice and the timer will be stopped by then.
#1932 
---
> Fixes the issue that BLE.scan() might hang the device.

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
The device, at times, do not register and instead stay in "searching" mode. In this case, it's unclear to tell if the device is even receiving a cellular signal which is useful for debugging purposes.
Query cellular signal as a part of periodically checking the status of registration. 
- Not checking for an `OK` for the signal queries as sometimes these queries can return `ERROR` while the module is not having cellular coverage 
- Watch logs with antenna removed
- [ch64153](https://app.clubhouse.io/particle/story/64153/query-signal-strength-as-a-part-of-registration-intervention-process)
> Query cellular signal while module tries to register

- hal/src/nRF52840/ble_hal.cpp
- user/tests/app/ble/scanner/application.cpp
- user/tests/app/ble/uart_central/application.cpp
- user/tests/wiring/api/ble.cpp
- user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
- user/tests/wiring/no_fixture_ble/ble.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
**This PR is targeting to feature/ip_ble_address**
1. `BleAddress` doesn't support validity check and invalidating object.
2. Scanning callback doesn't pass scanned result in reference manner.
3. `BleScanResult` should not access members directly
https://github.com/particle-iot/device-os/issues/2005
> Wiring BLE APIs consistency improvements

- user/tests/wiring/api/ble.cpp
- user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/application.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
**This PR is targeting to enhancement/ble_api_consistency/ch64120**
In the past, user application needs to implement a logic to filter the target devices to be connected. By introducing the scanning filter in Device OS, user can filter a bunch of desired target devices in the following manner for example:
```
void scan() {
BleScanFilter filter;
filter.deviceName("MyDevice").minRssi(-50).serviceUUID(0x1234);
auto scanResult = BLE.scanWithFilter(filter);
}
```
The `scanResult` vector only contains the scanned devices those comply with all of the following conditions:
- The scanned device should be broadcasting device name `"MyDevice"`.
- The scanned device should be broadcasting service UUID `0x1234`.
- The RSSI of the scanned device should be large than -50 dBm.
- …
> [wiring] BLE: implement BLE scanning filter.

- user/tests/wiring/api/ble.cpp
- user/tests/wiring/no_fixture_ble/ble.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
**This PR is targeting to the feature/ble_scan_filter/ch37224 branch.**
The existing wiring BLE APIs only support c style callback.
Using function wrapper to support c++ style callback.
1. Central side:
```c
SerialLogHandler log(LOG_LEVEL_INFO);
BleCharacteristic peerTxChar;
void onBleScanCallbackWrapper(const BleScanResult& result) {
Log.info("I'm a normal function.");
}
void onBleScanCallbackWithName(const char* name, const BleScanResult& result, void* context) {
Log.info("I'm a normal function with context: %s", name);
}
class Test {
public:
void scanHandler(const BleScanResult& result) {
Log.info("Test::scanHandler()");
}
void dataHandler(const uint8_t* buf, size_t len) {
Log.info("Test::dataHandler(), Data received:");
for (uint8_t i = 0; i …
```
> BLE: Scanned/Connected/Disconnected/Data Received callback in C++ style

- user/tests/wiring/api/ble.cpp
- user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
- user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
**This PR is targeting to the feature/ble_cpp_callback/ch65803 branch**
Allows for hierarchical discovery of characteristics inside services.
Adds a discoverAllCharacteristics function to BleServiceImpl class. 
peer->discoverAllServices();
peer.getServiceByUUID(service, <SERVICE TO LOOK FOR>);
service.discoverAllCharacteristics();
---
> Add characteristic discovery to BleService

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- system/src/system_sleep.cpp
- system/src/system_sleep_compat.cpp
- user/tests/wiring/sleep20/sleep20.cpp
Set a flag if cellular/wifi connection need to be restored after waking up and let the background system task to handle the connection establishment, instead of calling the network connect api to before exiting the sleep function.
`user/tests/wiring/sleep20`
N/A
---
> Gen2: platforms calling sleep20 API to enter stop/ulp mode may block user application.

- hal/src/electron/modem/mdm_hal.cpp
A regression got introduced in https://github.com/particle-iot/device-os/pull/2219 and C*REG URCs are not correctly being parsed.
Don't have a good way to test other than using the app below and watching the logs. There shouldn't be any significant delays (over 10 seconds) after receiving registered URC before connection process continues like in the log below:
```
185.293 AT read  +   14 "\r\n+CIEV: 2,3\r\n"
187.105 AT read  +   31 "\r\n+CREG: 5,\"XXXX\",\"XXXXXXXX\",6\r\n"
187.109 AT read  +   37 "\r\n+CGREG: 5,\"XXXX\",\"XXXXXXXX\",6,\"00\"\r\n"
187.113 AT read  +   14 "\r\n+CIEV: 3,1\r\n"
187.117 AT read  +   14 "\r\n+CIEV: 7,1\r\n"
187.121 AT read  +   14 "\r\n+CIEV: 9,2\r\n"
CIEV matched: 9,2
// Note over 10s gap here
198.556 AT send       8 "AT+CSQ\r\n"
199.622 AT read  +   14 …
```
> [electron] modem: fix C*REG URC parsing

- user/tests/wiring/no_fixture/fastpin.cpp
- wiring/inc/fast_pin.h
<details>
<summary><i>Always inline fastPinGetPinmap in order to speed pin set</i></summary>
Also add test to catch unintentional slowing of pin set in the future.  
</details>
For some users, calling `pinSetFast` or `pinResetFast` was noticeably slower on 2.0.0-rc.4 or later than on earlier releases. 
The 2.0.0 development line worked around an issue with initialization order by changing the way the HAL pin map was initialized and subsequently accessed.  This introduced some overhead in each call to fastPinGetPinmap.  We reduce that overhead here by always inlining` fastPinGetPinmap()`.
- Closes #2244 
Added a test to `/user/tests/wiring/no_fixture/fastpin.cpp` to set a limit to the allowable ticks.  Tested on Electron 2g.
> Always inline fastPinGetPinmap to speed pin sets

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- hal/src/nRF52840/sleep_hal.cpp
- hal/src/stm32f2xx/sleep_hal.cpp
- user/tests/wiring/sleep20/sleep20.cpp
`System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::HIBERNATE).network(SystemSleepNetworkFlag::INACTIVE_STANDBY))` doesn't make the device enter sleep.
Removes the restriction in sleep HAL to allow network stay standby in hibernate mode. 
```c
#include "system_threading.h"
SerialLogHandler logHandler(Serial, LOG_LEVEL_TRACE);
void setup()
{
waitFor(Serial.isConnected, 10000);
Log.info("before sleep");
SystemSleepConfiguration config;
config.network(Cellular, SystemSleepNetworkFlag::INACTIVE_STANDBY);
config.mode(SystemSleepMode::HIBERNATE);
config.gpio(D0, RISING);
System.sleep(config);
}
void loop()
{
}
```
---
> [hal] sleep: allows the network to stay standby in HIBERNATE mode.

- hal/src/stm32f2xx/usart_hal.c
- user/tests/wiring/no_fixture/uart.cpp
```c++
Wire.begin();
Serial1.begin(115200);
Serial1.end();
```
The following code will leave I2C peripheral in a non-functioning state on Gen 2 platforms, because `D0` Alternate-Function will be reset to default value unconditionally by a call to `Serial1.end()`.
- `wiring/no_fixture` `UART*` tests
N/A
- [CH70258]
- [CH70277]
---
> [gen2] usart: fix D0 AF unconditionally being changed in hal_usart_end()

- hal/inc/ble_hal.h
- hal/inc/ble_hal_defines.h
- hal/inc/hal_dynalib_ble.h
- hal/src/nRF52840/ble_hal.cpp
- hal/src/nRF52840/ble_hal_impl.h
- user/tests/wiring/api/ble.cpp
- user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
- user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
- user/tests/wiring/ble_central_peripheral
N/A
---
> BLE: supports legacy pairing.

- hal/inc/power_hal.h
- system/inc/system_dynalib.h
- system/inc/system_power.h
- system/src/system_power.cpp
- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- user/tests/wiring/power_management/power.cpp
- wiring/inc/spark_wiring_power.h
- wiring/inc/spark_wiring_system.h
- wiring/inc/spark_wiring_system_power.h
- wiring/src/spark_wiring_power.cpp
The power manager may override user requests to disable battery charging.  While the user may set the charge state on the PMIC, the power manager may enable charge state silently.
Add a flag for non-volatile power management configuration that ensures that the power manager honor user requests to disable charging.  Additionally create get methods for the configuration so that the user can query the current configuration.
Which unit/integration/application tests are applicable to this code change? (At minimum a test of some kind should be provided)
```c
SerialLogHandler logHandler;
void setup() {
// Apply a custom power configuration
SystemPowerConfiguration conf;
conf.feature(SystemPowerFeature::DISABLE_CHARGING);
int res = System.setPowerConfiguration(conf); …
```
> Allow power manager to disable charging

- hal/network/lwip/basenetif.h
- hal/network/lwip/cellular/pppncpnetif.cpp
- hal/network/lwip/cellular/pppncpnetif.h
- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/lwip/esp32/esp32ncpnetif.h
- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
This PR improves the network connection and modem power management for Gen3 platforms. Whenever a network API is called, the final network state intends to be consistent with the final call. And it gracefully transits network state according to the sequence that network APIs are called.
```c
SerialLogHandler log(115200, LOG_LEVEL_ALL);
void setup() {
while (!Serial.isConnected());
Log.info("Type 'o', 'f', 'c', 'd', 'p' to test.");
Log.info("'o' -- WiFi/Cellular.on()");
Log.info("'f' -- WiFi/Cellular.off()");
Log.info("'c' -- WiFi/Cellular.connect()");
Log.info("'d' -- WiFi/Cellular.disconnect()");
Log.info("'p' -- Particle.connect()");
Log.info("'q' -- Particle.disconnect()");
}
void loop() {
if (Serial.available()) {
char …
```
> Gen3: Network management improvement

- hal/inc/cellular_hal.h
- hal/network/ncp/cellular/cellular_hal.cpp
- hal/shared/cellular_sig_perc_mapping.cpp
- hal/shared/cellular_sig_perc_mapping.h
- hal/src/electron/cellular_internal.cpp
- hal/src/electron/cellular_internal.h
- modules/electron/system-part1/src/cellular_hal.cpp
- test/unit_tests/cellular/CMakeLists.txt
- test/unit_tests/cellular/cellular.cpp
- user/tests/unit/makefile
Current signal values to percentage conversion is incorrect depending on the values.
Changing the signal percentages reported to the cloud such that they render an accurate representation of the cellular signal.
- [ch66635](https://app.clubhouse.io/particle/story/66635/change-the-how-device-os-signal-quality-percentages-are-calculated-in-device-os)
---
> Signal values to percentage mapping

- hal/network/lwip/wiznet/wiznetif.cpp
- hal/network/lwip/wiznet/wiznetif.h
- system/src/system_sleep.cpp
The device may timeout waiting the ethernet interface to be off() when sleep is requested and the ethernet interface is present.
Report the Wiznetif power state to system network manager.
Note that the W5500 module is actually on still even if we've called the corresponding API to turn it off. Because there is no hardware pins to control the power to the W5500 module, nor we implement the low power mode for W5500.
```c
STARTUP(System.enableFeature(FEATURE_ETHERNET_DETECTION));
SerialLogHandler l(LOG_LEVEL_ALL);
void setup() {
while (!Serial.isConnected());
Log.info("Application started.");
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::ULTRA_LOW_POWER).duration(5s));
}
void loop() {
}
```
---
> Wiznetif: report module power state.

- bootloader/src/main.c
- hal/network/ncp/wifi/platform_ncp_update.cpp
- hal/src/gcc/platform_config.h
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/littlefs/filesystem.cpp
- hal/src/nRF52840/rgbled_hal.c
- hal/src/newhal/platform_config.h
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- hal/src/stm32f2xx/rgbled_hal.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/platform_config.h
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/hw_config.c
- platform/MCU/nRF52840/inc/platform_config.h
- platform/MCU/nRF52840/src/hw_config.c
- services/inc/rgbled.h
- services/src/panic.c
- services/src/rgbled.c
- system/src/firmware_update.cpp
- system/src/system_sleep.cpp
- system/src/system_sleep_compat.cpp
- user/tests/unit/led_service.cpp
- user/tests/unit/rgbled.cpp
- wiring/src/spark_wiring_rgb.cpp
- wiring/src/spark_wiring_wifitester.cpp
<details>
<summary><i>Rename simple numbered LED defines to have PARTICLE prefix to avoid possible collision with user applications.</i></summary>
</details>
What Bug or Missing Feature does this PR address? (A short summary is preferred over links)
Simple define names such as `LED2` have caused some users problems due to namespace collisions.  
By adding a `PARTICLE_` prefix to these defines, we avoid possible namespace collisions. 
At the moment tests under `/user/tests` are using `LED_RGB` which is derived from these defines. 
Replace any reference to eg `LED2` with `PARTICLE_LED2` in your applications.  
---
> Use unique Particle prefix for LED defines

- user/tests/wiring/api/system.cpp
- user/tests/wiring/power_management/power.cpp
Power management tests were incomplete for a new battery charge disable feature.
How does this PR address the problem stated above? (Describing the solutions implemented in code will facilitate a smooth discussion, review and testing of this PR)
The `wiring/api` and `wiring/power_management` tests were updated for compile and on-device tests.  Use make commands to compile and program
``` bash
$ make PLATFORM=<your platform> TEST=wiring/api clean all
$ make PLATFORM=<your platform> TEST=wiring/power_management all program-dfu
```
Results will show a clean build for the `wiring/api` compile and something similar to the following for `wiring/power_management`
```
Test POWER_16_PrepareDisableChargingFeatureFlag skipped.
Test POWER_17_DisableChargingFeatureFlag passed.
Device will pause about …
```
> Update disable charging feature in power management wiring and API tests

- hal/inc/cellular_hal_constants.h
- hal/network/ncp/cellular/cellular_hal.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/src/b5som/ota_flash_hal.cpp
- hal/src/boron/ota_flash_hal.cpp
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- hal/src/electron/ota_flash_hal.cpp
- hal/src/tracker/ota_flash_hal.cpp
- system/src/system_setup.cpp
Send modem firmware version string to cloud.
Report this as a part of System describe message.
```c
void setup() {
}
void loop() {
}
```
Modem firmware version is reported to cloud, and is seen on the device-service logs as follows:
1. Boron LTE
```
"{\"p\":13,\"imei\":\"352753090224310\",\"iccid\":\"89010303300014910245\",\"radiofw\":\"L0.0.00.00.05.08,A.02.04\",\"m\":
```
2. Electron LTE
```
"{\"p\":10,\"imei\":\"352753091571107\",\"iccid\":\"89014103271229647548\",\"radiofw\":\"L0.0.00.00.05.08,A.02.04\",\"m\":
```
3. Tracker EVB
```
"{\"p\":26,\"imei\":\"860112043255142\",\"iccid\":\"89014103271549980686\",\"radiofw\":\"BG96MAR04A04M1G\",\"m\"......
```
4. Boron 2G/3G
```
"{\"p\":13,\"imei\":\"357520078500895\",\"iccid\":\"89014103271549980678\",\"radiofw\":\"23.60,A01.01\",\"m\":
``` …
> Send modem firmware version to cloud

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
Boron LTEs get stuck in initialization with third party SIMs, due to AT+CIMI (IMSI lookup) error in certain cases.
In an attempt to set credentials during init, for any SIMs whose ICCIDs are not recognized, their IMSI is checked. Checking IMSI after setting UMNOPROF (mobile network operator profile) gives a `CME ERROR: SIM failure` or `CME ERROR: SIM wrong` if not added a delay. Currently when this happens, we already have a retry logic that should have worked but the impl exits with an error instead of retrying. 
1. Added delay so that we don't expect these failures
2. Fixed retry logic
```
Callbox SIM
=========
0000060048 [ncp.at] TRACE: > AT+CIMI
0000060050 [ncp.at] TRACE: < +CME ERROR: SIM wrong
0000060152 [ncp.at] TRACE: > AT+CIMI
0000060157 [ncp.at] TRACE: < 001010123456789 …
```
> [Boron LTE] Fix external SIM getting stuck in init

- wiring/src/spark_wiring_ble.cpp
`getCharacteristicByDescription()` return `true` even if there is no characteristic is matched.
return `false` if there is no characteristic matches the given description.
N/A
N/A
> [wiring] BLE: return false if expected characteristic is not found.

- hal/src/nRF52840/usart_hal.cpp
- test/unit_tests/CMakeLists.txt
Originally reported in https://community.particle.io/t/serial1-rx-randomly-dies-on-boron-2-0-1-red-sos-crash-with-second-serial1-begin/58888/10
There is a problem in how we commit received bytes while RX DMA transfer is still ongoing (https://github.com/particle-iot/device-os/blob/develop/hal/src/nRF52840/usart_hal.cpp#L279), causing ring buffer to get into an invalid state and subsequent RX DMA transfers to be configured incorrectly with very large sizes, which causes out of bounds writes.
1. The timer that counts the received bytes with PPI can count more than what's actually been put into the receive buffer by DMA, so we'll simply limit by that. This is the main fix. https://github.com/particle-iot/device-os/compare/fix/ch70753-gen3-uart-out-of-bounds?expand=1#diff-7b4e007cfccb7b35c77f6 …
> [Gen 3] Fixes UART RX DMA transfer size issues

- hal/network/ncp/at_parser/at_parser.h
- hal/network/ncp/at_parser/at_parser_impl.cpp
- hal/network/ncp/at_parser/at_parser_impl.h
- hal/network/ncp_client/esp32/esp32_ncp_client.cpp
- hal/network/ncp_client/esp32/esp32_ncp_client.h
- hal/network/ncp_client/quectel/quectel_ncp_client.h
- hal/network/ncp_client/sara/sara_ncp_client.h
- hal/src/nRF52840/event_group_stream.h
- hal/src/nRF52840/gsm0710muxer/channel_stream.h
- hal/src/nRF52840/serial_stream.h
- hal/src/tracker/esp32_sdio_stream.h
Now that we have ESP32 support on Tracker, it's impossible to differentiate between NCP client / gsm0710 muxer logs that come from the cellular modem and ESP32.
Add instance-local custom log categories support for AT parser and gsm0710muxer.
This PR also fixes a bug in `ChannelStream` in `waitEvent()` timeout handling and makes sure that we have a single implementation of the gsm0710muxer (by having a common Stream base class that support `eventGroup()` method).
Run the test app, watch logs. It should be easy to differentiate NCP/muxer logs that come from the modem and from ESP32.
```c++
void setup() {
waitUntil(Serial.isConnected);
Particle.connect();
}
void loop() {
WiFiAccessPoint results[5];
WiFi.scan(results, …
```
> AT parser and gsm0710 muxer custom log category support

- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
We recently increased the AT_TIMEOUT from 1 to 3 seconds, which is causing a few extra seconds of power on time.
- Set AT_TIMEOUT for _powerOn() function back to 1s, and use 3s for everywhere else when modem is on.
- Also increase number of tries from 10 to 25 to keep the power on delay to roughly 30 seconds before attempting to hard reset the modem.
- wiring/no_fixture
- can also simulate modem not responsive by changing baudrate in mdm_hal.cpp to something other than 115200
- monitor cold and hard boot times
---
> [gen2] speed up cellular modem powerOn time

- hal/network/lwip/cellular/pppncpnetif.cpp
- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/ncp/wifi/platform_ncp_update.cpp
- hal/network/ncp_client/esp32/esp32_ncp_client.cpp
- services/inc/system_cache.h
- services/src/system_cache.cpp
- system/src/control/cellular.cpp
- system/src/control/config.cpp
- system/src/control/wifi_new.cpp
1. We've introduced a regression in https://github.com/particle-iot/device-os/pull/2217 and broke warm boot
2. During handshake with the cloud we need to send ESP32 NCP firmware version as it is one of the module, so it's present in the system describe. On Tracker during the cloud connection establishment it's not guaranteed that ESP32 is on, so we have to turn it on in order to query for its version, which prolongs the handshake process. What complicates things even more is that since https://github.com/particle-iot/device-os/pull/2217 we'll also watch the current NCP state closely and power off immediately, so several sequential calls to query ESP32 NCP firmware version may have to power on the ESP32 and initialize it multiple times
1. Keep the NCP state as-is unless some command (on, …
> [Gen 3] Fix warm boot; [Tracker] Cache ESP32 firmware version

- communication/inc/protocol_defs.h
- communication/src/firmware_update.cpp
- communication/src/firmware_update.h
- communication/src/protocol_defs.cpp
- services/inc/system_error.h
- system/src/system_update.cpp
- test/unit_tests/communication/firmware_update.cpp
Before https://github.com/particle-iot/device-os/pull/2199, a failure to apply an OTA update was causing the device to be reset. This PR restores that behavior on Gen 2 platforms and updates the v3 protocol implementation on Gen 3 platforms so that it breaks the comms loop on OTA errors causing a reconnection to the cloud.
Reproducing the issue caused by the new logic introduced in https://github.com/particle-iot/device-os/pull/2199 with an unmodified firmware is tricky. The easiest way would be to modify `HAL_FLASH_End()` so that it fails early. With that change in place:
1. Flash a user app that requires a newer system firmware to a Gen 2 or Gen 3 device. The device should reconnect to the cloud in safe mode.
2. When the device will receive the new system firmware and fail to apply it, …
> Disconnect from the server on OTA update errors

- hal/network/ncp/cellular/network_config_db.cpp
- hal/src/electron/cellular_hal_utilities.cpp
- test/unit_tests/cellular/cellular.cpp
- test/unit_tests/services/simple_file_storage.cpp
Story details: https://app.clubhouse.io/particle/story/70820
As far as I know I have no way to test this currently, as I don't have an affected SIM (Kore/AT&T SIM with a prefix of 89010)
> Add new Kore SIMs to static APN map

- hal/network/lwip/wiznet/wiznetif.cpp
- hal/shared/spi_lock.h
The SPI interface default chip select state is set to `SPI_DEFAULT_SS` which may override user defined pin map controls over GPIO pins.  Normally the user will assign and manage their own chip select and not use the native SS pin from the MCU peripheral.
Replace references to the default MCU peripheral chip select pin, SS, with an invalid pin map entry, `PIN_INVALID` so that the user can specify GPIO.
N/A
N/A
N/A
---
- [x ] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x ] Problem and Solution clearly stated
> Fix default assignment for SPI chip select

- hal/network/ncp_client/esp32/esp32_ncp_client.cpp
Tracker takes several minutes to enter sleep mode. The root cause is that ESP32 NCP power state is not reflecting the actual state on boot (which should be off).
Fix that.
N/A
N/A
- [CH72616]
---
> Make sure that ESP32 NCP power state is correctly initialized on boot

- hal/src/nRF52840/mbedtls/ecp_curves_enable.c
nRF52840 CC310 hardware crypto support for each particular elliptic curve takes about 700 bytes in closed source Nordic CC310 support library (see `ssi_ecpki_domain_*` symbols in the map file).
Stub out ECC curves not supported by mbedTLS!
```
481540	   2588	  60404	 544532	  84f14	../../../build/target/system-part1/platform-12-m/system-part1.elf
511904	   2660	  61552	 576116	  8ca74	../../../build/target/system-part1/platform-13-m/system-part1.elf
512224	   2692	  61560	 576476	  8cbdc	../../../build/target/system-part1/platform-23-m/system-part1.elf
508688	   2692	  61560	 572940	  8be0c …
```
> [gen3] disable some of the elliptic-curves not in use to save flash space

- hal/src/electron/modem/mdm_hal.cpp
On u-blox modems, the COPS timeout of 3 minutes has been found to not be respected by the modem, sometimes taking up to 4 minutes or slightly more.
Increase the COPS timeout to 5 minutes.
---
> [u-blox][gen2] COPS_TIMEOUT increased to 5 minutes

- hal/shared/cellular_sig_perc_mapping.cpp
- test/unit_tests/cellular/cellular.cpp
Current mapping is not reflective of the data and performance obtained from the field units.
Present this mapping correctly close to the performance observed in the field devices.
- [ch66647](https://app.clubhouse.io/particle/story/66477/device-details-page-shows-poor-rf-warnings-when-it-s-actually-fine-and-the-platform-behaves-as-expected)
- [ch66635](https://app.clubhouse.io/particle/story/66635/change-the-how-device-os-signal-quality-percentages-are-calculated-in-device-os)
- [PR2236](https://github.com/particle-iot/device-os/pull/2236)
---
> Modify mapping for LTE signal values to percentages

- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- wiring/inc/spark_wiring_power.h
- wiring/inc/spark_wiring_system_power.h
- wiring/src/spark_wiring_power.cpp
The battery state is not reported consistently.
1. When charging is enabled (through the `HAL_POWER_CHARGE_STATE_DISABLE` flag), we debounce the CHARGING/CHARGED/CHARGING/CHARGED events.
2. When charging is disabled, we use the `VCELL` of the fuel gauge to detect the battery state.
1. Flashing the attached application to the platforms with PMIC and fuel gauge installed
2. Attach/detach batteries with different capacity and observe the reported battery state.
3. Plug/unplug the power source and observe the reported battery state, as well as the reported power source
```c
Serial1LogHandler logHandler(115200, LOG_LEVEL_ALL);
static system_tick_t loopTick = 0;
constexpr char const* batteryStates[] = {
"unknown", "not …
```
> System power management inprovements

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/quectel/quectel_ncp_client.h
- hal/src/nRF52840/serial_stream.cpp
- hal/src/nRF52840/serial_stream.h
Restoring network connection from warm bootup on Trackers does not work reliably and fails sometimes.
Two problems have been identified:
1. `AT+CGEREP` returning ERROR response
2. Failure to exit data mode in the data channel
1. Ignore `AT+CGEREP` errors, there are no negative consequences to that, this command is simply for informative purposes
2. Modify the sequence to exit data mode to perform several attempts
Perform OTA updates of Cat M1 Trackers while watching Serial1 logs. The devices should not be resetting the modem on boot and should be successfully restoring the connection.
N/A
N/A
---
> [network] quectel: ignore CGEREP errors, send data mode break sequence multiple times

- hal/inc/ble_hal.h
- hal/src/nRF52840/ble_hal.cpp
- user/tests/wiring/api/ble.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
This builds on the community-submitted PR(https://github.com/particle-iot/device-os/pull/2287) to add BLE5 long range and does the following:
HAL:
- Add check when setting Advertising parameters, that the PHY is properly selected (for advertising, only one PHY can be chosen).
- When setting the extended scan parameter, check if Coded PHY is selected either by itself or bitwise with another PHY. In either of those cases, extended must be set to 1.
Wiring:
- Add setScanPhy() API
- Add setAdvertisingPhy() API
Integration/Application tests run on 2 Tracker Ones, which can communicate with each other and switch PHYs
Usage example:
Scanner:
BLE.setScanPhy(BlePhy::CODED | BlePhy::MBPS1);
Advertiser:
BLE.setAdvertisingPhy(BlePhy::CODED);
> Ble5 long range wiring API

- .buildpackrc
- .workbench/manifest.json
- bootloader/src/nRF52840/nrf_it.c
- build/arm-tools.mk
- build/common-tools.mk
- hal/src/nRF52840/core_hal.c
- hal/src/nRF52840/posix/syscalls_posix.cpp
- hal/src/nRF52840/spi_hal.cpp
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- modules/photon/system-part1/makefile
- modules/photon/system-part2/makefile
- newlib_nano/src/mallocr.c
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/hw_config.c
- scripts/fetch-buildpack
We're out of flash space in system-part2 on Photon.
Enable LTO when building Photon system part modules. We have previously [enabled](https://github.com/particle-iot/device-os/pull/2235) it for Electron, but doing the same for Photon causes various compile- and runtime errors with GCC 9.2.1. Building with GCC 10.2.1 seems to resolve those issues.
Enabling LTO frees up ~3 and ~11K of flash memory in Photon's system-part1 and system-part2 respectively.
- [ch73834]
> Enable LTO for Photon system firmware

- system/src/system_cloud.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
`Particle.unsubscribe()` clears system subscriptions to cloud events along with the application subscriptions and disrupts functioning of IOTA updates.
The list of registered event handlers is managed by the protocol layer that doesn't distinguish between system and application events. As a workaround, the system layer now re-adds system subscriptions after clearing them via the protocol's `spark_protocol_remove_event_handlers()`.
Verify that a product application based on the example code below can be updated OTA. Alternatively, add some logging to the `systemEventHandler()` function and verify that the system correctly receives `particle/*` events during handshake.
```cpp
SYSTEM_MODE(SEMI_AUTOMATIC)
SYSTEM_THREAD(ENABLED)
// PRODUCT_ID(...)
// …
```
> Particle.unsubscribe() doesn't preserve system subscriptions

- communication/inc/dtls_session_persist.h
- communication/src/dtls_message_channel.cpp
- crypto/inc/mbedtls_config_default.h
- hal/src/nRF52840/mbedtls/mbedtls_config_platform.h
This PR enables the DTLS Connection ID extension (described in [this](https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-09) draft RFC).
Verify that session resumption works as expected.
- [ch55112]
> Support for DTLS connection IDs

- system/inc/system_cloud.h
- system/inc/system_threading.h
- system/src/active_object.cpp
- system/src/main.cpp
- system/src/system_cloud.cpp
- system/src/system_cloud_connection.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- system/src/system_event.cpp
- system/src/system_task.cpp
- system/src/system_threading.cpp
- test/unit_tests/cloud/publish_vitals.cpp
- user/tests/integration/application/include/test.h
- user/tests/integration/application/src/application.cpp
- user/tests/integration/application/src/test_suite.cpp
- user/tests/unit/usb_control_request_channel.cpp
- wiring/inc/spark_wiring_cloud.h
- wiring/src/spark_wiring_cloud.cpp
1. The integration test framework defines the `setup()` and `loop()` functions making it impossible for test applications to run custom code in those functions.
2. The system Device OS API doesn't provide a way to force a new session to be established with the cloud which makes it difficult to write tests around session resumption.
1. Introduce a couple macros that can be defined in an integration test's `test.mk`: `NO_TEST_APP_INIT` and `NO_TEST_APP_SETUP_AND_LOOP`. The first macro disables automatic execution of the test framework's global initialization code, and the second one prevents the framework from defining the `setup()` and `loop()` functions. In both cases the test application is responsible for initializing the test framework:
```cpp
#include "test.h"
STARTUP({
testAppInit(); …
```
> Allow clearing session data and running custom setup code in integration tests

- hal/inc/pinmap_hal.h
- hal/src/nRF52840/gpio_hal.cpp
- hal/src/nRF52840/i2c_hal.cpp
- hal/src/nRF52840/timer_hal.cpp
- hal/src/stm32f2xx/gpio_hal.c
- hal/src/stm32f2xx/i2c_hal.c
- hal/src/tracker/am18x5.cpp
- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- user/tests/wiring/no_fixture/i2c.cpp
- user/tests/wiring/timer_stress/README.md
- user/tests/wiring/timer_stress/application.cpp
- user/tests/wiring/timer_stress/simple_ntp_client.cpp
- user/tests/wiring/timer_stress/test.mk
- user/tests/wiring/timer_stress/ticks.cpp
- wiring/inc/spark_wiring_fuel.h
1. [Gen 3] Micros/millis/unixtime may become non-monotonic (especially with hot/cold ambient temperature) due to unaccounted clock drift between 32KHz RTC and `DWT->CYCCNT`
2. [Gen 3] Non-monotonic micros may cause internal I2C HAL timeouts to expire early and cause I2C HAL to perform bus reset in the middle of the transaction.
3. [Gen 2 / Gen 3] Current I2C bus reset procedure is destructive if happens in the middle of the unfinished transaction and may cause erroneous data to be written into the I2C slave. Devices populated with BQ24195 PMIC (cellular) or AM1805 RTC (tracker) may very well end up in a broken state (e.g. powered off)
See also https://github.com/particle-iot/device-os/issues/2291
1. [Gen 3] Properly account for positive and negative clock drift between RTC and …
> [Gen 3] Fix micros/millis/unixtime becoming non-monotonic / Make I2C bus reset less destructive if performed in the middle of the transaction

- system/src/system_power_manager.cpp
- system/src/system_power_manager.h
- user/tests/wiring/power_management_long_running/power.cpp
- wiring/inc/spark_wiring_power.h
- wiring/src/spark_wiring_power.cpp
Add a manual test application for validating battery state. This is a supplement of https://github.com/particle-iot/device-os/pull/2272.
> Fixes abnormal battery charged behavior and adds a test for battery state deducing.

- system/src/system_network_cellular.h
If the WLAN_WD expires during device is connecting to the cellular tower followed by user requests to cancel the on-going cellular operation, the modem might be reset still.
Clear the WLAN_WD on user request to cancel the on-going cellular operation.
N/A
```c
SerialLogHandler logHandler(115200, LOG_LEVEL_ALL);
bool shutoff = false;
system_tick_t last_sync = 0;
// handler for mode button being clicked to trigger
// connect/disconnect
void mode_clicked(system_event_t event, int param)
{
shutoff = !shutoff;
Log.info("mode button clicked");
}
// background thread to call blocking API
// this appears to allow the idle task in during the `Cellular.off` sequence
// and trigger the WLAN watchdog
void background_thread_func()
{
while(true)
{ …
```
> Gen2: fixes the issue that the cellular modem is reset unexpectedly.

- system/src/system_network_manager_api.cpp
- system/src/system_sleep.cpp
- user/tests/wiring/sleep20/sleep20.cpp
For sleep 2.0 API, if the modem is powered on, but not establishing connection, it won't restore the modem power state after device is woken up.
Tracks the modem power state and connection state respectively in system sleep.
Running the example below building against develop branch you won't see the modem is on after device is woken up, but you will if you build it against the current branch.
```c
Serial1LogHandler l(115200, LOG_LEVEL_INFO);
void setup() {
Log.info("Turning on the modem...");
Cellular.on();
waitUntil(Cellular.isOn);
Log.info("Done");
delay(2s);
Log.info("Entering sleep...");
SystemSleepResult r = System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::STOP).duration(5s));
if (r.error() == …
```
> Restores the modem state after device is woken up.

- system/inc/system_task.h
- system/src/system_network_compat.cpp
- system/src/system_network_internal.h
- system/src/system_network_manager_api.cpp
- system/src/system_sleep.cpp
- system/src/system_sleep_compat.cpp
1. If the modem is just turned on by `Network.on()` and there is something wrong processing the modem events to cause a WLAN_WD to fire or somehow the `SPARK_WLAN_RESET` is set to reset the modem, device will try connecting to the network after the modem is reset.
2. If the modem is just turned on by `Network.on()` and system sleep API is called to make device enter sleep mode, after the device wakes up it will try connecting to the network. (Gen2 with all sleep API and Gen3 with sleep 1.0 API)
Introduce a new flag to indicate if network connection should be restored after powering cycle the modem. The flag is set 
1. before the modem is reset if networking in connecting or ready:
```diff
--- a/system/src/system_network_compat.cpp
+++ b/system/src/system_network_compat.cpp
@@ -248,6 …
```
> Gen2: network connection is established unexpectedly.

- ci/install_gcovr.sh
CI fails when installing `gcovr` and its dependencies. See e.g. https://g.codefresh.io/build/609bcf2539bf357f8705df27
```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
ws.require(__requires__)
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 834, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 0.0.0 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('MarkupSafe>=2.0.0rc2'), {'jinja2'})
During handling of the above exception, another exception occurred:
Traceback …
```
> [ci] fix MarkupSafe weirdness

- hal/src/photon/wlan_hal.cpp
- user/tests/wiring/no_fixture/wifi.cpp
Entering listening mode on Photon and P1 does not invalidate current sockets, while at the same time `wlan_restart()` will call into WICED to deinitialize LwIP stack, which invalidates netconns that are in use by WICED sockets and our socket layer.
Performing socket actions on a handle that has a reference to invalidated WICED socket/LwIP netconn may cause a crash.
Make sure to call `socket_close_all()` in `wlan_restart()` to avoid getting into this state.
- `wiring/no_fixture`: `WIFI_15_entering_listening_mode_and_enabling_softap_closes_active_sockets_cleanly`
N/A
- [CH78867]
---
> [photon/p1] wlan: make sure to close all sockets when deinitializing WICED connectivity subsystem

- hal/inc/cellular_hal.h
- hal/inc/hal_dynalib_cellular.h
- hal/network/lwip/cellular/pppncpnetif.h
- hal/network/ncp/cellular/cellular_hal.cpp
- hal/network/ncp/cellular/cellular_ncp_client.h
- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/quectel/quectel_ncp_client.h
- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
- hal/src/electron/cellular_hal.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
- hal/src/nRF52840/sleep_hal.cpp
- system/src/system_network_manager_api.cpp
- system/src/system_sleep.cpp
- user/tests/wiring/no_fixture/cellular.cpp
When we specify `.network(Cellular)` as a wakeup source when calling the system sleep API, we leave the modem running. When there is URC coming from the modem, like when Cellular moving from tower to another, it wakes up the device, which is unwanted. From the user's view, the device may be woken up frequently.
This PR also fixes issues:
1. Tracker specifically, which is when Cellular is specified as wakeup source, on waking up the on-board ESP32 module is turned on unexpectedly.
Inhibit URCs before going into sleep.
To verify the patch, you need to make the comparison:
1. Checkout and build the branch within this PR and observe the log from `Serial1`. 
2. Comment out `cellular_urcs(false, nullptr);` in `system_sleep.cpp` and build again. Observe the log from `Serial1`.
You'll see some …
> Inhibit Cellular URCs before going into sleep

- hal/inc/exrtc_hal.h
- hal/inc/hal_dynalib.h
- hal/src/nRF52840/exrtc_hal.cpp
Applications (tracker) must instantiate their own version of RTC drivers to manage the watchdog.  While the device OS handles synchronization of time and general RTC functions, it does not expose the RTC watchdog features, if any.  Application code size may be reduced by not having the additional/redundant driver for things that device OS may already handle.
Expose the watchdog portions of the HAL RTC driver to the application so that the device OS can offer it without a separate application driver.  Four functions would be essential to support the watchdog:
1. Enable/configure
2. Disable
3. Reset/kick
4. Check limits of watchdog timeouts
1. Setup the watchdog per the user app below, observe that the device does not reset.
2. Comment out the inner `loop()` portion of code and observe the …
> Add system watchdog API for user applications

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
1. The SIM select functionality for Kore ATT defaults the MNO profile to 198 (which does not support ATT band 5) which for older radio firmware defaults to UMNOPROF:2 (which supports Band 5 along with other ATT bands) [ch78344](https://app.clubhouse.io/particle/story/78344/r410-05-12-umnoprof-s-kore-att-equivalent-now-defaults-to-198-instead-of-2)
2. Radio does not respond over data channel after some cold boot runs [ch78322](https://app.clubhouse.io/particle/story/78322/r410-05-12-radio-does-not-respond-over-data-channel-after-some-cold-boot-runs)
3. PSM/eDRX are enabled by default with UMNOPROF=100. Disable it before (it's idle timer expires when) AT becomes unresponsive [ch78529](https://app.clubhouse.io/particle/story/78529/r410-05-12-psm-enabled-by-default-with-umnoprof-100-disable-it …
> [Gen3] Support for SARA R410 - 05.12 firmware

- hal/network/ncp_client/sara/sara_ncp_client.cpp
Refactor logic that hard codes UMNOPROF for Kore ATT
Test any tinker-like app with Kore ATT SIM on the R410 05.12 firmware, and ensure UMNOPROF is set to 2 (ATT)
- https://github.com/particle-iot/device-os/pull/2317
- https://github.com/particle-iot/device-os/pull/2318
---
> [Gen3] 05.12 - Refactor logic that hard codes UMNOPROF for Kore ATT

- hal/src/electron/modem/mdm_hal.cpp
The SIM select functionality for Kore ATT defaults the MNO profile to 198 (which does not support ATT band 5) which for older radio firmware defaults to UMNOPROF:2 (which supports Band 5 along with other ATT bands) [ch78344](https://app.clubhouse.io/particle/story/78344/r410-05-12-umnoprof-s-kore-att-equivalent-now-defaults-to-198-instead-of-2)
Hard code UMNOPROF to 2 (ATT) if Kore ATT is detected on this radio firmware
Test any tinker-like app with Kore ATT SIM and ensure UMNOPROF: 2 is selected
- [ch78344](https://app.clubhouse.io/particle/story/78344/r410-05-12-umnoprof-s-kore-att-equivalent-now-defaults-to-198-instead-of-2)
> [Gen2] Support for SARA R410 05.12 firmware

- user/tests/integration/communication/events/events.spec.js
- user/tests/integration/communication/functions/functions.spec.js
- user/tests/integration/communication/variables/variables.spec.js
Verbose logs in integration tests are disabled by default.
Use `console.log()` to print debug info.
Run `communication/*` integration tests.
> Print debug info in integration tests

- build/module-defaults.mk
Starting with GCC 9 not returning a value from a function declared to return non-void type will cause a hardfault. This is easily overlooked in applications where warnings are not promoted to errors by defaults.
Force -Wreturn-type to always trigger an error even if building applications where warnings are not promoted to errors.
Test app should fail to build with an error.
```c++
int test() {
}
/* executes once at startup */
void setup() {
Log.info("%d", test());
}
/* executes continuously after setup() runs */
void loop() {
}
```
N/A
---
> [build] force -Wreturn-type to always trigger an error

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
ICCID is not obtained when queried through `particle serial identify` in listening mode
```
blah@MacBook-Pro ~ $ particle serial identify
Your device id is e00fce68835b20e067d53c87
Your system firmware version is 3.0.0
```
This is the because the AT command that reads ICCID errors out in CFUN=0 state but it's OK in CFUN:4 or CFUN:1 state.
- Run CFUN=4 if the modem is in CFUN=0 state
- Run any tinker like app. The modem doesn't need to connect to cloud for this test
- Put the module in listening mode
- Run `particle serial identify`
- The module should give SIM info as well
```
blah@MacBook-Pro ~ $ particle serial identify
Your device id is e00fce68835b20e067d53c87
Your IMEI is 865284045753088
Your ICCID is 89010303300014910310
Your system firmware version is 3.0.0
```
---
> Prevent ICCID errors by using CFUN=4 instead of CFUN=0

- hal/network/lwip/esp32/esp32_ncp_util.cpp
- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/lwip/esp32/esp32ncpnetif.h
- hal/network/ncp/wifi/ncp.h
- hal/network/ncp/wifi/platform_ncp_update.cpp
- hal/network/ncp/wifi/wifi_ncp_client.h
- hal/network/ncp_client/esp32/esp32_ncp_client.cpp
- hal/network/ncp_client/esp32/esp32_ncp_client.h
- hal/src/nRF52840/bootloader.cpp
- services/inc/addr_util.h
- services/inc/system_cache.h
- services/src/system_cache.cpp
- services/src/tlv_file.cpp
1. Some changes in https://github.com/particle-iot/device-os/pull/2302 are now affecting the boot times of ESP32-based devices (mainly Argon) where ESP32 on bootup may be powered on and off multiple times to query version/MAC address.
2. Non-MBR-based bootloader updates are broken after https://github.com/particle-iot/device-os/pull/2302
1. Cache both ESP32 fw version and MAC address and use cached values whenever possible
2. Use `SERIAL_FLASH` as source when replacing bootloader without using MBR
1. Boot up Argon and Tracker in `SEMI_AUTOMATIC` mode and make sure that ESP32 is not powered on after the version/MAC have been cached
2. Downgrade bootloader using a debugger to < 2.0.0 version while keeping system part etc on this branch. Make sure SMH correctly updates the bootloader.
N/A
- …
> [Argon / Tracker] ESP32 MAC and firmware version caching; [Gen 3] Fixes non-MBR-based bootloader updates

- platform/MCU/nRF52840/src/flash_mal.c
Monolithic builds are broken on Gen 3 platforms.
This is a side-effect of a feature introduced in https://github.com/particle-iot/device-os/pull/2322 to invalidate 128KB application in the bootloader when detecting a write into the 256KB user app area.
Monolithic builds should work.
N/A
N/A
---
> [nrf52840] platform: we only need to erase user application when building in modular

- ci/cf_generate_message.sh
`$CF_BUILD_URL` generated by CF contains a private URL requiring CF sign-in even though we have public build logs enabled on CF.
Patch it.
Take a look at Device OS bots channel for build logs out of this branch/PR - the URL should be public and viewable without sign-in.
N/A
N/A
---
> [ci] generate public CF url in slack notification

- wiring/src/spark_wiring_ble.cpp
Seems like a bug that the memory is allocated with malloc but never freed. I didn't run a test to check if there was an actual memory leak, so I might have missed how it's freed. I did test that this new code compiles and the function works as expected (re-ran the `ble_scanner_broadcaster` tests)
---
> Free malloc'ed memory

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/modem/mdm_hal.h
The SARAR510 modem can potentially report a -1 value in the Radio Access Technology (RAT or AcT) field of at least two AT commands: `AT+COPS?` and `AT+CEREG?`
This value results in an incorrectly parsed cellular access technology that breaks the signal strength reporting in particle console.
Ublox confirmed this is a bug and will be fixed in later modem firmware versions, but a workaround should still detect this problem. 
If a -1 value is parsed from the `CEREG` URC or `COPS` command result, it will be reset to the fixed R510 value of 7. This should ensure the correct cellular access technology value. 
You can manually introduce the problem by substituting the COPS and CEREG strings with the -1 values. IE:
```
+CEREG: 2,5,"6a41","07f06011",-1
+COPS: 0,0,"AT&T",-1
```
Problem is not …
> [u-blox] Handle erroneous -1 AcT response from CEREG and COPS commands on R510

- communication/inc/dtls_message_channel.h
- communication/inc/protocol_defs.h
- communication/src/dtls_message_channel.cpp
- communication/src/protocol_defs.cpp
- system/inc/active_object.h
- system/inc/system_threading.h
- system/src/system_listening_mode.cpp
- system/src/system_network_compat.cpp
1. Network/socket layer errors cause the session data to be invalidated, which may lead to significantly increased data usage in low signal conditions.
2. Recursively calling into the MDM HAL from within the `HAL_NET_notify_disconnected()` callback causes a stack overflow on Electron (Device OS 2.1.0 doesn't seem to be affected). Stack trace:
```
#0  MDMParser::waitFinalResp (...) at ../../../hal/inc/../src/electron/modem/mdm_hal.cpp:495
...
#3  MDMParser::socketClose (... at ../../../hal/inc/../src/electron/modem/mdm_hal.cpp:3091
#4  MDMParser::socketFree (...) at ../../../hal/inc/../src/electron/modem/mdm_hal.cpp:3140
#5  socket_close (...) at ../../../hal/inc/../src/electron/socket_hal.cpp:100
#6  system_cloud_disconnect (...) at …
```
> Do not reset the session on socket errors

- hal/src/nRF52840/ble_hal.cpp
- user/tests/wiring/ble_central_peripheral/ble_central/central.cpp
`scan_phys` in default BLE scan parameters are not initialized.
Initialize correctly.
Run `wiring/ble*` tests.
N/A
N/A
---
> [gen3] ble: fix unintialized scan_phys in default scan parameters

- hal/network/ncp/cellular/cellular_hal.cpp
- hal/shared/cellular_ncp_dev_mapping.h
- hal/src/electron/modem/mdm_hal.cpp
- hal/src/electron/platform_ncp_electron.cpp
- hal/src/photon/platform_ncp_photon.cpp
- modules/electron/system-part1/src/cellular_hal.cpp
Early boards with the SARA R510 did not have the Network Coprocessor Identifier programed into the OTP memory locations. To work around this SARA R510 was hard coded in the GEN2 modem hal and the GEN3 `platform_primary_ncp_identifier`. 
The latest gen 2 / 3 SARAR510 EVT devices have this data so the workaround should not be needed going forward
For gen 3, the `platform_primary_ncp_identifier` function already reads the NCP id OTP data.
For gen 2, there is no `platform_ncp_electron` file, but rather it appears the other OTP data (device serial number, secret, etc) is accessible via `deviceid_hal`. I opted to extend the existing gen 2 deviceid hal, but there may be reasons we dont want to do that.  
Run example app, some hardware may not have R510 OTP programmed. This case still needs to be …
> Use ncp_id from OTP to determine modem type

- hal/network/ncp_client/esp32/esp32_ncp_client.cpp
On the ESP32 based platforms, if it is running the application with MANUAL mode and then goes into sleep mode without touching the network/modem functionality, it will draw ~300uA, which is violate the expected ~80uA.
Output high level on the ESPBOOT pin after booting up.
Which unit/integration/application tests are applicable to this code change? (At minimum a test of some kind should be provided)
```c
SystemSleepConfiguration config;
void setup(){
}
void loop() {     
config.mode(SystemSleepMode::ULTRA_LOW_POWER)
.duration(1min);
delay(1s);
System.sleep(config);
}
```
N/A
---
> Fixes the power leakage issue on the ESP32 module.

- services/inc/jsmn.h
- services/inc/jsmn_compat.h
- services/inc/services_dynalib.h
- services/src/jsmn.c
- services/src/jsmn_compat.c
- services/src/services_dynalib.c
- user/tests/wiring/no_fixture/json.cpp
- wiring/src/spark_wiring_json.cpp
(based on https://github.com/particle-iot/device-os/tree/fix/jsmn-library-updates)
Due to usage of `-fshort-enums` we were exporting `jsmn_parse()` which in fact was only returning an `int8_t`, preventing parsing of relatively large JSONs. This is now fixed in the upstream version of jsmn library (returns in `int`) and also in our "fork" contained within Device OS sources in services.
We will sync up with the upstream jsmn at a later point.
1. Update `jsmn` fork sources to return `int` and not use `jsmnerr_t` directly
2. Add `jsmn_parse_deprecated()` with old signature for dynalib compatibility purposes
N/A
N/A
N/A
---
> [services] Fixes jsmnerr_t issues in jsmn

- communication/inc/protocol.h
- communication/inc/protocol_defs.h
- communication/src/spark_protocol_functions.cpp
- hal/src/nRF52840/ota_flash_hal.cpp
- hal/src/stm32f2xx/ota_flash_hal_stm32f2xx.cpp
- platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c
- platform/MCU/nRF52840/inc/flash_access.h
- platform/MCU/nRF52840/src/flash_mal.c
- platform/MCU/shared/STM32/inc/flash_access.h
- services/inc/str_util.h
- system/src/system_cloud_internal.cpp
- test/unit_tests/services/str_util.cpp
- user/tests/integration/.gitignore
- user/tests/integration/ota/multiple_ota_no_reset/multiple_ota_no_reset.cpp
- user/tests/integration/ota/multiple_ota_no_reset/multiple_ota_no_reset.spec.js
- user/tests/integration/package-lock.json
- user/tests/integration/package.json
- user/tests/wiring/no_fixture/system.cpp
When system resets are disabled via `System.disableReset()`, it is possible to flash the device OTA multiple times without it resetting itself to apply the first received update. Module slots that are stored in the DCT and trigger the bootloader to copy the module's data from the OTA section to its destination section in the internal flash are not cleared in this case, even if the received modules occupy the same area in the OTA section, which may result in a corrupted firmware update.
Clear all non-factory module slots in the DCT at the beginning of an OTA update.
1. Flash the example application to a Gen 2 or Gen 3 device. Let the device connect to the cloud.
2. Flash the main system part module that is already running on the device OTA. The device will not reset after the update and …
> Clear module slots in DCT when preparing for an OTA update

- ci/install_gcovr.sh
Try using latest stable gcovr instead of latest develop branch.  Note that latest stable might not be compatible with the python version installed
<details>
```
```
</details>
What Bug or Missing Feature does this PR address? (A short summary is preferred over links)
How does this PR address the problem stated above? (Describing the …
> Attempt to fix gcovr installation

- user/tests/wiring/electron_disable_external_rtc_clock/clock.cpp
This PR contains the missed commits ported retroactively from [2.0.2](https://github.com/particle-iot/device-os/commits/v2.0.2) to develop. Please see https://github.com/particle-iot/device-os/pull/2354, https://github.com/particle-iot/device-os/pull/2360
https://github.com/particle-iot/device-os/pull/2354
https://github.com/particle-iot/device-os/pull/2360
---
> Extended: Merge '[Electron] Optional feature to use HSE/LSI as RTC clock source instead of LSE (external 32KHz XTAL)' to develop

- hal/network/ncp_client/sara/sara_ncp_client.cpp
- [feature] Rebasing multiple times has caused some missing code for R510 support of CEDRXS
- [bugfix] Two bugs fixed while testing backports of R510 support for 2.3.0
- [u-blox] mitigate bug with R510 v3.15 that ERRORs with UGPIOC=23,10
- [u-blox] R510 bug, modem doesn't respond to PWR_ON to turn off modem
- [enhancement] use ncpId() consistently
- [enhancement] prevent R410 flags from affecting other modems before initialization
- [feature] remove AT+CFUN=0 command that shouldn't have been there, add CEDRXS parsing support for R510
- [bugfix] Two bugs fixed while testing backports of R510 support for 2.3.0
- [u-blox] go back to using UGPIOC=23,0 output and set high.  Output mode will be persistent, but the high level will be set about 4-5 seconds after boot.
- [u-blox] when R510 modem …
> [u-blox] SARA R510 support extras

- ci/install_gcovr.sh
In order to pull in gcovr dependencies, update pip to the last release version that supported Python 3.5
> Update pip to last compatible with Python 3.5

- hal/network/lwip/esp32/esp32ncpnetif.cpp
- system/src/control/wifi_new.cpp
BLE setup process fails on Wi-Fi platform. We directly call into the NCP client's `connect()` function and bypass the system network manager. We need to disconnect the connection after Wi-Fi credentials is verified to succeed the setup process, otherwise, the network manager won't do that for us due to the improvement that has been introduced in netif.
Synchronize the NCP Client / NcpNetif and system network manager state after Wi-Fi credential is set.
N/A
N/A
---
> fix the issue that BLE setup fails on Wi-Fi platform.

- hal/src/nRF52840/ota_flash_hal.cpp
- user/tests/integration/wiring/gen3_invalid_compat_user_app
- user/tests/wiring/gen3_invalid_compat_user_app/application.cpp
- user/tests/wiring/gen3_invalid_compat_user_app/gen3_invalid_compat_user_app.spec.js
- user/tests/wiring/gen3_invalid_compat_user_app/test.cpp
Devices may present invalid user modules in system describe which can appear as some other type of module with potentially a set of invalid dependencies which cannot be satisfied preventing OTA from working correctly.
This happens because we ignore integrity or any other checks when making a decision on whether to include read-out module data in system describe. This is more problematic with Gen 3 devices running 3.1.0+ with 256KB applications as the compat (128KB) module header location would be in the middle of the larger binary. If by chance bytes at that location contain something seemingly valid (e.g. correct module type), this erroneous module would be reported in the describe message. If there is additionally a seemingly valid dependency, this is going to prevent product updates …
> [gen3] hal: zero out invalid user modules

- hal/network/ncp_client/sara/sara_ncp_client.cpp
Some of R510 warm boots take longer than expected and failing SLO criteria. In one of the runs with debugging enabled, it is noticed a run that took 115sec during warm boot (expected <30s) was blocked at ATI9 command for 90sec (which is default AT command timeout) and was causing the additional delays. It's next command though, works. 
Add additional AT-OK checks at init() which helps if there was an internal race condition that could block the AT interface.
Apply warm resets on any test app where cellular is initialized
[SC90828](https://app.shortcut.com/particle/story/90828/r510-at-command-timeouts-during-warm-boot)
---
> [R510] AT command timeouts after warm boot

- hal/src/nRF52840/ble_hal.cpp
- hal/src/nRF52840/ble_hal_impl.h
- user/tests/wiring/ble_scanner_broadcaster/ble_broadcaster/broadcaster.cpp
- user/tests/wiring/ble_scanner_broadcaster/ble_scanner/scanner.cpp
- wiring/inc/spark_wiring_ble.h
- wiring/src/spark_wiring_ble.cpp
Now that 3.1 supports Coded PHY, we should also support scanning for advertisements that are up to 255 bytes instead of 31 bytes. 
This PR changes `BleAdvertisingData's` buffer for advertisement data from an array with fixed size of 31, to a Vector. I selected this rather than an array of 255 bytes to save RAM, since an instance of `BleAdvertisingData` is created for every `BleScanResult`. 
For the Broadcaster, this PR changes the fixed size array from 31 (BLE_MAX_ADV_DATA_LEN) to 255 (BLE_MAX_SCAN_REPORT_BUF_LEN). Since there's a single instance of the Broadcaster, I think this is ok, although we could make this a Vector as well.
Added tests in `user/tests/wiring/ble_scanner_broadcaster` for both the Broadcaster and the Scanner.
---
> Add ability to set and scan extended advertisement size (when using Coded PHY)

- bootloader/src/nRF52840/nrf_it.c
- hal/src/nRF52840/core_hal.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
This fixes the broken hardfault handler as reported in #2380 
I added the `.align 4` line, which I think might be the actual fix for the compiler warning that the commit that introduced the bug intended to address.
It is very easy to test the hard fault handler, so it seems that the compiler warning was 'fixed' in the commit below without any testing! :fearful: 
https://github.com/particle-iot/device-os/commit/7b6e2086af907668d395c63404ecc754ee36fe41
I think that you are actually causing a hardfault in the hardfault handler now, resulting in an endless loop! @avtolstoy @sergeuz 
```cpp
void setup()
{
int (*bad_instruction)(void) = nullptr;
bad_instruction();
}
void loop()
{
HAL_Delay_Milliseconds(1);
}
```
> Fix hardfault handler to SOS again

- .gitmodules
- build/gcc-tools.mk
- ci/install_boost.sh
- communication/src/subscriptions.h
- hal/src/gcc/ota_flash_hal.cpp
- services/src/rgbled.c
- system/src/system_cloud_internal.cpp
- test/unit_tests/communication/util/coap_message.cpp
- third_party/mbedtls/build.mk
- wiring/inc/spark_wiring_cloud.h
- wiring/inc/spark_wiring_system.h
This PR fixes compilation errors on recent Linux distros with GCC 11 and updated system header files.
The following dependencies were updated:
- Boost to [1.78.0](https://www.boost.org/users/history/version_1_78_0.html).
- Catch to [2.13.7](https://github.com/particle-iot/Catch2/tree/v2.13.7).
- FakeIt to [2.0.9](https://github.com/particle-iot/FakeIt/tree/2.0.9).
Verify that the unit tests as well as the virtual device platform build and run without errors.
- [sc-93882]
> Fix compilation errors on Linux

- bootloader/src/nRF52840/nrf_it.c
- hal/src/nRF52840/core_hal.c
- hal/src/stm32f2xx/core_hal_stm32f2xx.c
- user/tests/wiring/filesystem/posix.cpp
See https://github.com/littlefs-project/littlefs/issues/268
1. Use patch from the above PR.
2. Add stress test to `wiring/filesystem` test suite. It fails without the patch on checking the integrity of the data after a truncate, it works fine with the patch.
3. (Minor and unrelated) Use .balign instead of .align in inline assembly, as `.align X` on ARM platforms semantically means 2^X alignment (and on other platforms it's just X alignment). `.balign` always means `X` alignment.
- `wiring/filesystem` built out of this branch with 3.2.0-rc.1, `wiring/filesystem` with system-part built out of this branch
N/A
- [SC93531]
---
> [Gen 3] LittleFS truncate fix (https://github.com/littlefs-project/littlefs/issues/268)

- hal/src/nRF52840/ota_flash_hal.cpp
We've introduced a bug in https://github.com/particle-iot/device-os/pull/2374 in the condition used to skip 'invalid' modules from module info. Due to the behavior of `fetch_module()` it actually returns additional validation flags apart from the ones being requested (in our case only `INTEGRITY` check is of concern).
Fix the check to only take into account `MODULE_VALIDATION_INTEGRITY` and add a comment on the behavior of `fetch_module()`.
Flash Gen 3 device with Device OS built out of this branch. Update OTA to 3.2.0. The update should succeed. After 3.2.0 application has been flashed, `particle serial inspect` should report user module with unsatisfied dependencies. On `develop`, `particle serial inspect` should not report any user module at all.
N/A
- …
> [gen3] hal: only skip modules that fail integrity check from module info

- hal/src/nRF52840/app_no_bootloader.ld
This PR is to complement #2391 to add GCC feature build-id for monolithic firmware.
> linker: Add GCC feature 'build-id' into monolithic firmware

- modules/shared/nRF52840/part1.ld
- system/inc/system_version.h
- system/src/system_cloud_internal.cpp
- test/unit_tests/system/string_interpolate.cpp
- test/unit_tests/system/system_task.cpp
- wiring/inc/spark_wiring_system.h
Remove initialisation of size field and move this into the code to remain compliant with the API.
Allows C files to access the constants and version API in system_version.h
> Make system_version.h compliant with C; Coalesce FreeRTOS task list internals into single location

- hal/inc/power_hal.h
- system/inc/system_power.h
- system/src/system_power_manager.cpp
- test/unit_tests/wiring/fuel_gauge.cpp
- user/tests/wiring/api/system.cpp
- user/tests/wiring/power_management/power.cpp
- user/tests/wiring/power_management_long_running/power.cpp
- wiring/inc/spark_wiring_fuel.h
- wiring/inc/spark_wiring_system_power.h
- wiring/src/spark_wiring_fuel.cpp
When loading a custom FuelGauge battery model, the SoC calculation may use a 18 or 19 bit model.  This must be recalled by the system FuelGauge class for use in properly calculating SoC.
Add an API to the SystemPowerConfiguration:
- [SET] `SystemPowerConfiguration& SystemPowerConfiguration::socBitPrecision(uint8_t bits);`
- [GET] `int SystemPowerConfiguration::socBitPrecision();`
- .socBitPrecision() defaults to 18 bit if not set explicitly
- Run unit tests
- Compile `TEST=wiring/api`⌛ 
- Run `TEST=wiring/power_manager`⌛ ⌛ 
- Run `TEST=wiring/power_manager_long_running` ⌛ ⌛ ⌛ ⌛ ⌛ ⌛ 😅 
- Run example app with default internal 18 bit battery model
- Run example app with loading an external 19 bit battery model
```c
Serial1LogHandler log1Serial(115200, LOG_LEVEL_ALL); …
```
> [gen3] adds SystemPowerConfiguration::socBitPrecision(uint8_t bits)) API [sc-94643]

- system/src/system_control_internal.cpp
- system/src/system_listening_mode.cpp
- system/src/system_task.cpp
If Wi-Fi credential is missing and safe mode is requested, device cannot enter listening mode to allow user to configure Wi-Fi credentials. As result device cannot finally connect to the cloud and stay in safe mode.
Do not process scenarios that is based on  the `FEATURE_DISABLE_LISTENING_MODE` flag when safe mode is requested.
```c
STARTUP( System.enableFeature(FEATURE_DISABLE_LISTENING_MODE) );
void setup() {
WiFi.clearCredentials();
}
void loop() {
}
```
N/A
---
> Listening mode should be allowed to enter when safe mode is requested.

- user/tests/wiring/no_fixture/system.cpp
- user/tests/wiring/no_fixture/time.cpp
- wiring/no_fixture SYSTEM/THREAD/TIME all had some intermittent tests
- improve reliability of SYSTEM/THREAD/TIME tests
- for SYSTEM/THREAD tests, run wiring/no_fixture via integration test runner as that was what was required to see the issue
`device-os/user/tests/integration $ device-os-test run boron wiring/no_fixture -v`
- run TIME tests via TEST=wiring/no_fixture with only TIME_19 compiled in, and use the new `repeat` feature to run this test 5000 times.  It should not fail.
```
Repeat tests how many times?: 5000
Repeating tests 5000 times!
Running tests
...
Test TIME_19_LocalTimeIsCloseToNtpTime passed.
Test [5000/5000]:1 passed, 0 failed, 0 skipped, out of 1 tests(s).
Total [5000/5000]: 5000 passed, 0 failed
Average [5000/5000]: 100.0% passed, 0.0% failed
```
> NOTE: for now, the …
> Improves reliability of a few wiring/no_fixture tests

- user/tests/app/ble/prov_mode/application.cpp
This PR adds an example app which uses the BLE provisioning mode APIs
[sc99863](https://app.shortcut.com/particle/story/99863/provide-ble-provisioning-integration-test-app)
#2382 
---
> [app] BLE provisioning mode for manual testing

- ci/install_gcovr.sh
[Bug with the latest jinja2](https://github.com/gcovr/gcovr/pull/576) so we'll downgrade for now.
> [ci] fixes gcovr report generation

- hal/src/nRF52840/device_code.cpp
API call to get device setup code `get_device_setup_code()` returns an error when dummy setup code is set, although it's a valid case.
Overwrite return error when dummy code is return as setup code
- Clear OTP so that setup code is empty
- Test that dummy setup code `XXXXXX` is returned and the device didn't crash.
```c
void setup() {
/* A minimal example app is super helpful 
* for testing new features and fixes. 
* A link to a Docs PR is even better!
*/
}
void loop() {
}
```
N/A
---
> [gen3] Dummy setup code should not return error

- user/tests/integration/slo/connect_time/connect_time.cpp
- user/tests/integration/slo/connect_time/connect_time.spec.js
Integration test `connect_time/slo` was failing intermittently on various devices for a number of reasons:
1. The test is designed to run cold boot and warm boot 10 times each, and take the 75th percentile result to compare to the SLO for each test case.  If any individual test failed, it would count towards the total number of tests as a failure, even if the individual test was one of the 25th percentile outliers.
2. Every test in the test runner suite has a 10 minute timeout value, so if the device `waitFor()` timeouts exceed that, the test will result in a failure and we won't know what was really failing in the test.
3. The test was running 10 test cases, and looking for a 75th percentile SLO which is not evenly divisible within 10 test cases, so the math was actually calculating the …
> [test] fixes integration slo/connect_time

- .circleci/config.yml
- build/lang-std.mk
- platform/MCU/STM32F2xx/CMSIS/Include/core_cmFunc.h
- test/unit_tests/CMakeLists.txt
1. Updates C++ standard version to C++17 (gnu variant)
2. Fixes branch name escape logic for CircleCI/Docker.
3. Bumps `nrf5_sdk` to a version with C++17-related `register` fixes.
N/A, CI should succeed
N/A
N/A
---
> Updates C++ standard version to C++17 (gnu variant)

- user/tests/wiring/no_fixture/ble_provisioning.cpp
- user/tests/wiring/no_fixture/network.cpp
NETWORK_00 and NETWORK_01 tests which are in the beginning of the test suite depend on the previous tests to establish a cloud connection. If a cloud connection was not established successfully in the previous tests, these tests immediately fail.
Reduce dependency by adding API to connect to Network and add relevant scope guards to ensure listening mode is disabled in LISTENING_XX tests.
Run on-device tests
N/A
---
> [test] fix listening network tests

- user/tests/integration/communication/functions/functions.spec.js
- user/tests/integration/communication/variables/variables.spec.js
It may take a while for the device to finish transmitting a large describe with many (50-100) functions/variables and API to report that. Retry a few times in JS side of the tests.
> [test] communication/functions communication/variables fixes for large describes

- bootloader/src/nRF52840/usbd_dfu_mal.cpp
- platform/MCU/nRF52840/src/flash_mal.c
There are a few lingering warnings when compiling Device OS
```
MCU/nRF52840/src/flash_mal.c: In function 'FLASH_CheckValidAddressRange':
MCU/nRF52840/src/flash_mal.c:273:30: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
273 |         return (startAddress >= 0x00000000 && endAddress <= 0x100000) ||
|                              ^~
MCU/nRF52840/src/flash_mal.c:279:29: warning: comparison of unsigned expression in '>= 0' is always true [-Wtype-limits]
279 |         return startAddress >= 0x00000000 && endAddress <= EXTERNAL_FLASH_SIZE;
|                             ^~
```
```
MCU/nRF52840/src/flash_mal.c: In function 'FLASH_CheckValidAddressRange':
MCU/nRF52840/src/flash_mal.c:273:30: warning: comparison of unsigned expression in '>= 0' is always true …
```
> [gen3] suppress certain reviewed GCC warnings [sc-100940]

- docs/dependencies.md
This documentation change updates the ARM GCC version in dependencies file to 10.2.1. I noticed that what was listed was out of date. Looks like only legacy builds/source versions are stored on launchpad.net now and mainline things are on ARMs official website directly.
- Updates Formula
- Bumps version requirements
- Links to more current source on: [developer.arm.com](developer.arm.com)
> Update dependencies for ARM GCC 10.2.1

- communication/src/spark_protocol_functions.cpp
- hal/inc/adc_hal_compat.h
- hal/inc/hal_platform.h
- hal/inc/i2c_hal_compat.h
- hal/inc/pwm_hal_compat.h
- hal/inc/rtc_hal_compat.h
- hal/inc/spi_hal_compat.h
- hal/inc/usart_hal_compat.h
- hal/src/nRF52840/bootloader.cpp
- hal/src/nRF52840/mesh_hal_deprecated.cpp
- system/src/control/config.cpp
- system/src/control/storage.cpp
- user/tests/wiring/api/adc.cpp
- user/tests/wiring/api/ble.cpp
- user/tests/wiring/api/i2c.cpp
- user/tests/wiring/api/pwm.cpp
- user/tests/wiring/api/rtc.cpp
- user/tests/wiring/api/spi.cpp
- user/tests/wiring/api/system.cpp
- user/tests/wiring/api/usart.cpp
- wiring/inc/spark_wiring_system.h
There are a number of uppercase HAL APIs that were deprecated and renamed to lowercase.  We would like to remove these uppercase APIs in Device OS 5.x, however customers do not have any way currently to know they will be removed in 5.x.
Add this warning to these deprecated messages so customers will be notified during Device OS 4.x releases:
```
Will be removed in 5.x!
```
- Clean build `TEST=wiring/api` should show no warnings
[sc-101375](https://app.shortcut.com/particle/story/101375/update-device-os-4-x-deprecation-messages-to-notify-removal-in-5-x)
---
> [deprecation] Adds warning to some deprecated API's that will be removed in Device OS 5.x

- system/src/system_network_manager_api.cpp
- system/system-threading.md
Listening mode cannot be entered through MODE button press with system threading enabled
ASYNC/SYNC calls related to system threading cannot be performed in HAL ISR. Adjust accordingly.
Ensure listening mode can be entered through the following ways with system threading enabled and disabled.
1. User presses SETUP button
2. Application calls Wiring function to enter listening mode
3. USB control request to enter listening mode
4. If there are no credentials in the device
[SC-102872](https://app.shortcut.com/particle/story/102872/unable-to-put-argon-into-listening-mode-through-button-press)
#2419 
---
> [Gen3] Device unable to enter listening mode with button press

- hal/src/nRF52840/usb_hal.cpp
When logging from ISR is enabled and use the Serial1 as the log interface, device runs into SOS. This is because that SD APIs require SVC interrupt to be enabled, whereas logging from ISR will prehibit the SVC interrupt and device has a chance to call into SD APIs and then hardfault.
Temporarily increase the BASEPRI value to enable SVC interrupt handling.
```c
void setup() {
}
void loop() {
}
```
N/A
---
> [gen3] fixes hardfault during low level USB peripheral initialization under an atomic section

- user/tests/wiring/no_fixture_wifi/wifi.cpp
WiFi.resolve() tests sometimes fail when run with a new connection
Add retries 
Run `wiring/no_fixture_wifi` on device-os test runner and ensure tests pass.
```
No fixture wifi
argon
systemThread=disabled
✓ WIFI_00_connect (26.7s)
✓ WIFI_01_resolve_3_levels (5.8s)
✓ WIFI_02_resolve_4_levels
✓ WIFI_03_resolve
✓ WIFI_04_config
✓ WIFI_05_scan (4.8s)
✓ WIFI_06_restore_connection
✓ WIFI_11_scan_returns_zero_result_or_error_when_wifi_is_off (6.9s)
✓ WIFI_12_restore_connection
✓ WIFI_13_wifi_class_methods_work_correctly_when_wifi_interface_is_off (2.9s)
systemThread=enabled
✓ WIFI_00_connect (19.3s)
✓ WIFI_01_resolve_3_levels (5.8s)
✓ WIFI_02_resolve_4_levels (5.8s)
✓ WIFI_03_resolve (5.8s)
✓ WIFI_04_config
✓ WIFI_05_scan (4.8s)
✓ WIFI_06_restore_connection
✓ …
```
> [Gen3] WiFi resolve tests need retries

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
Boron entering hibernate mode after startup in MANUAL mode consumes ~700UA current, which beyonds the expected <100uA.  The root cause of the issue is that the modem uart is initialized on startup, while the system sleep API checks that the cellular interface is off so that the modem off procedure is not performed, thus, the modem uart is kept on.
Controls the modem uart according to the modem power status after startup.
Run the simple example below on a Boron, it should consum <100uA after it enters hibernate mode.
```c
void setup() {   
delay(10s);
SystemSleepResult res = System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::HIBERNATE).gpio(D2, RISING));
}
void loop() {
}
```
N/A
---
> [gen3] hal: fix power leak on Boron

- .buildpackrc
- build/create_module.py
- build/make_release.sh
- build/release-publish.sh
- build/release-tests.sh
- build/release.sh
- ci/cf_generate_message.sh
- ci/enumerate_build_matrix.sh
- user/tests/wiring/no_fixture_long_running/pwm.cpp
HIL / Concourse need to be updated to support the esomx platform. There are various build scripts used by these tools to compile firmware and tests that need to be updated
Update the needed scripts/files to allow building for esomx platform
Concourse should be able to build
N/A
---
> [gen3][esomx] ESOMX board support on HIL / Concourse

- .buildpackrc
- CHANGELOG.md
- build/release.sh
- build/version.mk
- modules/shared/system_module_version.mk
- system/inc/system_version.h
- system/system-versions.md
> ## :warning: Please note this is in internal release, do not use on production devices!
- [esomx] Adds support for new platform esomx [#2443](https://github.com/particle-iot/device-os/pull/2443) [#2459](https://github.com/particle-iot/device-os/pull/2459)
- [E404X] Determine flash part at runtime [#2456](https://github.com/particle-iot/device-os/pull/2456)
- [gen3][quectel] Adds support for BG95-M1, BG95-MF, BG77, and EG91-NAX [#2458](https://github.com/particle-iot/device-os/pull/2458)
- [gen3] hal: fix power leak on Boron [#2452](https://github.com/particle-iot/device-os/pull/2452)
- [workbench] update-device-os-workbench-manifest-json [#2457](https://github.com/particle-iot/device-os/pull/2457)
- [ci] test-build-system-tune-timeouts …
> 4.0.0-alpha.2 Pre release

- build/module-defaults.mk
- ci/build_boost.sh
- hal/src/gcc/boost_json.h
- hal/src/gcc/core_hal.cpp
- hal/src/gcc/device_config.cpp
- hal/src/gcc/device_config.h
- hal/src/gcc/eeprom_hal.cpp
- hal/src/gcc/filesystem.cpp
- hal/src/gcc/filesystem.h
- hal/src/gcc/include.mk
- hal/src/gcc/ota_flash_hal.cpp
- system/src/system_cloud_internal.cpp
- system/src/system_cloud_internal.h
- wiring/inc/spark_wiring_version.h
The GCC platform only supports on-demand OTA updates which prevents us from using it for testing multistage and product updates.
- Allow overriding the describe message sent by the virtual device and preserve the module info between device "resets" during an update.
- Allow setting the product version via command line arguments.
- Build a test application and run it with a `--describe` argument followed by the path to the device's describe message in JSON format.
- Flash a user application requiring a higher version of Device OS than what is specified in the describe data to the virtual device.
- Validate that the virtual device receives all necessary modules and gets "updated" to the target Device OS version.
- sc-106316
> Enable OTA updates on the GCC platform

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.cpp
Currently on our 2G/3G/Cat-1 devices, we require CSD and PSD connections to be registered before we start a data connection. So if one won't connect, likely the CSD connection... it will block the device from connecting. 
Early on in Electron development I believe we waited for CSD connections so that we could dial out and receive calls to potentially wake on RING indication, but this has never been implemented and currently cannot be used with current SIMs.
- Wait for (PSD || EPS) registration instead of ((CSD && PSD) || EPS) for both u-blox & Quectel modems
- ~Disable setting Cellular Global Identity (CGI) for CSD registration since we're not waiting for CSD anymore~
- After talking this over with Keerthy, we decided that it doesn't hurt to leave this code in since PSD and EPS …
> Register without waiting for CSD connections [sc-96611]

- hal/src/rtl872x/exflash_hal.cpp
- user/tests/wiring/no_fixture_spi/spix.cpp
- user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp
1. To improve firmware download speed, we need to make use of `FLASH_TxData256B()`
2. We're using 80MHz in the P2 flash clock configuration while MX25R32 requires up to 60MHz clock speed.
3. Minor fixes for SPI unit test
**NOTE: This PR requires updating the prebootloader!**
1. Run `usb-dfu` to update DVOS to confirm the speed is improved
1. Update the prebootloader to observe the flash clock with an oscilloscope
1. Run the unit test `wiring/no_fixture_spi`
---
> [p2] Flash supports page write and other fixes

- build/arm-tools.mk
- build/arm/linker/linker_freertos_task_symbols.ld
- modules/shared/nRF52840/linker_system_part1_common.ld
- modules/shared/rtl872x/linker_system_part1_common.ld
- third_party/freertos/build.mk
- third_party/freertos/makefile
Due to refactoring of linker files in #1953 (and those changes actually coming after P2 merge) we lost a quirk in linker files which coalesced FreeRTOS task/timer symbols into a single location in .bss for some of the tooling that we use (#2399). This also wasn't really working with LTO enabled as is the case with Gen 3 system part builds.
Fix that.
Build out of this branch, check system-part map files, `pxCurrentTCB` and other FreeRTOS symbols should be located in `.bss` section between `__rtos_capture_start` and `__rtos_capture_end`.
N/A
- #2399
- #1852
---
> [linker] make sure that FreeRTOS task/timer symbols are coalesced in bss section, disable LTO for FreeRTOS sources as well

- hal/src/rtl872x/hal_platform_rtl8721x_config.h
<details>
<summary>Allow P2 to use our legacy ethernet detection</summary>
</details>
Ethernet detection was disabled on P2 until now
Simply enable our legacy ethernet detection on the traditional SPI port
Which unit/integration/application tests are applicable to this code change? (At minimum a test of some kind should be provided)
```c
SerialLogHandler logHandler(115200, LOG_LEVEL_INFO);
void setup() {
System.enableFeature(FEATURE_RESET_INFO);
int reason = System.resetReason();
delay(4000);//wait for usb serial to start
Log.info("setup start after reset: %d", reason);
// as a test, clear wifi credentials and force ethernet connection
Log.info("clear wifi creds...");
WiFi.clearCredentials();
if …
```
> allow ethernet detection on P2

- user/applications/tinker/application.cpp
Deprecating tinker-fqc broke tinker for non p2 platforms
Only build FQC functionality for p2 platforms
build tinker / run CI 
tinker
---
> [tinker] Fix tinker build for non-p2 platforms

- hal/network/ncp_client/realtek/rtl_ncp_client.cpp
<details>
<summary>P2 wifi network configuration info provided by the `WiFi.wifi_config()` method was missing </summary>
</details>
Provide more complete wifi_config information to the  `WiFi.wifi_config()` method
Updated `RealtekNcpClient::getNetworkInfo(WifiNetworkInfo* info)` to fill in provided `WifiNetworkInfo` struct
connect to wifi network and verify network information is provided to a user app
```c++
SerialLogHandler logHandler(115200, LOG_LEVEL_INFO);
static void network_check() {
// fetch the WLanConfig, which typically doesn't change after cloud connection is established
Log.info("fetch wifi_config...");
WLanConfig* wifi_cfg = WiFi.wifi_config();
Log.info("wifi_config uaSSID: '%s' ",  wifi_cfg->uaSSID); …
```
> [p2][wifi] Add more complete WiFi network configuration information for P2

- hal/src/rtl872x/gpio_hal.cpp
- hal/src/tron/pinmap_defines.cpp
- hal/src/tron/pinmap_defines.h
This PR is to add `VBAT_MEAS` and charging pin to P2 pinmap.
- `VBAT_MEAS` is an ADC-dedicated pin, it can measure the input voltage with 5V tolerance,
- Charging pin is only used on Lightcycle
Add VBAT_MEAS as the A6 pin, note that the reference voltage is 5V instead of 3.3V
1. Re-compile and download bootloader/system-part1/user-app
2. Measure different voltage with A6 pin
```c
void setup() {
}
void loop() {
int value = analogRead(A6);
Log.info("A6 value: %d, volt: %f", value, value / 4096.0 * 5.0);
int A0Value = analogRead(A0);
Log.info("A0 Value: %d, volt: %f", A0Value, A0Value / 4096.0 * 3.3);
delay(1000);
}
```
---
> [p2][photon2] Add VBAT_MEAS pin and charging indication pin for Photon2

- ci/enumerate_build_matrix.sh
- ci/run_tests.sh
- hal/src/gcc/device_config.cpp
- test/unit_tests/services/dcd.cpp
- user/tests/wiring/api/wiring.cpp
- wiring/src/user.cpp
As title says:
1. Fixes builds of GCC platform under some versions of GCC
2. Fixes building of `wiring/api` tests on CI
3. Fixes `wiring/api` tests for P2
4. Clean up weak `serialEvent` stuff and make sure unused serialEvent references are optimized out
Wait for CI build.
---
> Fix GCC platform on some versions of GCC; Fix wiring/api tests for P2; Fix building of wiring/api tests on CI

- hal/inc/hal_dynalib_wlan.h
<details>
<summary><i>Tracker needs separate declaration of wifi dynalib methods</i></summary>
</details>
---
> [tracker][wifi][enhancement] add wifi country code stubs for tracker

- bootloader/prebootloader/src/tron/part1/sleep_handler.cpp
- bootloader/prebootloader/src/tron/part1/update_handler.c
- hal/src/rtl872x/km0_km4_ipc.cpp
- hal/src/rtl872x/km0_km4_ipc.h
- hal/src/rtl872x/sleep_hal.cpp
- hal/src/rtl872x/spi_hal.cpp
- hal/src/rtl872x/usart_hal.cpp
- platform/MCU/rtl872x/inc/platform_flash_modules.h
- platform/MCU/rtl872x/src/flash_mal.c
- services/inc/align_util.h
A clone of https://github.com/particle-iot/firmware-private/pull/381.
Buffers being used by DMA or between KM0 and KM4 should be 32-byte aligned, and the length of it should be multiple of 32 bytes, otherwise, data in SRAM might be corrupted.
N/A
Tested:
1. Flash new prebootloadder and bootloader agianst the branch in this PR
2. Flash old system firmware that is against the `develop` branch.
3. Verified sleep functionalities.
4. Verified bootloader updating using `particle flash --serial`
"Old prebootloader/bootloader + new system firmware" is broken, but this normally won't happen given that users wil go 
through the safe mode healer to update system firmware.
---
> [rtl872x] DCache alignment requirement

- hal/inc/interrupts_hal.h
- hal/src/rtl872x/interrupts_hal.cpp
- user/tests/wiring/no_fixture/interrupts.cpp
`INTERRUPTS_01_isisr_willpreempt_servicedirqn` test fails on P2 due to unimplemented HAL
Use an array to backup any overridden ISR handlers. When override is removed, restore the backup.
There are other parts of the HAL that are still unimplemented, namely `HAL_Core_Restore_Interrupt()` and the `link_interrupt_vectors_location` RAM table in general during `HAL_Core_Config()`.
This PR is still a WIP to facilitate discussion on how to approach these problems. 
Run `wiring/no_fixture`, specifically `INTERRUPTS_01_isisr_willpreempt_servicedirqn`
Run `wiring/no_fixture`
---
> [p2] fixes INTERRUPTS_01_isisr_willpreempt_servicedirqn test

- hal/src/rtl872x/spi_hal.cpp
DCache PR added some more parameter checks in the SPI driver, some of them are not necessary.
Revert changes.
`wiring/no_fixture_spi`
[CH107141]
---
> [P2] hal: revert SPI parameter check

- CHANGELOG.md
- build/release.sh
- build/version.mk
- modules/shared/system_module_version.mk
- system/inc/system_version.h
- system/system-versions.md
> ## :warning: Please note this is an internal release, do not use on production devices!
- [p2] Allow setting WiFi country code and channel plan [#2485](https://github.com/particle-iot/device-os/pull/2485) [#2473](https://github.com/particle-iot/device-os/pull/2473)
- [p2][wifi] Add more complete WiFi network configuration information for P2 [#2474](https://github.com/particle-iot/device-os/pull/2474)
- [p2][photon2] Add VBAT_MEAS pin and charging indication pin for Photon2 [#2482](https://github.com/particle-iot/device-os/pull/2482)
- [ethernet][p2] Allow ethernet detection on P2 [#2478](https://github.com/particle-iot/device-os/pull/2478)
- [p2] usart: flush DMA FIFO data when required [#2477](https://github.com/particle-iot/device-os/pull/2477)
- [p2] deprecate tinker-fqc app …
> Device OS v5.0.0-alpha.2

- user/applications/tinker/src/burnin_test.cpp
- user/applications/tinker/src/burnin_test.h
The P2 burn in process is supposed to indicate how long it has run by blinking the LED every 1s. An alternating green/blue pattern indicates the tests are still running and passing.
For burn in hours X:
x >= 72h : 6 green blinks 4 blue
72h > x >= 48h : 7 green blinks 3 blue 
48h > x >= 24h : 8 green blinks, 2 blue
x < 24h : 9 green blinks, 1 blue
The current LED blink logic is convoluted, and relies on the `System.millis()` value monotonically increasing. Unfortunately there is also a bug right now where it resets sometimes, which causes the LED logic to break and stop blinking all together. 
Simplify LED blink logic. Just use `delay()` since LED loop has its own thread. No need to rely on `System.millis()`
Build tinker, run burnin
Tinker …
> [p2] Simplify burn in LED blink, work around System.millis() reset

- hal/src/boron/pinmap_hal.c
- user/tests/wiring/no_fixture/gpio.cpp
- user/tests/wiring/no_fixture_long_running/pwm.cpp
`wiring/no_fixture_long_running` PWM tests are failing on esomx platform, specifically PWM tests with pin `C5`.
`C5` shares a PWM channel with the RGB LEDs (channel 0). When running the PWM long running tests, the RGB led would interfere with the tests, causing them to fail.
Disabling the RGB LED during the PWM tests allows them to execute without the LED system interfering.
**`NOTE:` this change does affect all PWM tests on all platforms, not just esomx**
I tested this PR with `esomx`, `p2` and `boron` platforms and all passed.
Run `wiring/no_fixture_long_running` tests
Run `wiring/no_fixture_long_running` tests
---
> [tests] [esomx] disable RGB pwm channel(s) when running pwm tests

- hal/src/rtl872x/delay_hal.cpp
- system/src/system_task.cpp
- user/tests/wiring/no_fixture/delay.cpp
`DELAY_01_delay_1ms_is_within_tolerance` fails occasionally on p2 `no_fixture` tests, ie the 1ms delay ends up being out of the 6% margin of error ( > 1060 us). 
Changing the `HAL_Delay_Microseconds()` implementation to a simple poll of `HAL_Timer_Get_Micro_Seconds()` seems to be no worse than using the rom `DelayUs()` function.
Also tweaked the `system_delay_pump()` logic when doing a 1ms delay, which is what happens in the DELAY_01 test. 
However, the 6% threshold is still too short in some situations. Doubling it seems to ensure tests pass a higher % of the time. I still see an occasional failure where the delay took >1120 us, but this happened once in 300 test iterations. Not sure if this is infrequent enough to ignore or if the threshold should be raised even higher.
Run …
> [rtl872x] Poll micros instead of rom DelayUs function. Tweak 1ms test

- hal/src/rtl872x/timer_hal.cpp
`HAL_Timer_Get_Milli_Seconds()` / `HAL_Timer_Get_Micro_Seconds()` Eventually reset after ~1 hour of execution. This results in `millis()` rolling over to zero. 
It appears that the problem is due to integer promotion (in this case, demotion?) when calculating elapsed micro seconds:
```
constexpr int US_PER_OVERFLOW = 65536;                 // 65536us
...
return usSystemTimeMicrosBase_ + state.overflowCounter * US_PER_OVERFLOW + ticksToTime(state.curTimerTicks);
```
Making `US_PER_OVERFLOW` a uint64_t seems to solve the problem.
Modify `timer_hal.cpp` `init()` and `start()` functions to start the `overflowCounter_` at a value close to 65536
```
overflowCounter_ = 65000;
```
Run the app and observe the uptime millis incrementing beyond `0004294659`
tinker or any app with timestamp logging …
> [rtl872x] Fix millis() rollover

- hal/src/nRF52840/interrupts_hal.cpp
- hal/src/rtl872x/interrupts_hal.cpp
- user/tests/app/interrupts/interrupts.cpp
- [P2] attachInterrupt() failing to call interrupt handler after using noInterrupts()/interrupts()
- [gen3] interrupts() API should not clear pending interrupts
- [P2] The fact that the interrupts() API cleared the pending interrupts also disabled the currently attached interrupt upon re-enabling global interrupts.  Simply removing the clearPending call resolves it.
- [gen3] pending interrupts was being cleared unintentionally.  Simply removing the clearPending call resolves it.
- run `TEST=app/interrupts` on all platforms, jumpering a wire from A5 to D0 ~ D6 one at a time and resetting the device between tests.
- [sc-107555](https://app.shortcut.com/particle/story/107555/p2-attachinterrupt-fails-to-call-interrupt-handler)
- [P2] fixes attachInterrupt() failing to call interrupt handler …
> [p2][gen3] fixes for attachInterrupt() / noInterrupts() / interrupts() APIs

- hal/src/nRF52840/interrupts_hal.cpp
- user/tests/app/interrupts/interrupts.cpp
- [gen3] interrupts() API should not clear pending interrupts
- [gen3] pending interrupts was being cleared unintentionally.  Simply removing the clearPending call resolves it.
- run `TEST=app/interrupts` on all platforms, jumpering a wire from A5 to D0 ~ D6 one at a time and resetting the device between tests.
- [sc-107555](https://app.shortcut.com/particle/story/107555/p2-attachinterrupt-fails-to-call-interrupt-handler)
- [gen3] fixes interrupts() API, should not clear pending interrupts
---
> [4.x] [gen3] fixes interrupts() API, should not clear pending interrupts

- hal/src/rtl872x/usart_hal.cpp
- services/inc/ringbuffer.h
When running the Serial2 stress test app as attached below, device may hang up over time.
1. Implement recursive TX/RX lock
2. Fix minor bug in ring buffer
3. Do not suspend DMA unless necessary.
Build and run the below test app.
```c
Serial1LogHandler log(115200, LOG_LEVEL_ALL, {
{"system", LOG_LEVEL_WARN}
});
constexpr uint16_t buffLen = 64;
uint8_t txBuff[buffLen];
uint8_t rxBuff[buffLen] = {};
system_tick_t was = 0;
void setup() {
Serial2.begin(115200);
for (int i = 0; i < buffLen; i++) {
txBuff[i] = (uint8_t)i;
}
was = millis();
}
bool done = true;
size_t txLen = 0;
size_t rxCnt = 0;
void loop() {
if (done) {
txLen = random(1, buffLen);
txLen = Serial2.write(txBuff, txLen);
Log.printf("TX Done: %d\r\n", txLen);
done = …
```
> [rtl872x] hal: fix issue that uart rx dma may hang up.

- hal/src/rtl872x/interrupts_hal.cpp
- user/tests/app/input_pinmode/input_pinmode.cpp
- user/tests/wiring/no_fixture/interrupts.cpp
From [Docs on attachInterrupt](https://docs.particle.io/reference/device-os/api/interrupts/attachinterrupt/):
> NOTE: pinMode() MUST be called prior to calling attachInterrupt() to set the desired mode for the interrupt pin (INPUT, INPUT_PULLUP or INPUT_PULLDOWN).
P2 implementation currently does not respect this and modifies the pin pull up based on the InterruptMode type (RISING/FALLING/CHANGE).
- The Realtek routines that modify pullup/pulldown resistors are `GPIO_Init()` and `GPIO_INTMode()`.  Since these are compiled libraries, we have to reimplement them without the calls to `PAD_PullCtrl()` for use only in `hal_interrupt_attach()`
- I moved the placement/timing of `GPIO_Init_HAL()` based on guidance from Realtek examples and documentation.
- Run `TEST=wiring/no_fixture` …
> [p2] attachInterrupt() should not configure input pullup/pulldown/nopull

- .circleci/config.yml
- If you want to push changes to fix test-build-system, currently you have to modify the branch pattern to do so.  There should be some pattern we can use for PRs that allows us to test changes in the PR before they are merged... without having to think about changing the pattern.  Suggest anything matching `*test-build-system*`.
- Also doesn't include `develop-*.x` branches
- Modify/Add required patterns
- CircleCI should run the `test-build-system` workflow when a branch contains `test-build-system`
- CircleCI should run the `test-build-system` workflow when a branch is merged to `develop-4.x`
[sc-107219](https://app.shortcut.com/particle/story/107219/add-a-branch-pattern-to-workbench-test-build-system-circleci-script-workflow-to-assist-fixing-changing-the-test-build-system)
---
> [ci] branch pattern changes for test-build-system

- .circleci/config.yml
- If you want to push changes to fix test-build-system, currently you have to modify the branch pattern to do so.  There should be some pattern we can use for PRs that allows us to test changes in the PR before they are merged... without having to think about changing the pattern.  Suggest anything matching `*test-build-system*`.
- Also doesn't include `develop-*.x` branches
- Modify/Add required patterns
- CircleCI should run the `test-build-system` workflow when a branch contains `test-build-system`
- CircleCI should run the `test-build-system` workflow when a branch is merged to `develop-4.x`
[sc-107219](https://app.shortcut.com/particle/story/107219/add-a-branch-pattern-to-workbench-test-build-system-circleci-script-workflow-to-assist-fixing-changing-the-test-build-system)
---
> [ci][4x] branch pattern changes for test-build-system

- hal/src/rtl872x/pinmap_hal.cpp
- hal/src/rtl872x/pwm_hal.cpp
- user/tests/wiring/no_fixture_long_running/pwm.cpp
- user/tests/wiring/pwm/application.cpp
- user/tests/wiring/pwm/pwm.cpp
- user/tests/wiring/pwm/test.mk
P2 cannot read a PWM pin itself using `pulse_in()`. This PR adds a PWM fixture test that uses one pin to generate a PWM output and another to measure it via `pulse_in()`. 
Port the `no_fixture_long_running/pwm` tests into a `wiring/pwm` fixture test app. 
- In general, tests configure one pin as the "output" pin, which a PWM signal is generated on. Each other PWM pin is configured as in "input" pin, and `pulse_in` is used to measure the output pins signal. Each permutation of output/input pins is configured and run for each test. 
- Capacitance doesnt seem to be an issue but if it is, the test can be modified to only test certain pairs/combinations of pins
Implementing these tests resulted in some PWM hal fixes/changes:
- Default PWM resolution changed to "8 bit" resolution (The KM4 PWM …
> P2 PWM fixture tests. PWM HAL fixes

- hal/inc/deviceid_hal.h
- hal/src/gcc/deviceid_hal_impl.h
- hal/src/nRF52840/deviceid_hal_impl.h
- hal/src/newhal/deviceid_hal_impl.h
- hal/src/rtl872x/ble_hal.cpp
- hal/src/rtl872x/ble_hal_impl.h
- hal/src/rtl872x/deviceid_hal.cpp
- hal/src/rtl872x/deviceid_hal_impl.h
- hal/src/trackerm/network/network.cpp
- hal/src/tron/network/network.cpp
```c
void setup() {
BLE.on();
BLE.advertise();
// BLE.setAddress("D3:12:34:56:78:AB");
delay(3000);
auto foo = BLE.address();
Log.info(foo.toString());
}
```
---
> RTL872x: Implement APIs to set/get BLE address

- user/tests/wiring/no_fixture/time.cpp
TIME_17 was failing, presumably due to a race condition with time sync arriving late
Run TIME_17 offline and use the RTC as-is (it might have sync'd time, it might not... doesn't matter for the test)
- Run `TEST=wiring/no_fixture` (TIME*) tests
---
> [test] fixes race condition with wiring/no_fixture TIME_17

- services/inc/devicetree_stubs.h
- services/inc/services_dynalib.h
- services/src/devicetree_stubs.cpp
Reserve functions in services dynalib for device tree support and for now just return `SYSTEM_ERROR_NOT_SUPPORTED` or other defaults where possible.
> [services] device tree stubs

- wiring/inc/spark_wiring_logging.h
- wiring/src/spark_wiring_logging.cpp
Device OS disables logging to the USB serial when the device is in listening mode in order to prevent mixing up the serial console and logging output. However, it turns out that messages logged via `LOG_PRINT()` and other macros for direct logging still get through and may garble the serial console output. This PR fixes that by disabling direct logging in listening mode.
> Disable direct logging in listening mode

- user/tests/integration/package-lock.json
- user/tests/integration/package.json
See https://github.com/particle-iot/binary-version-reader/pull/54
When running locally make sure to `npm install` inside `user/tests/integration` folder first.
Run `ota/multiple_ota_no_reset` on all platforms, they should pass on P2 and Tracker M (there is another issue on Tracker M though currently related to this).
N/A
- https://github.com/particle-iot/binary-version-reader/pull/54
---
> [tests] integration: bump binary-version-reader and device-constants dependency for P2-related module manipulationfixes

- modules/shared/rtl872x/inc/system-part1/module_system_part1.inc
Missing cellular hal calls in dynalib which is causing issues when the user module calls `hal_storage` related tables
Add missing cellular hal into dynalib for supporting platforms
Run user `ota/multiple_ota_no_reset` integration tests
---
> [rtl872x] add cellular hal into dynalib for supporting platforms

- system/src/system_task.cpp
- user/tests/wiring/no_fixture/time.cpp
Calling `delay(1)` from a user application in a tight loop does not allow the RTOS application task to yield and does not pump the system thread. Attempting to delay down to the microsecond resolution is also problematic.
Always delay at least 1 ms, ignore microsecond resolution, and explicitly call `spark_process` no matter what during each call. 
`no_fixture` test `TIME_17_RtcAlarmFiresCorrectly` on Tracker was the original test that failed
Run `no_fixture` and test `TIME_17_RtcAlarmFiresCorrectly`
---
> Ensure task yield and system thread pump in system_delay_pump

- build/release.sh
- ci/enumerate_build_matrix.sh
Tracker M prebootloader binaries are not included in the combined-binaries zip file.
Add Tracker M to release.sh for the prebootloader build.
- Build in CircleCI
- Check combined-binaries workflow artifacts for correct files in zip
---
> [rtl872x] adds Tracker M in release.sh for prebootloader build

- modules/shared/rtl872x/inc/system-part1/module_system_part1.inc
Missing dynalib tables in the .inc file causing problems to access `cellular_signal` function from `cellular_hal` table
Fix the relevant #defines according to the platforms in the .inc file that holds the main table of dynalib pointers
Run `slo/connect_time` tests 
N/A
---
> [rtl8721x] Fix HAL defines in the main dynalib pointers table

- hal/inc/storage_hal.h
- hal/src/nRF52840/storage_hal.cpp
- hal/src/rtl872x/storage_hal.cpp
Adds hal wiring API calls to access OTP
Make the relevant functions available over wiring protected by `PARTICLE_USE_UNSTABLE_API`
```c
#define PARTICLE_USE_UNSTABLE_API
#include "exflash_hal.h"
void setup() {
uint8_t ncpId = 0;
int r = hal_storage_read(HAL_STORAGE_ID_OTP, NCP_ID_OTP_ADDRESS, &ncpId, sizeof(ncpId));
Log.info("Read result: %d / %u == %x", r, ncpId, ncpId);
ncpId = 0x67;
r = hal_storage_write(HAL_STORAGE_ID_OTP, NCP_ID_OTP_ADDRESS, &ncpId, sizeof(ncpId));
Log.info("Write result: %d", r);
r = hal_storage_read(HAL_STORAGE_ID_OTP, NCP_ID_OTP_ADDRESS, &ncpId, sizeof(ncpId));
Log.info("Read result after writing: %d / %u == %x", r, ncpId, ncpId);
}
void loop() {
}
Result on P2:
0000002148 [app] INFO: Read result: 1 / 255 == ff
0000002154 [app] INFO: Write …
```
> HAL wiring api calls to access exflash read/write functions

- user/tests/wiring/no_fixture/thread.cpp
- wiring/inc/spark_wiring_thread.h
- wiring/inc/spark_wiring_watchdog.h
- wiring_globals/src/spark_wiring_watchdog.cpp
See [SC](https://app.shortcut.com/particle/story/109275/application-watchdog-running-for-double-time)
This is a bug/problematic behavior in ApplicationWatchdog: https://github.com/particle-iot/device-os/blob/develop/wiring/inc/spark_wiring_watchdog.h#L52
https://github.com/particle-iot/device-os/blob/develop/wiring_globals/src/spark_wiring_watchdog.cpp#L22
`checkin()` gets called after `ApplicationWatchdog` thread has been started and the thread went to sleep. This updates `last_checkin` and upon wake-up in 10 minutes in this case the condition `now - last_checkin` will not be `>= timeout`, requiring another sleep cycle.
Update `last_checkin` first, use `last_checkin` + `timeout` as initial timeout in watchdog thread.
- `wiring/no_fixture` `APPLICATION*`
See SC
- [SC109275]
---
> [wiring] ApplicationWatchdog: fixes potential 2x timeout required  to fire

- user/tests/wiring/no_fixture/ble_provisioning.cpp
Listening mode tests are unstable on trackerM with threading enabled.
1. Unable to process feature flag as expected
2. Radio is repeatedly turned off indefinitely
1. Some of the tests depend on a certain feature flag being processed by Spark_Idle_Events(), hence calling Particle.process() unblocks the system thread as needed and processes the feature flag
3. Network.listen() calls could potentially interfere with the state of ncpClient() and renders undefined behavior and doesn't detect the cell radio being powered off, hence calling Particle.disconnect() at the beginning of the tests keeps the ncpClient() states as expected
Run `wiring/no_fixture` tests
[SC-107222](https://app.shortcut.com/particle/story/107222/tracker-m-invoke-particle-connect-inside-listening-tests-cause-blocking-behavi …
> [tests] Fix listening mode tests on trackerM

- hal/inc/wlan_hal.h
- hal/network/ncp_client/realtek/rtl_ncp_client.cpp
As title says. 2.4G channels 13-14 are not available by default and 14 is also not available in current country codes, same story with 5G. Even if only for testing allow explicitly allow all channels. The default is still US.
N/A
---
> [hal] wifi: add generic 'world' country code as not every country code is exposed through API

- hal/src/rtl872x/usbd_cdc.h
USB linecoding struct is supposed to be 7 bytes only, due to default packing configuration compiler aligns it to 8 bytes currently, which causes SET_LINE_CODING requests to fail.
N/A
- [SC109872]
---
> [rtl872x] usb: make sure CDC line coding struct is packed

- user/tests/integration/ota/multiple_ota_no_reset/multiple_ota_no_reset.cpp
Add delay workaround for TrackerM units that fail to communicate with QSPI flash chip with an active cellular connection.
This workaround is added to run tests for trackerM 5.1.0 release (fix in progress)
Run `ota/multiple_ota_no_reset` tests
!TODO
---
> [tests/trackerm] Add workaround for TrackerM ota tests

- hal/network/ncp_client/realtek/rtl_ncp_client.cpp
- Adds support for WPA2/WPA3 mixed APs
- Fixes race condition in `RealtekNcpClient::getNetworkInfo()` when calling into Realtek SDK without a lock with network threads potentially doing the same. This occasionally causes a crash.
N/A
N/A
N/A
---
> [p2] WiFi bugfixes

- user/tests/wiring/no_fixture_i2c/i2c.cpp
`no_fixture_i2c` tests were only validated against `p2` and `tracker` platforms. Unfortunately other platforms fail the tests.
`boron`: For some reason, the PMIC on boron NAKs bytes after 34 reads, where the same part on tracker will allow 64 byte reads.
`bsom`: The BSOM initializes the PMIC on boot, so the `Wire` interface is already initialized when attempting to init with a null buffer
`device-os-test --test-dir ~/develop/device-os/user/tests/integration --device-os-dir ~/develop/device-os run bsom wiring/no_fixture_i2c -v `
`no_fixture_i2c`
---
> Fix no_fixture_i2c for esomx,boron,bsom platforms

- system/src/system_network_manager.cpp
TrackerM attempts to connect over wifi as well (as cellular), with wifi running in scan-only mode. This is seen only when wifi credentials are provided on the device.
Skip interfaces that are not supported for connection
Since wifi credentials are not able to configured by default with `HAL_PLATFORM_WIFI_SCAN_ONLY` mode, this flag needs to be disabled first to configure the credentials for testing
1. Configure wifi credentials on trackerM using the following process
1. Disable `HAL_PLATFORM_WIFI_SCAN_ONLY` flag [here for trackerM](https://github.com/particle-iot/device-os/blob/develop/hal/src/trackerm/hal_platform_config.h#L18)
2. This facilitates configuring wifi credentials on the device. Use `particle serial wifi --file credentials.json` or similar approach
2. Flash tinker with this …
> [TrackerM] Prevent connection over wifi when configured in SCAN_ONLY mode

- hal/src/nRF52840/i2c_hal.cpp
- hal/src/rtl872x/i2c_hal.cpp
James reported a trackerm device that would not breathe cyan when running on battery power. The device appeared deadlocked. After investigation, the deadlock was traced to the i2c HAL mutex. The power management thread held the I2C mutex and the user application thread was blocked waiting on it. However, the scheduler was disabled so the power management thread could never execute and release the lock, resulting in a deadlock. 
Re-enable scheduling when acquiring the i2c hal lock in order to allow any other tasks using it to execute and release their lock
Running any user app that uses the PMIC/Fuel gauge should work on trackerm hardware
```c
void setup() {
/* A minimal example app is super helpful 
* for testing new features and fixes. 
* A link to a Docs PR is even better!
*/
}
void …
```
> Fix i2c hal deadlock

- hal/network/ncp/cellular/cellular_ncp_client.h
- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
Under unknown circumstances with some SIMs R410-based devices may encounter a problem executing `AT+IFC` or some other unrelated to SIM management/registration AT commands, which causes `CME ERROR` to be reported.
1. Add an additional condition when checking for SIM readiness - `AT+IFC?` not producing CME errors
2. When going into full functionality/airplane mode (CFUN=1/CFUN=4), wait for SIM initialization
3. Refactor functionality mode management to keep additional steps/workarounds in a single location as opposed to being sprinkled around.
1. Test on affected devices showing this behavior (R410)
2. Test in general on R410 05.08 05.11 05.12, U201, R510
N/A
N/A
---
> [Cellular] R410 initialization SIM failure workaround

- user/tests/wiring/no_fixture_spi/spix.cpp
The default SPI `SS` pin on Tracker M is `A2` - this change was originally made in the `trackerm-proto2-eval` branch for testing but is valid for all Tracker M devices. 
Run `wiring/no_fixture_spi` without errors on Tracker M FF board.
> [tests] Modify pins for trackerM spix tests

- dynalib/inc/dynalib.h
- hal/src/rtl872x/core_hal.c
- hal/src/rtl872x/exflash_hal.cpp
- platform/MCU/rtl872x/src/flash_mal.c
- platform/MCU/rtl872x/src/hw_config.c
When the user app is writing or erasing the Flash with the Flash API, in the meanwhile,  the system thread is trying to read a lot of data via XIP e.g. CRC32 calculation, we'll see a crash on P2.
Since our firmware is running on the PSRAM, XIP will not be used most of the time on KM4, any accesses to the external flash will use the Flash API. So we were going to disable XIP altogether, however, given the poor performance of the flash read API, we finally compromised to enable the XIP only in `hal_exflash_read()`
```
memcpy (XIP):
0000078766 [app] INFO: Read Time of 1MB data: 190 ms
0000079957 [app] INFO: Read Time of 1MB data: 190 ms
0000081147 [app] INFO: Read Time of 1MB data: 189 ms
FLASH_RxData:
0001106790 [app] INFO: Read Time of 1MB data: 909 ms
0001108700 [app] INFO: Read Time of …
```
> P2: Fixes the conflict between Flash API and XIP

- hal/network/lwip/cellular/pppncpnetif.cpp
- hal/src/rtl872x/sleep_hal.cpp
- hal/src/rtl872x/usart_hal.cpp
- system/src/system_sleep.cpp
1. P2 may consume high current after entered sleep mode
2. Trackerm doesn't turn off cellular modme after entered sleep mode
1. Avoid deead loop in uart hal driver
2. Delay more time before entering sleep state to make sure that resources being occupied by BLE stack are completely leased.
3. Generalize system sleep sequence to turn off modem by NCP client 
Build and run the attached example app.
```c
auto& SerialDev {Serial1};
Serial1LogHandler logger(115200, LOG_LEVEL_ALL);
static void print_menu()
{
SerialDev.printf("Enter option:\r\n");
SerialDev.printf("1. Enter sleep mode\r\n");
}
static void print_sleep_result(const SystemSleepResult& result) {
switch (result.wakeupReason()) {
case SystemSleepWakeupReason::BY_GPIO: …
```
> rtl872x: sleep improvements

- hal/inc/adc_hal.h
- hal/src/nRF52840/adc_hal.cpp
There are a number of supply secure products that use a new DCDC part from Richtek called the RT5760. A quality issue was discovered where 10% of the components have a large output voltage ripple. 
We can workaround this by switching the ADC to the internal NRF reference voltage. 
1. Pick a defective BRN404X
2. Download the example app
3. Measure the GND/3V3 and random voltage, and observe the VPP(peak-to-peak) value
Here is a log for the test results between internal reference and external reference.
```
0000323583 [app] INFO: avg: 1654.8, max: 1646.8, min: 1629.1, vpp: 17.7
0000324590 [app] INFO: avg: 1654.8, max: 1646.0, min: 1629.9, vpp: 16.1
0000325597 [app] INFO: avg: 1654.8, max: 1646.0, min: 1629.9, vpp: 16.1
0000326606 [app] INFO: avg: 1654.4, max: 1650.0, min: 1629.1, vpp: 20.9 …
```
> Use the internal ADC reference on BRN404X

- user/tests/integration/slo/startup/startup-slos.spec.js
As title says
Run device-os-test runner for slo/startup tests.
```
Device startup service level objectives (SLOs)
trackerm
Target device: 0a10aced202194944a001be0 (keerthy-trackerm-ff-05)
Flashing application: startup.bin
Getting device tests
systemThread=enabled
Initializing device test suite
Running device test: slo_startup_stats
Device test passed
Waiting cloud event: startup_stats
startupStats JSON { free_mem: 3334304, app_flash_size: 20480 }
actual_free_mem=3334304 target_free_mem=3145728 platform=trackerm
actual_app_flash_size=20480 target_app_flash_size=21504 platform=trackerm
✓ slo startup stats (112.5s)
Resetting device
1 passing (2m)
```
[SC-110519](https://app.shortcut.com/particle/story/110519/trackerm-tests-exceeds-flash-size-and-free-mem-for-on-device-tests)
---
> [test] Add thresholds for trackerM for slo tests

- user/tests/wiring/no_fixture/fastpin.cpp
wiring/no_fixture Fast Pin test requiring a bit more overhead on HIL tests
- bump limit from 1% to 10%
- Run HIL tests, wiring/no_fixture Fast Pin
---
> [test] bump fastpin max limit to 10%

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- user/tests/integration/slo/connect_time/connect_time.cpp
Signal values on certain Cat-M1 radios are invalid. Example: BG95-M1 / TrackerM
Account for `eMTC` type/sysmode while collecting signal values from QCSQ. Added minor correction around NBIoT wording.
Run test-runner for `slo/connect_time` tests on trackerM or any module with BG95-M1 radio
Results should have valid signal values collected as below.
```
stats:
{ cold:
{ cloud_connect: [ 15233, 14841, 17527, 17399, 15229, 14993, 15228, 18301 ],
network_connect: [ 5670, 5550, 5514, 5610, 5535, 5533, 5814, 5614 ],
cloud_full_handshake: [ 8373, 8109, 10831, 10599, 8504, 8274, 8231, 11497 ],
signal:
{ rat:
[ 'LTE M1', 'LTE M1', 'LTE M1', 'LTE M1', 'LTE M1', 'LTE M1', 'LTE M1', 'LTE M1' ],
sig_perc: [ 67.5, 72.5, 72.5, 80, 80, 65, 75, 75 ],
qual_perc: [ 100, 87.5, 100, 87.5, 100, 87.5, 100, 87.5 …
```
> [Quectel] Account for "eMTC" type while obtaining signal values

- hal/src/rtl872x/ble_hal.cpp
- system/inc/system_setup.h
- system/src/ble_provisioning_mode_handler.cpp
- system/src/system_setup.cpp
- wiring/inc/spark_wiring.h
- wiring/src/spark_wiring_stream.cpp
1. System events are blocked due to blocking function `serialReadLine()` when device resides in system setup mode
2. P2-specific:
1) we may destroy the BLE adv timer in its handler
2) We may try exiting the BLE events thread relying on a BLE event queue when it is the current thread, which may cause deadlock.
3) BLE adv state may not set reliably
1. Refactor `SystemSetupConsole::read_line/read_multiline`
2. P2-specific: marshall BLE commands to a dedicated thread to make sure ADV states are reliably transitted
N/A
---
> System setup and BLE threading improvements

- hal/src/nRF52840/adc_hal.cpp
There are potentially many different platforms that may end up using the richtek DCDC part with the excessive ripple voltage. For already shipped `BRN404X` platforms, the `HW_VERSION` OTP field can be used to identify them. For other SKUs, we need a different method.
The `HW Feature Flags` bytes of HW INFO in OTP have bits available. However, the `tracker` platform [uses all but one of these bits](https://docs.google.com/document/d/1NWEVTn1BI07rdKzzvx_HsGqpiBn-hIN0Kc91B989_3c/edit#heading=h.35xkyity7v7y). We will use the last OTP feature flag bit to denote the presence of the RIchtek part, and thus the need to switch to the internal ADC reference voltage. 
1. Clear the OTP bit
2. Reboot, and the ADC should use the internal reference
```
#define PARTICLE_USE_UNSTABLE_API
#include …
```
> Use OTP Feature flag to change ADC reference source

- hal/src/rtl872x/core_hal.c
- hal/src/rtl872x/exflash_hal.cpp
- platform/MCU/rtl872x/src/flash_mal.c
- user/tests/wiring/no_fixture/thread.cpp
Temprorarily enabling RSIP for reading encrypted data from flash requires as a safety-measure disabling interrupts. Reading the flash requires acquiring a mutex, which will not work under disabled interrupts/scheduling.
Now that XIP is globally disabled everywhere other than exflash_hal itself, move RSIP handling in there as well and ensure the correct sequence of events so that the deadlock does not happen.
Also fixes a flaky `CONCURRENT_MUTEX_02_priority_inheritance_three_threads` test. (Use https://github.com/particle-iot/device-os/pull/2596/files?w=1 for review to avoid tab->space changes in the diff).
1. On-device tests should pass, devices should not lock-up and fail to respond over USB (main indicator)
2. Make sure that encrypted modules are correctly reported in `serial inspect` …
> [rtl872x] Fixes a deadlock when requiring to enable RSIP

- hal/src/trackerm/ota_flash_hal.cpp
Currently running `particle serial identify` on TrackerM doesn't provide cellular info
```
$ particle serial identify
Your device id is 0a10aced202194944a001be0
Your system firmware version is 5.1.0
```
Collect cellular info as a part of system info collection similar to other cellular platforms
Run `particle serial identify` on trackerM
```
$ particle serial identify
Your device id is 0a10aced202194944a001d40
Your IMEI is 862464063731082
Your ICCID is 89883070000013773179
Your system firmware version is 5.1.0
```
N/A
---
> [TrackerM] Collect cellular properties with system info

- hal/src/rtl872x/usart_hal.cpp
TrackerM devices eventually deadlock after running for a few hours. The issue was traced to the cellular USART RX DMA transfer. On some transfers, the DMA controller does not report the final block of bytes was transferred from the USART to memory. As a result, we wait in a loop that will never complete.
The solution is to workaround the DMA controller behavior by checking if the RX DMA transfer channel becomes disabled while waiting for the transfer to complete. According to the data sheet in these circumstances the DMA transfer has actually completed and the data should be available. It should be safe to continue with the assumption that we have not lost any data from the modem. So far this appears to be true, but will need additional testing to explicitly confirm all bytes are …
> [trackerm/p2] Fix USART/DMA deadlock

- bootloader/prebootloader/src/rtl872x/part1/sleep_handler.cpp
- hal/src/rtl872x/interrupts_hal.cpp
- hal/src/rtl872x/sleep_hal.cpp
```c
void setup() {
/* A minimal example app is super helpful 
* for testing new features and fixes. 
* A link to a Docs PR is even better!
*/
}
void loop() {
}
```
N/A
---
> [rtl872x] Support IO wakeup sources through IO expander.

- hal/src/rtl872x/delay_hal.cpp
`HAL_Delay_Microseconds` on the P2 has this main loop:
```
system_tick_t start_micros = HAL_Timer_Get_Micro_Seconds();
system_tick_t current_micros = start_micros;
system_tick_t end_micros = start_micros + uSec;
...
while (current_micros < end_micros) {
current_micros = HAL_Timer_Get_Micro_Seconds();
}
```
If `end_micros` is close to `UINT_MAX` then it is possible that updating `current_micros` can wrap the counter and reset it to a low value, extending the wait by > 71 minutes. The closer `end_micros` is to precisely `UINT_MAX`, the less likely the loop will ever terminate.
Check if we've waited long enough by using unsigned difference instead of comparing to `end_micros`. Watchdog isn't implemented yet but is expected later and makes this mirror the nRF code.
`wiring/no_fixture` runs …
> fix overflow error in HAL_Delay_Microseconds

- hal/src/rtl872x/deviceid_hal_impl.h
- hal/src/tron/hal_platform_config.h
- user/applications/tinker/src/fqc_test.cpp
Photon 2 devices are going into production. The feather pinout of the Photon 2 differs from the bare P2 module. The FQC test will need to be updated to test the feather pins
Update the GPIO pin mapping to reflect which pins are available and adjacent on the feather pins
Run FQC tests with photon 2 (NOTE: Current pre DVT photon 2 boards do not have the efuse model variant settings programed, so they will not be detected as Photon 2s. In order to test FQC, you will have to make local modifications to tinker to use the photon 2 pins, then jumper those pins together). 
Use Tinker
---
> [photon2] Update FQC test with photon 2 pinout

- system/src/main.cpp
Factory reset through bootloader and long MODE button press until blinking WHITE is only available as of right now on nRF52840 platforms.
Fix that, enable on P2 and Tracker M as well.
List of things that are reset:
1. Wifi configuration
2. Cellular configuration (SIM external/internal/APN etc)
3. Everything in DCT except for device keys
4. Power management settings
1. ~Reset power management configuration?~ In DCT, already reset.
2. Reset system cache (NCP fw version, NCP MAC, ADC calibration offset)?
3. Reset OTA transfer state?
1. Flash system part out of this branch
5. Hold RESET and MODE, release RESET, continue holding until flashing WHITE (after MAGENTA and YELLOW)
6. Release MODE
7. Device should boot and lose its WiFi configuration, feature flags etc.
N/A
N/A
---
> [rtl872x] enable factory reset feature

- user/tests/integration/application/src/request_handler.cpp
- user/tests/integration/application/src/request_handler.h
- user/tests/integration/runner/mailbox/mailbox.cpp
- user/tests/integration/runner/mailbox/mailbox.spec.js
- user/tests/integration/slo/application_max_size/application_max_size.cpp
- user/tests/integration/slo/connect_time/connect_time.cpp
- user/tests/integration/slo/connect_time/connect_time.spec.js
- user/tests/libraries/unit-test/ParticleFunbag.cpp
- user/tests/libraries/unit-test/unit-test.h
- user/tests/wiring/no_fixture/system.cpp
Currently there is no sane way of writing automated tests using our test framework that:
1. Generate messages during the test that the JS side can act upon
2. Notify device-os-test-runner about on-device tests triggering a reset/detach
Add a device->host mailbox interface to send either specific notifications (e.g. device is going to reset) or generic data e.g. statistics from SLO tests.
NOTE: requires https://github.com/particle-iot/device-os-test-runner/pull/21
- runner/mailbox
- slo/connect_time
- wiring/no_fixture: system reset test
See runner/mailbox test.
---
> [test] mailbox support and support for resets within tests

- ci/run_tests.sh
- hal/inc/watchdog_hal.h
- system/src/server_config.cpp
- system/src/system_cloud_internal.cpp
- user/tests/libraries/unit-test/ParticleFunbag.cpp
1. Newhal and GCC platform builds are broken as of current develop
2. Those platforms are not actually being built during CI
> [ci] Fix gcc and newhal builds

- hal/inc/adc_hal.h
- hal/inc/hal_dynalib_gpio.h
- hal/src/nRF52840/adc_hal.cpp
- hal/src/rtl872x/adc_hal.cpp
- user/tests/wiring/api/wiring.cpp
- wiring/inc/spark_wiring.h
- wiring_globals/src/spark_wiring_gpio.cpp
Customer wishes to change ADC reference source from the default external VCC source to the internal voltage reference because it has greater accuracy on their particular design. 
Add Wiring API to change the source at runtime. Setting is not persistent
I used a boron to test ADC reading on pin A5 with 2v from a bench supply. 
```c
void setup() {
/* A minimal example app is super helpful 
* for testing new features and fixes. 
* A link to a Docs PR is even better!
*/
}
void loop() {
static uint8_t i = 0;
int analogPin = A5;
int value = 0;
String source;
// Set ADC reference source
if (i++ % 2) {
analogSetReference(AdcReference::INTERNAL);
} else {
analogSetReference(AdcReference::VCC);
}
source = (analogGetReference() == AdcReference::INTERNAL ? "INTERNAL" : "VCC     ");
// Read ADC
value …
```
> [wiring][gen3] Allow gen3 to select internal ADC reference source

- user/tests/wiring/watchdog/watchdog.cpp
Watchdog test 3 requires manual triggering of WKP pin to pass. This isnt feasible on HIL with automated tests. 
Change test to duration based hibernation with watchdog enabled. Only run tests on platforms that support this: RTL872X platforms + Tracker
run `wiring/watchdog` tests
`wiring/watchdog`
---
> Remove manual wakeup. Hibernate + watchdog on platforms that support it

- system/inc/active_object.h
- system/inc/system_cloud.h
- system/inc/system_dynalib_cloud.h
- system/src/system_cloud.cpp
- user/tests/wiring/no_fixture/ble_provisioning.cpp
- user/tests/wiring/no_fixture/tcp.cpp
- user/tests/wiring/no_fixture/thread.cpp
- user/tests/wiring/no_fixture/time.cpp
- wiring/inc/spark_wiring_cloud.h
Test `THREAD_07_particle_process_behavior_when_threading_enabled` fails in most cases with current `develop`. The problem is that when an Async task is inserted into the application thread queue, we only call `Particle.process()` once to execute the task. This works fine unless there are other work items in the queue ahead of that task. 
For now, we will simply exhaust the queue by calling `Particle.process()` repeatedly. See discussion [here](https://s.slack.com/archives/CS0T32ZKK/p1676072611430139?thread_ts=1676047385.672259&cid=CS0T32ZKK)
Longer term we need to investigate if all queue items should be consumed when explicitly calling `Particle.process()` outside of the normal system idle loop.  
Run test runner test `THREAD_07_particle_process_behavior_when_threading_enabled` …
> Ensure thread07 test executes as intended

- hal/src/rtl872x/core_hal.c
- hal/src/rtl872x/interrupts_hal.cpp
- platform/MCU/rtl872x/src/hw_config.c
- user/tests/wiring/shared_interrupt/shared_interrupt.cpp
PR #2608 introduced a regression in MODE button handling for RTL872x-based platforms (P2, Tracker M).
1. hal_button_init() is postponed until global constructors in system-part1 have been called and malloc has been enabled
2. interrupts_hal refactored to not remove entries unnecessarily (as our Vector implementation anyway does not free the memory) and instead safely invalidate them
3. Thread/interrupt-safety improvements for interrupts_hal
4. `wiring/shared_interrupt` test fix for configuration version to make it work after #2614
- `wiring/shared_interupt`
- MODE button presses should allow listening mode entry/exit as well as signal strength bars query
- Button should also still work correctly in bootloader
N/A
- [SC115613]
- #2608 
- #2614
---
> [rtl872x] hal: fix heap allocation issue in interrupt hal and postpone the mode button initialization.

- user/tests/wiring/watchdog/watchdog.cpp
- user/tests/wiring/watchdog/watchdog.spec.js
- `TEST=wiring/watchdog` failing for cellular devices due to WDT firing too soon
- Add a setup phase to WDT tests that turns off the NCP, to ensure sleep will enter in a timely manner for WDT tests.
> [test] turn off NCP before testing wiring/watchdog

- platform/MCU/rtl872x/src/flash_mal.c
> [rtl872x] bootloader: fix destination address flash page alignment in case of compressed modules

- hal/src/rtl872x/ble_hal.cpp
- user/tests/app/ble/uart_central/application.cpp
- wiring/src/spark_wiring_ble.cpp
1. It may be failed to stop BLE advertising
2. BLE scanning may timeout most of time
3. BLE scanning may cause buffer overflow
4. BLE disconnection might be failed
5. It may be failed to establish a new BLE connection
Fixed
Peripheral:
```c
const BleUuid serviceUuid("6E400001-B5A3-F393-E0A9-E50E24DCCA9E");
const BleUuid rxUuid("6E400002-B5A3-F393-E0A9-E50E24DCCA9E");
const BleUuid txUuid("6E400003-B5A3-F393-E0A9-E50E24DCCA9E");
BleCharacteristic peerTxCharacteristic;
void onDataReceived(const uint8_t* data, size_t len, const BlePeerDevice& peer, void* context) {
Log.info("CBack: Data Received with len=%d and data=%s", len, data);
for (size_t ii = 0; ii < len; ii++) { …
```
> Fix inconsistent BLE state issue.

- bootloader/src/rtl872x/osdep_service.cpp
- hal/src/rtl872x/usbd_driver.cpp
- hal/src/rtl872x/usbd_driver.h
```
const size_t RTW_USBD_TASK_MAIN_LOOP_SEMAPHORE_OFFSET = 364;
const size_t RTL_USB_DEV_PCD_OFFSET = 0xd8;
const size_t RTL_USB_PCD_SPINLOCK_OFFSET = 0x15c;
```
Most likely at the very least the above definitions need to be adjusted due to internal USB stack struct changes.
We found the USB request Get Line Coding couldn't get a response on the AMD Windows PC, the symptom could be that we can't open the com port on a serial tool software on the AMD Windows PC.
By enabling the low level USB log in `hw_config.c`
```
ConfigDebugClose = 0;
DBG_ERR_MSG_ON(MODULE_USB_OTG);
DBG_WARN_MSG_ON(MODULE_USB_OTG);
DBG_INFO_MSG_ON(MODULE_USB_OTG);
ConfigDebug[LEVEL_TRACE] |= BIT(MODULE_USB_OTG);
```
we can see the last log when P2 got stuck, that is a race condition to access TxFIFO between EP3 and …
> Apply new usb stack and patch to fix the USB issue on Windows

- hal/src/rtl872x/ble_hal.cpp
`BLE.connect()` causes an assertion failure waiting for connection events from the stack.
Start BLE stack/event dispatching before a connection attempt.
See app below.
```c++
void setup() {
uint8_t addr[] = {0,1,2,3,4,5};
Log.info("try connect");
BLE.on();
BLE.connect(BleAddress(addr));
}
void loop() {
}
```
- [SC116668]
---
> [rtl872x] ble: start BLE stack/event dispatching before a connection attempt

- hal/src/rtl872x/usbd_driver.cpp
After #2625 it seems that the Realtek SDK has new behavior again and doesn't pass even more interface requests to setup request callback.
Fake/force it to pass those requests by patching in wrapper `__wrap_usb_hal_read_packet` with `bmRequestTypeType` = `SetupRequest::TYPE_CLASS`. This for some reasons makes the SDK deliver these requests to our setup request callback.
Build bootloader, go into DFU, test that `dfu-util -d 2b04:d020 -a 1 -s 3106:192 -U p2.der` works fine (involves SET_INTERFACE request).
N/A
- Fixes #2625 
---
> [rtl872x] usb: force SDK to pass recipient=interface requests by faking type=class

- hal/src/rtl872x/i2c_hal.cpp
1. RTL872x-based platforms acting as I2C master may failed to communicate with certain type of slave device.
2. RTL872x-based platforms acting as I2C slave may failed to communicate with I2C master.
1. Re-enabled I2C before performing the I2C transmission.
2. Fix I2C slave race conditions.
```c
SerialLogHandler l(115200, LOG_LEVEL_ALL);
uint8_t i2cAddr = 0x3C; // SSD1306
void setup() {
Log.info("Application started");
Wire.begin();
uint8_t test[2] = {0x55, 0xaa};
bool stop = true;
for (uint8_t i = 0; i < 4; i++) {
Wire.beginTransmission(i2cAddr);
Wire.write(test, sizeof(test)); 
int ret = Wire.endTransmission(stop);
if (ret != 0) {
Log.info("TX FAILED");
while (1);
}
if (i < 2) {
Wire.beginTransmission(i2cAddr);
Wire.write(test, sizeof(test));
int …
```
> [rtl872x] hal: I2C may fail to read/write from/to slave device.

- hal/src/rtl872x/usart_hal.cpp
If the device on the other end of the UART bus is transmitting while doing `Serial1.begin()`, the P2 freezes.
Conditionally enable NVIC IRQ in `AtomicBlock`
Get two P2s, build and flash the following example app accordingly.
```c
#if 1
void setup() {
Serial.begin(9600);
WITH_LOCK(Serial) {
Serial.printf("\n%s - Hello", (const char*)Time.timeStr());
}
Serial1.begin(9600, SERIAL_8N1);
}
void loop() {
Serial1.printlnf("Tick: %ld", millis());
delay(1s);
}
#else // The other end of UART
void setup() {
Serial1.begin(9600, SERIAL_8N1);
}
void loop() {
Serial1.printlnf("Tick: %ld", millis());
delay(10);
}
#endif
```
https://community.particle.io/t/serial1-causing-solid-led-on-p2/64269/7
---
> [rtl872x] hal: uart may deadlock on initialization.

- hal/network/ncp_client/sara/sara_ncp_client.cpp
R410 was failing the `slo/connect_time` tests due to PS only mode not being saved for R410 devices.
Guard against running PS only mode code for any device other than R510 for now to preserve system cache settings for those devices, in case we decide to enable this for them in the future.
Run integration tests `slo/connect_time` for R410 based devices.
#2639 
---
> minor fix to ensure PS only mode is only applied to R510 at this time

- hal/src/rtl872x/usart_hal.cpp
P2 USARTs enable software pullups on TX/RX pins, which is unnecessary.
Dont enable pullups by default
Run any serial logging app, confirm communication works fine
```c
SYSTEM_MODE(AUTOMATIC);
void setup() {
Serial3.begin(115200, SERIAL_8N1 | SERIAL_FLOW_CONTROL_RTS_CTS);
Serial3.write("Application started");
}
void loop() {
if (!Serial3.available()) {
return;
}
while (Serial3.available()) {
char c = Serial3.read();
Log.info("got char %c", c);
Serial3.write(c);
}
}
```
[Community post here](https://community.particle.io/t/p2-module-tmc2209-driver-tx-rx-pullup-issue-possibly-preventing-bidirectional-comms/64194/1)
---
> [rtl872x] Dont enable usart RX/TX pullups

- hal/inc/radio_hal.h
- hal/network/ncp/wifi/wlan_hal.cpp
- hal/src/nRF52840/radio_common.cpp
- hal/src/nRF52840/radio_common.h
- hal/src/rtl872x/radio_common.cpp
- hal/src/rtl872x/radio_common.h
`WiFi.selectAntenna()` is not implemented for P2
On P2, BLE and WiFi share the same physical antenna, so use `selectAntenna()` from `radio_common.cpp`
Use test app below to verify antenna switches
```c
SYSTEM_MODE(AUTOMATIC);
SerialLogHandler logHandler(LOG_LEVEL_ERROR,
{
{ "app", LOG_LEVEL_ALL },
});
String anntena_names[] = {"Internal", "External", "", "Automatic"};
void setup() {
}
void loop() {
if (!Serial.available()) {
return;
}
while (Serial.available()) {
char c = Serial.read();
Log.info("Got %c", c);
int result = 0;
if (c == 'i') {
result = WiFi.selectAntenna(ANT_INTERNAL);
}
else if (c == 'e') {
result = WiFi.selectAntenna(ANT_EXTERNAL);
}
else if (c == 'a') {
result = WiFi.selectAntenna(ANT_AUTO);
}
else if (c == 'n') {
result = …
```
> [rtl872x] Implement WiFi.selectAntenna

- hal/src/rtl872x/ble_hal.cpp
BLE scanning may finally panic after running for a long time, bacause of corrupted BLE stack.
Restart BLE stack, instead of panic.
`user/tests/app/ble/scanner` or `user/tests/app/ble/uart_central`
N/A
---
> [rtl872x] BLE scanning panic

- hal/src/nRF52840/sleep_hal.cpp
Device wakes up immediately if uart is confirgured as wakeup source and the uart has received data before sleep.
Clear the RXDRDY event accordingly before enabling the RXDRDY interrupt in sleep HAL.
N/A
---
> [nRF52] UART sleep/wakeup

- hal/network/ncp/cellular/cellular_ncp_client.h
- hal/network/ncp_client/sara/sara_ncp_client.cpp
- hal/network/ncp_client/sara/sara_ncp_client.h
- services/inc/system_cache.h
Currently R510 based devices (Boron/BSoM/ESoMX) power up with CS (Circuit Switched) and PS (Packet Switched) operation modes both enabled.  CS mode is not used, therefor it may be disabled which simplifies the data centric nature of the device.
Enable PS Only operation mode on first boot.  This feature is non-volatile and only needs to be checked and set once. However, if the cellular registration process should linger, we will also double check that its set correctly during the registration intervening process.
- Test with (Boron/BSoM/ESoMX) devices that have never been setup before.  Flash the base firmware without letting the device boot.  Flash new system firmware with tinker-serial-debugging for logging, and cold or warm boot the device.  First boot should show AT+CEMODE? query == 2 …
> [r510] enable PS (packet switched) Only mode for R510 modems (Boron/BSoM/ESoMX)

- bootloader/prebootloader/src/rtl872x/part1/rtl_support.c
We want to allow Particle built prebootloader binaries to boot Realtek SDK based KM4 bootloader binaries. This is broken in the current Device OS.
The RTK SDK KM4 based bootloaders expect a `FLASH_InitTypeDef flash_init_para` structure to be present in `BKUP_REG7` at boot. We had this originally, but since our bootloader does not need this, it was removed.
It doesnt appear that anything internal to DVOS uses `BKUP_REG7`, so this change should be safe
1. Build `prebootloader-part1` from this branch, flash to p2
1. Flash SDK KM4 Bootloader + APP images
1. Verify the KM4 bootloader + KM4 APP runs
Ask scott for KM4 SDK Bootloader binary
---
> [rtl872x] Allow KM4 SDK Bootloader images to boot

- hal/src/rtl872x/usb_hal.cpp
- hal/src/rtl872x/usb_hal_hid.cpp
- hal/src/rtl872x/usbd_cdc.cpp
- hal/src/rtl872x/usbd_cdc.h
- hal/src/rtl872x/usbd_device.cpp
- hal/src/rtl872x/usbd_driver.cpp
- hal/src/rtl872x/usbd_driver.h
- hal/src/rtl872x/usbd_hid.cpp
- hal/src/rtl872x/usbd_hid.h
- user/tests/wiring/usbhid2/usbhid.py
- wiring/inc/spark_wiring_platform.h
- wiring/inc/spark_wiring_usbkeyboard.h
- wiring/inc/spark_wiring_usbmouse.h
- wiring/src/spark_wiring_usbkeyboard.cpp
- wiring/src/spark_wiring_usbmouse.cpp
USB HID (Mouse / Keyboard) support for P2 / Photon 2.
Same APIs as previously on Photon / P1 / Electron:
https://docs.particle.io/reference/device-os/api/keyboard/keyboard/
https://docs.particle.io/reference/device-os/api/mouse/mouse/
1. `Mouse.moveTo()` might not be moving the cursor (at least on Linux). Might need to come up with a different digitizer descriptor. Wayland uses multiple pointers, so standard pointer doesn't move. Might be the same nowadays on Windows/OSX.
2. We are out of USB endpoints to run CDC + HID at the same time. When both are enabled we are again using a hack from Electron times where one of the CDC endpoints is in fact invalid. This works fine on Linux, double check Windows / OSX behavior, but should probably behave fine as well, as again we've done the same …
> [rtl872x] usb: HID

- build/module.mk
- modules/shared/rtl872x/build_linker_script.mk
1. Applications with large number of sources can trigger `Argument list too long` when Make calls shell + rm + list of files to remove
2. PSRAM size calculations for RTL872x-based platforms do not account for `.dynalib` section, which also resides in PSRAM
> Fixes clean target for applications with large number of fils + P2 PSRAM size calculation issues

- hal/src/rtl872x/i2c_hal.cpp
I2C read timeout is not correct.
Use the timeout specified in the given parameter in read request API.
See the following test app.
I2C master:
```c
void setup() {
Serial.begin(115200);  // start serial for output
waitFor(Serial.isConnected, 10000);
Wire.begin();        // join i2c bus (address optional for master)
}
void loop() {
char c {};
unsigned int numCharsReceived {};
Wire.requestFrom(8, 1);    // request 1 byte from slave device #8
while (Wire.available()) { // slave may send less than requested
c = Wire.read(); // receive a byte as character
numCharsReceived++;
}
Serial.printlnf("Character received = %c,  NumCharsReceived = %u", c, numCharsReceived);
delay(1000);
}
```
I2C slave:
```c …
```
> [rtl872x] fix incorrect I2C read timeout

- hal/network/lwip/esp32/esp32ncpnetif.cpp
- hal/network/lwip/realtek/rtlncpnetif.cpp
- user/tests/wiring/sleep20/sleep20.cpp
`wiring/sleep20` test failures:
- Test `12_System_Sleep_With_Configuration_Object_Hibernate_Mode_Bypass_Network_Off_Execution_Time` [Photon2]
- Test `33_System_Sleep_With_Configuration_Object_Stop_Mode_Execution_Time` [Argon/Photon2]
- Test `34_System_Sleep_With_Configuration_Object_Ultra_Low_Power_Mode_Wakeup_Execution_Time` [Argon/Photon2]
- Test `35_System_Sleep_With_Configuration_Object_Network_Power_State_Consistent_Off` [ Argon/Photon2]
---
> [test] resolve sleep20 test failures.

- hal/src/rtl872x/core_hal.c
- hal/src/rtl872x/rtc_hal.cpp
RTC is always reset after waking up from hibernate mode.
Do not initialize the RTC if device wakes up from hibernate mode.
See the following test app.
```c
Serial1LogHandler l(115200, LOG_LEVEL_ALL);
static time32_t year, month, day, weekday, hour, minute, second;
void updateTime() {
year = Time.year();
month = Time.month();
day = Time.day();
weekday = Time.weekday();
hour = Time.hour();
minute = Time.minute();
second = Time.second();
}
STARTUP(updateTime());
void setup() {
Log.info("%d-%d-%d, %d:%d:%d, %d, test: %ld", year, month, day, hour, minute, second, weekday);
delay(5s);
updateTime();
Log.info("%d-%d-%d, %d:%d:%d, %d, test: %ld", year, month, day, hour, minute, second, weekday); …
```
> [rtl872x] RTC is not remained after waking up from hibernate mode.

- user/tests/integration/ota/factory_reset/factory_reset.cpp
- user/tests/integration/ota/factory_reset/factory_reset.spec.js
Factory Reset is a feature where an application module can be stored in flash at a specified `EXTERNAL_FLASH_FAC_ADDRESS` address and copied over the running application either by the firmware itself via `System.factoryReset()` or via a USB control request. 
This feature is used internally and by some customers but is not tested. We should expand the automated testing to cover these use cases.
Add tests to OTA update suite. They are mostly the same as the multiple ota tests.
Use test runner on a gen 3 platform
```
device-os-test --test-dir ~/develop/device-os/user/tests/integration --device-os-dir ~/develop/device-os run ota/factory_reset argon -v -- -fixture
```
See test app 
Side note: Realtek platforms do not support Factory Reset (yet). There are a few things that need to be added to …
> [nrf] Add Factory Reset Tests

- hal/src/rtl872x/spi_hal.cpp
For the external flash read/write test, SPI0 and SPI1 passed test at 25MHz. SPI0 failed to communicate with the flash at the highest speed 50MHz.
Writting the regular data `0x55 0x55 0x55 ...` to the flash, which is 01010101 waveform on the oscilloscope, we read back the data `0xaa 0xaa ... 0xaa 0x1a 0xaa...`, this anomaly seems to have a pattern, the data appears to have shifted by one bit.
The data corruption issue can be fixed by setting the sample delay to one clock cycle.
Please refer to < UM0400 Ameba-D User Manual > 25.2.3.1.1 RXD Sample Delay
[CH119867]
---
> rtl872x: set RXD sample delay for SPI0@50MHz

- bootloader/prebootloader/src/rtl872x/part1/rtl_support.c
We enabled brown out detection on all p2 platforms in device os `5.2.0`. This may be causing problems with P2 platform specifically since it does not have an external reset IC like photon 2 / msom
Disable brown out reset + interrupt while we investigate the issue
[See slack](https://s.slack.com/archives/C05BMP0GVE1)
[sc-120473](https://app.shortcut.com/particle/story/120473/p2-bor-causes-lockup-issue)
---
> [rtl872x] Revert BOD reset

- hal/inc/gpio_hal.h
- hal/src/rtl872x/gpio_hal.cpp
- hal/src/rtl872x/i2c_hal.cpp
- hal/src/rtl872x/pwm_hal.cpp
- hal/src/rtl872x/spi_hal.cpp
During the EVT test, we observed significant overshoot. This issue occurs on every high-speed bus, including SPI, I2C, PWM, I2S, and DMIC.
There are four drive strength can be configured for RTL872x, all the GPIO were configured to `PAD_DRV_STRENGTH_3` at boot.
- PAD_DRV_STRENGTH_0: 4mA
- PAD_DRV_STRENGTH_1: 8mA   (Severe overshoot, not recommended to use it)
- PAD_DRV_STRENGTH_2: 12mA
- PAD_DRV_STRENGTH_3: 16mA  (Severe overshoot, not recommended to use it)
We compared the overshoot issue with each drive strength configuration and found `PAD_DRV_STRENGTH_0` and `PAD_DRV_STRENGTH_2` were better than `PAD_DRV_STRENGTH_1` and `PAD_DRV_STRENGTH_3`
Below is the clock pin of SPI0@50MHz
Selecting PAD_DRV_STRENGTH_2 could be a solution to avoid the overshoot issue while maintaining a high drive …
> rtl872x: overshoot issue

- hal/src/msom/network/network.cpp
GPIO pins for ethernet on msom platform were not updated to match M2 eval board pinout
Fix it
Enable ethernet feature
```
System.enableFeature(FEATURE_ETHERNET_DETECTION);
```
Reset and try ethernet on M2 eval 
Use snippet to print ethernet configuration / state
```c
auto conf = Ethernet.getConfig();
uint8_t ethernet_mac[6] = {};
Ethernet.macAddress(ethernet_mac);
Log.info("MAC: %02X:%02X:%02X:%02X:%02X:%02X",
ethernet_mac[0],ethernet_mac[1],ethernet_mac[2],
ethernet_mac[3],ethernet_mac[4],ethernet_mac[5]);
Log.info("localIP: %s", Ethernet.localIP().toString().c_str());
Log.info("DHCP: %s", Ethernet.dhcpServerIP().toString().c_str());
Log.info("Gateway IP: %s", Ethernet.gatewayIP().toString().c_str());
Log.info("Subnet Mask: %s", Ethernet.subnetMask().toString().c_str());
for (const auto& …
```
> [msom] Fix ethernet cs, reset, interrupt GPIO pins for M2 eval

- hal/src/rtl872x/usart_hal.cpp
The delay in UART `flush()` may cause user app fail to synchronize with the peer UART device.
The delay actinng as a hacky workaround was introduced in this PR2586: https://github.com/particle-iot/device-os/pull/2586 and may be potentially fixed by another PR2581: https://github.com/particle-iot/device-os/pull/2581
Remove the delay. 
Re-run the test app that is shown in the PR2586 and it turned out to be working fine after removing the delay, i.e. device can enter sleep as expected and it doesn't leak power in sleep mode.
N/A
---
> [rtl872x] remove the delay in UART flush().

- build/arm-tools.mk
- services/src/printf_export.c
- services/src/scanf_export.c
- user/tests/integration/wiring/strformat
- user/tests/wiring/strformat/application.cpp
- user/tests/wiring/strformat/printf_scanf.cpp
- user/tests/wiring/strformat/strformat.spec.js
- user/tests/wiring/strformat/test.mk
Patches nano variants of `_printf_i`, `_vsfprintf_r`, `__ssvfscanf_r` and `_scanf_i` to support 64-bit format specifiers.
Also fixes a bug with `%X` scanf format, which was incorrectly parsing as signed integer (whereas `%x` worked as intended).
- `wiring/strformat`
```
0000002561 [app] INFO: 18446744073709551615 ("%llu" == "18446744073709551615") parsed=18446744073709551615
0000002570 [app] INFO: ffffffffffffffff ("%llx" == "ffffffffffffffff") parsed=ffffffffffffffff
0000002578 [app] INFO: FFFFFFFFFFFFFFFF ("%llX" == "FFFFFFFFFFFFFFFF") parsed=FFFFFFFFFFFFFFFF
0000002586 [app] INFO: 18446744073709551615 ("%PRIu64" == "18446744073709551615") parsed=18446744073709551615
0000002595 [app] INFO: ffffffffffffffff ("%PRIx64" == "ffffffffffffffff") parsed=ffffffffffffffff
0000002604 [app] INFO: …
```
> [services] add long long support to printf/scanf

- test/unit_tests/wiring/string.cpp
- wiring/inc/spark_wiring_string.h
- wiring/src/spark_wiring_string.cpp
Add 64-bit integer types (`long long` and `unsigned long long`) support to the `particle::String` class.
* `tests/unit_tests/wiring/string`
```cpp
void setup() {
Serial.begin();
constexpr uint64_t number64 {12345678901234ULL}; // 0x00000b3a_73ce2ff2
auto str64 = String(number64, HEX);
Serial.printlnf("Big number in hex: %s", str64.c_str());
}
void loop() {
}
```
Result
```
Big number in hex: b3a73ce2ff2
```
---
> [wiring] Add 64-bit string conversions

- bootloader/src/rtl872x/rtl_it.c
- bootloader/src/rtl872x/rtl_it.h
- hal/src/rtl872x/core_hal.c
- hal/src/rtl872x/interrupts_irq.h
- platform/MCU/rtl872x/src/hw_config.c
- services/inc/panic.h
> [rtl872x] correctly handle SecureFault

- hal/network/ncp_client/quectel/quectel_ncp_client.cpp
- hal/network/ncp_client/quectel/quectel_ncp_client.h
- After the UART fixes of #2698, the UART is a bit faster now and that has surfaced some lurking issues.  The Quectel NCP Client was not waiting for the modem to be ready on cold boot, causing a boot loop from CFUN=1,0 failing in initReady()
- Add a retry scheme for CFUN=1,0 on initReady() only at this time.
- Cold boot the device and ensure any CFUN errors are handled, retried and the device boots successfully.
- All integration tests should pass, especially the cold boot SLO test.
#2698 
---
> Fixes ncp-client not waiting for modem ready on cold boot
