main/tests/core-v1/testapp1/time.cpp, wiring/src/spark_wiring_time.cpp
=> remove newline from Time.timeStr()

README.md
Update instructions to use homebrew for installing the toolchain
Update doc references to firmware repo name
Bump dfu-util version reference (confirmed that the latest works)
Fix a typo
=> Update firmware README

misc/driver/windows/photon.inf, misc/driver/windows/spark_core.inf
Fixed manufacturer string. Updated Spark Core Manufacturer to Particle.io
This was a joint effort by myself, @kennethlimcp, and @ScruffR
=> Windows Driver manufacturer fix

wiring/src/spark_wiring_usartserial.cpp
Someday, I will get this all together.  ;)  I think it is all in place now, between this, and a pull request to change the docs.
=> Moved the halfduplex() function out of the Constructors area of the file

user/inc/application.h
This will add itoa and friends so they can be used by users.
=> Add string_convert.h to includes in application.h

hal/inc/pinmap_hal.h, hal/src/stm32f2xx/pinmap_hal.c
I followed how the extra pins on the Electron were added and add the spare pins for the P1
=> Feature/added spare pins for P1

hal/src/photon/socket_hal.cpp
The reason for the bug is WICED deallocating the connection handler twice.
It occurs because in `WICED/network/LwIP/WICED/tcpip.c:920` the `netconn_delete( socket->conn_handler );` is not followed by `socket->conn_handler = NULL;` as it is in other places in the code for example in `WICED/network/LwIP/WICED/tcpip.c:931`. This leads `wiced_tcp_delete_socket` to delete the connection handler again, leading to a crash.
This should fix #516 and #490. @andyw-lala can you run your tests against this branch please?
This should also be reported to Broadcom so they can fix this upstream.
=> Work around a WICED bug crashing when socket connection fails

wiring/inc/fast_pin.h
Add pinReadFast() for direct IDR GPIO register read.
=> Add pinReadFast(_pin)

user/tests/wiring/api/network.cpp, wiring/inc/spark_wiring_udp.h, wiring/src/spark_wiring_udp.cpp
=> implementation of dynamically allocated UDP buffers

hal/src/photon/socket_hal.cpp
This is an alternative approach to #542: check the LwIP connection error in the `isClosed`. Instead of reaching through to LwIP directly, use a WICED-style wrapper `wiced_last_error` that check LwIP `netconn_err`.
This avoid the asynchronicity of the callback and works in more cases. It makes the test program in #542 work for the TEST_READ and TEST_PRINT case. The TEST_CONNECTED_ONLY still fails (connected always returns true), but that test case fails with the callback too.
=> Add a method to retrieve the last error on a socket

hal/src/core/interrupts_hal.c, hal/src/core/pinmap_hal.c, hal/src/core/pinmap_impl.h, wiring/inc/fast_pin.h
The bit-banding code is common across all STM32Fx series
=> fast-pin: Cortex M3 Bit-Band access to perform fast GPIO atomic read-modify-write

CHANGELOG.md, hal/inc/hal_dynalib_socket.h, hal/inc/socket_hal.h, hal/src/core/socket_hal.c, hal/src/gcc/socket_hal.cpp, hal/src/photon/socket_hal.cpp, hal/src/template/socket_hal.c, wiring/inc/spark_wiring_tcpclient.h, wiring/src/spark_wiring_tcpclient.cpp, wiring/src/spark_wiring_tcpserver.cpp
Fetches the remote IP for a TCPClient.
=> TCPClient.remoteIP

hal/inc/wlan_hal.h, hal/src/core/wlan_hal.c, hal/src/photon/wlan_hal.cpp, system/inc/system_network.h, system/inc/system_setup.h, system/src/system_network.cpp, system/src/system_setup.cpp, wiring/inc/spark_wiring_wifi.h
FIRM-155 prompt for the Security Cipher if it cannot be determined automatically. This makes it possible to connect to offline and hidden networks via Serial setup.
Addresses #562.  Release pending support in particle CLI for the new serial interaction.
=> serial setup supports hidden networks

hal/src/electron/modem/mdm_hal.cpp
Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>
=> fixed "balaced" typo

.travis.yml, ci/create_spark_cli_json.sh, ci/enumerate_build_matrix.sh, ci/handle_test.sh, ci/test_memory_available_with_real_core.sh, ci/test_setup.sh
Remove unnecessary builds. Add some color. Switch to particle-cli.
=> Travis build tweaks

hal/src/stm32f2xx/i2c_hal.c
contribution from @pra in the community. Thanks! https://community.particle.io/t/i2c-lcd-freezes-photon/15666
If you have a MCP23017 or Adafruit RGBLCDShield please test and report if this improves I2C connectivity!
=> I2C fix for MCP23017 / Adafruit RGBLCDShield

hal/src/core/usart_hal.c, hal/src/stm32f2xx/usart_hal.c
fix copypasta in usart code. addresses issue #682
=> copypasta in usart HAL code

hal/inc/timer_hal.h, system/inc/system_dynalib.h, system/inc/system_event.h, system/inc/system_update.h, system/src/system_event.cpp, system/src/system_task.cpp, system/src/system_update.cpp, user/tests/app/otacontrol/otacontrol.cpp, wiring/inc/spark_wiring_system.h
Provides system event notification and system flags to control when an OTA update is started and when the system can reset to apply the update.
=> ota update control

.travis.yml, hal/src/stm32f2xx/dac_hal.c
Many thanks to @ScruffR and @unreason for the fixes.
Fixed two issues:
1) Initialize DAC_InitStructure to zero prior to configuration.  This
fixes issue #671.
2) Enable DAC channel only once in DAC_Init().  This shows fix issues
#662
=> fix issue #671 and #662

user/tests/wiring/adc_dac/adc_dac.cpp
Add the failure case for issue 671.  The original failure is somewhat
random depends on the state of the memory stack.  The issue is no
longer reproducible when compiled against the latest development branch.
=> add test for github issue 671

user/tests/wiring/adc_dac/adc_dac.cpp, user/tests/wiring/adc_dac/readme.md
=> Dac unit test

hal/inc/concurrent_hal.h, hal/src/stm32f2xx/concurrent_hal.cpp, wiring/inc/spark_wiring_timer.h
Add software timer timerChangePeriod() function.  Also, order of fromISR parameter in os_timer_change() was incorrect.
=> Add timerChangePeriod()

hal/inc/cellular_hal.h, hal/inc/hal_dynalib_cellular.h, hal/src/electron/cellular_hal.cpp, hal/src/electron/modem/enums_hal.h, hal/src/electron/modem/mdm_hal.cpp, hal/src/electron/modem/mdm_hal.h, hal/src/electron/socket_hal.cpp, hal/src/stm32f2xx/platform_headers.h, wiring/inc/spark_wiring_cellular.h
* adds Cellular.command() to Wiring API for sending and parsing AT commands
* current safe with multithreading disabled (not thread safe yet, you've been warned)
* refactored some typedefs and enums out into a separate header for user access
```
int Cellular.command(_CALLBACKPTR_MDM cb, void* param, system_tick_t timeout_ms, const char* format, ...);
```
4 different basic signatures with and without printf style formatting
```
int ret = Cellular.command(_cbUSOCTL, &handle, 10000, "AT+USOCTL=%d,1\r\n", 0);
int ret = Cellular.command(_cbUSOCTL, &handle, 10000, "AT+USOCTL=0,1\r\n";
int ret = Cellular.command(_cbUSOCTL, &handle, "AT+USOCTL=%d,1\r\n", 0);
int ret = Cellular.command(_cbUSOCTL, &handle, "AT+USOCTL=%d,1\r\n");
int ret = Cellular.command(10000, "AT+USOCTL=%d,1\r\n", 0);
int ret = …
```
=> Cellular.command() for Electron - FIRM-276

hal/src/stm32f2xx/eeprom_hal.c
* [Don't erase a page of flash ON EVERY BOOT](https://github.com/monkbroc/firmware/blob/18eda04106ea7f54d1a4a794840aa2403dad28bd/hal/src/stm32f2xx/eeprom_hal.c#L539) to increase Flash life and avoid erasing Flash in every low power situations
* Don't format the EEPROM in case both pages are valid, just erase one
* Lock the Flash after initialization or variable write
Bad chargers and depleted batteries cause the EEPROM contents to be lost on the Photon and Electron.
http://community.particle.io/t/eeprom-persistence-issue/16514
https://community.particle.io/t/photon-ran-low-on-battery-now-stuck-in-sos/16710
#704
The root cause is still not clear but one factor making it worse is the fact that the STM EEPROM emulation code (AN3390) erases one page of Flash on every boot. This is unnecessary …
=> Improve EEPROM stability and persistence

hal/src/core/wlan_hal.c, system/src/system_network_wifi.h
=> initialize wifi on the core when determining if credentials should be cleared

hal/inc/interrupts_hal.h, hal/src/core/interrupts_hal.c, hal/src/stm32f2xx/interrupts_hal.c, hal/src/template/interrupts_hal.cpp, user/tests/wiring/api/wiring.cpp, wiring/inc/spark_wiring_interrupts.h, wiring/src/spark_wiring_interrupts.cpp
Implements support for priorities in attachInterrupt()
Closes #806
=> Support for configurable interrupt priority in attachInterrupt()

user/tests/wiring/spi_shield/spi_fram.cpp
This test checks the issue #791 of SPI User callback firing before the actual SPI transfer has finished.
=> A test for SPI DMA issue #791 fixed in PR #801

hal/inc/concurrent_hal.h, hal/src/stm32f2xx/concurrent_hal.cpp, user/tests/wiring/no_fixture/timer.cpp, wiring/inc/spark_wiring_timer.h
- adds support for class member callbacks
- use of std::function for lambda support. 
- one-shot timers 
- Automated tests for timers 
- avoids destroying a timer while it's callback function is active
=> software timer enhancements and tests

system/src/system_setup.cpp, user/tests/wiring/no_fixture/interrupts.cpp, user/tests/wiring/no_fixture/thread.cpp, wiring/inc/spark_wiring_interrupts.h, wiring/inc/spark_wiring_thread.h
Implements
```
WITH_LOCK(Serial) {
}
```
and
```
TRY_LOCK(Serial) {
}
```
and
```
SINGLE_THREADED_BLOCK() {
// single threaded code
}
```
and
```
ATOMIC_BLOCK() {
}
````
Tested on the Photon with an app that writes to serial during listening mode.
=> locking API redux

build/module.mk, main/import.mk, modules/makefile
tested from main/ and modules/ per make commands in issue #899 
working for Photon (modular) and Core (monolithic)
=> fixes issue #899

user/tests/readme.md
Right now, the Tests readme page is broken:
https://github.com/spark/firmware/blob/develop/user/tests/readme.md
This fixes it.  You can view the output here:
https://jbt.github.io/markdown-editor/#nVZNb+M2EL3rVxDIIUkRy+g1yC6QTdNiTxtsvKdgUdHiyGJDiSo/4ri/vm9ISVacAAV6skzOx5uZNzM8ExvywRfF2Zn4TTuqg3UH8e2F3IumfVGshBwGsRIBUvxpdC2Dtr0vcHhnbFSsj28Zg+0kxJKo7nfCNqJmAdGQDNHhxuhnEk3s62ThSrxIp+XWED6/bW5FHBQbKOHU6K3DJXRWwsdhsC6ZPB431mVMtVUEBUeNoWQXGltZP4tgx1+OT7jY9wlUL8LeQovxXCinEenax+1fUBbSOdnvqKM+XMJm7DVHtqtryHeDNqTyWTIJgb12bHMFqytFL7omoftAO5dS9N6zBMxdNNKJO/i/Eg+tDThGKA+/iot7DsCxHpBT0iZVXhapNg9GBsTcTeWa/2cn9Ep1DMROHEkjWunUXjoqWflMfInaKAZxamZzWlbkgMQW4kE0zsJ8S2LAWR+EmulRdVL3lYieTXYSRd3r0AqplGYj0hRQkR0Fcv66KKqqKpLU5v5x8+lmGDF8Xt8weHjvIfs5iRW/Ixn0KrvBID+cCEYuqt7+2ehXZlGFFIsqZ766Egcbxd5GyOydDnTqLMutj+rZyy1 …
=> Fix Tests readme broken markdown

CHANGELOG.md, hal/src/gcc/core_hal.cpp, hal/src/gcc/device_config.cpp, hal/src/gcc/eeprom_file.h, hal/src/gcc/eeprom_hal.cpp, hal/src/gcc/filesystem.cpp, hal/src/gcc/filesystem.h, hal/src/gcc/readme.md
adds eeprom support for virtual devices
---
Doneness:
=> adds eeprom support for virtual devices

CHANGELOG.md, docs/reference/firmware.md, hal/inc/core_hal.h, hal/inc/hal_dynalib_core.h, hal/src/core/core_hal.c, hal/src/electron/core_hal.c, hal/src/gcc/core_hal.cpp, hal/src/photon/core_hal.c, hal/src/stm32f2xx/core_hal_stm32f2xx.c, hal/src/stm32f2xx/core_hal_stm32f2xx.h, platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/dct.h, services/src/panic.c, system/inc/system_update.h, system/src/main.cpp, system/src/system_cloud_internal.cpp, system/src/system_update.cpp, user/tests/wiring/api/system.cpp, wiring/inc/spark_wiring_system.h, wiring/inc/spark_wiring_watchdog.h, wiring/src/spark_wiring_system.cpp
=> Store last reset reason and publish it to the cloud

hal/src/stm32/pwm_hal.c
=> Use floating point arithmetics in PWM on Electron to save some flash space

hal/src/stm32f2xx/spi_hal.c, user/tests/wiring/spi_master_slave/spi_master/spi_master.cpp, user/tests/wiring/spi_master_slave/spi_slave/spi_slave.cpp
---
Doneness:
ENHANCEMENT
- Extended spi_master_slave tests with SPI_MODE0/1/2/3 and MSBFIRST/LSBFIRST testing [#1056](https://github.com/spark/firmware/pull/1056)
=> Extending spi_master_slave tests with SPI_MODE0/1/2/3 and MSBFIRST/LSBFIRST testing

hal/src/stm32f2xx/usb_hal.c, hal/src/stm32f2xx/usb_settings.h, platform/MCU/STM32F2xx/SPARK_Firmware_Driver/inc/usbd_mcdc.h, platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/usbd_mcdc.c, services/inc/ringbuf_helper.h
The issue seen, while testing 0.6.0-rc.1 release... sometimes the USB serial or USB serial1 connection would terminate unexpectedly.
- TX buffer tail pointer advanced only after transmission
- Added critical section to `HAL_USB_USART_Send_Data`
---
Doneness:
N/A
=> USB Serial fixes

hal/src/electron/modem/mdm_hal.cpp, user/tests/wiring/no_fixture/application.cpp, user/tests/wiring/no_fixture/can.cpp, user/tests/wiring/no_fixture/cellular.cpp, user/tests/wiring/no_fixture/concurrent.cpp, user/tests/wiring/no_fixture/delay.cpp, user/tests/wiring/no_fixture/eeprom.cpp, user/tests/wiring/no_fixture/gpio.cpp, user/tests/wiring/no_fixture/interrupts.cpp, user/tests/wiring/no_fixture/led.cpp, user/tests/wiring/no_fixture/random.cpp, user/tests/wiring/no_fixture/servo.cpp, user/tests/wiring/no_fixture/spi.cpp, user/tests/wiring/no_fixture/string.cpp, user/tests/wiring/no_fixture/tcp.cpp, user/tests/wiring/no_fixture/thread.cpp, user/tests/wiring/no_fixture/time.cpp, user/tests/wiring/no_fixture/timer.cpp, user/tests/wiring/no_fixture/tone.cpp, user/tests/wiring/no_fixture/wifi.cpp, user/tests/wiring/no_fixture/wire.cpp, user/tests/wiring/sleep/sleep.cpp
Original PR #1069 
Updates to tests wiring/no_fixture that allow electron to pass reliably.
- updated BAND_SELECT and CLOUD tests
- updated TIME tests to account for 24 hour wrap case, expand time zone test coverage
- updated APPLICATION_WATCHDOG
- numbered all wiring/no_fixture tests to ensure an ordered test sequence
---
Doneness:
N/A
=> [0.5.x] Feature/test wiring no fixture updates

build/test/files/applibs_v2_vendored/app_explicit/src/app.cpp, build/test/libs.bats
From original PR #1101 
Fixes Libraries V2 acceptance tests
---
Doneness:
N/A
=> [0.5.x] Feature/vendor lib test fix

wiring_globals/src/wiring_globals_i2c.cpp
Signed-off-by: Kenneth Lim <kennethlimcp@gmail.com>
=> guage --> gauge

docs/gettingstarted.md
Suggested sudo for Linux users and fix "makes silences" to just "silences".
---
Doneness:
=> Suggested sudo for Linux users and fix "makes silences" to just "silences".

communication/src/dtls_protocol.cpp
Only changes a comment.
---
Doneness:
=> Corrects comment about UDP ping frequency

docs/build.md
Single line docs fix. Please merge.
=> Fix typo in Markdown

system/src/main.cpp
---
Doneness:
N/A - fixes to 0.6.1-rc.1 commits
=> Fixes spontaneous SETUP button click on reset

docs/gettingstarted.md
Documentation still points at using the 'latest' branch which no longer exists.
Switched from 'latest' to 'release/stable'
https://docs.particle.io/faq/particle-tools/local-build/photon/
=> Changed branch to checkout from 'latest' to 'release/stable'

hal/src/electron/cellular_hal.cpp, hal/src/electron/cellular_internal.cpp, hal/src/electron/cellular_internal.h, hal/src/gcc/concurrent_hal_impl.h, user/tests/app/diagnostics/diagnostics.cpp, user/tests/unit/cellular.cpp, user/tests/unit/makefile, user/tests/unit/wlan.cpp, wiring/inc/spark_wiring_cellular_printable.h, wiring/inc/spark_wiring_wifi.h, wiring/src/spark_wiring_cellular_printable.cpp, wiring/src/spark_wiring_wifi.cpp
<details>
```
```
</details>
- Adds unit tests for the functionality introduced by #1423
- Adds application from #1424 as `app/diagnostics` test to simplify debugging
- Run the unit tests :)
N/A
- #1423
- #1424
- [CH9200]
- [CH9012]
---
=> Signal strength/quality unit tests

crypto/inc/crypto_dynalib.h, crypto/inc/mbedtls_weaken.h, crypto/makefile, crypto/src/mbedtls_util.cpp, modules/electron/system-part2/makefile, modules/photon/system-part1/makefile, modules/shared/stm32f2xx/part1_build.mk, services/inc/printf_float.h, services/inc/services_dynalib.h, services/src/services_dynalib.c, user/tests/unit/service_bytes2hex.cpp
<details>
```
```
</details>
We need to move some things around in order to free some space in Photon/P1 system-part2.
Do exactly that:
- Moves _printf_float from part2 into part1 on Photon/P1
- Moves a part of mbedtls back into part1 on Photon/P1 (md5, md4, des, md)
Compare the binary sizes.
```
text	   data	    bss	    dec	    hex …
```
=> part2 optimizations

user/tests/unit/makefile, wiring/src/string_convert.cpp
#1443 required changes to the unit test build.  I'd asked for these to be merged in to the remote branch so they would be part of the PR, but that didn't happen, so submitting here as it's own PR.
=> fixes the unit test build

STYLE_GUIDE.md
A style guide will help our contributors write clean, testable and visually consistent code.  This is the first step in that direction.
=> beginnings of the style guide

README.md
bug: CONTRIBUTE link in README.md not work
use CONTRIBUTING.md to replace it
=> README.md: fix CONTRIBUTE link

system/inc/active_object.h, system/src/active_object.cpp
This PR back-ports https://github.com/particle-iot/firmware/commit/e8f77ec3eec9ea11e0bac713eca0d31904abcb14 and https://github.com/particle-iot/firmware/commit/d4ece2c5ab43fc06a59cbb0e0e04aaf18eade402 from `mesh-develop`.
- [ch25788]
---
=> Do not disable interrupts on every system loop iteration

communication/src/protocol.cpp
This PR cherry-picks https://github.com/particle-iot/firmware/pull/1623 from `mesh-develop`.
=> Do not set the sticky skip hello after handshake

user/inc/Arduino.h
```
#include "Arduino.h"
SYSTEM_MODE(AUTOMATIC);
volatile uint32_t *portreg;
/* This function is called once at start up ----------------------------------*/
void setup()
{
// Configure the port to output.
portreg = portModeRegister(digitalPinToPort(D2));
*portreg = 0xFFFFFFFF;
portreg = portOutputRegister(digitalPinToPort(D2));
*portreg = 0xFFFFFFFF;
}
/* This function loops forever --------------------------------------------*/
void loop()
{
// Port output high
*portreg = 0xFFFFFFFF;
delay(1000);
// Port output low
*portreg = 0x00000000;
delay(1000);
}
```
=> CH26714: Arduino compatibility for mesh platforms.

build/release-all.sh, build/release.sh
Add comments to release.sh
refactor bootloader build section in `release.sh`
remove `release-all.sh` in favor of new `make_release.sh`
=> Refactor release scripts

system/system-versions.md
Fixes recent merge issues with `system-versions.md`
---
---
- [Internal] [docs] Fixes recent merge issues with `system-versions.md` [#1715](https://github.com/particle-iot/device-os/pull/1715)
=> Fixes recent merge issues with `system-versions.md` [ci skip]

hal/src/nRF52840/ble_hal.cpp, system/src/ble_control_request_channel.cpp, user/tests/app/ble/uart_central/application.cpp, wiring/src/spark_wiring_ble.cpp
**This PR targets currently `feature/ble/develop` branch**
- [CH33667]
- [CH33670]
=> BLE: optimize the semaphores' usage in BLE HAL.

build/make_release.sh, build/release-publish.sh, build/release-tests.sh, build/release.sh, system/inc/system_cloud.h, wiring/inc/spark_wiring_cloud.h
- Updates `spark_publish_vitals` documentation.
- Update error messages on the build scripts
---
- [internal] [docs] Updates `spark_publish_vitals` and build scripts documentation. [#1800](https://github.com/particle-iot/device-os/pull/1800)
=> [docs] Updates `spark_publish_vitals` and build scripts documentation.

user/tests/readme.md
---
- [internal]  [docs] update the test documentation [#1683](https://github.com/particle-iot/device-os/pull/1683)
=> update the test documentation

hal/src/electron/modem/mdm_hal.cpp, user/tests/wiring/no_fixture/cellular.cpp
=> fixes RSSI regression on G350 (2G) devices [ch35194] (original PR #1841)

docs/artifacts.md
Provide a formal definition for artifact naming conventions.
---
- [Internal] [docs] Adds Artifact Versioning and Tagging (1.0.0) artifacts.md [#1703](https://github.com/particle-iot/device-os/pull/1703)
=> Define versions

system/src/system_cloud_internal.cpp
https://github.com/particle-iot/device-os/commit/4a73449a4f7345c9b8e03b81baf141a68ead4cad restored the pre-1.1.0 behavior where the safe mode event is sent only after a full handshake with the cloud. It turns out that this logic may actually break the firmware update process under some circumstances.
A simple test to reproduce the problem:
1. Flash 1.4.0 firmware to a device, e.g. an Argon.
2. Flash 1.4.1-rc.1 tinker to the device.
(device resets and connects to the cloud in safe mode)
3. Reset the device while it is receiving 1.4.1-rc.1 system firmware.
(device reconnects to the cloud and stays in safe mode forever)
1. Set the module version to 1401 (1.4.0), compile and flash this branch to a device.
2. Perform the steps 2-3 from the test in the description, and verify that the device …
=> Send safe mode event when the session is resumed

hal/src/boron/network/sara_ncp_client.cpp
Gen 3 cellular devices were having twice as many connection attempts as expected during registration, with a deactivated SIM
- Removed the unconditional COPS=2 call at the beginning of registration, and only called when it's absolutely required 
- Also changed hard reset at the end of registration to a soft power off 
- Run a B SoM / Boron with a deactivated SIM with tinker-serial-debugging in monolithic mode, and observe that COPS=2 is not run unconditionally every time registration is performed, that occurs every 5 min in case of a deactivated SIM. 
Closes ch40865
---
=> [Gen 3] Fix too many connection events with deactivated SIM [ch40865]

hal/inc/sleep_hal.h, hal/src/core/sleep_hal.cpp, hal/src/gcc/sleep_hal.cpp, hal/src/nRF52840/sleep_hal.cpp, hal/src/stm32f2xx/sleep_hal.cpp, services/inc/system_defs.h, system/inc/system_dynalib.h, system/inc/system_network.h, system/inc/system_sleep.h, system/src/system_sleep.cpp, wiring/inc/spark_wiring_network.h, wiring/inc/spark_wiring_system.h, wiring/src/spark_wiring_system.cpp
**This branch currently target to internal/sleep2_0-ch41111**
N/A
N/A
N/A
N/A
https://github.com/particle-iot/device-os/pull/1965
---
=> Rework wiring system sleep APIs.

bootloader/src/stm32f2xx/dfu_usb.c, bootloader/src/stm32f2xx/stm32_it.c, build/arm-tools.mk, build/arm/linker/linker_nrf52840_bootloader.ld, dynalib/inc/dynalib.h, hal/src/electron/newlib_stubs.cpp, hal/src/nRF52840/memory_no_bootloader.ld, hal/src/nRF52840/newlib_stubs.cpp, hal/src/photon/newlib_stubs.cpp, modules/electron/system-part1/src/newlib_stubs.cpp, modules/electron/user-part/src/newlib_stubs.cpp, modules/photon/user-part/src/newlib_stubs.cpp, modules/shared/nRF52840/inc/user-part/newlib_stubs.inc, platform/MCU/STM32F2xx/STM32_USB_Device_Driver/inc/usbd_dfu_core.h, platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_core.c, platform/MCU/STM32F2xx/STM32_USB_Device_Driver/src/usbd_dfu_core.c, test/unit_tests/CMakeLists.txt, test/unit_tests/wiring/CMakeLists.txt, test/unit_tests/wiring/print.cpp, user/inc/Arduino.h, wiring/inc/spark_wiring_fixed_point.h, wiring/inc/spark_wiring_print.h, wiring/src/spark_wiring_print.cpp
Supports GCCv8.3.1
Fix all the regressions.
Run all the unit tests in the Device OS.
The test report is available in this [Document](https://docs.google.com/document/d/1hscqGpdE2FEnCQ2uNDfspzTBAXsU5Nf0D3zL94brFYE/edit?usp=sharing).
Unit tests for `printNumber()` changes.
N/A
[CH37700]
[CH42677]
---
=> Supports GCCv8.3.1

hal/inc/cellular_hal.h, hal/src/b5som/network/quectel_ncp_client.cpp, hal/src/boron/network/sara_ncp_client.cpp
=> Minimum registration timeout is 5 minutes

wiring/src/spark_wiring_time.cpp
Story details: https://app.clubhouse.io/particle/story/30983
=> Add boundary checking to format string copy

user/tests/unit/string.cpp, wiring/src/spark_wiring_string.cpp
Story details: https://app.clubhouse.io/particle/story/42242
=> String::substring() unnecessarily modifies the source buffer

hal/src/nRF52840/i2c_hal.cpp
I2C might get hang up by slave device and never lease the bus.
Reset I2C bus by simulating 9 clocks on the SCL line and reset the I2C state machine.
This PR also fixes the issue that Fuel Gauge returns 256 if it fails to read the SoC.
1. Build and flash the given example below for B5SoM or BSoM (SoM evaluation board is required).
2. Connect the SoM evaluation board to your computer and open a serial monitor to watch the log.
3. Disconnect and reconnect the `PM_SCL` jumper on the SoM evaluation board randomly, quickly and repeatedly.
4. See if the SoC is get updated as long as the `PM_SCL` jumper is connected. And if the `PM_SCL` is disconnected, the SoC should be `-1`.
```c
SerialLogHandler log(115200, LOG_LEVEL_ALL);
FuelGauge fuel;
void setup() …
```
=> Gen3: fixes I2C hang up issue

system/src/usb_control_request_channel.cpp
When testing Device OS in automated scenarios, we frequently need to recover devices under test from some blocked state caused by, for example, the network registration process.
Allow resetting the device and cancelling the cloud connection directly in the USB HAL's ISR.
Using [this](https://github.com/particle-iot/particle-usb/tree/reset_req/ch57751) branch of particle-usb:
```js
const usb = require('particle-usb');
async function run() {
let dev = null;
try {
const devs = await usb.getDevices();
if (!devs.length) {
throw new Error('No devices found');
}
dev = devs[0];
await dev.open();
// This should reset the device immediately
// await dev.reset({ force: true });
// This should cause the device to disconnect from the cloud immediately
// await dev.disconnectFromCloud({ force: true }); …
```
=> Allow resetting the device via a low-level vendor-specific USB request

wiring/inc/spark_wiring_client.h, wiring/inc/spark_wiring_udp.h, wiring/src/spark_wiring_tcpclient.cpp, wiring/src/spark_wiring_udp.cpp, wiring/src/spark_wiring_udp_posix.cpp
Closes #2160
Supersedes and closes #2161
N/A
N/A
N/A
---
=> [wiring] fixes member vars initialization

hal/network/api/ifapi.h
I managed to mess up the rebase on #2166, hence the new PR.
=> if_power_state_t is an enum

hal/src/nRF52840/sleep_hal.cpp
Gen3: device might exit from the ULP mode immediately when USART is specified as the wakeup source
Disable TX related interrupts before entering the ULP mode.
```c
void setup() {
}
void loop() {
delay(1000);
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::ULTRA_LOW_POWER).usart(Serial1));
}
```
Device running the above application may wakes up from the the ULP mode immediately before applying the fix.
---
=> Gen3: fixes USART wakeup source for the ULP mode

wiring/inc/fast_pin.h
#2192 
The initialization order between the translation units is undefined, so the inline static variable which gets a reference to the pin map from the HAL can be initialized at any point in time during traversal of the global ctor list, making it impossible to use fastpin functions within global constructors e.g. `STARTUP()` in a different translation unit that uses a function to call fastpin.
```c++
// a.cpp
const void* testval = (const void*)0x5a5a5a5a;
extern void test();
STARTUP(test());
void setup() {
}
void loop() {
delay(1000);
Serial.printlnf("%x", testval);
}
// b.cpp
extern void* testval;
void test() {
// as of develop
testval = (const void*)PIN_MAP;
// as of this PR
// testval = (const void*)fastPinGetPinmap();
}
```
- [CH62885]
- Closes #2192 
---
=> [wiring] fastpin: use function with static variable to overcome initialization order woes

ci/unit_tests.sh, hal/inc/cellular_hal.h, hal/inc/cellular_hal_constants.h, hal/inc/cellular_hal_utilities.h, hal/network/ncp/cellular/cellular_network_manager.h, hal/network/ncp/cellular/network_config_db.cpp, hal/network/ncp/cellular/network_config_db.h, hal/network/ncp_client/quectel/quectel_ncp_client.cpp, hal/network/ncp_client/quectel/quectel_ncp_client.h, hal/network/ncp_client/sara/sara_ncp_client.cpp, hal/network/ncp_client/sara/sara_ncp_client.h, hal/src/electron/cellular_hal.cpp, hal/src/electron/cellular_hal_utilities.cpp, hal/src/electron/cellular_internal.cpp, hal/src/electron/cellular_internal.h, hal/src/electron/modem/mdm_hal.cpp, hal/src/electron/modem/mdm_hal.h, modules/electron/system-part1/src/cellular_hal.cpp, system/src/system_network_internal.h, test/unit_tests/cellular/CMakeLists.txt, test/unit_tests/cellular/cellular.cpp, user/tests/unit/fuel_gauge.cpp, wiring/inc/spark_wiring_fuel.h, wiring/src/spark_wiring_fuel.cpp, wiring/src/spark_wiring_wifi.cpp
A number of issues found while bringing up the new Twilio Super SIM.
- [gen2] [gen3] adds fixes for UMNOPROF when using Twilio Super SIM [ch60727]
- [gen2] move CFUN=1,0 code within if (_init .. block
- ensure CIMI timeout is at least 10s on u-blox modems [ch61658]
- fixes running unit tests via ci/unit_tests.sh locally
- [gen3] delay registration intervening for twilio super sim for first 5 mins [ch60883]
- run both sets of unit tests
```
device-os $ source ci/install_boost.sh
device-os $ source ci/build_boost.sh
device-os $ ci/unit_tests.sh
```
- lots of manual testing with the app below to help facilitate resetting the UMNOPROF back to 0 with cold and warm boots
```c
Serial1LogHandler logHandler(115200, LOG_LEVEL_ALL);
bool …
```
=> Twilio Fixes

user/tests/wiring/i2c_master_slave/i2c_master/i2c_master.cpp, user/tests/wiring/i2c_master_slave/i2c_slave/i2c_slave.cpp
As title says.
#2093 
#2184 
---
=> Test: add test case for I2C restarted transaction.

ci/cf_generate_message.sh, ci/cf_update.sh, ci/enumerate_build_matrix.sh, ci/functions.sh, ci/install_gcovr.sh, ci/report/report.py, ci/run_tests.sh, ci/unit_tests.sh
=> [CI] Migration to Codefresh

user/tests/wiring/api/ble.cpp, wiring/inc/spark_wiring_ble.h, wiring/inc/spark_wiring_ipaddress.h, wiring/src/spark_wiring_ble.cpp, wiring/src/spark_wiring_ipaddress.cpp
=> [wiring] add more operators for BleAddress/BleUuid/IPAddress.

platform/MCU/nRF52840/src/flash_mal.c
We've introduced an incompatibility in https://github.com/particle-iot/device-os/pull/2097 between older Gen 3 system-part1 modules and new bootloader in handling of `MODULE_DROP_MODULE_INFO` flag.
Prior to the change the expected behavior for the bootloader was to check the module header in the OTA section and look at the actual flags from it (where `MODULE_DROP_MODULE_INFO` would be present).
After the change, the expected behavior for the bootloader is to only look at the update module slot flags that are stored in DCT, however DeviceOS versions that don't have the change do not set the appropriate slot flag that would instruct the bootloader to drop module info when applying the update.
This breaks SoftDevice updates under following conditions:
1. Gen 3 platforms
2. system-part1 …
=> [gen3] bootloader: add workaround for MODULE_DROP_MODULE_INFO

hal/inc/ble_hal.h, hal/inc/ble_hal_defines.h, hal/inc/hal_dynalib_ble.h, hal/src/nRF52840/ble_hal.cpp, user/tests/wiring/api/ble.cpp, user/tests/wiring/ble_central_peripheral/ble_central/central.cpp, user/tests/wiring/ble_central_peripheral/ble_peripheral/peripheral.cpp, wiring/inc/spark_wiring_ble.h, wiring/src/spark_wiring_ble.cpp
BLE core spec 5.0, Vol.3, Part H, Section 2.3.5.6.
---
=> BLE: supports LESC pairing.

.circleci/config.yml, .workbench/manifest.json, ci/enumerate_build_matrix.sh
[SC-100967](https://app.shortcut.com/particle/story/100967/gen2-supply-secure-workbench)
[SC-100965](https://app.shortcut.com/particle/story/100965/gen2-supply-secure-ci)
=> [gen2][supply secure] CI and Workbench

communication/README.md, communication/inc/protocol_defs.h, communication/src/build.mk, communication/src/communication_dynalib.cpp, communication/src/description.cpp, communication/src/dsakeygen.cpp, communication/src/handshake.cpp, communication/src/handshake.h, communication/src/protocol_defs.cpp, communication/src/spark_protocol_functions.cpp, communication/tests/Main.cpp, user/tests/integration/communication/events/events.spec.js, user/tests/integration/communication/functions/functions.cpp, user/tests/integration/communication/functions/functions.spec.js, user/tests/integration/communication/variables/variables.cpp, user/tests/integration/communication/variables/variables.spec.js
Gen2 Supply Secure for Communications module
[SC-100985](https://app.shortcut.com/particle/story/100985/gen2-supply-secure-communication-and-communication-dynalib)
---
=> [gen2][supply secure] Communication

communication/tests/Main.cpp
Fixes a minor error in #2423 
[SC-100985](https://app.shortcut.com/particle/story/100985/gen2-supply-secure-communication-and-communication-dynalib)
=> [gen2][supply secure] communications minor

wiring/inc/fast_pin.h, wiring/inc/spark_wiring_cloud.h, wiring/inc/spark_wiring_platform.h, wiring/inc/spark_wiring_spi.h, wiring/inc/spark_wiring_timer.h, wiring/inc/spark_wiring_version.h, wiring/inc/spark_wiring_wifi.h, wiring/src/spark_wiring.cpp, wiring/src/spark_wiring_cellular_printable.cpp, wiring/src/spark_wiring_logging.cpp, wiring/src/user.cpp, wiring_globals/src/spark_wiring_gpio.cpp
[sc-101081](https://app.shortcut.com/particle/story/101081/gen2-supply-secure-wiring-and-wiring-globals?vc_group_by=day&ct_workflow=all&cf_workflow=500127125)
=> [gen2][supply secure] wiring and wiring_globals

system/inc/system_cloud.h, system/inc/system_network.h, system/inc/system_sleep_configuration.h, system/src/build.mk, system/src/control/config.cpp, system/src/control/storage.cpp, system/src/main.cpp, system/src/system_network_compat.cpp, system/src/system_network_internal.h, system/src/system_sleep.cpp, system/src/system_sleep_compat.cpp, system/src/system_task.cpp, system/src/system_threading.cpp, system/src/system_update.cpp, system/src/usb_control_request_channel.cpp, system/system-threading.md, test/unit_tests/system/system_info.cpp
[SC-101076](https://app.shortcut.com/particle/story/101076/gen2-supply-secure-system-and-system-dynalib)
=> [gen2][supply secure] system

docs/artifacts.md, docs/build.md, docs/debugging.md, docs/dependencies.md, docs/gettingstarted.md, dynalib/inc/module_info.inc, dynalib/src/readme.md
[sc101038](https://app.shortcut.com/particle/story/101038/gen2-supply-secure-protobuf)
[sc100989](https://app.shortcut.com/particle/story/100989/gen2-supply-secure-dynalib-generic)
[sc100988](https://app.shortcut.com/particle/story/100988/gen2-supply-secure-docs)
=> [gen2][supply secure] protobuf, dynalib and docs

.circleci/config.yml, crypto/inc/mbedtls_config.h, crypto/inc/mbedtls_config_default.h, crypto/src/mbedtls_util.cpp, hal/shared/platforms.h, hal/src/nRF52840/readme.md, system/inc/system_threading.h
[SC-100996](https://app.shortcut.com/particle/story/100996)
=> [gen2][supply secure] Clean up

communication/src/dtls_message_channel.cpp
A [CID](https://datatracker.ietf.org/doc/html/rfc9146) packet carries no indication of whether the device is reconnecting to the Cloud or continuing to talk over the already established session.
Use a custom content type with CID packets when resuming the session.
The device should be able to resume its session and connect to the cloud.
- sc-101456
=> Use a custom content type with CID packets when resuming the session

hal/src/rtl872x/usart_hal.cpp
For platforms, like TrackerM, rely on the UART HAL event group APIs, but they are not implemented yet.
Implements the UART HAL event group APIs. This PR also implements the UART HAL sleep API.
This test app is for verifying the HAL sleep API.
```c
#define SERIAL                  Serial2
#define SERIAL_INTERFACE        HAL_USART_SERIAL2
void setup() {
SERIAL.begin(115200);
pinMode(D11, INPUT_PULLUP);
}
void loop() {
if (digitalRead(D11) == LOW) {
delay(1s);
SERIAL.printlnf("available1: %d", SERIAL.available());
hal_usart_sleep(SERIAL_INTERFACE, true, nullptr);
while (digitalRead(D11) == LOW);
hal_usart_sleep(SERIAL_INTERFACE, false, nullptr);
delay(1s);
SERIAL.printlnf("available2: %d", SERIAL.available());
while …
```
=> RTL872x: Implement HAL event group for UART

user/tests/wiring/no_fixture/time.cpp
=> [test][4x] fixes race condition with wiring/no_fixture TIME_17

system/src/system_task.cpp
After recent changes to system_delay_pump(), DELAY_01 was out of tolerance.
Revert part of system_delay_pump() for the microsecond accuracy of 1ms delays.
- Run `TEST=wiring/no_fixture` DELAY* and TIME*
---
=> [tests] restores accuracy of system_delay_pump for DELAY_01 test

system/src/system_task.cpp
=> [tests][4x] restores accuracy of system_delay_pump for DELAY_01 test

system/src/ble_control_request_channel.cpp
The BLE control request channel sends an incorrectly sized reply packet if `system_ctrl_alloc_reply_data()` allocated a larger buffer for the payload data than the actual size of the data:
```cpp
system_ctrl_alloc_reply_data(req, 100 /* size */, nullptr /* reserved */);
req->reply_size = 99;
memset(req->reply_data, 0, req->reply_size);
system_ctrl_set_result(req, 0 /* result */, nullptr /* handler */, nullptr /* data */, nullptr /* reserved */);
```
Sending multiple `CTRL_REQUEST_DIAGNOSTIC_INFO` requests to a device in a row must succeed.
- sc-109824
=> Fix BLE control request channel sending malformed packets

bootloader/prebootloader/src/rtl872x/part1/rtl_support.c
=> [rtl872x] prebootloader: enable BOR with lowest available thresholds

hal/src/rtl872x/usart_hal.cpp
=> [rtl872x] hal: remove an assert in read()/peek() and instead adjust read/peek size

system/src/server_config.cpp, system/src/system_cloud_internal.cpp
This PR fixes the build for GCC platform that was broken in https://github.com/particle-iot/device-os/pull/2570.
=> Fix GCC platform build

hal/src/nRF52840/sleep_hal.cpp
When `.ble()` and `.duration(...)` are specified as wakeup sources, device will crash on entering sleep mode.
Wait until RTC is ticking before `__disable_irq()`
Build and flash the below app to Argon(Boron)
```c
void setup() {
delay(5s);
BLE.advertise();
delay(1s);
System.sleep(SystemSleepConfiguration().mode(SystemSleepMode::ULTRA_LOW_POWER).ble().duration(10s));
}
```
https://community.particle.io/t/device-wake-up-via-ble-and-duration-getting-sos-hard-fault/63466
---
=> [nRF52] BLE plus RTC sleep causes hardfault

hal/src/nRF52840/watchdog_hal.cpp, hal/src/rtl872x/watchdog_hal.cpp, user/tests/wiring/watchdog/watchdog.cpp
=> [test]: add more watchdog test cases.

bootloader/src/main.c, platform/MCU/rtl872x/inc/flash_access.h, platform/MCU/rtl872x/inc/flash_mal.h, platform/MCU/rtl872x/src/flash_mal.c
This PR supports detecting and copying an alternate system part firmware from an offset of the flash to the target address. 
Collaborate with https://github.com/particle-iot/realtek_ambd_sdk/pull/3 
---
=> Combined MFG firmware
